### ISSUE TITLE
DQ1 Wrenna does not get recruited into the save file

### ISSUE THREAD

**Issue by Mirnaia** [larsiusprime/tdrpg-bugs#10]
Operating System: Windows 7 64bit
Browser/Download: Download
Demo/Full? : Full Version
Version: haxe_dq1_build_04_23_2014

(I'm still unable to export saves :( )

Play until you recruit Wrenna.
Do anything afterwards (quit immediately or play a few extra battles).
Reload, it loads from the point where you get Wrenna and have to name her.

**Comment by larsiusprime** [comment]
Whoo, old bugs :) Fixing it now.

1) Can you export with the latest builds.
2) Reproduced the wrenna bug. Working on it.
3) After a battle she is logged as in your party. Only quitting immediately triggers the bug.
