### ISSUE TITLE
incorrectly-labeled buttons

### ISSUE THREAD

**Issue by adolson** [larsiusprime/tdrpg-bugs#1000]
These buttons seem to be missing the appropriate labels.
![20160611224451_1](https://cloud.githubusercontent.com/assets/6351421/15988624/13d1b55e-3026-11e6-9542-bfb37a490f9a.jpg)

**Comment by larsiusprime** [comment]
This bug has been cropping up a lot lately, but I can't reproduce it on any
of my machines.

I assume this is in Linux? What distro and architecture(64bit vs 32bit) are
you running? I wonder if there's a pattern to this.

On Sat, Jun 11, 2016 at 9:45 PM, Dana Olson <notifications@github.com>
wrote:

> These buttons seem to be missing the appropriate labels.
> [image: 20160611224451_1]
> <https://cloud.githubusercontent.com/assets/6351421/15988624/13d1b55e-3026-11e6-9542-bfb37a490f9a.jpg>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1000>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-JbcAEwXEuySKsECH_LEds_DZLUvks5qK3K_gaJpZM4IzsDi>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by adolson** [comment]
Debian, 64-bit. (I'm shineuponthee on twitter, btw)

**Comment by larsiusprime** [comment]
I've found a little fix I think may work... will be in 0.9.8

**Comment by adolson** [comment]
Excellent. I was just coming back to report that it's coming up in the battles too, like if I go to restart when it asks me to keep the same formation, etc.

**Comment by ManDude** [comment]
I think this is a duplicate, too.

**Comment by adolson** [comment]
Yes. Dupe of #992 . I didn't search before reporting.
