### ISSUE TITLE
hard-to-read text in a Big Picture / ten-foot setting

### ISSUE THREAD

**Issue by adolson** [larsiusprime/tdrpg-bugs#1001]
Lars requested I upload screens here where I find text difficult to read, as I'm playing in my living room on a TV, sitting on a sofa, with a Steam Controller in hand.

Unless I specify otherwise, the text in question is always the black text on the textured background in the images. It just seems that it's the only stuff that is more difficult to read for me; maybe it just needs a bit more weight and/or size to the font.

![20160611223458_1](https://cloud.githubusercontent.com/assets/6351421/15988675/9a673dae-3027-11e6-8f2c-bb03a6d1bb5b.jpg)

![20160611225619_1](https://cloud.githubusercontent.com/assets/6351421/15988679/a818e4ca-3027-11e6-98c6-82699d9c3daa.jpg)

![20160611230047_1](https://cloud.githubusercontent.com/assets/6351421/15988712/7a19c372-3028-11e6-96d0-461fe1fd4679.jpg)

![20160611230927_1](https://cloud.githubusercontent.com/assets/6351421/15988753/e0b9329c-3029-11e6-903a-bf5883b51bec.jpg)
(Tooltip in that one could be slightly larger, but it is readable anyhow).

Really, I think black on that one background is what causes me the most problems.

**Comment by larsiusprime** [comment]
Specifically -- black against the textured background of the brown
scroll/parchment?

So that gives me some quick tweaks to try first -- I could try lightening
up the scrolls for one, and if that doesn't work I can look into increasing
font/text size. The latter's more involved but I imagine I'll have to bite
the bullet eventually for couchplay so I might as well start now :)

On Sat, Jun 11, 2016 at 10:12 PM, Dana Olson <notifications@github.com>
wrote:

> Lars requested I upload screens here where I find text difficult to read,
> as I'm playing in my living room on a TV, sitting on a sofa, with a Steam
> Controller in hand.
>
> Unless I specify otherwise, the text in question is always the black text
> on the textured background in the images. It just seems that it's the only
> stuff that is more difficult to read for me; maybe it just needs a bit more
> weight and/or size to the font.
>
> [image: 20160611223458_1]
> <https://cloud.githubusercontent.com/assets/6351421/15988675/9a673dae-3027-11e6-8f2c-bb03a6d1bb5b.jpg>
>
> [image: 20160611225619_1]
> <https://cloud.githubusercontent.com/assets/6351421/15988679/a818e4ca-3027-11e6-98c6-82699d9c3daa.jpg>
>
> [image: 20160611230047_1]
> <https://cloud.githubusercontent.com/assets/6351421/15988712/7a19c372-3028-11e6-96d0-461fe1fd4679.jpg>
>
> [image: 20160611230927_1]
> <https://cloud.githubusercontent.com/assets/6351421/15988753/e0b9329c-3029-11e6-903a-bf5883b51bec.jpg>
> (Tooltip in that one could be slightly larger, but it is readable anyhow).
>
> Really, I think black on that one background is what causes me the most
> problems.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1001>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-OtIqjCWIbj2V0-w7d9-jxY5VNF3ks5qK3kvgaJpZM4IzsTi>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by adolson** [comment]
Yeah, that background is the most trouble for me. I think it it were
lighter it would probably solve it since similar-sized text seems OK on the
solid white or yellow backgrounds. Increasing the weight slightly might do
it, too.

**Comment by larsiusprime** [comment]
This is fixed for the console releases at least. I might roll it into the normal version too.
