### ISSUE TITLE
Recruit lacks capitalization.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1003]
Just looks weird, not matching Weapons / Armor.

![ze](https://cloud.githubusercontent.com/assets/19625520/15989081/d0af19a2-3038-11e6-95ec-f1ed76a533cf.png)

**Comment by dqhol** [comment]
'Talk' in NG+, too.

**Comment by larsiusprime** [comment]
Seems fixed.
