### ISSUE TITLE
Play time accumulating faster than reality?

### ISSUE THREAD

**Issue by adolson** [larsiusprime/tdrpg-bugs#1004]
I started a new game tonight and played probably 2.5 hours, but definitely no more than 3 hours (checking timestamps from when I uninstalled and reinstalled the game). However, the time tracked by the game is saying I played 5 hours 15 minutes. My first thought is perhaps it's somehow doubling the time I'm playing, as that would probably be fairly close to what I really played.

(I am assuming that the speed of the battles has no bearing on the tracked time, as that would be kinda silly).

I'm on Debian, 64-bit, if it makes any difference.

**Comment by larsiusprime** [comment]
Fixed! Finally!

2.0.6 has the fix
