### ISSUE TITLE
German translation: weird characters in the cutscene viewer thingy

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#1007]
![image](https://cloud.githubusercontent.com/assets/19844461/15990865/236e9038-30a1-11e6-89dd-a5e308471779.png)

We got those in act 3, scene 1 (see above) and also

act 7, endings a, d, and e

**Comment by ManDude** [comment]
What letters are those supposed to be?

**Comment by larsiusprime** [comment]
I don't think there's supposed to be anything there at all, I wonder if it's garbage formatting characters sneaking in or something.

**Comment by ThomasFaust** [comment]
Yup, definitely garbage.
