### ISSUE TITLE
NG+ bows are the only items to lack the "A mysterious + symbol..." text

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1012]

**Comment by ManDude** [comment]
Wait what? You mean "An enchantment has made this weapon stronger." or something?

**Comment by dqhol** [comment]
No. The storebought ones.

**Comment by larsiusprime** [comment]
There was a tab where it shouldn't have been in the TSV file :) Fixed in 2.0.0
