### ISSUE TITLE
Slak's out of position in the Forgotten Temple sidequest.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1014]
Markos covers him all up.

![ze](https://cloud.githubusercontent.com/assets/19625520/15998634/dcbc52fc-310d-11e6-9f25-8a986f9db956.png)

**Comment by IBwWG** [comment]
Also his name isn't bold, should it be?

**Comment by dqhol** [comment]
Mentioned in another bug report already. No, they're not bold, but they probably should be.

**Comment by larsiusprime** [comment]
Slak's still a bit broken but I fixed the bold text in 2.0.0
