### ISSUE TITLE
German translation: Meet the Berserker - last page untranslated

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#1015]
![image](https://cloud.githubusercontent.com/assets/19844461/16000324/0726ce26-314c-11e6-80d4-2cc76348d078.png)

**Comment by larsiusprime** [comment]
Dunno what causes this, can't fix in time for launch I think :( 

Will look into it later.

**Comment by ManDude** [comment]
Is this actually translated in the files?

**Comment by larsiusprime** [comment]
It IS! Or at least seems so. Something weird is going on that's going to
require me to dig into this when I'm not sleep deprived. It's probably
something obvious, but it's late-game content so I'll have to circle back
to it while I put out other fires.

On Tue, Jun 14, 2016 at 12:06 AM, ManDude <notifications@github.com> wrote:

> Is this actually translated in the files?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1015#issuecomment-225781002>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-LNxgt53pwsh11TwL0V-DOIlM1HFks5qLjbkgaJpZM4I0EmI>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
So I found it, you had a random "B" at the beginning of the flag marker for that particular page, so it couldn't find it and fell through to english text.

Fixed in 2.0.8
