### ISSUE TITLE
German translation/general: diary secret content

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#1017]
![image](https://cloud.githubusercontent.com/assets/19844461/16000383/5d9e7394-314c-11e6-9393-d80ba1fcb271.png)

There's a big gap (English as well), is that supposed to be there? (Or haven't I unlocked everything? In that case, disregard.)

Furthermore, in German it still says "SECRET" which should read "GEHEIM"

**Comment by larsiusprime** [comment]
Fixed in 1.0.1
