### ISSUE TITLE
32-bit Linux version (via itch.io app) segfaults on startup on Linux Mint 17.2

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1019]
Version downloaded just now (assuming it's at least 0.9.5...given #1018) gave a generic error trying the Launch button in the itch.io app.  Opened its installation folder and tried both the .sh file and the dqi686 (which the .sh runs, effectively) and got this:

```
~/.config/itch/apps/Defenders Quest Valley of the Forgotten DX $ ./DefendersQuest.sh
Could not find primitive lime_drop_event_manager_register__prime.
Could not find primitive lime_window_set_maximized__prime.
Segmentation fault
```

This is my first time trying it on Linux and on this machine.  It's a netbook (Intel Atom n2600 processor, 1 GB RAM) running Linux Mint 17.2.

**Comment by larsiusprime** [comment]
Hmmmm. I'm wondering if the lime ndll needs to be switched on, too. I guess I can start doing that. Are you open to doing a quick test in the next hour to verify?

**Comment by IBwWG** [comment]
Sure thing.  :)

**Comment by IBwWG** [comment]
BTW not sure what you meant by switched on, but I seem to recall that there was a similar sounding file in the root of the install dir.

**Comment by IBwWG** [comment]
Also, I have another netbook here, with an Intel Atom n280 (64-bit processor, but 32-bit OS installed, according to `uname -m`), and it also crashes on startup, but differently:

```
~/.config/itch/apps/Defenders Quest Valley of the Forgotten DX$ ./dqi686
Called from *::closure /usr/lib/haxe/std/cpp/_std/EReg.hx line 174
Called from cpp.Lib::load /usr/lib/haxe/std/cpp/Lib.hx line 34
Error : Could not load module regexp@regexp_new_options__2
```

**Comment by IBwWG** [comment]
Saw your tweet and tried it on both...seems to be two steps back: on both machines it appears that Itch now thinks that they're macs.  They don't launch, and if you go into the install folder it now looks completely different--there's a DefendersQuest.app/Contents/MacOS(etc.) hierarchy instead of lime.ndll, DefendersQuest.sh, dqi686, etc.

**Comment by larsiusprime** [comment]
Whoops, I mislabled them. I just clicked the right boxes, does it look correct now?

**Comment by IBwWG** [comment]
Mint now says something like `ln: Cannot make a symbolic link out of lime.ndll: file already exists`.  (Indeed, it does.)
Ubuntu says more or less the same thing as before (EReg.hx and Lib.hx trace) but first has a line that I have to look up, because it's a German install of Ubuntu, but I think it's saying what Mint now says.

**Comment by larsiusprime** [comment]
Gotcha, I have some fresh linux builds coming in the next 5 minutes...

On Tue, Jun 14, 2016 at 1:19 AM, KJB <notifications@github.com> wrote:

> Mint now says something like ln: Cannot make a symbolic link out of
> lime.ndll: file already exists. (Indeed, it does.)
> Ubuntu says more or less the same thing as before (EReg.hx and Lib.hx
> trace) but first has a line that I have to look up, because it's a German
> install of Ubuntu, but I think it's saying what Mint now says.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1019#issuecomment-225789869>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-JbQ4bERPjh9pEg3Me97aL5okERvks5qLkgAgaJpZM4I0PTq>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
They don't seem to download to my itch.io app on either machine...

BTW, I forgot, this time I did `./DefendersQuest.sh` rather than `./dqi686`.  On Mint, the `ln` line is from the .sh script.  The segfault is from a window that pops up for only an instant.

**Comment by IBwWG** [comment]
OK, the Ubuntu machine is downloading, but the Mint one still not, even after restarting itch a few times.

Also, verified on the Mint machine that the lime dll is a symlink to the correct version, i686, in the same dir.

**Comment by IBwWG** [comment]
The Ubuntu box now does [exactly as before](https://github.com/larsiusprime/tdrpg-bugs/issues/1019#issuecomment-225614577)

**Comment by larsiusprime** [comment]
Okay, so was kind of afraid of that. Looks like *ALL* the libraries need 32-bit and 64-bit versions, arg. Luckily I know what to try.

**Comment by IBwWG** [comment]
OK, I see it now making more symlinks.

On Mint, it still segfaults on dqi686, unfortunately.  Ubuntu, downloading now...

**Comment by larsiusprime** [comment]
Weird (sigh).

On Tue, Jun 14, 2016 at 12:45 PM, KJB <notifications@github.com> wrote:

> OK, I see it now making more symlinks.
>
> On Mint, it still segfaults on dqi686, unfortunately. Ubuntu, downloading
> now...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1019#issuecomment-225959672>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-AKwmwwcG7bm85AnafhDQES237F0ks5qLuifgaJpZM4I0PTq>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
(Sorry.)

**Comment by IBwWG** [comment]
Also, good news!  On Ubuntu it works fine now, 2.0.0!

**Comment by larsiusprime** [comment]
Sweet

**Comment by larsiusprime** [comment]
Too quick on the draw I guess 
So here's what I'd like to know -- is it a script setup issue, or a problem with the libraries themselves. Because all the library files (both 32 bit and 64 bit) and both executables are just there, I wonder if some smart linux nerd will poke around in there and just tell us what the launch script should be instead.

(wishful thinking)

**Comment by IBwWG** [comment]
I don't think it's a script setup problem.  Symlinks look fine.  And it's not DefendersQuest.sh-related, because even launching dqi686 just immediately shows and hides a window, and says it segfaulted.

**Comment by IBwWG** [comment]
/var/log/syslog says this:

```
 dqi686[5725]: segfault at 74614472 ip b10fdd5c sp bfdf8e40 error 4 in i915_dri.so[b0e8b000+526000] 
```

**Comment by IBwWG** [comment]
This could be something with my hardware or options or something.  Anyway since it's not general it can go on the backburner...

**Comment by IBwWG** [comment]
Also I just got HaxeFlixel set up on this Mint machine, and even without HF, just the PiratePig OpenFL demo, locally compiled, gives a similar segfault and syslog entry.

**Comment by larsiusprime** [comment]
Hmmm, interesting! I wonder if it has something to do with your setup.
Let's see if anyone else on linux has an issue with this build.

On Wed, Jun 22, 2016 at 10:41 PM, KJB <notifications@github.com> wrote:

> Also I just got HaxeFlixel set up on this Mint machine, and even without
> HF, just the PiratePig OpenFL demo, locally compiled, gives a similar
> segfault and syslog entry.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1019#issuecomment-227941975>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-MgOwiES_yJK3LI9-eOg1BrZ1pmAks5qOgB7gaJpZM4I0PTq>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
I may not be the only one who would run into this, I've heard a few more examples lately in other contexts.

So I reported it here, and there's an interesting result that got it to work: https://github.com/openfl/openfl/issues/1176
