### ISSUE TITLE
German translation: savegame menu tool tips untranslated

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#1020]
![image](https://cloud.githubusercontent.com/assets/19844461/16020829/0ff6c326-31b0-11e6-9da1-6f1a1b2b3366.png)

applies to Spiel+, Export, Löschen, and Import

**Comment by larsiusprime** [comment]
If you provide translations for these I'll put them in.

**Comment by larsiusprime** [comment]
Made a comprehensive list of what appears to be missing, shared it with you

**Comment by larsiusprime** [comment]
Fixed in 2.0.8
