### ISSUE TITLE
'Defense' is cut off in the party menu.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1021]
![ze](https://cloud.githubusercontent.com/assets/19625520/16028203/038bc690-31ab-11e6-9b02-75bd88ce62fa.png)

Lowest resolution, standard.

**Comment by ManDude** [comment]
Maybe it should be replaced with the icon.

**Comment by larsiusprime** [comment]
Fixed in 2.0.0
