### ISSUE TITLE
Obtaining several books still lists Azra as $MCG

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1025]
![ze](https://cloud.githubusercontent.com/assets/19625520/16028705/e06bbf26-31af-11e6-9cd5-bd63508cad94.png)

**Comment by larsiusprime** [comment]
What version?

**Comment by dqhol** [comment]
0.9.8

**Comment by larsiusprime** [comment]
Fixed in 2.0.0

**Comment by ManDude** [comment]
2.0.0? Weren't we on 1.0.0 or something before?

**Comment by larsiusprime** [comment]
Jumping to 2.0.0 for release, because the old version of the game was listed as 1.X.Y, and so it will be confusing if our number isn't higher.
