### ISSUE TITLE
Beating a bonus level in Normal makes NG+'s bonus level think you've already beaten it.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1026]
You can still get the reward, but visually the text is white, making you think you've already beat the  level.

![ze](https://cloud.githubusercontent.com/assets/19625520/16028806/dcf4e920-31b0-11e6-8cef-59891d2ad83f.png)

**Comment by larsiusprime** [comment]
This is fixed in 2.0.6
