### ISSUE TITLE
Importing doesn't require .dfq files, results in crash.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1027]
![ze](https://cloud.githubusercontent.com/assets/19625520/16046547/d68d1818-321a-11e6-89a6-4557ff037bcb.png)

And if you accidentally select anything that isn't a .dfq file, Null Object Reference.

Can't imagine this will affect anyone but the butterfingered.

**Comment by larsiusprime** [comment]
Yeah, result of a last minute patch to fix file dialogues on Linux. I'll
patch in proper file filtering / error checking pots launch.

On Tue, Jun 14, 2016 at 9:30 AM, dqhol <notifications@github.com> wrote:

> [image: ze]
> <https://cloud.githubusercontent.com/assets/19625520/16046547/d68d1818-321a-11e6-89a6-4557ff037bcb.png>
>
> And if you accidentally select anything that isn't a .dfq file, Null
> Object Reference.
>
> Can't imagine this will affect anyone but the butterfingered.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1027>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-GX_b_kNnz2FxSncuh98GjWvtvwZks5qLrsFgaJpZM4I1Yqc>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
