### ISSUE TITLE
Missing background in options menu, battle, town etc.

### ISSUE THREAD

**Issue by Deraen** [larsiusprime/tdrpg-bugs#1029]
Steam version on Ubuntu 16.04 64bit.

The background texture for options menu, new battle view, town etc. is not properly stretched and is only small part is shown in the left top corner. There are similar problems with tooltip textures in party screen also (active character, skill tooltip).

![image](https://cloud.githubusercontent.com/assets/648087/16054254/fee3cd0c-3274-11e6-8158-fd854e548b60.png)

![image](https://cloud.githubusercontent.com/assets/648087/16054517/2c2a8098-3276-11e6-8307-f5cd0934a664.png)

![image](https://cloud.githubusercontent.com/assets/648087/16054281/1a5951ec-3275-11e6-8cd5-7730d0f38c6c.png)
 
![image](https://cloud.githubusercontent.com/assets/648087/16054436/cb1e08d8-3275-11e6-97b1-f175ddd18494.png)

**Comment by IBwWG** [comment]
How much graphics memory do you have?

**Comment by Deraen** [comment]
2GB (Nvidia GTX770)

**Comment by IBwWG** [comment]
Er, what I meant to ask was, do you know your graphics card's max texture size...only because I ran into something similar with my game, where too large a texture for a system (in this case the parchment background) just wouldn't show at all.  Common configs are 1024x1024, 2048x2048, 4096x4096.

**Comment by IBwWG** [comment]
Although with that card I doubt it would be so low.

**Comment by larsiusprime** [comment]
Can anyone else confirm whether this is happening to them too on a 64-bit system? I want to isolate whether it's a "some people" or "all people" problem. This is certainly the first I've seen of it.

**Comment by Deraen** [comment]
I have two displays, 1920x1200 in pivot and 4k. I tried with only the 1920x1200 display without rotation and no change.

But I found that using a smaller resolution fixes this, e.g. 1366x768 instead of 1920x1200 window.

**Comment by larsiusprime** [comment]
Ah, I can definitely confirm I have not tested this robustly at 4K on linux! That might be our issue (I don't have a 4K monitor so I have to rely on testers to help with these things).

When I have time to give this its proper attention, would you be willing to test some builds that attempt to fix this?

**Comment by Deraen** [comment]
Seems like the problem is triggred by resolution 1920x1200 or larger, 1920x1080 works.

Sure, I'll be happy to help testing this.

**Comment by Deraen** [comment]
Yep, I booted to Windows 10 and I'm seeing the same problem here.

**Comment by larsiusprime** [comment]
Okay, well looks like a generic problem them. I just need to implement properly intelligent scaling for 4K, nothing I can't handle in the inevitable laundry list of post-launch bugs...

**Comment by 1skandar** [comment]
I'd like to add that I have this problem also. Any fullscreen option triggers it, and any windowed mode over half my resolution, 1280x720. I can't even choose my full resolution option at 2560x 1440

**Comment by larsiusprime** [comment]
Okay, I'm thinking the real, true, underlying culprit here is just a case of running out of texture memory, which might happen for some people at resolutions less than 1080p.

So, a quick test of this is to select a resolution with the problem, then go into the video options, and set sprites to "original" and see what happens on the overworld. The original art uses less memory, so if this is the culprit maybe things will start working again?

**Comment by Deraen** [comment]
Reproduced with original sprites:

![image](https://cloud.githubusercontent.com/assets/648087/16121344/8fee6f1a-33eb-11e6-8b98-68de63625f7c.png)

**Comment by 1skandar** [comment]
Yeah, fairly new graphics cards should not be running out of texture memory.

**Comment by larsiusprime** [comment]
This is fixed now in the latest patch.

**Comment by Deraen** [comment]
Yep, it works! :cake:
