### ISSUE TITLE
Slow Start-book makes enemies disappear from map.

### ISSUE THREAD

**Issue by razakin** [larsiusprime/tdrpg-bugs#1030]
Operating System: Windows XP
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : Steam DQ1 2.0.0

With the slow start-book equipped, enemies spawn from the spawn points, but then the enemies instantly move away from the map and thus disappear, making it impossible to clear the map.

**Comment by larsiusprime** [comment]
This will be fixed in the next major patch, thanks for the report.
