### ISSUE TITLE
Cannot run DX version from Steam client

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#1032]
This updated start script solves the issue (at least for me):

[DefendersQuest.txt](https://github.com/larsiusprime/tdrpg-bugs/files/314926/DefendersQuest.txt)

update: this is a linux only issue

**Comment by ManDude** [comment]
Assuming this is a Linux issue.

**Comment by larsiusprime** [comment]
This should be fixed now
