### ISSUE TITLE
Change resolution crash

### ISSUE THREAD

**Issue by tdthread** [larsiusprime/tdrpg-bugs#1036]
All video options grayed out and clicking full screen generates error message: 

Error! Scale must be positive &>0! (Scale was = 0)

Deluxe game, full version on windows 10

**Comment by ManDude** [comment]
What is the resolution of your monitor?

**Comment by tdthread** [comment]
Sorry . . .  1920x1080, also a laptop

 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by larsiusprime** [comment]
It is really strange to have 1080p monitors crashing out with this error...

The function in question that's breaking is this:

```haxe
public static function loadMonoScaledImage(src:String,Scale:Float,smooth:Bool=true,checkFlxBitmap:Bool=false,fixAlphaChannel:Bool=false):String
	{
		var bmpSrc:String = gfx(src);
		
		var	testBmp:BitmapData = null;
		
		if (!checkFlxBitmap)
		{
			testBmp = Assets.getBitmapData(bmpSrc, false);
			if (testBmp == null)
			{
				testBmp = Assets.getBitmapData(bmpSrc, true);
			}
		}
		else
		{
			var flximg = FlxG.bitmap.get(bmpSrc);
			testBmp = flximg != null ? flximg.bitmap : null;
		}
		
		if (testBmp != null)	//if the master asset exists
		{
			if (Scale <= 0)
			{
				throw "Error! Scale must be positive & > 0! (Scale was = " + Scale+")";  //<-- crash happens here
			}
			
			//if final size != master asset size, we're going to scale it
			if (Math.abs(Scale-1.00) > 0.001) 
			{
				var scaleKey:String = bmpSrc +"_ScaleX" + Scale;	//generate a unique scaled asset key
				
				//if it doesn't exist yet, create it
				if (FlxG.bitmap.get(scaleKey) == null)
				{
					var scaledBmp:BitmapData = new BitmapData(Std.int(testBmp.width*Scale), Std.int(testBmp.height*Scale),true, 0x00000000);	//create a unique bitmap and scale it
					
					var m:Matrix = getMatrix();
					m.identity();
					m.scale(Scale, Scale);
					scaledBmp.draw(testBmp, m, null, null, null, smooth);
					
					if (fixAlphaChannel)
					{
						//Create a black canvas
						var black = new BitmapData(scaledBmp.width, scaledBmp.height, true, 0xFF000000);
						//Copy the image onto it
						black.copyPixels(scaledBmp, scaledBmp.rect, new Point(), null, null, true);
						//Copy the alpha channel onto it
						black.copyChannel(scaledBmp, scaledBmp.rect, new Point(0, 0), BitmapDataChannel.ALPHA, BitmapDataChannel.ALPHA);
						
						var temp = scaledBmp;
						scaledBmp = black;
						temp.dispose();
					}
					
					var finalKey = FlxG.bitmap.add(scaledBmp, true, scaleKey);			//store it by the unique key
				}
				
				return scaleKey;										//return the final scaled key
			}
			else
			{
				FlxG.bitmap.add(testBmp, false, bmpSrc);
				return bmpSrc;		//couldn't scale it, return master asset key
			}
		}
		
		return null; 				//failure
	}
```

So now I need to deduce what is leading up to this...

**Comment by larsiusprime** [comment]
I got it!

It's so simple now that I think about it. The game simply can't tell what kind of resolution you have, it's getting 0,0 returned to it.

So every resolution is "bigger" than your monitor (and thus greyed out) and it has some kind of divide by zero error or whatever during image scaling.

So obviously I need to either fix the "get resolution" function, or have some elegant fallback when the game has no information about your display device to go off of.

**Comment by Xjph** [comment]
I don't know if you've made any progress on this or not, but as a potential fall back can you use the systems currently set desktop resolution?  Regardless of whether or not it's the native resolution of the display it should at least _work._

**Comment by larsiusprime** [comment]
That's the tricky bit, @Xjph -- that's the very value I'm trying to read that's returning 0,0.

I'll have a small test application uploaded here in a second that should help with some diagnostics if either of you want to try it out

**Comment by Xjph** [comment]
Wow.  I think that's the fastest response from a developer I've ever had in my life, including the ones I _work with!_ ;)

Certainly can't say you're not on top of things!

**Comment by larsiusprime** [comment]
@tdthread, @Xjph: can you two try running this file?
https://drive.google.com/open?id=0B82nNNq_hucHNm5nSmg1dmtFZms

It's an exe inside a zip. It should output something like this:

![2016-06-15 14_32_50-screenresolutionfail](https://cloud.githubusercontent.com/assets/739064/16094489/173435fe-3306-11e6-8383-ad6e0ae853d9.png)

**Comment by Xjph** [comment]
Getting this:

![image](https://cloud.githubusercontent.com/assets/455726/16094734/2b90874e-331c-11e6-8f91-3018670f006e.png)

And I have to step out for a bit, so responses will now be a bit more delayed.

**Comment by larsiusprime** [comment]
D'oh, let me pack in the libs with it...

**Comment by larsiusprime** [comment]
Try this:
https://drive.google.com/open?id=0B82nNNq_hucHQk5JYWJVb19ZaXM

**Comment by tdthread** [comment]
Returns this:

 



 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by larsiusprime** [comment]
What is "This?" It's blank for me.

**Comment by larsiusprime** [comment]
I think if that was an image from your email it didn't come through, maybe just type the text?

**Comment by tdthread** [comment]
PNG attached but here’s what it says: 

 

Capabilities.screenResolutionX/Y =0,0

Capabilities.screenDPI = 0

Lib.application.window.width/height = 800,480

 

 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by larsiusprime** [comment]
Okay so we have the confirmation, that's exactly what I thought it was. Now I can get to work figuring out what causes it.

**Comment by JulienDemaziere** [comment]
Same problem here and same result from test app : 

Capabilities.screenResolutionX/Y = 0,0
Capabilities.screenDPI = 0
Lib.application.window.width/height = 800,480

Windows 10 Pro, resolution : 2560 x 1440, dpi/zoom : 125%
GPU : GeForce 970 GTX, driver version 368.22
Tried with single and dual screen.

The non DX version works fine and I can select any resolution I want.

**Comment by larsiusprime** [comment]
Let's try another test:

> wmic desktopmonitor get screenwidth, screenheight

Enter that into a command line and tell me what you get.

**Comment by tdthread** [comment]
Screenheight    Screenwidth

1080                    1920

 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by larsiusprime** [comment]
Okay that's promising, I might be able to work around this issue on windows by calling wmic to get the screen resolution.

**Comment by larsiusprime** [comment]
Alrighty can you try this one too? @tdthread @juliendemaziere ?
https://drive.google.com/open?id=0B82nNNq_hucHcXpmeGFSQmZ1Vzg

This should output two additional lines "wmic screenwidth" and "wmic screenheight"

If this works then I'll be able to incorporate this test into the game.

**Comment by tdthread** [comment]
Capabilities.screenResolutionX/Y = 0,0

Capabilities.screenDPI = 0

Lib.application.window.width/height = 800,400

wmic screenwidth = 0

wmic screenheight = 0

 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by JulienDemaziere** [comment]
Same result : 0

Capabilities.screenResolutionX/Y = 0,0
Capabilities.screenDPI = 0
Lib.application.window.width/height = 800,400
wmic screenwidth = 0
wmic screenheight = 0

**Comment by larsiusprime** [comment]
Okay, one more time, @juliendemaziere @tdthread

https://drive.google.com/open?id=0B82nNNq_hucHODZDYzRyR1lZZkU

Thanks for your patience

**Comment by JulienDemaziere** [comment]
Got "square" characters for "raw screenwidth"

![untitled](https://cloud.githubusercontent.com/assets/19961409/16098889/8cd63786-3355-11e6-9190-5d9e8fabb7e5.png)

**Comment by tdthread** [comment]
Square boxes at the end? See attached.

 

Capabilities.screenResolutionX/Y = 0,0

Capabilities.screenDPI = 0

Lib.application.window.width/height = 800,400

wmic screenwidth = 1920

wmic screenheight = 1080

raw screenwidth = ScreenWidth 

 

 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by larsiusprime** [comment]
Okay, so that's an interesting result. The squares aren't a big deal. For one of you, we can get the screen resolution out of this method. For the other, we can't. Argh....

**Comment by larsiusprime** [comment]
Also @tdthread, just an FYI, any images you attach in an email don't show up over here on the github page :) We can't see them. Not a big deal but just thought you should know.

**Comment by tdthread** [comment]
Nope, didn’t know that. I’m new at this. J

 

Tom Threadgill

 

 <http://www.tomthreadgill.com/Blog> TomThreadgill.com

 <http://www.eagleeyeedits.com/> EagleEyeEdits.com

**Comment by larsiusprime** [comment]
Alright! I think I finally got it. Try this one.
https://drive.google.com/open?id=0B82nNNq_hucHczIwYnpZVzBwT2M

This one even gives me results!

**Comment by larsiusprime** [comment]
ping @tdthread @juliendemaziere

**Comment by tdthread** [comment]
![capture](https://cloud.githubusercontent.com/assets/19939437/16099419/dd8faaf0-331d-11e6-9bae-f927f87146b0.PNG)

Hope this works...

**Comment by larsiusprime** [comment]
Yep! I can see the image. This is a good result, just waiting to hear from Julien now.

**Comment by larsiusprime** [comment]
I'm pretty confident this is fixed now.

Fix will be in 2.0.1

**Comment by JulienDemaziere** [comment]
It worked :) 

![untitled](https://cloud.githubusercontent.com/assets/19961409/16106405/6f47ecac-3394-11e6-924c-90d7a7d56f4e.png)

**Comment by tdthread** [comment]
Can confirm the fix worked. Installed the new beta patch and can change resolutions.

**Comment by larsiusprime** [comment]
Okay it worked for some but not quite everybody. I'm doing one more patch to be super duper sure.

**Comment by larsiusprime** [comment]
Okay new patch is out.
