### ISSUE TITLE
Trackpad taps not registering as clicks on Mac

### ISSUE THREAD

**Issue by walkie** [larsiusprime/tdrpg-bugs#1039]
## Basic Info

```
Mac OS X 10.11.5
Download
Full Version
Version: Steam DQ1 2.0.0 - full -
```

On a Mid-2014, MacBook Pro (i.e. not a "Force Touch" trackpad).
## Steps to Reproduce
1. Launch game.
2. Attempt to click on menu items by lightly tapping the trackpad.
## Expected

Menu items respond to taps as though clicked on.
## Actual

Only approximately 50% of taps register as clicks. This problem appears both in menus and in-game. 
## Workaround

Press the trackpad hard enough to register a mechanical click. These always register as clicks. (Unfortunately, this gets uncomfortable pretty quickly.)
## Other Notes

This is a problem in a few other games on Mac, including Terraria, Don't Starve, and Human Resource Machine. However, the pre-DX version of Defender's Quest worked just fine.

**Comment by larsiusprime** [comment]
I have the same kind of MacBook Pro as you so hopefully this will be easy
to reproduce. It's got to be something with the underlying tech we're using
(SDL 2 this time instead of Adobe AIR) and how it handles input events from
the hardware at a low level.


On Tue, Jun 14, 2016 at 7:38 PM, Eric Walkingshaw <notifications@github.com>
wrote:

> Basic Info
>
> Mac OS X 10.11.5
> Download
> Full Version
> Version: Steam DQ1 2.0.0 - full -
>
> On a Mid-2014, MacBook Pro (i.e. not a "Force Touch" trackpad).
> Steps to Reproduce
>
>    1. Launch game.
>    2. Attempt to click on menu items by lightly tapping the trackpad.
>
> Expected
>
> Menu items respond to taps as though clicked on.
> Actual
>
> Only approximately 50% of taps register as clicks. This problem appears
> both in menus and in-game.
> Workaround
>
> Press the trackpad hard enough to register a mechanical click. These
> always register as clicks. (Unfortunately, this gets uncomfortable pretty
> quickly.)
> Other Notes
>
> This is a problem in a few other games on Mac, including Terraria, Don't
> Starve, and Human Resource Machine. However, the pre-DX version of
> Defender's Quest worked just fine.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1039>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-P8RiaefjzDd-K_f-1135iw6DyzGks5qL0l6gaJpZM4I15Wp>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
