### ISSUE TITLE
No border around any of the bonus levels with Original Sprites.

### ISSUE THREAD

**Issue by Wollmilchkuh** [larsiusprime/tdrpg-bugs#1040]
**Basic Info**

- Windows 10 64bit
- Steam DQ1 2.0.0

**Steps to Reproduce:**

Video Options:

- Select "Windowed Mode"
- Change "Game Window Size" to anything other than "800x600"
- Select "Original Sprites"

- Play any of the "Bonus Levels"

![20160615040539_1](https://cloud.githubusercontent.com/assets/19942096/16066047/5cdaae36-32b0-11e6-85ba-00d6237f3bd6.jpg)
![20160615040647_1](https://cloud.githubusercontent.com/assets/19942096/16066048/5cdb27e4-32b0-11e6-9469-d914a8d8ac7e.jpg)
![20160615040700_1](https://cloud.githubusercontent.com/assets/19942096/16066049/5cdc6730-32b0-11e6-9799-bfb7bd10da99.jpg)
![20160615040712_1](https://cloud.githubusercontent.com/assets/19942096/16066051/5cdfd1ae-32b0-11e6-94a2-359781906747.jpg)
![20160615040724_1](https://cloud.githubusercontent.com/assets/19942096/16066050/5cdde736-32b0-11e6-827b-daa4f0622a10.jpg)
![20160615040737_1](https://cloud.githubusercontent.com/assets/19942096/16066052/5ce04026-32b0-11e6-9e61-1e2ddc7efe92.jpg)
![20160615040749_1](https://cloud.githubusercontent.com/assets/19942096/16066053/5cf4e9cc-32b0-11e6-91ef-04af142b16db.jpg)

**Comment by larsiusprime** [comment]
Great catch!

On Tue, Jun 14, 2016 at 9:22 PM, Wollmilchkuh <notifications@github.com>
wrote:

> *Basic Info*
>
>    - Windows 10 64bit
>    - Steam DQ1 2.0.0
>
> *Steps to Reproduce:*
>
> Video Options:
>
>    - Select "Windowed Mode"
>    - Change "Game Window Size" to anything other than "800x600"
>    -
>
>    Select "Original Sprites"
>    -
>
>    Play any of the "Bonus Levels"
>
> [image: 20160615040539_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066047/5cdaae36-32b0-11e6-85ba-00d6237f3bd6.jpg>
> [image: 20160615040647_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066048/5cdb27e4-32b0-11e6-9469-d914a8d8ac7e.jpg>
> [image: 20160615040700_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066049/5cdc6730-32b0-11e6-9799-bfb7bd10da99.jpg>
> [image: 20160615040712_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066051/5cdfd1ae-32b0-11e6-94a2-359781906747.jpg>
> [image: 20160615040724_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066050/5cdde736-32b0-11e6-827b-daa4f0622a10.jpg>
> [image: 20160615040737_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066052/5ce04026-32b0-11e6-9e61-1e2ddc7efe92.jpg>
> [image: 20160615040749_1]
> <https://cloud.githubusercontent.com/assets/19942096/16066053/5cf4e9cc-32b0-11e6-91ef-04af142b16db.jpg>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1040>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-I4xzmo6O_9Yh_rC4ONA50UCc36Yks5qL2HjgaJpZM4I18Cp>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
This should be fixed now
