### ISSUE TITLE
Equipment tooltip won't show in battle

### ISSUE THREAD

**Issue by joaociocca** [larsiusprime/tdrpg-bugs#1041]
Couldn't find an open issue about this. When in-battle, while selecting a defender, mousing over equipment won't show tooltips like it used to in the old version. Any defender, both weapons and armors.

**Comment by ManDude** [comment]
This is true. Surprised this wasn't reported already.

**Comment by larsiusprime** [comment]
This is fixed, might be released already, but definitely is in 2.0.7
