### ISSUE TITLE
Dragons maxed out range won't show Melee/Ranged

### ISSUE THREAD

**Issue by joaociocca** [larsiusprime/tdrpg-bugs#1046]
At least happened here to me. Last stage, extreme, 2nd recruit, lvl 60. Range display was nice up until 4 lvl boost, when I boosted for the last, the inner Melee circle vanished, along with the "Melee" and "Ranged" texts, leaving only the outer Ranged circle, like a Ranger...

**Comment by ManDude** [comment]
What are you playing this on? What are the system specs?

**Comment by joaociocca** [comment]
------------------
System Information
------------------
      Time of this report: 6/15/2016, 12:36:13
             Machine name: JOHNNYC-PC
         Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release_sec.160422-1850)
                 Language: Portuguese (Regional Setting: Portuguese)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: To be filled by O.E.M.
                     BIOS: F13
                Processor: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 CPUs), ~3.1GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16330MB RAM
                Page File: 14588MB used, 4174MB available
              Windows Dir: C:\Windows
          DirectX Version: 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Not Available
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.10586.0000 64bit Unicode

anything else you need?

**Comment by larsiusprime** [comment]
I can't reproduce this, is it still happening? If so, what resolution are you using?
