### ISSUE TITLE
Penalty for failure in DQDX is added instead of subtracted

### ISSUE THREAD

**Issue by liartar** [larsiusprime/tdrpg-bugs#1047]
# Basic Info

```
Windows 10
Version # STEAM DQ1 2.0.0
```
# Description

As far as I can tell, in DQDX penalties in case of mission failure are added instead of being subtracted. See screenshot for after battle summary:

![screenshot 2016-06-15 10 47 04](https://cloud.githubusercontent.com/assets/4038140/16083388/209d8884-3315-11e6-9220-48f592d18ad9.png)

# Steps to reproduce
1. Start any mission
2. Kill some enemies, but lose the mission
3. Look at the total XP and scrap gained in the after-mission summary

P. S. Issue copied from community forum ([Penalty for failure in DQDX is added instead of subtracted](http://discourse.leveluplabs.com/t/penalty-for-failure-in-dqdx-is-added-instead-of-subtracted/)) for better tracking.

**Comment by ManDude** [comment]
Thank you! This will get sorted out soon.

**Comment by larsiusprime** [comment]
Fixed in 2.0.1
