### ISSUE TITLE
Classes not available in base game after New Game+ has been started

### ISSUE THREAD

**Issue by Blarlack** [larsiusprime/tdrpg-bugs#1049]
1. Finish game in New Game, unlocking New Game+
2. Begin New Game+, unlock a few classes (at the time of writing this, I had just unlocked Ice Mages)
3. Go back to Play (not Play+) and attempt to use Knights or Dragons.

Expected Results:
Since these classes have been unlocked in the base game, they should be usable in the base game.

Actual Results:
Neither Knights or Dragons are available to me in the base game, because I have not yet unlocked them in New Game+.

**Comment by Blarlack** [comment]
Oh, right - I should mention that this was noticed as I'm playing in Hero Mode - I'm not sure if having basic recruits of these classes would affect this outcome at all, but I cannot place either Markos or Niru because I haven't unlocked them.

**Comment by larsiusprime** [comment]
Fixed in 2.0.1
