### ISSUE TITLE
Null Error crash during sheep battle

### ISSUE THREAD

**Issue by Marakk** [larsiusprime/tdrpg-bugs#1050]
Place 5 or more defenders in the narrow, single-tile strip in the far upper-right corner of the map, just below the Blue X spawn location.

Crank the speed up to 4x or 8x.

Boost your defenders to at least level 3 (4 is better).

Wait until Wave 21 (normal) or Wave 27 (advanced).

Game gives a null error and crashes to the desktop.  Too much happening onscreen in too tight an area, perhaps?

**Comment by ManDude** [comment]
Can you reproduce this consistently?

**Comment by Marakk** [comment]
Yeah, I got stuck on this battle until I started putting only a few defenders in other (less optimal) parts of the map.  Every time I load up the "Blue X" area with defenders, it crashes about 75% of the way through the battle.  Happened 4x in a row on Advanced and 3x in a row on Normal.

**Comment by Marakk** [comment]
Clarification: the crash pop-up window reads: "Error - Null Object Reference".  Just happened again when I tried putting 6 level-4 boosted defenders in a tight cluster in the lower-right corner of the map.  Wave 26, Advanced.

**Comment by ManDude** [comment]
Alright. Added the high priority tag so this can get sorted out asap.

**Comment by Marakk** [comment]
At least there's a workaround, if anyone else is getting this - use as few defenders as you can to beat Normal, and spread them out.  I was able to do it with Ketta in the upper left and Slak and Wrenna in the lower left, all at Boost level 2 or 3.  However, at the moment, I can't even seriously attempt Advanced and obviously Extreme would be 100% impossible.

Not sure if this matters, but I do have the "official" Hero Mode enabled.

**Comment by Marakk** [comment]
Happened again in the Tunnel Escape battle.  Same deal: 6 defenders, all highly boosted, all clustered around Azra in the south.  Null Object Reference crash on Wave 9, Advanced.

**Comment by larsiusprime** [comment]
Can you post your save file? Also what resolution are you using?

**Comment by larsiusprime** [comment]
Also do you know how to run the game from the command line? If you do, when it crashes you should be able to see a stack trace which will hopefully isolate the bug.

**Comment by Marakk** [comment]
Resolution: 800x600, windowed mode.  Been running it through Steam.  Where are the save files and how do I run it via command line?

**Comment by Marakk** [comment]
Argh, I feel like a dummy here.  I exported the save file; how do I upload/post it?

**Comment by ManDude** [comment]
Savefiles are stored in %appdata%\LevelUpLabs\DefendersQuest. Put the savefiles into a zip and just drag n' drop them here.

To run from the command prompt, open the cmd prompt then launch the game with it (drag n' drop the .exe to the prompt if you're lazy to type it out).

**Comment by Marakk** [comment]
Here goes:

[DefendersQuest Null Bug Save.zip](https://github.com/larsiusprime/tdrpg-bugs/files/316816/DefendersQuest.Null.Bug.Save.zip)

**Comment by Marakk** [comment]
Wrong file, I was pulling from the legacy version because I'm trying to do this with a headache.  Trying again:

[SAVE_SLOT_1.zip](https://github.com/larsiusprime/tdrpg-bugs/files/316830/SAVE_SLOT_1.zip)

**Comment by Marakk** [comment]
Ugh, also not seeing an .exe file, just a bunch of .xml files (appdata/leveluplabs/dfq folder)

**Comment by ManDude** [comment]
The exe is the game itself and is located in the game's folder. :P

**Comment by Marakk** [comment]
All I have is a demo folder, then achievements.xml, locale.xml, options.xml, paths.xml, then the save file.

**Comment by ManDude** [comment]
The exe is located in the game's folder, not the savefiles folder.

**Comment by Marakk** [comment]
and the game folder is typically where?

**Comment by larsiusprime** [comment]
You can find the game folder by right clicking in the library, then properties, then local files, then "browse game files." It's in some path steam sticks it in.

**Comment by Marakk** [comment]
Yeah, if I run that via the command prompt it fires up on older (legacy) version of the game with different save files.

**Comment by larsiusprime** [comment]
find the exe in the "dx/" folder

**Comment by Marakk** [comment]
Ahh, missed the DX folder.  Sorry for all the hassle! (can you tell I do this sort of stuff a lot?)

**Comment by ManDude** [comment]
It's okay. :)

**Comment by Marakk** [comment]
Hahaha, Null Object pops up right after the HaxeFlixel logo.

**Comment by larsiusprime** [comment]
does it say anything int he stack trace?

**Comment by ManDude** [comment]
I have the same issue. Stack trace:
`Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Colombo II>C:\DefendersQuest\Alpha\DQ1\DefendersQuest.exe

C:\Users\Colombo II>Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 761
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 530
Called from flixel.FlxGame::step flixel/FlxGame.hx line 663
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx line 1486
Called from flixel.FlxGame::update flixel/FlxGame.hx line 713
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 623
Called from com.leveluplabs.tdrpg.State_Init::create com/leveluplabs/tdrpg/State_Init.hx line 101
Called from com.leveluplabs.tdrpg.State_Initializer::create com/leveluplabs/tdrpg/State_Initializer.hx line 41
Called from flixel.addons.ui.FlxUIState::create flixel/addons/ui/FlxUIState.hx line 119
Called from flixel.addons.ui.FlxUITooltipManager::new flixel/addons/ui/FlxUITooltipManager.hx line 53
Called from flixel.addons.ui.FlxUITooltip::new flixel/addons/ui/FlxUITooltip.hx line 38
Called from flixel.addons.ui.FlxUITooltip::refresh flixel/addons/ui/FlxUITooltip.hx line 350
AL lib: (EE) alc_cleanup: 1 device not closed`

**Comment by Marakk** [comment]
C:\Users\Nematocyst>Called from ApplicationMain::main ApplicationMain.hx line 15
9
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/Na
tiveApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_back
end/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 761
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/Di
splayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObje
ct.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDi
spatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 530
Called from flixel.FlxGame::step flixel/FlxGame.hx line 663
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx lin
e 1486
Called from flixel.FlxGame::update flixel/FlxGame.hx line 713
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 623
Called from com.leveluplabs.tdrpg.State_Init::create com/leveluplabs/tdrpg/State
_Init.hx line 101
Called from com.leveluplabs.tdrpg.State_Initializer::create com/leveluplabs/tdrp
g/State_Initializer.hx line 41
Called from flixel.addons.ui.FlxUIState::create flixel/addons/ui/FlxUIState.hx l
ine 119
Called from flixel.addons.ui.FlxUITooltipManager::new flixel/addons/ui/FlxUITool
tipManager.hx line 53
Called from flixel.addons.ui.FlxUITooltip::new flixel/addons/ui/FlxUITooltip.hx
line 38
Called from flixel.addons.ui.FlxUITooltip::refresh flixel/addons/ui/FlxUITooltip
.hx line 350
AL lib: (EE) alc_cleanup: 1 device not closed
"C:\Program Files (x86)\Steam\SteamApps\common\DefendersQuest\dx\DefendersQuest.
exe"

**Comment by ManDude** [comment]
Funny. Exact same trace.

**Comment by Marakk** [comment]
Hopefully all that helps?  I tried running it a second time and it actually booted up the game, going to try and crash another battle quick.

**Comment by ManDude** [comment]
Oh what the heck,. I didn't know the second time it worked. This helps a lot.

**Comment by Marakk** [comment]
No trace this time, just a pop-up windows stating "Null Object" as usual, then the game window closes.  Wave 29, sheep battle, advanced.

**Comment by larsiusprime** [comment]
I put in an if guard for the tooltip error. I'm going to try to repro the sheep bug now that I have your save file. 

ARe you playing fullscreeN?

**Comment by Marakk** [comment]
Nope, 800x600 windowed so I can do other things on my not-so-large laptop monitor while playing.

**Comment by larsiusprime** [comment]
Reproduced

**Comment by larsiusprime** [comment]
```Called from com.leveluplabs.tdrpg.DefenderSprite::tryCheaperAttack com/leveluplabs/tdrpg/DefenderSprite.hx line 886```

**Comment by Marakk** [comment]
Yay!  (?)

**Comment by Marakk** [comment]
Ahh, advanced targeting was my downfall.  Figures.  ;)

**Comment by larsiusprime** [comment]
FIXED.

I was checking an "enemies" array that could be null, or contain null members (but apparently only rarely).

Some null checks in and you can play the whole battle!

**Comment by larsiusprime** [comment]
Fixed in 2.0.1, coming next patch.
