### ISSUE TITLE
Post Your Save File!

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#1052]
I'm working on a new save file bank to help players who have lost their saves from the old game. If you would like to contribute a save, please post it here!

Understand that you're giving us permission to share your save file on our official website for anybody to use for any purpose, ie you're licensing us the data under the MIT license:
https://opensource.org/licenses/MIT

We are most in need of _mid game_ save files with a variety of character party configurations and progress through the game (both before and after new game+ is started).  We have lots of saves already at the very beginning and very end of the game.

The idea is if we can get enough, then players can pick a point that's pretty close to where they last were and keep on going.

**Comment by IBwWG** [comment]
[dq-export-level7.zip](https://github.com/larsiusprime/tdrpg-bugs/files/317205/dq-export-level7.zip)

**Comment by michaelachrisco** [comment]
[export.txt](https://github.com/larsiusprime/tdrpg-bugs/files/321603/export.txt)
(About 1/3 way through game)
