### ISSUE TITLE
German Translation: Cut scene buttons identical

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#1053]
In the steam version (DQ1 2.0.0 - full) the button to move within the dialogs are identical ("Zurück" and "Zurück" instead of "Zurück" and "Weiter").
![screenshot_20160615_215327](https://cloud.githubusercontent.com/assets/1015465/16095233/0809fd28-3344-11e6-8d79-9206a81e3044.png)

**Comment by larsiusprime** [comment]
Fixed in latest build, will roll out soon
