### ISSUE TITLE
Spanish translation marked as fan translation

### ISSUE THREAD

**Issue by FelipeMercader** [larsiusprime/tdrpg-bugs#1054]

**Comment by FelipeMercader** [comment]
Spanish translation is marked both as fan translation and professional translation

**Comment by larsiusprime** [comment]
Whoops!

**Comment by larsiusprime** [comment]
Are there any mistakes on the others?

These should be professional:
-English
-German
-French
-Spanish
-Japanese

These should be volunteer:
-Italian
-Czech
-Korean
-Russian

**Comment by larsiusprime** [comment]
![2016-06-15 21_16_28-defender s quest i](https://cloud.githubusercontent.com/assets/739064/16103447/722d471a-333e-11e6-936e-1156446cd623.png)

Hmmm, are you sure? Where does it say volunteer?

**Comment by larsiusprime** [comment]
Oh, there it is, at the bottom. That's weird.

**Comment by larsiusprime** [comment]
Found it. It's not marked as volunteer, but we have an untranslated string in the "beta" note for Spanish only:

```<text id="es-ES" title="BETA" body="This is a volunteer fan translation.$N$NContributors:"/>```

I just need to replace that with the spanish equivalent for
> This translation is still in beta. Untranslated text, missing characters, and other visual glitches are very likely not the fault of the translator.

**Comment by FelipeMercader** [comment]
Hi Lars,

Sorry for not being able to answer properly to that. I am right now
traveling for a medical family thing and won't have access to my pc
(answering with my phone now).

Yes the other languages are ok but as you can see in your screenshot,
spanish is marked as professional but also as fan in the line below the
name.

Alright, so it would only be the replacement then!

I think I translated it last year. Since I cant check right now, here is
the translation again:
Esta traducción todavía está en beta. Es muy probable que el texto sin
traducir, los caracteres que no se muestran y cualquier otro fallo visual
no sean responsabilidad del traductor.

**Comment by larsiusprime** [comment]
Perfect, not a problem. Looks like it was a coding error on my part, this will be fixed in the 2.0.1 patch!
