### ISSUE TITLE
Book of Blood + Zelemir bad interaction

### ISSUE THREAD

**Issue by nattthebear** [larsiusprime/tdrpg-bugs#1058]
Windows 7
Steam DQ1 2.0.0

When Zelemir is encountered in "The Face of Madness", he has a lightning attack that deals 80% of the defender's current HP in damage.  When the librarian is using the Book of Blood, this damage is amplified.  This makes it one-shot kill a Berserker.  Other characters are also affected, but armor reduction seems to be involved in some way so they are not one-shot killed.

In the original game, this particular attack does not benefit from Book of Blood.

**Comment by larsiusprime** [comment]
Great catch, fixed in 2.0.8
