### ISSUE TITLE
Priest AI locks up

### ISSUE THREAD

**Issue by Zadown** [larsiusprime/tdrpg-bugs#1060]
Basic Info

Windows 10
Download (Steam)
Full Version
Version # 2.0.0

Steps to Reproduce

In longer battles my one of my priests sometimes stops casting. Not sure what triggers it. They have always been in the healing AI mode (the first button). They have always been at least rank 2 when this happens, maybe rank 3 or even 4.

What I expected to happen:

I expected the priests to keep healing wounded units and attacking enemies instead of standing still.

What happened instead:

The priest (it's not both of them at the same time) stops casting even though there's wounded units within range. Not 100% sure if they also stop attacking. Switching the AI to attack and then back to healing fixes the issue temporarily.

**Comment by ManDude** [comment]
I think this is already reported. In any case, I'm getting this issue too.

**Comment by IBwWG** [comment]
Could be #791 and/or #804
