### ISSUE TITLE
Suggestion: Scroll Wheel Up/Dwn to Switch Spells

### ISSUE THREAD

**Issue by Geardan** [larsiusprime/tdrpg-bugs#1061]

**Comment by Geardan** [comment]
Title says it all. I like when I can be lazy sometimes. ;p

Right-click should also de-select current unit/spell. I think it use to work that way (and I think there's a ticket in for that).

**Comment by ManDude** [comment]
DQ is more of a keyboard-oroented game. You can use the spell hotkeys to quickly select/deselect spells.

**Comment by Geardan** [comment]
Eh, it just seems like it'd be a nice option. Also, I think you have to hit escape to deselect, instead of hitting key again.

**Comment by ManDude** [comment]
Hmm that's not how it worked...
