### ISSUE TITLE
"Null Object Reference" error trying to export game materials for modding

### ISSUE THREAD

**Issue by kyle-kilcrease** [larsiusprime/tdrpg-bugs#1063]
Operating System: Windows 10
Browser/Download: Download
Demo/Full: Full
Version #: 2.0.0
Optional Info: This is with the DX version, just to be clear

1. Load up the game
2. Hit start and head to mods
3. Create a new mod
4. Select any set of files for exporting (It crashes no matter what is selected)
5. Name the mod and hit accept

I suppose the game is meant to export the selected files and then let you know this process was completed. However, on my end, it freezes for a split second before popping up with a Null Object Reference text box and upon closing the text box, the game closes.

It does create a folder with the name you type in for your mod, but the only files in the folder are the following

\fonts\myriadproz.woff
\fonts\verdana.ttf
\locales\es-ES\defender.tsv
icon.png
settings.xml

**Comment by Sponsch** [comment]
I have the exact same problem i just have Windows 7

**Comment by larsiusprime** [comment]
Working on this for a patch later this week.

**Comment by Sponsch** [comment]
Okay thanks I can barely wait to play modded

**Comment by Sponsch** [comment]
I now found a very similar bug i do the same but i try to load a mod from my mods and then i get the error: "bad node type, expected Element but found 6

**Comment by larsiusprime** [comment]
This should now be fixed in 2.0.5c
