### ISSUE TITLE
Misspelling on annon book.

### ISSUE THREAD

**Issue by michaelachrisco** [larsiusprime/tdrpg-bugs#1064]
Basic Info:

Windows 10
Download (Steam)
Full Version
Version # 2.0.0

Steps to Reproduce:

When a player starts a new game, they may chose not to look at the Defenders Quest Facebook page. If they do, they will receive the anonymous book. 
What happened:

Misspelling when you get the anonymous book near the title screen. I wish I could give you guys more but that would require me to restart the game.

**Comment by ManDude** [comment]
Is this the "anwya" typo or something?

Try making a new mod with pretty much no data then load it. It makes the secrets button come back.

**Comment by michaelachrisco** [comment]
Will do. Ill report back.

**Comment by larsiusprime** [comment]
Fixed in 2.0.8

**Comment by michaelachrisco** [comment]
Thanks!
