### ISSUE TITLE
Download issues - no game (Steam)

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#1071]
Okay, so we already talked about this on Twitter. Here's what's happening: the game won't run at all, citing a missing executable as the reason (both new and legacy versions). And indeed, when I checked in the install folder, the only thing that Steam downloaded was the game's soundtrack.

Nothing is working. Not validating, not changing to test_public, not changing servers.

Not quite sure if it's the same issue that's detailed here: https://github.com/larsiusprime/tdrpg-bugs/issues/1032

**Comment by larsiusprime** [comment]
This is a longshot, but have you tried changing the install directory?

**Comment by ThomasFaust** [comment]
That doesn't do the trick. 

Interesting: Steam says the game is 52MB

![image](https://cloud.githubusercontent.com/assets/19844461/16122338/f6554b98-33e6-11e6-88c3-c8ddf3bb6ea2.png)

**Comment by larsiusprime** [comment]
For some reason it's ONLY installing the soundtrack...

Still haven't heard from Valve.

**Comment by ManDude** [comment]
Is this fixed?

**Comment by ThomasFaust** [comment]
It is for me.

**Comment by ManDude** [comment]
Cool.
