### ISSUE TITLE
Null Object Reference on Equipment and Skills

### ISSUE THREAD

**Issue by SirPencil** [larsiusprime/tdrpg-bugs#1072]
Initially reported here: http://steamcommunity.com/app/218410/discussions/0/358415206078256763/?ctp=2

Operating System: Windows 7
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : test_public 2.0ish
Optional Info** : I am running the game in 2560x1080.

Steps to reproduce:
1. Run the game in a wide-screen resolution like 2560x1080.
2. Attempt to access the Equipment screen from the overworld map or at any other juncture.
3. Receive Null Object Reference error, followed by game crash.

Alternatively:
1. Run the game in a wide-screen resolution like 2560x1080.
2. Attempt to access Slak's skills.
3. Receive Null Object Reference error, followed by game crash -or- an instant game crash.

Stack trace:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

"D:\Program Files (x86)\Steam\steamapps\common\DefendersQuest\
dx\DefendersQuest.exe"

C:\Users\Kerberos>Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/Na
tiveApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_back
end/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 761
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/Di
splayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObje
ct.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDi
spatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 530
Called from flixel.FlxGame::step flixel/FlxGame.hx line 663
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx lin
e 1487
Called from flixel.FlxGame::update flixel/FlxGame.hx line 713
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 623
Called from com.leveluplabs.tdrpg.State_Init::create com/leveluplabs/tdrpg/State
_Init.hx line 100
Called from com.leveluplabs.tdrpg.State_Initializer::create com/leveluplabs/tdrp
g/State_Initializer.hx line 40
Called from flixel.addons.ui.FlxUIState::create flixel/addons/ui/FlxUIState.hx l
ine 206
Called from flixel.addons.ui.FlxUITooltipManager::init flixel/addons/ui/FlxUIToo
ltipManager.hx line 72
Called from flixel.addons.ui.FlxUI::getDefinition flixel/addons/ui/FlxUI.hx line
 1439
AL lib: (EE) alc_cleanup: 1 device not closed

Saves attached.

[SAVE_SLOT_1.zip](https://github.com/larsiusprime/tdrpg-bugs/files/318906/SAVE_SLOT_1.zip)

**Comment by larsiusprime** [comment]
Just got it fixed in 2.0.1 (third patch). This will go up in about 15 minutes to test_public

**Comment by larsiusprime** [comment]
Okay the new patch is up, can you try it?

**Comment by larsiusprime** [comment]
@SirPencil -- new patch is up, does this fix it?

**Comment by larsiusprime** [comment]
Gonna close this for now, reopen if it is not fixed in the latest 2.0.1 test_public patch.

**Comment by SirPencil** [comment]
Hey, sorry for the delay! I took a bit of a nap.

Just replying to confirm that this issue is resolved for me. Accessing Slak's skills and the equipment panel is working like a charm.

Thanks for all your hard work!
