### ISSUE TITLE
Null object reference on startup

### ISSUE THREAD

**Issue by Vuuni** [larsiusprime/tdrpg-bugs#1073]
Null object reference after HaxeFlixel Logo, at Loading 11/14 tasks complete

**Comment by Vuuni** [comment]
OS: Windows 10
Steam Download
Version #: Uhm i can't easily tell this one so just the latest non beta one on steam? 

Reproduce:
1. Launch game
2. Wait for it to load 11/14 tasks
3. Get Null object reference popup

What i expected.
Game launch

What happened
http://puu.sh/puYHB/a5be431d1c.png

**Comment by larsiusprime** [comment]
Does it break in the beta version too under the test_public beta branch?

**Comment by Vuuni** [comment]
Yeah.  Exact same result

**Comment by Vuuni** [comment]
For further info, i've tried reinstalling it, and verifying it twice. Not entirely sure how else i can try to fix it at the moment :c

**Comment by larsiusprime** [comment]
I'm working on another patch, hang tight. Sorry about this!

**Comment by larsiusprime** [comment]
Okay try it again, new patch up on 2.0.1 as of 10 minutes ago.

**Comment by Vuuni** [comment]
Both the normal and the test beta are still giving the null object error :c

**Comment by larsiusprime** [comment]
If you run the app from the command line do you get any stack trace output?

To do this, right click game in library, properties, local files tab, "browse locale files". Note the location. Open cmd.exe, navigate there. Then go into the "dx" folder and run DefendersQuest.exe (the other DefendersQuest.exe is the legacy game).

Running the game this way sometimes shows more information when it crashes.

**Comment by larsiusprime** [comment]
@Vuuni: just put up a new build, 2.0.1a, I think this will really fix it.

**Comment by Vuuni** [comment]
For the cmd thing, here is the error it gave
http://pastebin.com/nq2hr1tN

**Comment by larsiusprime** [comment]
Thanks that's a big help!

**Comment by Vuuni** [comment]
As for the patch, unless it didn't download (steam could be being fucky), it didn't help.

**Comment by larsiusprime** [comment]
What version number does it say on the title screen? I guess you can't get that far....

One thing you can do is if you "browse local files" is go to <gamefolder>/dx/assets/xml/

and look for "meta.txt". If it exists and says "a", it's the latest version. If not, it's not.

In any case I'm pushing 2.0.1b now to specifically address your issue.

**Comment by Vuuni** [comment]
It loads! tysm~

**Comment by larsiusprime** [comment]
Cheers :)
