### ISSUE TITLE
Achievement notification time-on-screen tied to current speed multiplier

### ISSUE THREAD

**Issue by NonaSuomi** [larsiusprime/tdrpg-bugs#1075]
When unlocking an achievement, the amount of time an achievement notification (if enabled) appears on screen appears to be tied to the current play speed- i.e. unlocking an achievement while using 1/4x speed makes it last for an excessive amount of time, while using something like 8x or 16x makes it disappear so quickly it's almost impossible to read.

**Comment by larsiusprime** [comment]
Excellent catch!

**Comment by larsiusprime** [comment]
Fixed in 2.0.7
