### ISSUE TITLE
Journal text runs outside the edge of the page

### ISSUE THREAD

**Issue by NonaSuomi** [larsiusprime/tdrpg-bugs#1076]
Journal entry for "Night 17- The Fox"

The first (left) page runs one line below the bottom of the graphic for the journal's page, making it difficult to read. Display settings are at 800x600 Windowed, the computer's native resolution is 1366x768.

**Comment by larsiusprime** [comment]
Is this English, or a different language?

**Comment by NonaSuomi** [comment]
English. I'm out at the moment, but when I get back home I can take a
screenshot if it will help.

**Comment by NonaSuomi** [comment]
Here's a screenshot of the page as it appears on my computer. [image](https://cloud.githubusercontent.com/assets/19984523/16140681/2105a88a-3408-11e6-98a0-3ed64cce9ac8.png)

OS is Win10, game is played via the Steam full version launching the "deluxe" option, version string is "Steam DQ1 2.0.1 b". Computer is a Dell Latitude E6320, screenshot is taken while outputting to the built-in LCD with no other displays attached, although any other display options (built-in VGA or HDMI, e-Port dock for VGA, DVI-D, or DisplayPort) all appear to give the same results.

**Comment by larsiusprime** [comment]
This is fixed now.
