### ISSUE TITLE
Eztli-Tenoch stuck preparing chain lightning

### ISSUE THREAD

**Issue by JKingweb** [larsiusprime/tdrpg-bugs#1077]
![image](https://cloud.githubusercontent.com/assets/89590/16138809/49eab96e-340f-11e6-8f10-e00d41ae977f.png)

He's been stuck with that icon beside him for a few minutes by now, doing nothing.  Draining a health bar to have him morph does not seem to have any effect: he does morph, but he's still stuck. This is on the third difficulty (before Extreme; I'm not sure now what it's called); I didn't experience this behaviour on Normal.

**Comment by ManDude** [comment]
This was a bug in the old game, too. Never got around to knowing what caused it exactly.
