### ISSUE TITLE
Crash on Coliseum Scene (The Scene Being able To purchase items for the first time)

### ISSUE THREAD

**Issue by BlaQSRk** [larsiusprime/tdrpg-bugs#1079]
Operating System: Windows 7
Browser/Download: Steam
Demo/Full?: Full Version.
Version #: Version 2.0.1b.  Deluxe Edition No Changes.
Optional Info** : 
Full Screen. 1920x1080 Resolution.

Right after Ketta says in the scene "Ye Gods I need a drink." and then Azra says "That makes two of us." When I press "Next" the game freezes and then crashes. 

Just playing the game over on a new save. Long time fan. Good luck!

**Comment by larsiusprime** [comment]
This should be fixed now.
