### ISSUE TITLE
Clicking a stage on the overview map incorrectly orients it in view

### ISSUE THREAD

**Issue by SirPencil** [larsiusprime/tdrpg-bugs#1085]
I'll try my best to explain this one, but I feel the following screenshots demonstrate it best.

When I click to select a stage, the screen will move as if to center it on screen. This regularly fails unless the stage is high enough on the overview map that it can't scroll much vertically to find it.

This means that after clicking on a stage, I will often have to manually scroll to pull it back into view.

Example before clicking on stage:
http://steamcommunity.com/sharedfiles/filedetails/?id=705220765

After:
http://steamcommunity.com/sharedfiles/filedetails/?id=705220742

Notice that my mouse cursor hasn't moved from its position relative to the screen.

**Comment by Landiss** [comment]
This happens to me as well, must be because of ultra widescreen resolution. I believe this is a clone of that issue:

https://github.com/larsiusprime/tdrpg-bugs/issues/1056

**Comment by larsiusprime** [comment]
Believe this has since been fixed.

**Comment by larsiusprime** [comment]
Fixed in 2.1.4
