### ISSUE TITLE
Some texts are not affected by language changes

### ISSUE THREAD

**Issue by Gama11** [larsiusprime/tdrpg-bugs#1086]
Game started with German selected, then switched to English on the load save screen.

The text that should say "stone skull" is still localized to German ("Steinschädel").

![](http://i.imgur.com/an61bDE.png)

Version: ![](http://i.imgur.com/9zEQsdY.png)

**Comment by Gama11** [comment]
Another instance of this: the descrition of active skills:

![](http://i.imgur.com/m80Y52r.png)

**Comment by Gama11** [comment]
Same on this screen:

![](http://i.imgur.com/QEAXjiV.png)

**Comment by larsiusprime** [comment]
Which version are you running? (Title screen, bottom left corner)

**Comment by Gama11** [comment]
You mean bottom right corner? I included a screenshot of that in the first post.

**Comment by larsiusprime** [comment]
Right you are missed that!

Okay, so this is the latest version, basically. We just updated to 2.0.1c but I'm not sure it will affect this at all.

**Comment by larsiusprime** [comment]
This is all fixed now in 2.0.8

**Comment by LarsMadeMeDoIt** [comment]
Azra's spell tooltips (in the party menu) are still affected by this.
