### ISSUE TITLE
Resolutions over 1920 x 1080 fail

### ISSUE THREAD

**Issue by Bozzley** [larsiusprime/tdrpg-bugs#1090]
Operating System: Windows 10
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : 2.0.1 c
Optional Info** : I'm using a 3440 x 1440 monitor with a 980Ti gfx card. If I select any resolution with either horizontal over 1920 or vertical over 1080 (that goes for both window and fullscreen options), the window goes black with only certain text in white and readable. Also looks like one of the tick boxes gets moved up and to the left. Happy to provide screenshots if you want them, or record a video if that will work.

**Comment by larsiusprime** [comment]
This bug has been reported a whole bunch of times, so we don't need any more evidence :) Been working on it for most of the day.

**Comment by Bozzley** [comment]
Sorry mate, I searched for it but I only saw an issue that was already resolved. Cheers!

**Comment by larsiusprime** [comment]
Np! Good to have this one on the bugtracker.
