### ISSUE TITLE
Weird effects at 16x

### ISSUE THREAD

**Issue by JKingweb** [larsiusprime/tdrpg-bugs#1094]
Basic info:
Windows 10
Download
Full Version 
Version # 2.0.1 b

Steps to reproduce:
1. Start challenge 5, pausing immediately
2. Array defenders as in attached screenshot (approx lvl 45)
3. Set speed to 16x
4. Wait a couple of seconds
5. Set speed to 1x

What should happen:
Nothing out of the ordinary.

What happens:
Weird stuff! Enemies go floating up off-screen and/or sideways through obstructions.  The enemies all eventually end up unstuck, but it significantly lessens the flow of battle.

![image](https://cloud.githubusercontent.com/assets/89590/16162865/01100d1c-34a4-11e6-8048-ffd8956b2222.png)

I wasn't able to find similar issues, so apologies if I missed any.

**Comment by ManDude** [comment]
I wonder if it's the Knight's knockback that's causing this. Does your Knight have knockback?

**Comment by JKingweb** [comment]
He does.  It also affects enemies nowhere near him.

**Comment by ManDude** [comment]
Can you reproduce this but with ONLY the knight in battle?

**Comment by JKingweb** [comment]
Actually, I can reproduce it with no one is battle:

![image](https://cloud.githubusercontent.com/assets/89590/16164330/7fb50512-34ab-11e6-812e-c5ad231e025a.png)

**Comment by JKingweb** [comment]
It actually happens for any battle, I've now noticed.

It appears to be something specific to that particular game, though.  If I load a different game or start a new one, it doesn't happen.  Attached an export in case it's any help.

[16x.weirdness.dqdx.txt](https://github.com/larsiusprime/tdrpg-bugs/files/321289/16x.weirdness.dqdx.txt)

**Comment by JKingweb** [comment]
Ah.  It appears to be the Slow Start book doing it.  Which I think doesn't actually work, come to think of it...

**Comment by larsiusprime** [comment]
Yup, it's the Slow start book. Working on a fix.

On Fri, Jun 17, 2016 at 4:28 PM, J. King <notifications@github.com> wrote:

> Ah. It appears to be the Slow Start book doing it. Which I think doesn't
> actually work, come to think of it...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1094#issuecomment-226885926>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Di-nwf1yYOX2Ye3LstAkWPlB69uks5qMxF7gaJpZM4I4sGc>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
OH I wasn't understanding the report very well. I thought the knight was pushing the enemies away from the screen or something.
