### ISSUE TITLE
Placeholder Image

### ISSUE THREAD

**Issue by mhaehnel** [larsiusprime/tdrpg-bugs#1096]
There is a placeholder image in the dialog after the "Desert Stronghold Entrance" mission in DQ1/DQDX is finished. If you progress through the dialog until Slack says "The last one was too much" and then navigate the dialog backwards it will become visible.

Example: 
http://steamcommunity.com/sharedfiles/filedetails/?id=705500739  

Original version:
http://steamcommunity.com/sharedfiles/filedetails/?id=705500679

It's kinda cute, but I guess not intentional ;)

(See also here: http://steamcommunity.com/app/218410/discussions/1/358415206084707083/ if images don't render)

System: Linux (Gentoo ~amd64)

**Comment by ManDude** [comment]
Resolution?

**Comment by mhaehnel** [comment]
Happens on any resolution and independent of Fullscreen or Windowed. 
I tried 800x600, 1024x768 and 1152x864 (4:3) as well as 1366x768 and 1280x720 (16:9).
