### ISSUE TITLE
DQDX : Ranged attacks from Ice Mage and Dragon missing targets

### ISSUE THREAD

**Issue by xbmchermit** [larsiusprime/tdrpg-bugs#1097]
I don't recall seeing this issue before, but I am seeing it a lot since DQDX dropped.  Quite often Ranged attacks from the Ice Mage and the Dragon not only miss their targets completely, but are often launched in such a way that they could never have hit a target in the first place.  

In a similar vein, if they are about to launch a ranged attack at an enemy (animation started), and that enemy dies, instead of switching to another enemy, they instead just launch that attack straight down.  In every case I have seen this, there were no enemies on that side of the screen at all.  I have seen it many times.  I have also seen the Dragon just randomly shoot a fireball at nothing, when there is no enemy in range, and was no enemy in range.  Had it do it twice in a row in the last battle, while a wave was just beginning and no enemies were anywhere nearby.

This does not happen with the Ranger at all.

Since I can't attach a video, you can grab a gameplay example here: https://db.tt/klNdkTfC You can see some odd things with the Ice Mage's ranged shots, including one bouncing off an opponent.

**Comment by hwoosh** [comment]
> This does not happen with the Ranger at all.

I've definitely noticed similar behavior with the Ranger: specifically, the Triple Shot and Spread Shot sometimes seem to miss their intended target completely, with not even one of the arrows connecting. I would assume the intended behavior is for the center arrow to track to the designated target for the shot just like any other ranged attack, but that's not what I've been observing.

**Comment by xbmchermit** [comment]
I have noticed the behavior you describe with Triple Shot and Spread Shot, but I figured that was part of the design of those shots, that they were slower or something.  It would be nice if the middle of those shots actually "led" their target correctly.

**Comment by xbmchermit** [comment]
Today, my Dragon shot my knight with a Fireball with no enemies on screen.  Not very nice of him.

**Comment by larsiusprime** [comment]
I believe I've fixed this in the latest builds, at least for the ice mage, and hopefully for everyone. Is it still happening?

**Comment by larsiusprime** [comment]
No confirmation that this is still happening, can't reproduce. Please re-open if it recurs in 2.0.8 or later.
