### ISSUE TITLE
"Expected Attribute Name" Error causes game to crash catastrophically.

### ISSUE THREAD

**Issue by huiguang-liang** [larsiusprime/tdrpg-bugs#1100]
Here's my referenced save-game: [http://pastebin.com/tyZ1u1cQ](url)

In the level="4_6_the_way_out", after completing the Normal mode for this level, the story plays out with conversations as normal. However, at the end of the conversations, the screen goes black and another window pops out with the text message 

> Expected Attribute Name

Pressing "skip" during the conversations also results in this behavior. I cannot progress with the game further with this bug. The expected behavior is to unlock the next stage.

Please have a look and let me know if you are able to reproduce it.

**Comment by avplol** [comment]
Hey, I'm having this issue also.

**Comment by larsiusprime** [comment]
This bug should have been fixed about two weeks ago, I believe I commented on it on the steam forums.

Is it fixed now for you guys?

**Comment by larsiusprime** [comment]
I'm pretty sure this is fixed, please re-open if you see it again.
