### ISSUE TITLE
Game crash when first encountering Niru in NG+, now Dragons are permanently locked

### ISSUE THREAD

**Issue by ean5533** [larsiusprime/tdrpg-bugs#1101]
Game crashed in NG+ when encountering Niru for the first time. When I reopened the game and replayed the level, the dialog was skipped but dragons weren't unlocked even after beating the level.

**Comment by ean5533** [comment]
Is there some kind of workaround I can use to unlock dragons manually?

**Comment by ManDude** [comment]
What resolution?

**Comment by ean5533** [comment]
1920x1080 fullscreen

**Comment by ManDude** [comment]
What is the error message?

**Comment by ean5533** [comment]
It was a few hours ago so I don't remember clearly, but I don't think there was an error message (not even like the "expected attribute name" message which I also get), just an instant crash to desktop.

**Comment by ManDude** [comment]
Try going to the movies menu.

**Comment by ean5533** [comment]
Ah, that worked. Game didn't crash when triggering the appropriate scene from the movies menu, and now dragons are unlocked. Good workaround, thanks.

**Comment by ean5533** [comment]
Scratch that, sorry, I was in NG mode. I went to NG+ mode and triggered the dialog but it didn't unlock the dragons. My bad.

**Comment by ManDude** [comment]
I was expecting the game to crash but glad it worked I guess. :D

**Comment by ean5533** [comment]
Well I still have no dragons in NG+ so I'm not sure worked is the right word

**Comment by ean5533** [comment]
In case anyone else encounters this problem or one like it, my workaround was to export my save game, open it in notepad, find the `plus_classes_hidden` section and delete it completely, then import it back in to a new save slot. Worked fine.

**Comment by larsiusprime** [comment]
Sorry I haven't commented yet, this bug got buried. I think I've fixed the cutscene bug that caused this bad state, glad you figured out the workaround.
