### ISSUE TITLE
Into the Shadows spells buttons in wrong order

### ISSUE THREAD

**Issue by aguakandra** [larsiusprime/tdrpg-bugs#1104]
Windows 10, Steam v 2.0.2a
I get this weird behavior playing this particular level (the first quest with the non-Azra main character), Normal difficulty. But other levels have been functioning properly.

In this map, the order (left to right) for the spell icons and descriptions are Lightning, Healing, Frenzy, Pushback, Dragon Fire, Crystal. But clicking on the spells (or using the keys 1-6) switches the cursor icon and spell cast to these spells (left to right): Lightning, Frenzy, Healing, Crystal, Pushback, Dragon Fire.

At 1280x720 windowed:
![spells-into-the-shadows](https://cloud.githubusercontent.com/assets/8533424/16175420/60fcd68c-35a9-11e6-9932-8c9cdea64919.png)

I also get this behavior at other screen resolutions (tested 800x600 windowed and 1600x900 full screen).

**Comment by ManDude** [comment]
Duplicate.
