### ISSUE TITLE
Previously-attained achievements displaying upon subsequent game loads

### ISSUE THREAD

**Issue by avplol** [larsiusprime/tdrpg-bugs#1105]
Certain achievements appear every time the game is loaded, such as intermediate librarian, unlock all 6 heroes, boost to level 5, and others.

**Comment by larsiusprime** [comment]
Does this still happen in the latest version?

**Comment by avplol** [comment]
Thanks Lars, you are right, it is no longer happening.

Great job on all the bug fixes! You the man!
On 11 Jul 2016 12:22 PM, "Lars Doucet" <notifications@github.com> wrote:

Closed #1105 <https://github.com/larsiusprime/tdrpg-bugs/issues/1105>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/larsiusprime/tdrpg-bugs/issues/1105#event-718186127>,
or mute the thread
<https://github.com/notifications/unsubscribe/ATFYJx9rK40WUjQsYjkDIUuCzeljk1XJks5qUaj4gaJpZM4I5KdX>
.
