### ISSUE TITLE
Karsk after burning

### ISSUE THREAD

**Issue by twc1990** [larsiusprime/tdrpg-bugs#1108]
Karsk can still be visited after it is burned: going to the town displays the following screen, with the begin button still clickable. The town acts as normal if you visit it.

![karsk](https://cloud.githubusercontent.com/assets/5121380/16183759/869e6dbc-3683-11e6-99b6-4fba27070c76.JPG)

**Comment by IBwWG** [comment]
Which OS and version?  I just saw this screen yesterday on 2.0.0 on linux 32-bit and it just had one button that caused you to go back to the map.

**Comment by twc1990** [comment]
Ah, sorry. Windows 7, steam version 2.0.2a

**Comment by IBwWG** [comment]
No worries, I wonder then whether it was introduced between 2.0.0 and 2.0.2a or if it's steam/windows-specific?

**Comment by larsiusprime** [comment]
Does this still happen?

Seems like a timing error on the popup

**Comment by ManDude** [comment]
Fixed for me at least. Will wait until others can confirm.

**Comment by twc1990** [comment]
It's still there on my old saves(both in normal and newgame+), and I just started a new game, ran through the first few missions, and the bugs there as well.

**Comment by ManDude** [comment]
What resolution are you using?

**Comment by twc1990** [comment]
Wide 1366 x 768, windowed.

**Comment by dawelty** [comment]
I can verify that this bug is still an issue.

I'm not sure why you're having trouble reproducing it. I can't produce any behavior except for this buggy behavior. I even started a brand new game to check and see if it made a difference, and it did not: still bugged.

OS: Linux Mint 17.3 (x86-64)
Kernel: 3.19.0-32-generic
Version: 2.0.7a (Steam - full version)

**Comment by larsiusprime** [comment]
As far as we can tell, this is a timing bug that only happens on some machines. I can't reproduce it locally, for instance. Will try to dig in some more.

**Comment by larsiusprime** [comment]
I have a fix that I believe takes care of this. Will be in version 2.1.0

**Comment by dawelty** [comment]
Yup, that fixed it.

P.S. Thank you for continuing to support this game for so long.
