### ISSUE TITLE
Crash when unable to open save file

### ISSUE THREAD

**Issue by theinternetftw** [larsiusprime/tdrpg-bugs#1113]
OS: Windows 10
Steam DQ1 2.0.2a

While in-game, if the save file exists but is unable to be opened, the game crashes with a "[file open..." error.  This is a very real problem because Dropbox can on occasion lock files, causing this behavior.

Repro:

1) Open game to overworld
2) Remove all file permissions (I did this by running ```chmod 000 SAVE_SLOT_1.dfq``` in cygwin)
3) Enter and leave a location to cause an autosave

More correct behavior would be to show an error dialog box to inform the player the game could not be saved and continue the game as normal, which would let them decide how to proceed.  The next autosave will usually clear things up (unless save games are on a USB stick that just worked its way out of a laptop or something).

In any case, crashing when failing to save compounds the problem.

**Comment by larsiusprime** [comment]
OOoohh, good catch. I'll work on this.

**Comment by larsiusprime** [comment]
Great, easy to reproduce by just checking "read-only" too. Working on this now.

**Comment by larsiusprime** [comment]
Fixed. I wonder how many garden variety "random crashes" had something to do with this...

Fix will be in version 2.0.5
