### ISSUE TITLE
Pre-Round Recall Psi Loss

### ISSUE THREAD

**Issue by Corgwn** [larsiusprime/tdrpg-bugs#1114]
Windows 10
Download
Full Version
Steam 2.0.2 a

Steps to Reproduce:
1. Start a level (I used Zelemir Appears for testing)
2. Press space to pause
3. Place a Healer
4. Recall the Healer
5. Unpause

What I Expected:
I expected to have full Psi again, as you should get all of it back before the waves start.

What happened instead:
I got 10-13 Psi back for every Healer that I tested it with.
I also tested with Berzerkers and got 21-23 back every time.

**Comment by ManDude** [comment]
Do you have Book of Synergy equipped?

**Comment by 90000r** [comment]
Yes

**Comment by 90000r** [comment]
I went and looked through closed bugs, I found that the book of synergy has a psi tax, but couldn't find where in the game that it says that.

**Comment by ManDude** [comment]
The description should say Psi Tax is 15%.

**Comment by 90000r** [comment]
At least for my install, it doesn't. I can't vouch for anyone else.

**Comment by larsiusprime** [comment]
I need to double check whether PSI Tax is listed in the tooltip.
