### ISSUE TITLE
Crash on loading formation

### ISSUE THREAD

**Issue by aradapilot** [larsiusprime/tdrpg-bugs#1115]
v2.0.2a, mac.

[SAVE_SLOT_1.dfq.zip](https://github.com/larsiusprime/tdrpg-bugs/files/324876/SAVE_SLOT_1.dfq.zip)

See savegame.  Load game, play (normal, not ng+), battle extreme on the halls of the god king.  When asked to load previous formation, click yes.  Game will try to load, and crash to desktop.

**Comment by larsiusprime** [comment]
Reproduced the crash, thanks.

This will be fixed in version 2.0.5!
