### ISSUE TITLE
ET line attributed to Azra in Normal Game, 'The Voice Speaks'

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1117]
![ze](https://cloud.githubusercontent.com/assets/19625520/16222219/060c71c0-3765-11e6-9074-f5de25e09ff6.png)

Also in NG+ this line lacks punctuation, needs a period at the end.

**Comment by larsiusprime** [comment]
Fixed in 2.0.6.

While I was at it, I made it so that "symbols text" appears right in foreign languages, too.
