### ISSUE TITLE
Can't load mods on Linux

### ISSUE THREAD

**Issue by xanni** [larsiusprime/tdrpg-bugs#1120]
OS: Linux, Download, full version "DQ1 2.02a a" installed from GOG v2.1.0.2

When I "Install from ZIP" the "Super Space Defenders" mod, it unzips but there's no way to access it in "My Mods".  "My Mods" always just shows eight empty mods "TITLE OF THE MOD" by AuthorName.

**Comment by ManDude** [comment]
I'm not sure if old mods work. Try creating a new one and see if it works.

**Comment by xanni** [comment]
Why ship it then?  Anyway no, creating a new mod crashes to desktop immediately after entering the mod name.  From then on, choosing "My Mods" immediately crashes to desktop as well.

**Comment by xanni** [comment]
More info:  Deleting the newly created mod directory from the test above and moving the unzipped mod into a new directory under the mods directory makes the mod show up correctly under "My Mods", but loading it has no effect after the game restarts.

**Comment by larsiusprime** [comment]
Super Space Defenders is compatible with the legacy version of the game, not the DX version.

I'm working on an updated DX-compatible version of SSD.
