### ISSUE TITLE
Inconsistent Video Options Disable on Battle Screen

### ISSUE THREAD

**Issue by Atomic-Lemonade** [larsiusprime/tdrpg-bugs#1121]
While the "Video" setting option is disabled on the main menu during battle, the video setting screen can be indirectly accessed through the "Accessibility" setting screen.

![video-settings-battle-1-small](https://cloud.githubusercontent.com/assets/17205804/16230951/8b0081a4-3789-11e6-99e8-416b2f1fec9b.png) | ![video-settings-battle-2-small](https://cloud.githubusercontent.com/assets/17205804/16231066/0b7d12ac-378a-11e6-9d5c-bd6f36f68578.png)
------ | ------
![video-settings-battle-3-small](https://cloud.githubusercontent.com/assets/17205804/16231068/0fef30a4-378a-11e6-8ba2-b30dc03c8690.png) | .

**Comment by ManDude** [comment]
dupe

**Comment by Atomic-Lemonade** [comment]
Sorry about the duplicates.  Since I'm not familiar with the Issues feature of GitHub, how can I check whether the issue has already been logged?  (I apologize if it's a stupid question.)

**Comment by ManDude** [comment]
On the issues menu, there is a search box at the top-left.
