### ISSUE TITLE
Appearance of Back Button at the First Scene of a Movie

### ISSUE THREAD

**Issue by Atomic-Lemonade** [larsiusprime/tdrpg-bugs#1122]
<h1>Basic Info</h1>
Windows 8.1
Steam Download
Full
Version # 2.0.2 a

<h1>Description</h1>
After progressing through a movie then pressing back button until the beginning of the movie, the back button remains at the bottom of the screen at the first scene of the movie.

<h1>Steps to Reproduce</h1>
1.a) View a cutscene for the first time
1.b) Select a cutscene from the "Movies" screen at the bottom of the map
2. Press "Next" at least once
3. Press "Back"

![back-button-1](https://cloud.githubusercontent.com/assets/17205804/16231463/f5a35692-378b-11e6-99b6-2d75f769bf91.png) | ![back-button-2](https://cloud.githubusercontent.com/assets/17205804/16231469/fc689c80-378b-11e6-8f65-f7daa075289e.png)
------ | ------

**Comment by larsiusprime** [comment]
Thanks for the report :)

I think we're just gonna let this one be as we've got our hands full with lots of other stuff and this seems pretty harmless.
