### ISSUE TITLE
Memory leak on Endless 1 (NG)

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1123]
At least I made it this far!  But about at 1.6 GB, it gave up.
2.0.3 - steam, win7x64, HD mode@1704x960windowed
![dq-crash5](https://cloud.githubusercontent.com/assets/16719964/16243762/1b7bec90-37f9-11e6-8975-cd4f803d6a15.png)

**Comment by IBwWG** [comment]
This may be the same as #1128

**Comment by ManDude** [comment]
Closing this one since the other one has more info. :smiling_imp:
