### ISSUE TITLE
Clicking steam achievement popup crashes the app

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1126]
2.0.3 - steam, win7x64, HD mode@1704x960windowed
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: DefendersQuest.exe
  Application Version:  0.0.0.0
  Application Timestamp:    5768993a
  Fault Module Name:    DefendersQuest.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   5768993a
  Exception Code:   c0000005
  Exception Offset: 00f7590e
  OS Version:   6.1.7601.2.1.0.768.3
  Locale ID:    4105
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

Just got Book Worm, on the map screen, clicked the achievement button, instant crash (no stack trace.)

**Comment by larsiusprime** [comment]
What achievement button? Do you mean the achievement popup? I didn't think it was clickable.

**Comment by IBwWG** [comment]
Yeah, the popup--it was in front of the quit button and I was trying to leave the game :)  If it's not clickable, then whatever I clicked behind it, or the fact that I tried to click something that maybe isn't actually part of the game's window, whatever it was, made it crash...
