### ISSUE TITLE
Strange line on level select since recent Steam update.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1127]
![ze](https://cloud.githubusercontent.com/assets/19625520/16254676/78ab0cc2-3810-11e6-9227-ca37a587e89b.png)

Smallest resolution, HD graphics.

**Comment by ManDude** [comment]
Happens to me too on vanilla.

**Comment by larsiusprime** [comment]
Should be fixed in the next patch

On Wed, Jun 22, 2016 at 10:42 AM, ManDude <notifications@github.com> wrote:

> Happens to me too on vanilla.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1127#issuecomment-227785511>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Dx_4TT3yo-DaKJfqZ24bXq7_1UMks5qOVfsgaJpZM4I7ZYY>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
