### ISSUE TITLE
Game crash on endless 1

### ISSUE THREAD

**Issue by ClaudioBasckeira** [larsiusprime/tdrpg-bugs#1128]
# Basic Info
Windows 10
Download (Steam)
Full Version
Version # 2.0.3 a

Running on a desktop PC at 1920x1080 native full screen, 16GB RAM, Core i5 4th gen, GTX 970 video card.

# Steps to reproduce:

1. Start the game on a save file with access to the "Endless 1" challenge. Mine has a Level 29 AZRA, all units hired and all units around level 28, except for dragons who are around level 23.
2. Start the "Endless 1" challenge.
3. Play the challenge adding your units close together evenly distributed for both lanes, on the upper half of the map.
4. As the game progresses, have every possible unit on the map and fully boost them.
5. When reaching a high enough wave, the game should crash. My last crash happened at wave 79 at the momment I finished boosting my very last unit to the highest level (an ice mage).

# What I expected to happen:

Play indefinitely until overwhelmed and having the stage finish normally.

# What happened instead:

The game crashed to desktop (Defender's quest stopped responding...) during wave 79, as described above.

**Comment by larsiusprime** [comment]
Excellent report

On Wed, Jun 22, 2016 at 9:35 AM, ClaudioBasckeira <notifications@github.com>
wrote:

> Basic Info
>
> Windows 10
> Download (Steam)
> Full Version
> Version # 2.0.3 a
>
> Running on a desktop PC at 1920x1080 native full screen, 16GB RAM, Core i5
> 4th gen, GTX 970 video card.
> Steps to reproduce:
>
>    1. Start the game on a save file with access to the "Endless 1"
>    challenge. Mine has a Level 29 AZRA, all units hired and all units around
>    level 28, except for dragons who are around level 23.
>    2. Start the "Endless 1" challenge.
>    3. Play the challenge adding your units close together evenly
>    distributed for both lanes, on the upper half of the map.
>    4. As the game progresses, have every possible unit on the map and
>    fully boost them.
>    5. When reaching a high enough wave, the game should crash. My last
>    crash happened at wave 79 at the momment I finished boosting my very last
>    unit to the highest level (an ice mage).
>
> What I expected to happen:
>
> Play indefinitely until overwhelmed and having the stage finish normally.
> What happened instead:
>
> The game crashed to desktop (Defender's quest stopped responding...)
> during wave 79, as described above.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1128>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-HnHnY4QzfTMrmyamHUfq6f_s0w4ks5qOUg9gaJpZM4I72jo>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Incidentally, can you post a save file just after you played this battle?
That way it will save the battle layout and I can test it under the exact
same conditions

On Wed, Jun 22, 2016 at 9:36 AM, Lars Doucet <lars.doucet@gmail.com> wrote:

> Excellent report
>
> On Wed, Jun 22, 2016 at 9:35 AM, ClaudioBasckeira <
> notifications@github.com> wrote:
>
>> Basic Info
>>
>> Windows 10
>> Download (Steam)
>> Full Version
>> Version # 2.0.3 a
>>
>> Running on a desktop PC at 1920x1080 native full screen, 16GB RAM, Core
>> i5 4th gen, GTX 970 video card.
>> Steps to reproduce:
>>
>>    1. Start the game on a save file with access to the "Endless 1"
>>    challenge. Mine has a Level 29 AZRA, all units hired and all units around
>>    level 28, except for dragons who are around level 23.
>>    2. Start the "Endless 1" challenge.
>>    3. Play the challenge adding your units close together evenly
>>    distributed for both lanes, on the upper half of the map.
>>    4. As the game progresses, have every possible unit on the map and
>>    fully boost them.
>>    5. When reaching a high enough wave, the game should crash. My last
>>    crash happened at wave 79 at the momment I finished boosting my very last
>>    unit to the highest level (an ice mage).
>>
>> What I expected to happen:
>>
>> Play indefinitely until overwhelmed and having the stage finish normally.
>> What happened instead:
>>
>> The game crashed to desktop (Defender's quest stopped responding...)
>> during wave 79, as described above.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/larsiusprime/tdrpg-bugs/issues/1128>, or mute the
>> thread
>> <https://github.com/notifications/unsubscribe/AAtG-HnHnY4QzfTMrmyamHUfq6f_s0w4ks5qOUg9gaJpZM4I72jo>
>> .
>>
>
>
>
> --
> www.fortressofdoors.com -- Games, Art, Design
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ClaudioBasckeira** [comment]
Sure, where can I find the save files generated?

**Comment by larsiusprime** [comment]
Just after you play the battle, quit the game, go to the save slot screen,
and click "export" to save a DFQ file to your hard drive. As long as you
haven't tried another battle after that it will save the battle layout.

On Wed, Jun 22, 2016 at 9:40 AM, ClaudioBasckeira <notifications@github.com>
wrote:

> Sure, where can I find the save files generated?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1128#issuecomment-227765548>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-ObjLKc0Whi_FCsFs7Lis-80tUxRks5qOUlggaJpZM4I72jo>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ClaudioBasckeira** [comment]
Here you go!
[after_endless_crash.zip](https://github.com/larsiusprime/tdrpg-bugs/files/328127/after_endless_crash.zip)

**Comment by larsiusprime** [comment]
Have you tried the latest version by any chance, or still 2.0.3a?

**Comment by ClaudioBasckeira** [comment]
Sorry, I forgot to update. I haven't had any more crashes inside battles since 2.0.5

**Comment by larsiusprime** [comment]
Perfect!
