### ISSUE TITLE
Crash when selecting "My Mods" if there is a mod installed

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1130]
2.0.3a, Windows, vanilla.

Game will crash if you select "My Mods" and if a mod exists. If a mod doesn't exist, the game will continue to run as usual.
![dq00](https://cloud.githubusercontent.com/assets/7569514/16271978/f7dea4da-3893-11e6-81df-e415d0610168.png)

**Comment by larsiusprime** [comment]
This will be fixed in 2.0.5

**Comment by ManDude** [comment]
Still happening. Instead of giving an error the game IMMEDIATELY closes without any error or anything.

**Comment by larsiusprime** [comment]
What about on test_public ?

**Comment by ManDude** [comment]
Erm I was using the vanilla version (2.0.5a). Not sure about the Steam versions.

**Comment by larsiusprime** [comment]
Ah, that should be the same. Thanks.

**Comment by larsiusprime** [comment]
Also if it crashes immediately that means crashdumper is working! Check your save directory for a crashdump.

**Comment by ManDude** [comment]
I edited my post with the crashdump :)

**Comment by larsiusprime** [comment]
Okay, should be fixed in 2.0.5b
