### ISSUE TITLE
'Dark' icon no longer has a mouseover tooltip.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1133]
![ze](https://cloud.githubusercontent.com/assets/19625520/16290468/8f01d4d6-38cb-11e6-8444-784ba34be88a.png)

**Comment by ManDude** [comment]
also appears lower than it should.

**Comment by larsiusprime** [comment]
It actually has a tooltip, it's just that the icon is offset weird so that it doesn't line up with the tooltip area, in any case this is fixed in 2.0.8b now.
