### ISSUE TITLE
Problems with bonus level in NG+

### ISSUE THREAD

**Issue by ddueber** [larsiusprime/tdrpg-bugs#1135]
Once I complete the bonus levels in the regular game, the bonus levels in NG+ have the completion text bold/white (i.e., it looks the way it is supposed to AFTER I complete the level, even though I haven not done all of them). Also, the achievement for wave 100+ in Endless 2 in NG+ was awarded early (not sure when). On the plus side, even though the display text indicates that I have finished the levels, the books are rewarding properly.

**Comment by IBwWG** [comment]
Partly a duplicate of #1026

**Comment by ManDude** [comment]
Yep, dupe.
