### ISSUE TITLE
Game crash after HaxeFlixel logo

### ISSUE THREAD

**Issue by benedictleejh** [larsiusprime/tdrpg-bugs#1136]
# Basic Info
Operating System: OS X 10.10
Browser/Download: Download, GOG
Demo/Full?: Full Version
Version: 2.0.3a
Additional info:
MacBook Air Early 2014
The game has no logo applications, using the default Mac application logo
The same thing happens even after uninstalling and reinstalling

# Steps to Reproduce
1. Start the game

# What I expected to happen
The game continues to the starting screen after showing the HaxeFlixel logo

# What happened instead
The game crashes after showing the logo

**Comment by larsiusprime** [comment]
We'll have 2.0.4c out to GOG soon!

On Thu, Jun 23, 2016 at 9:47 PM, Benedict Lee <notifications@github.com>
wrote:

> Basic Info
>
> Operating System: OS X 10.10
> Browser/Download: Download, GOG
> Demo/Full?: Full Version
> Version: 2.0.3a
> Additional info:
> MacBook Air Early 2014
> The game has no logo applications, using the default Mac application logo
> The same thing happens even after uninstalling and reinstalling
> Steps to Reproduce
>
>    1. Start the game
>
> What I expected to happen:
>
> The game continues to the starting screen after showing the HaxeFlixel logo
> What happened instead:
>
> The game crashes after showing the logo
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1136>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-NdQD-Qh31LXAj3DOiAQROtpri_5ks5qO0UkgaJpZM4I9a1X>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
