### ISSUE TITLE
Ice Mage equipped with Archshepherd Stave+ deals 3x damage to All, not just Sheep

### ISSUE THREAD

**Issue by PaladinOne** [larsiusprime/tdrpg-bugs#1141]
As title says; I started a NG+, spent some skulls on the Archshepherd Stave+ and gave it to Wrenna [Ice Mage] to take a swing at the sheep on my NG file, then one or two missions later realized that Wrenna was dealing 3x her skills listed damage to _all_ enemies, not just those on that one Sheep mission the staff was designed for. (And the damage text was displaying in the 'bonus damage' yellow outline)

Steam; Windows 10; first noticed in 2.02 (didn't have the Stave before that), last tested in 2.04c

**Comment by ManDude** [comment]
This has already been reported before. :) But don't worry about it.

**Comment by PaladinOne** [comment]
Hm. I did a search for it but didn't see an issue for it. What number was it?
