### ISSUE TITLE
Crash Upon Completing Challenge 4

### ISSUE THREAD

**Issue by nchrien** [larsiusprime/tdrpg-bugs#1142]
Operating System: OSX 10.11.5
Browser/Download: Download
Demo/Full?: Full
Version # : Steam DQ1 2.0.4c c
Optional Info: 
    Hardware: Late 2013 Macbook Pro, 13" Retina version, i5 processor
    I can provide further details on hardware, game configuration, party composition, etc. upon request. Also, I have tried all the standard idiot-level troubleshooting techniques, such as rebooting the computer and reinstalling the game. I haven't kept track of exactly how many times I've reproduced the bug, but it has been at least a dozen or so.

Steps to reproduce:
1. Start a new, standard (not NG+) deluxe version game
2. Unlock 70 or more stars
3. Launch bonus challenge 4
4. Conclude the level with any final outcome (Azra survived unharmed, Azra survived with injuries, or Azra was slain)

Expected:
The game would proceed to the post-battle party screen

Occurred:
The game exits instead. When the level is completed successfully (with or without injuries), this occurs upon clicking the OK button on the Level Passed popup; when failed, it occurs as soon as Azra dies. Note that the game does not appear to register this as an actual crash (at least, I can't find a crash log and OSX isn't telling me the application quit unexpectedly), the application just stops running. The crash-like event doesn't always happen upon failing the level (I haven't been able to discern any differences between when it crashes and when it doesn't to account for why), but it has thus far happened on every successful completion of the level.

**Comment by larsiusprime** [comment]
This should be fixed in 2.0.5c

**Comment by nchrien** [comment]
Awesome, thanks much!
