### ISSUE TITLE
Blank cutscene after loading completed save

### ISSUE THREAD

**Issue by Autoquark** [larsiusprime/tdrpg-bugs#1143]
Operating System: Windows 8.1
Browser/Download: Download
Demo/Full?: Full Version
Version #: Steam DQ1 2.0.4c

1. Win "The Way Out" and watch the credits.

2. After being booted to menu, attempt to resume save.

3. A blank black cutscene appears.

4. Clicking next or back a few times causes the game to crash with a null object reference.

After this I started the game again and exported a save (attached).

I then tried loading my save and instead clicking skip at the blank cutscene, which causes the game to progress to the map screen and work normally.

**Comment by Autoquark** [comment]
Not sure if you can upload files directly to Waffle, but here's the save mentioned: https://www.mediafire.com/?q6lcahay3gwp16z

**Comment by larsiusprime** [comment]
I've fixed this in the newest build (2.0.7), I believe.
