### ISSUE TITLE
Every time ET casts Dragonfire, the screen gets a little white permanently?

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1144]
https://www.youtube.com/watch?feature=player_detailpage&v=PJgi7KHedGE#t=983

**Comment by dqhol** [comment]
According to a streamer if he gets it white enough  it will crashes the game. Which will happen on NG+.

**Comment by larsiusprime** [comment]
Does this still happen in the latest version?

**Comment by larsiusprime** [comment]
I can no longer reproduce this in the latest version of the game and strongly suspect it is fixed. I definitely cleaned up some code related to AOE highlights so I think that might have done it.

**Comment by dqhol** [comment]
Reopened as of  2.0.7a

http://steamcommunity.com/app/218410/discussions/0/365172547948329436/

**Comment by dqhol** [comment]
http://steamcommunity.com/app/218410/discussions/0/365172547954329308/ Double-verified to still be in game.

**Comment by larsiusprime** [comment]
FINALLY reproduced this myself. Let's kill it with fire.

**Comment by larsiusprime** [comment]
Fixed in 2.0.8b
