### ISSUE TITLE
Wide screen makes people think only the bad ending exists.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1145]
What you see when wide screen on the split level **VS** What you see square screen.

Quite a few people miss that sliver of red bubble at the very bottom of their screen and only see the bad ending marker leading up.

I'd also maybe suggest replacing 'Ends the game' with 'Ending A' for the bad ending and 'Ending B, C, D or E' for the final level. People see 'Ends the game' and seem to get worried that they can't go back if they select the bad ending, if they see both both options at the split.

![ze](https://cloud.githubusercontent.com/assets/19625520/16361673/ea5ccd26-3b65-11e6-8e52-c2dd91422e77.png)

**Comment by ManDude** [comment]
Dupe.

**Comment by dqhol** [comment]
Of?

**Comment by ManDude** [comment]
Sorry I was on mobile which is a bit hard to use. Dupe of #1056.
