### ISSUE TITLE
Null Object Reference on completion of a bonus mission

### ISSUE THREAD

**Issue by nether9** [larsiusprime/tdrpg-bugs#1146]
OS: Windows 10 64-bit
GOG Download, Full Version, 2.0.4c

So far it has happened at Challenge 1 and Challenge 2. The game crashes right after clicking 'ok' at 'azra survived unharmed' window.

This error wasn't there 2 years ago when I first played this game.

[errorsave.zip](https://github.com/larsiusprime/tdrpg-bugs/files/333589/errorsave.zip)

**Comment by ManDude** [comment]
Can you launch the game from the cmd prompt to get a stack trace when it crashes?

**Comment by nether9** [comment]
Here is the output of the command prompt after launching DQ and playing Challenge 2:
C:\Program Files (x86)\GalaxyClient\Games\Defenders Quest>DefendersQuest.exe

C:\Program Files (x86)\GalaxyClient\Games\Defenders Quest>Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleMouseEvent lime/_backend/native/NativeApplication.hx line 337
Called from lime.app.Event_Float_Float_Int_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 188
Called from lime.app.Application::onMouseUp lime/app/Application.hx line 431
Called from openfl.display.Stage::onMouseUp openfl/display/Stage.hx line 461
Called from openfl.display.Stage::__onMouse openfl/display/Stage.hx line 1079
Called from openfl.display.Stage::__fireEvent openfl/display/Stage.hx line 899
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.ui.FlxTypedButton::onUpEventListener flixel/ui/FlxButton.hx line 499
Called from flixel.addons.ui.FlxUIButton::onUpHandler flixel/addons/ui/FlxUIButton.hx line 331
Called from flixel.addons.ui.FlxUITypedButton::onUpHandler flixel/addons/ui/FlxUITypedButton.hx line 1091
Called from flixel.addons.ui.FlxUI::event flixel/addons/ui/FlxUI.hx line 144
Called from com.leveluplabs.tdrpg.Popup_Confirmation::getEvent com/leveluplabs/tdrpg/Popup_Confirmation.hx line 206
Called from com.leveluplabs.tdrpg.Popup_Confirmation::close com/leveluplabs/tdrpg/Popup_Confirmation.hx line 223
Called from com.leveluplabs.tdrpg.State_Battle::getEvent com/leveluplabs/tdrpg/State_Battle.hx line 277
Called from com.leveluplabs.tdrpg.State_Battle::endBattle com/leveluplabs/tdrpg/State_Battle.hx line 1557
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Jagael** [comment]
Have the same issue.  Complete all waves in a bons mission, click OK to exit level, receive null object warning, game crashes.

OS: Win 7 SP 1 64-bit
Steam download, full version, 2.0.4c
Windowed 1152x648

**Comment by larsiusprime** [comment]
This should be fixed in 2.0.5.c
