### ISSUE TITLE
Psi shield takes all psi and also HP

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1148]
2.0.4c/win7x64

Equipped the psi shield on NG+ bonus level.  First enemy instead of taking the 109 HP per his stats, took that _and_ 535 PSI away.  From the description I figured he'd take 109 PSI away, and if she didn't have that, he'd take HP instead.  Even if that's not correct, it seems like this book is more like Book of Daring than a beneficial one :)

![dq-psi-shield](https://cloud.githubusercontent.com/assets/16719964/16363163/5899d610-3bc2-11e6-8bdc-f5da1d415f0d.png)

**Comment by larsiusprime** [comment]
What I think is happening, is that when enemies deal PSI damage instead of HP, they take way more PSI than they would HP. And if there's not enough PSI to satisfy them, they take off some HP as well.

So I think the book is working as intended.

**Comment by IBwWG** [comment]
But they take off the full amount of HP they normally would have?

And if 535 PSI < 109 HP, what's the conversion factor?  I think it would be good to advertise that in the description somewhere (whether you put the number explicitly or not.)

**Comment by ManDude** [comment]
If the enemy is supposed to deal 109 damage and Azra took 109 damage then it's definitely bugged.

**Comment by larsiusprime** [comment]
Can you post the exact save file, @KJB?

On Wed, Jun 29, 2016 at 7:41 PM, ManDude <notifications@github.com> wrote:

> If the enemy is supposed to deal 109 damage and Azra took 109 damage then
> it's definitely bugged.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1148#issuecomment-229529970>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-CjPN-eeehWuqMxYOlMfnt_n9oacks5qQxC4gaJpZM4I-kv_>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
[export-bonus-psi-shield.zip](https://github.com/larsiusprime/tdrpg-bugs/files/341348/export-bonus-psi-shield.zip)
