### ISSUE TITLE
Missing skull from "The Catacombs" in NG+

### ISSUE THREAD

**Issue by Aykernar** [larsiusprime/tdrpg-bugs#1149]
**Basic information:**
Bug found in Defender's Quest Deluxe v. 2.0.4c from GOG, on Windows 7.

**Steps to reproduce:**
I have not played through the game up to that point again to retry it, but assuming it is repoducable, play "The Catacombs" on Extreme and achieve a perfect rating without getting a perfect Advanced win first.

**What I expected to happen:**
In New Game+, the side quest map "The Catacombs" is supposed to give one stone skull for perfect advanced completion, and a bronze skull for perfect extreme completion.

**What happened instead:**
 If you do the extreme challenge immediately, it only rewards you with the bronze skull, instead of giving you both rewards as is the norm (with a "more" button to move to the 2nd reward). Replaying the map later on advanced does not award the missing skull - it is effectively lost.

I have **not** attempted doing the advanced challenge before doing the extreme challenge in DQ-Deluxe, so it is possible that the stone skull is not awarded upon completion of that, either, but I do not know.

**Attached save:**
The total skulls at the current progress should be 13 stone (4 from each of "The Coliseum", "Return to The Coliseum" and "River Escape", plus the missing one from "The Catacombs") and 1 bronze (from "The Catacombs"), but visiting the hermit shows only 12 stone skulls and the one bronze skull.
[Skull_bug.zip](https://github.com/larsiusprime/tdrpg-bugs/files/333815/Skull_bug.zip)

**Comment by ManDude** [comment]
I wonder if this happens to all other stages. Hmm.

**Comment by Aykernar** [comment]
Just ran another sidequest which also had the 1 stone/1 bronze reward combination (Gone Fishing), and I recieved both skulls. So it is definitely not something that happens in every case. Whether that means it is specific to The Catacombs or simply something that can happen anywhere very rarely though, I can't say without replaying the 15 hours it took me to get to this point. But I will update if I see the same happen in a different map.

**Comment by Aykernar** [comment]
Same issue just happened on "The Sons of Krast". Only Bronze skull awarded, with a "Continue" button instead of the "More" button that usually leads to the second reward. This time I beat the stage on extreme without having beaten it at any difficulty previously.

**Comment by larsiusprime** [comment]
Hmmm, this is pretty tricky to reproduce! I've tried several times now and each time I always get both skulls, with or without advanced pre-beaten.

**Comment by Aykernar** [comment]
Yeah, haven't found any particular triggers for it either myself - Wish I could be more helpful. Have only had it happen the two times so far, but I'm now exporting my save before each battle in case it happens again so I can go back and retry. That should at least show whether it is just random or actually related to something I do or some state in the game.

Failing that, I may try to do a bit of a speedrun over the next weekend and build up a new party to NG+ level to try the same missions, and see if that triggers it.
