### ISSUE TITLE
Marathon achievement popped in standard‏

### ISSUE THREAD

**Issue by thendarion** [larsiusprime/tdrpg-bugs#1150]
version: 2.04c on GOG
OS: win10

how did it happen?
I returned from Play+ to get the Endurance achievement and I succeeded (I let Azra die shortly after the 100th wave), however, this event triggered both the Endurance and Marathon achievements for me.

save file: https://gist.github.com/anonymous/5cb2a2e0f022274d353e5b0bcf5b1a23

**Comment by larsiusprime** [comment]
Thanks, we'll fix it. It's a known bug.

On Tue, Jun 28, 2016 at 11:48 AM, David Bertalan <notifications@github.com>
wrote:

> version: 2.04c on GOG
> OS: win10
>
> how did it happen?
> I returned from Play+ to get the Endurance achievement and I succeeded (I
> let Azra die shortly after the 100th wave), however, this event triggered
> both the Endurance and Marathon achievements for me.
>
> save file:
> https://gist.github.com/anonymous/5cb2a2e0f022274d353e5b0bcf5b1a23
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1150>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-H4cKML3OKrfmUUzzTttAlcSsgv9ks5qQVBcgaJpZM4JAThP>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
This will be fixed in 2.0.6
