### ISSUE TITLE
Dark creeps become separated from their cloud during "The God-King Walks Again"

### ISSUE THREAD

**Issue by Autoquark** [larsiusprime/tdrpg-bugs#1151]
OS: Windows 8.1
Version: Steam DQ1 2.0.5 c (full)
Other: 1366x768 resolution

Whilst playing "The God-King Walks Again" on Advanced difficulty I observed the cloud of darkness moving separately to several dark creeps that appeared from the rightmost entrance. By the time I took the screenshot, they had floated off screen. Could be something to do with NPCs casting spells?

Screenshot: http://imgur.com/a/pvQUY

**Comment by dqhol** [comment]
Same with bleed.

![ze](https://cloud.githubusercontent.com/assets/19625520/16457284/e928c894-3de8-11e6-819f-66dc7fad9c29.png)

**Comment by larsiusprime** [comment]
I believe this was related to the random crashes with effect recycling in a recent regression. I was seeing this bug for a looooong time, then I fixed the recent crash by applying an aggressive cleanup loop on effects before reusing them, and then I didn't see it anymore. I'm assuming it's fixed, please reopen if you see again.
