### ISSUE TITLE
Game does not start on Inspiron 1012 netbook computer (Windows and Linux)

### ISSUE THREAD

**Issue by DeeDeeG** [larsiusprime/tdrpg-bugs#1153]
Operating Systems: Windows 7 (32-bit), Xubuntu 16.04 (32-bit), Linux Mint 17.3 (64-bit)
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : Latest as of June 24

Info about what error messages I see:

On Linux Mint 64-bit, I simply get a "Segmentation fault"

On Xubuntu 32-bit, I get "Segmentation fault (core dumped)" but I'm not sure how to access that dump.

On Windows 7 32-bit, I get "Could not create SDL window: Could not initialize EGL." and "Could not create SDL renderer: Invalid window."

**Comment by DeeDeeG** [comment]
I actually do get the game to start on Windows 7 32-bit, but I can only hear the audio; There is no game window, and no way to interact with or play the game. In order to exit the game, I have to use task manager.

**Comment by IBwWG** [comment]
For Linux Mint, IIRC you can try `tail /var/log/syslog` and it should give a few lines about the segfault.

**Comment by larsiusprime** [comment]
This sounds like you might have an issue with your display drivers.

What store did you buy the game on? We have started shipping a GL version on steam for some users with display issues (the default version uses ANGLE), I can started making this available in other places too.

**Comment by DeeDeeG** [comment]
I have the game via an itch.io direct link, because of an ongoing problem with humble bundle direct links. If I need to PM you more details, I can.

**Comment by DeeDeeG** [comment]
As for /var/log/syslog on Linux Mint, I get this line:

Jun 29 15:59:26 mint-Inspiron-1012 kernel: [11193.549670] dqx86_64[4572]: segfault at 24d98 ip 00007f7c5a6dcf74 sp 00007fffb5048980 error 4 in i915_dri.so[7f7c5a40e000+554000]

**Comment by IBwWG** [comment]
Hey, same library as my error on Mint 17.2 32-bit:  https://github.com/larsiusprime/tdrpg-bugs/issues/1019#issuecomment-225979570

If y'all find a solution to that I'd love to try it there too :)

**Comment by DeeDeeG** [comment]
Getting a nearly identical message from build 2.0.5c-3-gacf9209, from the Google drive folder.

Jun 29 18:26:44 mint-Inspiron-1012 kernel: [20031.591544] DefendersQuest[5341]: segfault at 24d98 ip 00007f5febb4bf74 sp 00007fff1bbb9240 error 4 in i915_dri.so[7f5feb87d000+554000]


https://drive.google.com/open?id=0BxAP9Z8yy-2kQS00VnM1VnJVRW8

**Comment by larsiusprime** [comment]
Hmm, it's interesting that we now have two reports of this happening specifically with Mint.

**Comment by DeeDeeG** [comment]
I got it to run on the Inspiron 1012, under Xubuntu 16.04 32-bit, by loading the 3.19.0-56 kernel, which is older than the one I had been using (4.4.0-21).

(I tried the same kernel version 3.19.0-56 on Linux Mint 17.3 64-bit, and it did not work.)

**Comment by ManDude** [comment]
Just wondering, how do I know the game is running on ANGLE and not a different render mode (or something).

**Comment by DeeDeeG** [comment]
@ManDude I don't know about Linux or Mac, but on Windows I noticed this: you can open your Defender's Quest folder and mouse-over "libegl.dll" or "libglesv2.dll" (or right click -> Properties -> Details)

If you are using an ANGLE version, the tooltip that pops up should say eg: ANGLE libEGL Dynamic Link Library. (I have no idea if that's accurate, but I would have to assume.)

**Comment by ManDude** [comment]
Ah yes I realized that, but I was talking about this:
http://image.prntscr.com/image/ada36c448ed94ff4b8137dbe8b22f52a.png

**Comment by DeeDeeG** [comment]
On Win 64-bit I see "Hardware + ANGLE" in-game.

http://imgur.com/V3uo5pP.png

**Comment by larsiusprime** [comment]
Yes, from now on I put the renderer in the lower left hand corner. I've also started stamping 32 vs 64 bit there as well in newer builds.

Shall I call this fixed for now as it seems system/driver/etc specific?

I'll look into the other issue someone raised about the magic new google library to increase compatibility for windows users.

**Comment by DeeDeeG** [comment]
Sure, this can be closed.

_Just to leave my thoughts on what's going on, in order to wrap things up, or if this deemed important later and re-opened:_

_I think this happens when a user's graphics driver doesn't support a high enough version of OpenGL._

_I'm basing that on a similar thing/issue discussed here: https://github.com/servo/servo/issues/12053_

_So if that's what's going on, the only way to get the GPU to render the game, for these users, would be to somehow support lower version #'s of OpenGL._

_I don't really know if supporting older OpenGL versions is a) possible; b) justified for the few of us with old netbooks and such who can't run the game._

So yeah, again, probably time to close this one. Thanks for looking into it.
