### ISSUE TITLE
Range + Boosted Range circles won't disappear after using hotkey to deselect character

### ISSUE THREAD

**Issue by michael-camacho** [larsiusprime/tdrpg-bugs#1154]
### Basic Info:
Windows 10
Full Version
Version # 2.0.5c

I'm using fullscreen mode, and my screen resolution is 2560 x 1440.

### Steps to Reproduce:
1. Play any level where you have at least one boostable ranger or mage available
2. Select the ranger / mage (so that their current range is displayed as a white circle)
3. Hover the mouse over the "BOOST" button (so that the boosted range is displayed as a blue circle)
4. Press "Esc" to deselect _(I usually just press "Q" to select the Berserker tab instead)_

### What I Expected to Happen:
I expected the white and blue range circles to disappear, since the character was no longer selected.

### What Happened Instead:
The character was deselected, but both circles remained onscreen (and now both blue, for some reason). The circles wouldn't go away until a new character was selected.

**Comment by larsiusprime** [comment]
Fixed in 2.0.7
