### ISSUE TITLE
XP Level UP but no skills point and no level up

### ISSUE THREAD

**Issue by damien-giry** [larsiusprime/tdrpg-bugs#1155]
![level up](https://cloud.githubusercontent.com/assets/6086129/16471963/57dc11de-3e15-11e6-874a-060b1e5b4a15.png)
![but nothing in fact](https://cloud.githubusercontent.com/assets/6086129/16471968/5aca078e-3e15-11e6-9e18-03acdce61eec.png)

Windows 10, last version on steam (2.0.5c).
A ice mage lvl 6 level up to 850 XP. Normally nothing append but I got a "LEVEL UP!" message in the XP bar and no skills point.

**Comment by ManDude** [comment]
How much XP does Raska have?

**Comment by damien-giry** [comment]
850
I think that this is a problem when the XP level reach max level.

**Comment by ManDude** [comment]
Well you can edit your saves. Anyway at 850 is EXACTLY 0 XP to LVL 7 so that may be one way to reproduce this.

**Comment by ManDude** [comment]
Actually, XP can be given in decimals (normal Revenant give 0.5 XP + about 0.1 XP for each level they have). That's why you didn't get any perk, because you're not actually at LV7 and you didn't actually level up.

**Comment by damien-giry** [comment]
Good you find this quickly.
Really cool to replay this game from beginning in HD version :) Good luck with bug hunting.

**Comment by ManDude** [comment]
I recall this being in the old version too. Not really a gameplay bug, just display bug. :)
