### ISSUE TITLE
German translation: Diary pages clean-up

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#1156]
Alright, I thinnk the single most important fix for the German translation is those diary pages.

I've sent it via email before, but here it is again for convenience's sake:

DIARY PAGES:

Tag 3 - Anhang - overlap
Nacht 3 - Anhang 2 - overlap
Tag 4 - Buchhaltung - overlap
Tag 14 - Nomaden - overlap
Nacht 15 - Worte - overlap
Tag 16 - Narbigen Lippen - overlap
Nacht 17 - Fuchs - overlap
Tag 23 - Rede - first sentence on the 2nd page needs to be in italics
Tag 24 - Meuchel - needs more pages
Tag 24 - Superschaf - overlap, needs more pages
Tag 26 - Wrennas - needs more pages
Tag 27 - Das Böse - overlap
Tag 27 - Markos - needs one more page
Tag 28 - Tod - needs more pages
tag 32 - overlap
tag 33 - schwarzen - overlap
tag 34 - tagebuch - overlap
tag 34 - fünfter - overlap
tag 38 - frieden - overlap
tag 38 - ein abschiedstraum - overlap

SECRETS:
einleitung - needs more pages
der rock - needs more pages
stärke des - needs one more page
triff den berserker - last page untranslated
Der Ash-Tempel - needs more pages
schwertscheidenplatzierung - needs more pages
entfernte charaktere - needs more pages
dem bösen einen namen geben - needs more pages
Namen und Sprachen - overlap

All overlap issues have to be looked into by you, Lars. If something needs more pages, add an empty set of pages and I'll move the overflowing text onto those pages.

**Comment by larsiusprime** [comment]
Fixed in 2.0.8
