### ISSUE TITLE
Game crashes during cutscenes after intense battles

### ISSUE THREAD

**Issue by ClaudioBasckeira** [larsiusprime/tdrpg-bugs#1157]
# Basic Info
Windows 10
Download (Steam)
Full Version
Version # 2.0.4 c

Running on a desktop PC at 1920x1080 native full screen, 16GB RAM, Core i5 4th gen, GTX 970 video card.

# Steps to reproduce:

1. Start the game on a save file with very intense battles not yet finished. The last battles of the game work well, specially on NG+.
2. Play and win said battle on extreme, have the screen very busy in the meantime, enough to cause slowdown.
3. During the ensuing cutscene, there is a chance the game might crash after clicking "Next" in one of the scenes, normally after half the scenes were seen.

# What I expected to happen:
Watch the cutscene normally until the end and proceed with the game.

# What happened instead:
The game crashed to desktop (Defender's quest stopped responding...) the moment I clicked."Next" in one of the scenes.
When reopening the game and loading the save file the cutscene will immediately begin and go on as normal.

**Comment by larsiusprime** [comment]
Does this happen in 2.0.5c ?

**Comment by ClaudioBasckeira** [comment]
Ugh, will be hard for me to reproduce it now, as my lone save file already has NG+ completed. Is there a way to reset the "watched" flag for post battle cutscenes?

Another problem is that it doesn't always happen.

**Comment by ClaudioBasckeira** [comment]
Here you go

[2016_06_30.zip](https://github.com/larsiusprime/tdrpg-bugs/files/342181/2016_06_30.zip)

**Comment by ClaudioBasckeira** [comment]
The pattern I noticed is more or less: Whenever the game would have crashed mid-battle before it was solved (haven't been having any in-battle crashes since 2.0.4), now it will crash somewhere in the following cutscene. And I once had the game crash on the party screen while distributing skill points. But again, it happened a grand total of 4 times among about 20 battles where it seemed to meet this criteria. The behavior hasn't been consistent.

**Comment by larsiusprime** [comment]
I'm pretty sure I solved something that sounds very much like this in
2.0.5c, but let's make sure. Thanks for the save.

On Thu, Jun 30, 2016 at 2:31 PM, ClaudioBasckeira <notifications@github.com>
wrote:

> The pattern I noticed is more or less: Whenever the game would have
> crashed mid-battle before it was solved (haven't been having any in-battle
> crashes since 2.0.4), now it will crash somewhere in the following
> cutscene. And I once had the game crash on the party screen while
> distributing skill points. But again, it happened a grand total of 4 times
> among about 20 battles where it seemed to meet this criteria. The behavior
> hasn't been consistent.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1157#issuecomment-229764215>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Bgzn1PAPLunE31zrTHF5guCAOzWks5qRBmHgaJpZM4JCf8k>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
I'm going to go ahead and close this as I'm pretty sure it's fixed. Feel free to re-open if not.
