### ISSUE TITLE
Crash to desktop bug

### ISSUE THREAD

**Issue by Mallek0** [larsiusprime/tdrpg-bugs#1159]
Operating System: Windows 8.1
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : 2.0.4c

This bug while easily reproducible for me isn't something that would come up very often and I found it by complete accident

Steps:
1. Press the options menu on any screen
2. Press any of the sub menus such as audio or video
3. Click accept or cancel
4. Once the screen has returned to the main options menu press the space bar. Game will crash to desktop with a Null Object Reference error popup.

I expected the space bar to act as a exit for the menu simply because I had played a different game recently that used space bar in that way and my muscle memory tried it in this game on accident.

As I said this isn't a massive issue but since I could repeat it so easily I figured it was worth at least reporting.

**Comment by larsiusprime** [comment]
Does this still happen in 2.0.5c?

**Comment by larsiusprime** [comment]
Wow you're right! That's very easy to reproduce. What on earth is causing this?

**Comment by larsiusprime** [comment]
Okay I've got a fix in. It'll be available in 2.0.6a

**Comment by Mallek0** [comment]
Glad it was an easy fix! Thanks for the great game.
