### ISSUE TITLE
Battle options menu can be accidentally triggered to automatically open many times on close

### ISSUE THREAD

**Issue by theinternetftw** [larsiusprime/tdrpg-bugs#1160]
Windows 10
Steam DQ1 2.0.6

To Repro:
1) In-battle, open the options menu (e.g. by hitting escape)
2) Hit escape (nothing will immediately happen)
3) Close the options menu

The menu will be re-opened, thanks to that second escape keypress being saved as buffered input while in-menu.  Since the escape key is the "options menu open" hotkey, hitting it again to close the menu is a natural assumption, but that instead this triggers it to automatically open the menu again once you finally close it with the mouse.

This becomes an even bigger issue if you hit the key multiple times while in the options menu (wondering why the menu isn't closing), which results in the menu being automatically triggered however many times you hit escape, opening again each time you try and close it again.

(edit: change name/info to better describe why this is a problem)

**Comment by larsiusprime** [comment]
Thanks for the report, just reproduced this locally.

**Comment by larsiusprime** [comment]
Fixed in 2.0.7
