### ISSUE TITLE
Book of Plagues makes Super Sheep take 416,500 damage per second, BoP poison icon without tooltip.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1165]
Seems unintended.

**Comment by ManDude** [comment]
I'm pretty sure this has been reported before, actually.

**Comment by dqhol** [comment]
https://github.com/larsiusprime/tdrpg-bugs/search?q=sheep&type=Issues&utf8=%E2%9C%93 ?

**Comment by ManDude** [comment]
Whoops, must've been on the forum then.

**Comment by larsiusprime** [comment]
Fixed in 2.0.7
