### ISSUE TITLE
Crash when trying to level up ranger skill

### ISSUE THREAD

**Issue by xtj-9182** [larsiusprime/tdrpg-bugs#1167]
I tried to level up my rangers skill for the first time and I got a crash, I have 4 berserker and 4 ranger not sure if that makes any difference.

[_error.txt](https://github.com/larsiusprime/tdrpg-bugs/files/344121/_error.txt)

**Comment by larsiusprime** [comment]
Thanks for this report, the error message contains everything I need to
reproduce and fix this, we'll have it taken care of in the next patch.

I'm 99% sure your save file should not be affected and if you load back up
you shouldn't have lost any progress. Let me know if the bug happens again,
or if it's just a rare occurrence.

On Fri, Jul 1, 2016 at 3:22 PM, xtj-9182 <notifications@github.com> wrote:

> I tried to level up my rangers skill for the first time and I got a crash,
> I have 4 berserker and 4 ranger not sure if that makes any difference.
>
> _error.txt
> <https://github.com/larsiusprime/tdrpg-bugs/files/344121/_error.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1167>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-FMuBZe0OSeZUZrNTjaafXCgZsU5ks5qRXcfgaJpZM4JDdEQ>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by xtj-9182** [comment]
it happened like 4 times in a row when I tried to level up any ranger skill since then it didn't happen again and I have since progressed in the game, I'm not able to reproduce this anymore sadly.

**Comment by larsiusprime** [comment]
I'll definitely make sure it's fixed in the next build anyways, thanks for
the report.

On Fri, Jul 1, 2016 at 4:37 PM, xtj-9182 <notifications@github.com> wrote:

> it happened like 4 times in a row when I tried to level up any ranger
> skill since then it didn't happen again and I have since progressed in the
> game, I'm not able to reproduce this anymore sadly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1167#issuecomment-230052813>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-HJAUa9FBRjAFeTq2eJP1EYE2zwMks5qRYiegaJpZM4JDdEQ>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
I've put in a fix that should help in 2.0.7, will push that later this week.
