### ISSUE TITLE
Repeatedly, consistently crashing (Null Object Reference)

### ISSUE THREAD

**Issue by Risakisa** [larsiusprime/tdrpg-bugs#1169]
OS: Win7 ultimate x64
Download
Full (GOG)
V: 2.0.4c

Steps to reproduce: Start the first challenge, win, get Null Object Reference crash.

Tried with high- & low res. sprites, fullscreen and windowed. Gave up after the 5th crash, as this is an easy challenge, yet takes a while to finish.

I've been trying to attach my save file, but it won't let me. Instead, dropbox. (Yes, I am exceptionally immature when it comes to naming my troops. I was drunk at the time.) https://www.dropbox.com/s/j1g1ehhe9sa30yj/DQ%20Save.dfq

Added a video of the crash. https://youtu.be/p2v9ccCgkdI (It's uploading as I type this)

**Comment by ManDude** [comment]
GOG hasn't been updated it seems. We're on version 2.0.6.
