### ISSUE TITLE
extreme slow down on the new item screen

### ISSUE THREAD

**Issue by pszxzsd** [larsiusprime/tdrpg-bugs#1172]
Operating System: Linux 32bit (Ubuntu 16.04)
Browser/Download: Download, Steam
Demo/Full? : Full Version
Version # : 2.0.5c
Optional Info** : Netbook, 1024x600 screen, fullscreen, graphics and story animations set to classic (not HD), mouse pointer set to plain system

When receiving a new bonus item after a level the background is black and there is a window with the description and the options to equip it or to continue. Not much going on really but on that screen I get so much cpu usage and the mouse pointer gets so laggy that it's hard to actually click one of the buttons. This might not be noticeable on a half-decent computer but on my potato netbook it's very pronounced. I also see the fancy mouse cursor here, like in all the intermezzo story animations, despite setting it to plain.

**Comment by IBwWG** [comment]
Had you played earlier versions?  I was having this too, but 2.0.3a made it way faster.  (I haven't tried 2.0.5c on my linux netbook yet.)  If it was fast in that earlier version for you too, maybe it's a regression...?

**Comment by IBwWG** [comment]
Also the cursor issue has related issue https://github.com/larsiusprime/tdrpg-bugs/issues/772

**Comment by pszxzsd** [comment]
so far 2.0.5c is the only version I have played

**Comment by pszxzsd** [comment]
Some more info: this also happens on the new spell screen that is basically the same and the problem gets much, much worse as the game progresses (levels completed, not the time it has been running in a single session).

**Comment by pszxzsd** [comment]
Even more info since I was toying with the HD tiles: this bug really only occures with the classic graphics, with the HD ones it's fine. Also moving on the world map is dog slow with classic graphics. I thought this was just my netbook being ancient and didn't consider it a bug, but with the HD tiles movement on the world map is fast and smooth. Looks like some general problem with the classic graphics code paths.

**Comment by larsiusprime** [comment]
Hmmm, I'm having a hard time reproducing this, do you have problems with battles or only the overworld and the "you got" menus?

**Comment by pszxzsd** [comment]
The battles are reasonably fast, I'd say no or little difference between classic and HD tiles. I had really only opted for the classic graphics because I assumed that would be faster, but since the new graphics actually work better, the issue is basically no more on my end.
