### ISSUE TITLE
[Suggestion] Use SwiftShader as a workaround for users who have graphics driver problems

### ISSUE THREAD

**Issue by DeeDeeG** [larsiusprime/tdrpg-bugs#1173]
This is arguably not a real fix for users having a problem with their graphics drivers, but it would let them play the game. 

This blog post from Google explains what SwiftShader is.

http://blog.chromium.org/2016/06/universal-rendering-with-swiftshader.html

It's basically some C++ routines that implement the OpenGLES API (And apparently Direct3D 9), running purely on the CPU. You don't need working graphics drivers that can do hardware accelerated graphics. As a game developer, you don't have to change the game's code in order to use it. You just have to already be targeting OpenGLES or Direct3D 9.

Side Note: I can't figure out how to build the source, but I found a pre-compiled Windows (Direct3D 9) dll, and it let me run DQ. Framerate was low, but my machine isn't fast to begin with. I wasn't expecting more than that.

Their code repository is here: https://swiftshader.googlesource.com/SwiftShader

Seems like a crazy suggestion, I know, but you can consider it if you'd like.

"The SwiftShader libraries act as drop-in replacements for graphics drivers. On Windows, most applications can be made to use SwiftShader's DLLs by placing them in the same folder as the executable. On Linux, the LD_LIBRARY_PATH environment variable or -rpath linker option can be used to direct applications to search for shared libraries in the indicated directory first."

The License is Apache 2.0 and is totally compatible as far as I can tell with use in Defender's Quest.

**Comment by larsiusprime** [comment]
Wait WHAT? You just drop the dll's next to the executable and you have an instant software shader?

**Comment by DeeDeeG** [comment]
Pre-compiled binaries are now available from the SwiftShader authors. Located here: https://drive.google.com/drive/folders/0B8_BlOx5-97CcEhTdy1UNzhXSVE
