### ISSUE TITLE
Crash after battle fadeout on Ubuntu 14.04 32-bit

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1176]
2.0.5c, Ubuntu 14.04 32-bit.

Just after finishing a battle, the screen faded to black after clicking OK, and before the screen with the levelups, the window disappeared and we got this:

```
~/.config/itch/apps/Defenders Quest Valley of the Forgotten DX$ ./dqi686
fixTrailingSlash = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/
now = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/
fixTrailingSlash = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/
now = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
pathToFile = /home/mathilda/.local/share/LevelUpLabs/DefendersQuest/SAVE_SLOT_1.dfq
*** Error in `./dqi686': free(): invalid next size (fast): 0x13d21ab8 ***
Abgebrochen (Speicherabzug geschrieben)
```

There was also a crash clicking the OK button on the levelup screen, but we were running straight from itch-app, so we got no stack trace.  Unless it kept it somewhere.  I should check that.

**Comment by larsiusprime** [comment]
"*** Error in `./dqi686': free(): invalid next size (fast): 0x13d21ab8 ***" looks like a hard crash.

The stack trace looks like an infinite loop.

I think we might have fixed this in 2.0.6, which I'm trying to roll out later today for linux. Interested to see if it fixes it.

**Comment by larsiusprime** [comment]
@IBwWG: is this fixed?

**Comment by larsiusprime** [comment]
No confirmation that this is still happening, assuming it's fixed. Please re-open if it recurs in version 2.0.8 or later.
