### ISSUE TITLE
Crash after level completion

### ISSUE THREAD

**Issue by Tuberculosis** [larsiusprime/tdrpg-bugs#1178]
Operating System: Windows 10
Browser/Download: Download (Steam)
Demo/Full?      : Full Version
Version #       : 2.0.6a

1. Play any level (I played on NG+ but I assume it doesn't matter)
2. With a unit selected, press 'b' while the level-end pop-up is active (lose, win or perfect)

I expected nothing to happen.

'Null object reference' popped up and then the game closed down.

**Comment by larsiusprime** [comment]
Thanks, looking into it. I'm assuming it's still present in 2.0.6b (should
be up now)?

On Mon, Jul 4, 2016 at 10:37 PM, Tuberculosis <notifications@github.com>
wrote:

> Operating System: Windows 10
> Browser/Download: Download (Steam)
> Demo/Full? : Full Version
> Version # : 2.0.6a
>
>    1. Play any level (I played on NG+ but I assume it doesn't matter)
>    2. With a unit selected, press 'b' while the level-end pop-up is
>    active (lose, win or perfect)
>
> I expected nothing to happen.
>
> 'Null object reference' popped up and then the game closed down.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1178>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-B03NqTSoQ4dXWploB_AEpTaWDvvks5qSdGFgaJpZM4JEwQE>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Tuberculosis** [comment]
Yep, just downloaded it and it's still there in 2.0.6b

**Comment by larsiusprime** [comment]
Kay, we'll be sure to have it fixed in 2.0.7, thanks.

On Mon, Jul 4, 2016 at 10:51 PM, Tuberculosis <notifications@github.com>
wrote:

> Yep, just downloaded it and it's still there in 2.0.6b
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1178#issuecomment-230382456>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-InQGPYD3MpK9QtsPN2dZwI-M5Bhks5qSdS4gaJpZM4JEwQE>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Now fixed in 2.0.7, coming this week.
