### ISSUE TITLE
story background graphics not showing with some resolutions

### ISSUE THREAD

**Issue by pszxzsd** [larsiusprime/tdrpg-bugs#1180]
Operating System: Linux 32bit (Ubuntu 16.04)
Browser/Download: Download, Steam
Demo/Full? : Full Version
Version # : 2.0.5c
Optional Info*\* : Netbook, 1024x600 screen, fullscreen, graphics and story animations set to classic (not HD), mouse pointer set to plain system

At 1024x600 I get only black backgrounds during the story intermezzos, at 800x600 they show up fine. This is true for both classic and HD styles.

**Comment by larsiusprime** [comment]
I believe this has since been fixed.
