### ISSUE TITLE
Stopped Working on Linux (Steam)

### ISSUE THREAD

**Issue by Bekk72** [larsiusprime/tdrpg-bugs#1181]
OS: Linux Mint 17.1 Rebecca
Kernel: Linux 3.13.0-37 - generic (x86_64)
Version: Full
Purchased: Steam for Linux
Version #: Not sure (won't start), but new (first installed July 2, 2016) and have been playing it daily.
Betas: No
Other Info:  It had been starting perfectly approximately 12 hours earlier.  When I started Steam this time, it showed that the game was updating.

Started Steam.
Pressed the "PLAY" button.
Chose "Play Deluxe version (recommended)".
The "Preparing to launch..." window appeared for a second and closed.
Game did not start.

Same results when I try to start it from Steam's drop down menu on my panel (taskbar).

***

I've done various things to troubleshoot:

Uninstalled and reinstalled the game...it still wouldn't start.

Uninstalled the game and rolled back all the few updates to my operating system that were done since the game started correctly.  Reinstalled the game...it still wouldn't start.

Uninstalled the game, let my computer update again before reinstalling the game...still no luck.

I've verified the integrity of the game cache with Steam's tool with each installation...it says it's fine.

With every fresh installation, I try to start it "as is" before I copy my saved configuration folder into it and I've noticed that it doesn't run long enough to create the folder containing the paths.xml, options.xml, etc.

It doesn't start without nor with the restored folders.

***

Uninstalled Steam and reinstalled it...wash, rinse, repeat all of the above...no dice.

***

I tried to start it from the Terminal (command line) and it pulled a lot of errors, like...

`ERROR: ld.so: object '/home/(myname)/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

I would guess that it's reaching into the 32 bit folder when it should be reaching into the 64 bit folder...but we're getting into things I prefer not to tinker with unless I have an expert looking over my shoulder.

If there's anything else I can do on my end to help fix this, please let me know.

Thank you,
Bekk72

**Comment by dawelty** [comment]
I can verify this.

I'd been holding off playing until some bug fixes were in, so I can't pin down exactly what version I've got now but, when I tried to play on 2016-07-05, Steam updated the game and launching failed just as Bekk72 described.

I've tried verifying and reinstalling, just as he has, with no luck.

OS: Linux Mint 17.3
Kernel: 3.19.0-32-generic (x86-64)
Demo/Full: Full
Purchased: Steam for Linux
Version #: Unknown -- Steam version up to date as of 2016-07-05.
Betas: No

**Comment by larsiusprime** [comment]
sorry guys, i tried compiling on a new machine, i'll roll it back in a few hours

**Comment by larsiusprime** [comment]
rolled back. Does it work again?

**Comment by Bekk72** [comment]
Started right up for me after updating :-D

Thank you for making such a stellar game and debugging it so quickly!

Bekk72

**Comment by larsiusprime** [comment]
Okay, new VM installed, using Ubuntu 12.x this time, let's see if building on that has better compatibility for everybody.
