### ISSUE TITLE
Duplication of units when loading previous setup

### ISSUE THREAD

**Issue by Tuberculosis** [larsiusprime/tdrpg-bugs#1182]
![defendersquest](https://cloud.githubusercontent.com/assets/20292338/16613979/322e6408-43b2-11e6-97a8-a0ad745696cb.jpg)

Operating System: Windows 10
Browser/Download: Download (steam)
Demo/Full?      : Full Version
Version #       : 2.0.6b

I think this was caused by loading the previous setup when starting a level, then editing it before starting the first round, then replaying the same level and loading the previous setup again.

In the screenshot, you can see seven healers (some sharing a square with other units).  I _think_ there are also two Slaks in the one square up the top.

It has happened once before, but I can't reproduce it reliably.  All units still attack, though some units in the original or new setup don't seem to be placed due to limited psi (i.e. I think all units cost the correct amounts of psi, so because there are duplications I run out of psi at setup).

**Comment by larsiusprime** [comment]
Very interesting catch, thanks!
