### ISSUE TITLE
build 2.0.6x don't start on Linux/steam

### ISSUE THREAD

**Issue by Kupferdrache** [larsiusprime/tdrpg-bugs#1183]
OS: Ubuntu 16.04 LTS x86_64

Type: Download
Liscence: Full
Version 2.0.6 (x) steam
(humble version is still 1.x so I could us it to test as well)

<b>Steps to reproduce</b>

start steam
selecet DQ I
hit play
select Deluxe
hit start game

<b>Expected Behavior</b>

the game window appears

<b>that happened instead</b>

Nothing the game crease instantaneously without a error message.

**Comment by larsiusprime** [comment]
I rolled back 2.0.6 to 2.0.5x on steam, I'll upload a new linux version soon

**Comment by Kupferdrache** [comment]
though I file a proper bug report this time, I want to test the new translations and the other bug. so I have to wait until the new build is finished and running (this time hopefully, a successfull build, can crash anyway, a failed build won't run at all).

**Comment by larsiusprime** [comment]
New build should be up in about an hour on test_public. In the meantime can you confirm that 2.0.5x is successfully rolled back for linux?

**Comment by Kupferdrache** [comment]
Yup, it did reverse to 2.0.5c for me. so rollback seems to work.

**Comment by Kupferdrache** [comment]
The 2.07a beta is out now and it fixes this issue.

**Comment by larsiusprime** [comment]
EXCELLENT!

On Fri, Jul 8, 2016 at 8:05 AM, ManDude <notifications@github.com> wrote:

> Closed #1183 <https://github.com/larsiusprime/tdrpg-bugs/issues/1183>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1183#event-716978810>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-CFf9dJvbRjjx3S73jg8oRT0Fb8cks5qTksBgaJpZM4JG7mI>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
