### ISSUE TITLE
Crash in 2.0.6b when losing the game

### ISSUE THREAD

**Issue by xtj-9182** [larsiusprime/tdrpg-bugs#1184]
So this crash just happened when I was about to lose the match. The Stack trace looks similar to the one from an already fixed crash (https://github.com/larsiusprime/tdrpg-bugs/issues/1167) so no idea if this is a new one or if it's already fixed in 2.0.7.

[_error.txt](https://github.com/larsiusprime/tdrpg-bugs/files/351981/_error.txt)

**Comment by larsiusprime** [comment]
Hmmm, this looks like a new one. Added a null guard for 2.0.7 just to be safe, seems like a rare crash that only happens when a swimming enemy gets killed with extremely specific timing.

**Comment by xtj-9182** [comment]
oh I've looked at the stack trace from the wrong side. It's from down up and not from up down. Anyway thanks for fixing it.
