### ISSUE TITLE
Localization: Status effects not displaying in Spanish

### ISSUE THREAD

**Issue by FelipeMercader** [larsiusprime/tdrpg-bugs#1188]
Operating System: Windows 8.1
Steam version (public beta)
Version#: 2.0.7. a

Status effects are displayed in English. It happens for all units (see blue square in bottom-left corner)

![image](https://cloud.githubusercontent.com/assets/19960780/16684928/ff48f290-4507-11e6-91ad-7edcbf798d9b.png)

**Comment by LarsMadeMeDoIt** [comment]
Probably because the status descriptions file (status_effects.tsv) is entirely missing from the Spanish folder. You're also missing two other files by the way: goodies.tsv (the 'like us on facebook' reward) and mods.tsv

**Comment by larsiusprime** [comment]
My fault, I left out status_effects.tsv, and forgot to send felipe goodies/mods. Adding status_effects for 2.0.8
