### ISSUE TITLE
Localization: Some special characters not displaying in Spanish

### ISSUE THREAD

**Issue by FelipeMercader** [larsiusprime/tdrpg-bugs#1190]
I think it is not related with the characters themselves. I mean, the character "ú" is displayed sometimes, but not displayed in other cases. Cannot possibly understand why.

![image](https://cloud.githubusercontent.com/assets/19960780/16685403/35e009a8-450b-11e6-9751-c619555ab58f.png)
vs
![image](https://cloud.githubusercontent.com/assets/19960780/16685439/661dfd00-450b-11e6-8fb2-ec1a709225b1.png)

I noticed a pattern. Never displayed correctly when ending a word/having a space behind.
Weird but it seems like this, at least in several cases.

![image](https://cloud.githubusercontent.com/assets/19960780/16685571/46beeb58-450c-11e6-9ea9-7c5fefda3bd6.png)

![image](https://cloud.githubusercontent.com/assets/19960780/16685186/ac140f4a-4509-11e6-8ac3-855019dcef6e.png)

![image](https://cloud.githubusercontent.com/assets/19960780/16685383/1e8381cc-450b-11e6-8d7b-f50fb298bd93.png)

**Comment by larsiusprime** [comment]
Hmm, weird. Bet it's some unicode function I'm using that's not parsing everything properly.

**Comment by larsiusprime** [comment]
Somehow this was caused by actual corrupted data in the file itself:
```$TIP_10_TEXT	¡Puedes controlar el juego con el teclado!<N><N>- Seleccionar hechizos<N>- Selecionar qu? personajes invocar<N>- Mejorar / retirar defensores<N>- Pausar / reanudar el juego<N>- Cambiar entre defensores invocados<N>- Cambiar las opciones de fij. objetivo/velocidad<N>- Moverte entre pestañas en cualquier interfaz<N>- Mover el cursor/clicar con el teclado<N><N>(Personaliza las teclas en el men? de opciones)				```

**Comment by FelipeMercader** [comment]
I can see that it was well displayed in the original csv file (system.csv).
¡Puedes controlar el juego con el teclado!<N><N>- Seleccionar hechizos<N>- Selecionar qué personajes invocar<N>- Mejorar / retirar defensores<N>- Pausar / reanudar el juego<N>- Cambiar entre defensores invocados<N>- Cambiar las opciones de fij. objetivo/velocidad<N>- Moverte entre pestañas en cualquier interfaz<N>- Mover el cursor/clicar con el teclado<N><N>(Personaliza las teclas en el menú de opciones)

Maybe it got corrupted when changing into TSV format file (core.tsv)?

**Comment by larsiusprime** [comment]
Yeah it was almost certainly my fault somewhere in the pipeline. Luckily most of the transformations are obvious, I just sent you a comprehensive list if you want to double check it for me.
