### ISSUE TITLE
Localization: Cutscenes titles displaying badly when 2 lines. Spanish

### ISSUE THREAD

**Issue by FelipeMercader** [larsiusprime/tdrpg-bugs#1191]
Operating System: Windows 8.1
Steam version (public beta)
Version#: 2.0.7. a

Whenever there are two lines of text, squares are displayed. I guess these are non-breakable spaces or something added to avoid overlap?

![image](https://cloud.githubusercontent.com/assets/19960780/16685639/b2afd9bc-450c-11e6-9e58-45927812d5f8.png)
![image](https://cloud.githubusercontent.com/assets/19960780/16685643/bec79550-450c-11e6-8fb6-258307cd85f1.png)

**Comment by LarsMadeMeDoIt** [comment]
Pretty sure it's caused by the <T> command in those lines. I think you can just remove them.

**Comment by larsiusprime** [comment]
That might be it, it was necessary in the original game but might not be necessary (or useful) here...

**Comment by larsiusprime** [comment]
Yup, <T> not only cause artifacts in the new engine, they don't seem to be necessary to align things in the movies menu in DQDX.
