### ISSUE TITLE
Localization: units, classes and button in English when recruiting. Spanish.

### ISSUE THREAD

**Issue by FelipeMercader** [larsiusprime/tdrpg-bugs#1192]
https://www.youtube.com/watch?v=7K8j5Pz-Xbc
Operating System: Windows 8.1
Steam version (public beta)
Version#: 2.0.7. a

Displayed in English.

![image](https://cloud.githubusercontent.com/assets/19960780/16685831/0783abe8-450e-11e6-8869-5899d7f7094f.png)

**Comment by larsiusprime** [comment]
Should be fixed in 2.0.8
