### ISSUE TITLE
Using Dragon Fire Skill will cause Lightning Skill to show wait on the Icon even though the lightning skill has no cooldown and enough Psi is available

### ISSUE THREAD

**Issue by xtj-9182** [larsiusprime/tdrpg-bugs#1194]
I'm on NG+ and I'm using the Anonymous and Chain Lightning Books. When I use Dragon Fire the Lightning Skill Icon will say wait even though it has no cooldown and enough Psi is available.

tested on 2.0.7a

> SystemData
>   OS : Windows 7 SP1
>   RAM: 16725036 KB (15.95 GB)
>   CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>   GPU: NVIDIA GeForce GTX 670, driver v. 10.18.13.6175
> game id:    DQ1
> filename:   DefendersQuest
> package:    com.leveluplabs.defq1

**Comment by larsiusprime** [comment]
What level are you playing this on? Is it one of the sidequests?

What version are you playing? (Title screen, lower right hand corner).

Is it a purely visual bug or also a functional one? IE does it say "wait"
but still let you click?

On Fri, Jul 8, 2016 at 11:48 AM, xtj-9182 <notifications@github.com> wrote:

> I'm on NG+ and I'm using the Anonymous and Chain Lightning Books. When I
> use Dragon Fire the Lightning Skill Icon will say wait even though it has
> no cooldown and enough Psi is available.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1194>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-GzDu8lnLhCO30JJwrD4ozqpVx0Bks5qTn9YgaJpZM4JINCw>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by xtj-9182** [comment]
it's purely visual, the skill still works.

Level should be irrelevant it happens on every level that I played (NG+ or the Chain Lightning Book might be necessary to trigger it maybe)

2.0.7a is my version

**Comment by xtj-9182** [comment]
I can confirm it's caused by the Chain Lightning Book.

**Comment by larsiusprime** [comment]
Perfect. Thanks! I can fix this now.

On Fri, Jul 8, 2016 at 12:10 PM, xtj-9182 <notifications@github.com> wrote:

> I can confirm it's caused by the Chain Lightning Book.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1194#issuecomment-231417045>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-HE0cMvv4pDBRz8I5jOJpaJXWBTjks5qToSjgaJpZM4JINCw>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
