### ISSUE TITLE
Misspelling in flavour text

### ISSUE THREAD

**Issue by egroeggerg** [larsiusprime/tdrpg-bugs#1196]
OS: Windows 7 SP1
Download (steam)
Full Version (Deluxe)
Steam DQ1 2.0.7 a

Problem:
The word "always" is spelt "alwyas" on the second screen of the anonymous book. Example http://imgur.com/ulAhug0
Steps to reproduce
1.get the book of face optional item on the start screen
2. click on The yellow button at the bottom of the screen
3. click on No social networks...
4. aquire the Anonymous book
5.click ok
6.the second window will open and the spelling mistake appears here, the word "always" is spelt "alwyas". http://imgur.com/ulAhug0 for example.

**Comment by ManDude** [comment]
Already reported at #1064.
