### ISSUE TITLE
Eztli Tenoch fades to respawn but is stuck instead

### ISSUE THREAD

**Issue by MasterOfTheMiep** [larsiusprime/tdrpg-bugs#1198]
When trying to beat "The Godking Walks again" on Advanced Difficulty after already playing some levels in NG+, Eztli Tenoch fades to respawn, but gets stuck instead. (See Screenshot) He still takes damage and morphs, but stops doing anything.
![20160714200553_1](https://cloud.githubusercontent.com/assets/20464172/16851568/6e41705e-4a04-11e6-84c1-ab0daaa9109a.jpg)

Upon finally beating him, he will vanish but the level does not stop. There are no longer enemy waves coming and the defenders will stand idle apart from the healers who still cast Zeal. The level itself ran on and the notification flag for ET's heal spell is still around. (See screenshot)
![20160714200913_1](https://cloud.githubusercontent.com/assets/20464172/16851682/f0095afc-4a04-11e6-85dd-9184a2aaa79b.jpg)

After retrying the battle a bit later, ET froze again (This time without fading and while announcing to cast Dragonfire) But this time the level terminated.
![20160714210913_1](https://cloud.githubusercontent.com/assets/20464172/16852243/89a9b36c-4a07-11e6-9e4b-3fa8b6554ad5.jpg)

_Basic Information_
OS: Windows 7 Professional N 64Bit
Download: Steam Version
Full Version
Version: Steam DQ 1 2.0.7 a

Running on a Sony Vaio Notebook with 4 GB RAM

**Comment by ManDude** [comment]
Did he actually cast Dragon Fire?

**Comment by larsiusprime** [comment]
Thanks for the report, I think I've seen this once or twice myself.

On Thu, Jul 14, 2016 at 4:27 PM, ManDude <notifications@github.com> wrote:

> Did he actually cast Dragon Fire?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1198#issuecomment-232797782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-HNih21Y7InL_c1t7Uk7WmRLt6Hdks5qVqnOgaJpZM4JMwPS>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
