### ISSUE TITLE
Capitalization bug

### ISSUE THREAD

**Issue by case8180** [larsiusprime/tdrpg-bugs#1201]
Greetings,

Windows Vista 64-bit
Steam DQ1 2.0.8c - Deluxe Version (rec)

During story cutscenes, if you chose a name for one of your characters with a space in it, the second name won't be capitalized.
![20160722043606_1](https://cloud.githubusercontent.com/assets/20578758/17053888/cf0d2be2-4fc9-11e6-8ccc-1e1a01d87f2c.jpg)

However, it will be properly capitalized in the Index.
![20160722043538_1](https://cloud.githubusercontent.com/assets/20578758/17053900/e1f040f0-4fc9-11e6-8726-8987480c8ce7.jpg)

**Comment by larsiusprime** [comment]
Fixed in 2.0.9
