### ISSUE TITLE
Localization: French journal untranslated

### ISSUE THREAD

**Issue by LarsMadeMeDoIt** [larsiusprime/tdrpg-bugs#1203]
A French user mentioned that the journal is untranslated. Had a look at the file and indeed, over 90% of it is still in English.

 I know the French localization is still WIP, but from what I can tell the journal used to be completely translated in the classic version of DQ, so maybe the game is using the wrong file now?

**Comment by larsiusprime** [comment]
This is indeed a bug!

**Comment by larsiusprime** [comment]
Okay, got that fixed. Now there's the same French journal text in 2.0.9 that there was in the previous game. Don't have the budget yet for a full French translation of the new journal content, but it's at least as much as was originally there.
