### ISSUE TITLE
Librarian character sprite

### ISSUE THREAD

**Issue by case8180** [larsiusprime/tdrpg-bugs#1205]
Greetings,

Windows Vista 64-bit
Steam 2.0.8c - Deluxe Version (rec)

When I switch to standard graphics, the character sprite for the Librarian stretches off the screen. This doesn't happen for the other characters or in HD mode. If I switched to HD mode and back to standard, it doesn't fix it. This happens in full screen mode, but not in windowed mode.

Full screen:
![librarian stretch full](https://cloud.githubusercontent.com/assets/20578758/17152966/e7933976-533f-11e6-9967-9a58561d66ca.jpg)

Windowed:
![librarian win](https://cloud.githubusercontent.com/assets/20578758/17152973/ee4269c2-533f-11e6-97f8-d625bfbd6196.jpg)

**Comment by ManDude** [comment]
What's the fullscreen resolution?
