### ISSUE TITLE
Add modding support for arbitrary terrain categories

### ISSUE THREAD

**Issue by Autoquark** [larsiusprime/tdrpg-bugs#1207]
Currently, the game sorts terrains into three categories:

Illegal: no defender or enemy can stand there
Legal: defenders can be placed there
Path: any enemy can traverse the terrain
Water: enemies with the <walk value="water"> element in their definition can traverse the terrain.

This issue is a request to allow arbitrary additional terrain types to be defined, with enemies having the appropriate walk element being able to cross them. For example, you could add the following to assets/maps/index.xml:

``` xml
<terrain>
     ...usual content...
     <lava>
          <type id="my_lava_tile_1"/>
          <type id="my_lava_tile_2"/>
     </lava>
</terrain>
```

and then define an enemy with the <walk value="lava"> element. That enemy would then be able to cross the terrains defined as "lava".

This would also involve changing the way in which the UI describes creeps in the wave bar & selection panel. The modder would need to be able to specify what (localised) string to use to describe a particular creep capability - for example, the ability to cross water is currently described as "swims".

Finally, the game displays special "splashing" effects when creeps move through water. Ideally, modders would be able to specify such effects for their custom terrain categories.

**Comment by larsiusprime** [comment]
Just a tip -- on github if you want to display xml data you should put it between "fences" -- three ` marks in a row at the top and bottom, otherwise it won't render properly. I just edited it for you.

If you add the word "xml" right after the top fence it'll add syntax highlighting.
