### ISSUE TITLE
Cahnging level cap in defender.xml does nothing

### ISSUE THREAD

**Issue by TeModen** [larsiusprime/tdrpg-bugs#1209]
Not even sure if it's a bug , but...
BASIC INFORMATION:
Operating System: Windows 7
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : 2.0.6 b

STEPS TO REPRODUCE:
1. Create a new mod for core data files
2. Change `<level_cap value="60"/>` string in defender.xml to `<level_cap value="98"/>`
3. Start a "New Game" in this mod
4. Beat the first level 
5. Exit the reward screen from the first battle
6. Exit the game
7. set berserkers lvl to 60 and exp to 109999 (1 exp away from level 61 according to exp table) in corresponding save file `<info level="2" xp="43"/>` to `<info level="60" xp="109999"/>`
5. Beat the first level again 
6. Look at the reward screen

WHAT I EXPECTED TO HAPPEN:
Berserker reaches level 61

WHAT HAPPENED INSTEAD:
Berserker didn't get any exp 
![234](https://cloud.githubusercontent.com/assets/20875637/17458647/9f7447d0-5c21-11e6-91e9-26eb5094131e.png)

I've tried to search number "60" in all game files through the windows search, but found nothing related to level cap.

**Comment by ManDude** [comment]
Already reported I think.

**Comment by larsiusprime** [comment]
This should be fixed now!
