### ISSUE TITLE
HP and PSI labels overflow at higher resoultions (Azra's corner indicators and also battle menu)

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1214]
2.0.8c - steam, win7sp1x64, HD mode@1704x960windowed

![dq-psi-artifacts](https://cloud.githubusercontent.com/assets/16719964/17647646/e9e96830-61f9-11e6-9b2e-1329f5caa8d3.png)

At the top bar, near the P you see these white blobs behind the bar.

In the detail pane, there's no psi bar behind the P whatsoever.

AFAICT this is always the case, at least since I noticed it a few battles ago.

**Comment by ManDude** [comment]
I think that's "HP" with a line break after H, not psi. Afaik there was never a psi bar in Azra's battle menu.

**Comment by LarsMadeMeDoIt** [comment]
It looks like PSI and HP are displayed vertically at that resolution. Actually, it seems to be the case with anything over 1366 x 768.

**Comment by IBwWG** [comment]
Ah, so the scrap behind the top bars is the P from HP and the SI from PSI overflowing?

**Comment by LarsMadeMeDoIt** [comment]
Yes. Just to remove any doubt, I've changed "Psi" to "PsiXYZ" and "HP" to "HP1234". Here's what happened:
![psi](https://cloud.githubusercontent.com/assets/20359621/17670678/7a3a2df6-6313-11e6-81e4-e77762884f00.jpg)

**Comment by LarsMadeMeDoIt** [comment]
I can't reproduce it anymore in 2.05.

**Comment by larsiusprime** [comment]
Me neither.
