### ISSUE TITLE
ET dying doesn't trigger the ending, waits forever

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1215]
2.0.8c - steam, win7sp1x64, HD mode@1704x960windowed
![dq-zelemir-waiting-forever](https://cloud.githubusercontent.com/assets/16719964/17647936/9456e814-6205-11e6-9383-cd8fad204dad.png)

The game has been continuing several minutes at 16X.  Everyone's animating, Zelemir is occasionally making everyone have a Frenzy icon, but nothing more is happening.  I had just beaten ET by getting his last bearded self down to 0 HP, and he exploded into psi stars IIRC.

**Comment by IBwWG** [comment]
Pause/unpause/timescale change doesn't help trigger the ending either.

**Comment by IBwWG** [comment]
No more enemies appear, clicking Send Next just makes the button stay down but doesn't send anything either.

**Comment by IBwWG** [comment]
Menu keeps working normally too, everything is clickable.

**Comment by IBwWG** [comment]
@ManDude is Beta the standard milestone to use now?  Oops...

**Comment by IBwWG** [comment]
OK, I tried to reproduce this, but couldn't.  I believe the first time was on normal, whereas the two times I won without it happening were on casual.  All on NG.

**Comment by larsiusprime** [comment]
Hmm, I haven't pushed a new build so the bug is likely still there. Will try to hunt this one down when I have time.
