### ISSUE TITLE
Incorrect XML in enemy_plus.xml

### ISSUE THREAD

**Issue by Autoquark** [larsiusprime/tdrpg-bugs#1218]
I mentioned this to you in an email but so that there's a proper issue for it:

After exporting a mod, in enemy_plus.xml, the enemy with id "apc_sq7_plus" has two "select_box_offset" elements. (line 2221)

Also, the enemy with id "sheep_sq7_plus" has a spawn location where the y component is "0.0.025" (line 2572)

**Comment by larsiusprime** [comment]
Thanks, I'll try to fix these
