### ISSUE TITLE
Clicking Bonus button when Battle button is underneath opens battle

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1244]
2.0.8b, win10, fullscreen 1920x1080.

Scroll the map such that your current battle button happens to fall underneath the Bonus button, then click Bonus.  You get the battle, even though you can't see the battle button you're clicking.

**Comment by larsiusprime** [comment]
Fixed in 2.1.0

**Comment by IBwWG** [comment]
Not seeing 2.1.0 on itch yet, is it out?

**Comment by IBwWG** [comment]
Oh I see on your twitter it's out on steam.  Itch is pretty straightforward nowadays to create an alternative channel for if you want--user can select within the itch app which one to launch.
