### ISSUE TITLE
??? desert area doesn't show in NG+ hero mode

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1245]
2.0.8b, win10, 1920x1080 fullscreen.

I'm passed the level where the map branches left into the desert for the monument, but it doesn't.  Is the trigger different in hero mode on NG+?

**Comment by ManDude** [comment]
Do you have the book of secrets equipped?

**Comment by IBwWG** [comment]
Oh my gosh.  I knew I was forgetting something.  I didn't even get it from the start screen this time.  Thanks.  :)
