### ISSUE TITLE
Monument keyboard shortcuts click in wrong places

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1247]
2.0.8b, 1920x1080 fullscreen, win10, default QWERTY layout (also at the OS level.)

When you press numbers or letters on the keyboard, the mouse cursor jumps to consistent spots on the screen, but they don't happen to line up with monument clickables.  For example, pressing Z clicks the Leave button, and the numbers mostly click above the top row of symbols.

**Comment by larsiusprime** [comment]
Hmmm, strangely I can't reproduce this.

So couple of questions to possibly suss this out:
1) Do you have an ultra HD monitor?
2) Is display scaling active?
3) Do you have multiple monitors? (I do, but maybe that's a factor)

**Comment by IBwWG** [comment]
1) No, it's just a full HD 1920x1080 acer S230HL.
2) I don't think so, it's in fullscreen mode at a native resolution...
3) Not on this machine.

**Comment by IBwWG** [comment]
Windowed mode at 1024x600 works OK.

BTW I'm not sure about the display scaling because as mentioned in another thread, the graphics look scaled and rough.  But they shouldn't be with 1920x1080 (fs or windowed), right?

**Comment by IBwWG** [comment]
All fullscreen resolutions (at least this quirk where if you start fullscreen but switch to windowed, you're still full screen, but can now switch resolutions, resulting in varying the degree of scaling) seem to have broken keyboard shortcuts in the monument.  Where the cursor jumps to is definitely dependent upon the resolution.
