### ISSUE TITLE
Graphic overlays for enemies vertically or horizontally offset

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1254]
2.0.8b win10, 1920x1080hd fullscreen.

![dqeyenoenemy](https://cloud.githubusercontent.com/assets/16719964/20197032/63f93720-a76b-11e6-9f47-c8c52c9a221d.png)

See the eye above Azra?  It's not hers, and it's moving.  Here's a couple frames later:

![dqeyenoenemy2](https://cloud.githubusercontent.com/assets/16719964/20197059/813876d4-a76b-11e6-9736-ab484c281d58.png)

I can click the space below Azra all I want; despite the number pollution, there's nobody hiding there.  At least nobody responding to a mouse click.

I wonder if this is related to #842, because the mystery bars sometimes seem to correspond to enemy deaths.

**Comment by IBwWG** [comment]
Actually, I'm pretty sure it belongs to the enemy a whole space below:

![dqeyenoenemy3](https://cloud.githubusercontent.com/assets/16719964/20197249/7250d9da-a76c-11e6-84c8-49a213bb08da.png)

I guess this because I can't see the eye belonging to it, and as you can see from the sidebar, it would have one.

I wonder if it would help in general btw to have numbers be not full alpha, especially for crazy battle situations.

**Comment by IBwWG** [comment]
Just saw this again with the next Snake Ghoul+.

**Comment by larsiusprime** [comment]
This is most likely related to effects being recycled and not having numerical offsets reset to zero, or something. Is it easy to reproduce consistently?

**Comment by IBwWG** [comment]
I just saw it on The Halls of the God-King, in 2.0.8b on win10, 1920x1080 fullscreen, but horizontally this time--a lone drop of blood went flying off the left hand side of the screen starting from near the middle-right.  Unfortunately due to #1256 I couldn't reproduce it.  But I do see this bug often--just don't know the exact formula to cause it.

**Comment by IBwWG** [comment]
Still having trouble, although it may be related to being at 16x.  In this case it was from only Slak attacking, so it really depends on chance whether they bleed or not.

**Comment by IBwWG** [comment]
Ah, here it was happening: ![dqdrop3](https://cloud.githubusercontent.com/assets/16719964/20286429/b575c57e-aa94-11e6-8800-fdb92fa8a54f.png)

**Comment by IBwWG** [comment]
A few frames later at 1X then paused:

![dqdrop6](https://cloud.githubusercontent.com/assets/16719964/20286508/03e89092-aa95-11e6-866f-60999f59f780.png)

**Comment by IBwWG** [comment]
BTW you can't click anyone near that drop.

**Comment by IBwWG** [comment]
IE you can click the nearest monster, but there's nobody hidden near it or anything like that.

**Comment by IBwWG** [comment]
Keeps going:
![dqdrop7](https://cloud.githubusercontent.com/assets/16719964/20286551/3889f034-aa95-11e6-96b1-6045399fd53a.png)

**Comment by IBwWG** [comment]
After a few more frames it disappeared this time, before reaching the left edge.  I then lightning'd the two remaining bleeding monsters, killing them, but their blood icons instantly vanished.

**Comment by IBwWG** [comment]
Not sure if this is related or a separate bug: in this one, the selected enemy seems to be underneath Azra (and maybe the floor):

![dqunder](https://cloud.githubusercontent.com/assets/16719964/20294130/df344c5c-aac9-11e6-9d7d-239cc03cdd33.png)

If it is related, that might be what's happening in the other screenshots above too...

**Comment by IBwWG** [comment]
Likewise, ET seems missing here:

![dqinvis](https://cloud.githubusercontent.com/assets/16719964/20319035/ac55f9f4-ab3a-11e6-8432-680e2dff06e9.png)

**Comment by IBwWG** [comment]
Also, I witnessed on another level the overlays being vertically offset, then moving horizontally once the overlay hit the top of the screen.

**Comment by IBwWG** [comment]
This, if it's related, is a really bad side effect: Azra is taking damage and there isn't anyone near her!

![dqazradmg](https://cloud.githubusercontent.com/assets/16719964/20319969/2d630aac-ab3e-11e6-9c6b-3ce947e4c522.png)

**Comment by IBwWG** [comment]
Er, it happened enough times that she went from undamaged to dead.  Then, during her death anim, she apparently came back to life with 15 HP... is that related to that old duplicate Azra bug?

![dqazrares](https://cloud.githubusercontent.com/assets/16719964/20320024/60d3a5a4-ab3e-11e6-8bdd-631c055d7958.png)

**Comment by IBwWG** [comment]
Or does Zelemir's damage transfer to Azra?  Should it?

**Comment by Nicholas-Steel** [comment]
For me it looks like the "Blinded" graphic (eyeballs) keep moving at a consistent pace in the last known direction the enemy was moving in when the problem occurs (I've never been able to pay attention to the correct area of the screen when the issue occurs to see exactly what causes it to happen).

That's my observation when playing the game.

**Comment by Nicholas-Steel** [comment]
IWBG, it'd be nice if you could split your musings in to separate reports.

**Comment by IBwWG** [comment]
@Nicholas-Steel true say, the second bug I did think was related, but now that I look again I have no idea why I would've thought the third one is.  I'll move it.

**Comment by IBwWG** [comment]
Actually, on third thought, maybe I do see the connection (although I left it over at #1268), it doesn't seem directly related the OP, but if the second aspect (seeming z-order trouble) is, and the #1268 is related to that, then it's related to the OP indirectly.

However, now that I think about it, the OP doesn't seem to have to do with z-order trouble after all, since you can usually see the enemy that the overlay belongs to.  So probably I should move the second part to #1268 too, because those too seem more closely related.  I'll just separate them and link them I guess.
