### ISSUE TITLE
After purchase, tooltip (every time) shows wrong item info

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1258]
2.0.8b win10 (don't have steam on this box, so this is the latest I can get via itch) 1024x600 windowed:

![dqwrongtip](https://cloud.githubusercontent.com/assets/16719964/20456112/7f59a6ae-ae3b-11e6-9634-42afbe18b034.png)

I just bought the one described in the tooltip, but now no matter how many times I mouse away and mouse over the Valley of the Forgotten again, it gives the tooltip for the Book of Synergy instead, which had been in that slot before I bought it.

**Comment by IBwWG** [comment]
I can confirm it's this and not Valley of the Forgotten specific.  After the above shot I bought Book of Plagues, and now:

1. Book of Blood has Book of Plagues' tooltip
1. Valley of the Forgotten has Book of Blood's tooltip

**Comment by larsiusprime** [comment]
@ManDude @IBwWG This still happening?

**Comment by ManDude** [comment]
Yes.

**Comment by ManDude** [comment]
![image](https://user-images.githubusercontent.com/7569514/35165904-eca66fce-fd47-11e7-8363-8b0349a3b401.png)
(I bought Book of Plagues)

**Comment by codingthat** [comment]
Still happening on 2.2.6 on Linux.
