### ISSUE TITLE
Enemies don't diverge at path junctions

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1261]
http://steamcommunity.com/sharedfiles/filedetails/?id=806756477
http://steamcommunity.com/sharedfiles/filedetails/?id=806756591

Enemies spawning at the Blue X will always go up and around the square path and never go down and around.

**Comment by Nicholas-Steel** [comment]
Windows 10 x64

**Comment by ManDude** [comment]
I'm pretty sure this also happened on the old version. Nice catch, though!

**Comment by Nicholas-Steel** [comment]
I imagine it would require there to basically be 2 waves of monsters spawning from X at the same time with each wave traveling the opposite way from each other around the square path and you interleave the waves so it looks like the enemies alternate between going up and around and down and around.

**Comment by Nicholas-Steel** [comment]
You would combine the 2 waves on the Wave List at the left side of the screen to keep the Wave List looking the same as it does now..

**Comment by larsiusprime** [comment]
It's a good catch, but too low on the priority list right now. Maybe something we'll tackle in DQII.
