### ISSUE TITLE
incorrect sprite appearance

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1262]
http://steamcommunity.com/sharedfiles/filedetails/?id=806756477

1 up, 2 right from the person ou must defend. Berzerker's in this location seem to be half covered by the background.

**Comment by Nicholas-Steel** [comment]
Windows 10 x64

**Comment by ManDude** [comment]
I don't see any problem here. Care to clarify?

**Comment by Nicholas-Steel** [comment]
http://imgur.com/Jd36HNF

That Berzerker marked in the red box is missing the right half of his sprite.

**Comment by Nicholas-Steel** [comment]
Hmmm, maybe I'm just not used to seeing a Berzerker standing facing that direction.

**Comment by ManDude** [comment]
Nope, the sprite is fine. Closing.
