### ISSUE TITLE
Camera doesn't center on your character on the map when traveling between levels

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1264]
The camera doesn't vertically center on your character on the map when traveling between levels. 

So to navigate to a level below you you must scroll the view down first to see it.

https://youtu.be/q7HTjYSlfVY

Windows 10 x64

**Comment by ManDude** [comment]
Closing this since it is known and already reported. All reports are welcome, though. What version is this?

**Comment by Nicholas-Steel** [comment]
The current stable deluxe recommended version.
