### ISSUE TITLE
Dragon attack radius changes to normal visual instead of yellow ranged visual

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1265]
Incorrect: http://steamcommunity.com/sharedfiles/filedetails/?id=808363831
Incorrect: http://steamcommunity.com/sharedfiles/filedetails/?id=808770879
Correct: http://steamcommunity.com/sharedfiles/filedetails/?id=808363937

https://youtu.be/NxtJlfuDP7k

**Comment by Nicholas-Steel** [comment]
Windows 10 x64

**Comment by ManDude** [comment]
Huh. Weird. Is it consistent? Does it always happen to the same dragon?

**Comment by Nicholas-Steel** [comment]
Seems to affect multiple dragons and am unsure what causes it, perhaps boosting it 3 times (So it learns Roar) and then boosting something else? I added another image URL to the original report to show it also affecting other dragons and have also uploaded a video showcasing the bug happening to 2 dragons.

On a unrelated side note: I figured out why there is no audio in my recordings, I figured it was a Nvidia Shadowplay bug but it is because I was disabling excess audio devices in Device Manager to ensure software used the right device. You need to leave "Nvidia Virtual Audio Device (Wave Extensible) (WDM)" enabled for Shadowplay to record audio.

**Comment by Nicholas-Steel** [comment]
The video URL is provided in the initial report and the video has finished uploading.

**Comment by larsiusprime** [comment]
Thanks for the report, working on this now.

**Comment by Nicholas-Steel** [comment]
I've noticed it in various different levels. The only common thing is what Boost Level the dragon is (Boost Level 3 or 4 and higher).
