### ISSUE TITLE
The Movies button doesn't list NG+ movies?

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1266]
I wanted to re-watch the initial talk with the Hermit but can't, unless the cutscene isn't listed under Act 1.

Windows 10 x64, Steam, latest stable recommended release.

**Comment by ManDude** [comment]
Act 1 ends somewhere after the prison scene, so yeah it's probably in act II if I recall correctly.

**Comment by LarsMadeMeDoIt** [comment]
If you mean when he shows up with the message from Bakal, that happens in chapter 2, scene 4b.

 If you mean something else you'll have to be more specific.

**Comment by ManDude** [comment]
I'm closing this until more details are provided.
