### ISSUE TITLE
Invisible / hidden actors

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1269]
The selected enemy seems to be underneath Azra (and maybe the floor):

![dqunder](https://cloud.githubusercontent.com/assets/16719964/20294130/df344c5c-aac9-11e6-9d7d-239cc03cdd33.png)

Likewise, ET seems missing here:

![dqinvis](https://cloud.githubusercontent.com/assets/16719964/20319035/ac55f9f4-ab3a-11e6-8432-680e2dff06e9.png)

Er, maybe he's just getting ready to move.  A few frames later he started to fade in, then moved suddenly.

Although, I watched closely the next time he teleported, and he didn't seem to go invisible beforehand.  So I think something is actually wrong, on third thought...

It seems like whatever causes this could potentially also cause #1268.

**Comment by larsiusprime** [comment]
@ManDude @IBwWG This still happening?

**Comment by ManDude** [comment]
I never noticed it during my playthroughs.
