### ISSUE TITLE
"Use previous party set up" function ignores the status of Blue Crystals

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1273]
http://steamcommunity.com/sharedfiles/filedetails/?id=812244898

1) Destroy a blue crystal
2) Place a character where the crystal was
3) Restart the mission
4) When asked to re-use the same character positions, click Yes.
5) The character spawns on top of the blue crystal (blue crystal should be destroyed or the character shouldn't spawn there).

**Comment by larsiusprime** [comment]
Thanks very much! I think what I will do is not place characters on those locations, which seems like the safe choice (can always place an extra character or two, can't uncrack the crystals).

**Comment by larsiusprime** [comment]
Reproduced & fixed. Fix available in version 2.1.2

**Comment by Nicholas-Steel** [comment]
Alternatively you could just disallow casting Lightning on the blue crystals until after the first wave of enemies spawns. The "Re-use previous character setup' option seems to stop tracking your setup as soon as the first wave of enemies spawns so it should be a simple solution to the issue.
