### ISSUE TITLE
Italian localization: extra line needed to fix singular/plural issue

### ISSUE THREAD

**Issue by LarsMadeMeDoIt** [larsiusprime/tdrpg-bugs#1280]
Aka: "simple UI issue that I should have posted long ago."

 If I'm not mistaken "$MISC_ARMOR" is used both in the shop menu and the units tooltip (for the armored revenants). My problem is that the former instance should be plural and the latter singular, which is not possible with only one line.

 Would it be hard to differentiate the two cases by adding one extra line, or would that mess things up for the other languages?

**Comment by larsiusprime** [comment]
What I can do is add a second line, and then by default add a redirect for the new line, so that the old languages will continue to behave as normal, but can be updated later.

**Comment by larsiusprime** [comment]
Fixed in 2.1.2

**Comment by LarsMadeMeDoIt** [comment]
Sounds good, thanks.
