### ISSUE TITLE
rename glitch?

### ISSUE THREAD

**Issue by CureUnlovely** [larsiusprime/tdrpg-bugs#1284]
Not entirely sure if this is a bug or not, but... when I was asked to name most main characters in NG+, the name I gave them in the original game was already typed in. But not for Slak. It just had "Slak" typed in. The name I had given him was "Slaking", so I'm wondering if it was a glitch triggered by the fact that his default name was contained in the beginning of the name I gave him.

**Comment by larsiusprime** [comment]
Hmmm, I'll look into it. Thanks for the report.

**Comment by IBwWG** [comment]
Also experiencing something similar on the latest version for Windows available via the itch app.

Started with Azra named "Fern", then (I think after the first battle?) changed to "Phern."  In many places thereafter, it was still "Fern," but in others it was now "Phern."  Sometimes mixed even in the same context, like within a scene, or within the in-battle dialog.
