### ISSUE TITLE
Azra spell cursors initially crossed out until you move the cursor a bit

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1287]
Happens consistently when switching spells via keyboard shortcut.  Linux Mint 18.1 x64, fullscreen 1920x1080, dq 2.1.2c or whatever the latest Itch version is.

 
![dq crossed out](https://cloud.githubusercontent.com/assets/16719964/22182736/2ad1a02e-e0ad-11e6-923a-8cf6babeedef.gif)

**Comment by IBwWG** [comment]
Actually the title screen says "2.1.2c c" (maybe something is cut off?  the second 'c' is right at the edge of the screen.)

**Comment by larsiusprime** [comment]
Thanks for the new batch of bugs, working through them and the rest of my backlog this week.
