### ISSUE TITLE
Mods options "my mods" and "steam workshop" just quit the game (crash?) without warning

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1292]
Just installed steam on linux Mint MATE 18.1 x64.  Installed DQDX (full) so latest "2.1.2c c".  Chose the super space mod made by the devs, and subscribed to it.  (It said, to use the mod, subscribe to it.)

Launch the game, choose DX version.  Asks if I want steam cloud saving, I choose yes.

Start -> Mods -> (either my mods or steam workshop) -> OK = game closes without warning.

**Comment by IBwWG** [comment]
The crash dumps are identical in both cases:

```
SystemData
{
  OS : 	Linux Mint 18.1 Serena (x86_64)
  RAM: 16357240 KB (15.6 GB)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  GPU:  Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
, driver v. unknown
}
--------------------------------------
game id:	DQ1
filename:	DefendersQuest
package:	com.leveluplabs.defq1
version:	2.1.2c - full - steam  release,
tdrpg v:	2.1.2
session ID:	DQ1_2017-02-12_09'02'57
started:	2017-02-12 09:02:57
--------------------------------------
crashed:	2017-02-12 09:03:12
duration:	00:00:15
error:		UNCAUGHT ERROR : Invalid directory
stack:
sys.FileSystem.readDirectory (/home/travis/haxe/std/cpp/_std/sys/FileSystem.hx line 88)
com.leveluplabs.tdrpg.Popup_MyMods.getModGems (com/leveluplabs/tdrpg/Popup_MyMods.hx line 287)
com.leveluplabs.tdrpg.Popup_MyMods.postCreate (com/leveluplabs/tdrpg/Popup_MyMods.hx line 238)
com.leveluplabs.tdrpg.Popup_Confirmation.create (com/leveluplabs/tdrpg/Popup_Confirmation.hx line 106)
flixel.util.FlxTimer.update (flixel/util/FlxTimer.hx line 162)
flixel.util.FlxTimerManager.update (flixel/util/FlxTimer.hx line 239)
flixel.FlxGame.update (flixel/FlxGame.hx line 748)
com.leveluplabs.tdrpg.Main.update (com/leveluplabs/tdrpg/Main.hx line 2192)
flixel.FlxGame.step (flixel/FlxGame.hx line 674)
flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 541)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 237)
openfl.display.DisplayObject.__broadcast (openfl/display/DisplayObject.hx line 243)
openfl.display.DisplayObjectContainer.__broadcast (openfl/display/DisplayObjectContainer.hx line 355)
openfl.display.Stage.render (openfl/display/Stage.hx line 761)
openfl.display.Stage.addRenderer (openfl/display/Stage.hx line 200)
```

**Comment by IBwWG** [comment]
Indeed, the mods directory specified in paths.xml does not exist.

a) should that one even be used for the steam workshop setting?  I don't know how steam workshop works, but it seemed like steam would be downloading the mod, not dq, when you subscribed to it

b) it should probably be autocreated, no?

Anyway paths.xml has:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<data>
	<save value="/home/kev/.local/share/LevelUpLabs/DefendersQuest/"/>
	<mods value="/home/kev/Documents/LevelUpLabs/DefendersQuest/mods"/>
</data>
```

**Comment by IBwWG** [comment]
If I go "create new" in dq, then after creating a stock one with the default options, the 'steam workshop' and 'my mods' options both now show the same thing, a listing showing my new stock mod.

So, workaround achieved, but I think this isn't how it should be out of the box.  :)  I'll open another bug for the steam mod not appearing there...

**Comment by codingthat** [comment]
This still doesn't work out of the box.  Picking "Launch editor" from Steam with a fresh install opens a window (transparent body--just the window frame is visible) for a few seconds, and then closes it.

`~/.local/share/Steam/steamapps/common/DefendersQuest/deluxe/assets/xml/paths.xml` now has:

```
<?xml version="1.0" encoding="utf-8" ?>
<data>
	<mods s="%DOC_GAME%/mods"/>
	<save s="%APPDATA_GAME%"/>
</data>
```

**Comment by codingthat** [comment]
If `%DOC_GAME%` means `~/Documents/LevelUpLabs/DefendersQuest`, nothing beyond the OS-created `~/Documents` existed.  Creating that and then `mods` beneath it doesn't help the "Launch editor" issue.

**Comment by codingthat** [comment]
This is what I get from the command line trying to launch the level editor:
``` sh
~/.local/share/Steam/steamapps/common/DefendersQuest/deluxe $ ./LevelEditor
Segmentation fault
~/.local/share/Steam/steamapps/common/DefendersQuest/deluxe $ ./LevelEditor.sh
Setting breakpad minidump AppID = 218410
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198312656362 [API loaded no]
Timed out waiting for game mapping!
Segmentation fault
```

**Comment by codingthat** [comment]
Also `$LD_LIBRARY_PATH` seems to be undefined in my environment

**Comment by codingthat** [comment]
(This is on beta opt-out BTW; launching DQ gives version 2.2.2_1/30/2018 in the corner of the title screen.)

**Comment by codingthat** [comment]
Actually though if I first play the game and pick "mods" then "create a mod", instead of crashing, it creates the above-mentioned directory.  So that's better than before.  Still don't see a way to launch the level editor though.

**Comment by codingthat** [comment]
This workaround is still needed to make it so mods show up at all (c.f. #1321 ) but these crashes don't seem to be present anymore.
* * *
DQ 2.2.6_6/1/2018 on Linux Mint 19 (64-bit) in fullscreen mode on a 1920x1080 single-monitor setup with an Intel HD Graphics 4400 chipset.
