### ISSUE TITLE
Steam mod installing broken?  (Or unclear...)

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1293]
Through the steam workshop page (either from Shift+Tab and clicking Workshop, in-game, or just through the steam app), I select a mod, and am told to subscribe to download it:

> Subscribe to download
> Super Space Defenders

Next to that is a big green button that says, "Subscribed," because I had clicked it when it said "Subscribe."

After numerous restarts and [getting the mod directory to exist so the game doesn't crash](https://github.com/larsiusprime/tdrpg-bugs/issues/1292#issuecomment-279203975) (plus another restart) this mod is not appearing in the mods list that I get from Start -> Mods -> Steam Workshop or My Mods.

**Comment by IBwWG** [comment]
Also it doesn't appear to be downloaded and hiding somewhere under steam's files, unless its name is obfuscated:

```sh
~/.local/share/Steam $ find . -name *Super*
~/.local/share/Steam $
```

**Comment by codingthat** [comment]
For anyone reading this now, the description at http://steamcommunity.com/sharedfiles/filedetails/?id=155176929 has been updated to say that this particular mod is not DQDX-compatible.

Maybe it could be put in a repo with a todo list somewhere, and the community could help port it?

**Comment by codingthat** [comment]
This process is still not clear on a fresh install.  After creating a test mod as a workaround, it seems that Steam Workshop mods now show up under "My Mods" instead.  Also, once they do, then selecting "My Mods" from the mods menu gives this:

![20190823165959_1](https://user-images.githubusercontent.com/26723818/63602341-7db9c080-c5c7-11e9-8a4c-05ffebdfcbeb.jpg)

Whereupon clicking Okay immediately crashes the game:

```
$ ./DefendersQuest.sh
Setting breakpad minidump AppID = 218410
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198312656362 [API loaded no]
OmniData.initUser()
addPrecache()
Timed out waiting for game mapping!


Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 212
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 370
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 179
Called from lime.app.Application::__catchError lime/app/Application.hx line 340
Called from openfl.display.Application::__dispatchErrorEvent openfl/display/Application.hx line 88
Called from openfl.events.EventDispatcher::dispatchEvent openfl/events/EventDispatcher.hx line 95
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from crashdumper.CrashDumper::onErrorEvent crashdumper/CrashDumper.hx line 188
Called from com.leveluplabs.tdrpg.CrashDumperTDRPG::doErrorStuff com/leveluplabs/tdrpg/CrashDumperTDRPG.hx line 123
```
* * *
DQ 2.2.6_6/1/2018 on Linux Mint 19 (64-bit) in fullscreen mode on a 1920x1080 single-monitor setup with an Intel HD Graphics 4400 chipset.
