### ISSUE TITLE
Level editor just black for me.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1294]
I launch Level Editor. It goes through a couple of CMD pop-ups, then shows the level editor which is completely black. Not frozen, not crashing, just black.

**Comment by larsiusprime** [comment]
We found the bug. I left in a hard-coded debug routine that tries to write to `C:\temp\log.txt`.

I'm deploying a fix now, but a temporary workaround until then is to create that file locally.

**Comment by larsiusprime** [comment]
Bug fix is deployed. Force steam to redownload it by the "verify file integrity" under properties/local files and it should work?

**Comment by ManDude** [comment]
Wait when was this made?? Why did I not know about this until now?? This is really cool I gotta check it out.

**Comment by larsiusprime** [comment]
We're announcing it Monday :)
