### ISSUE TITLE
Despite having two custom levels enabled, only one appears.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1300]
I selected both my levels in the mod tab.

Closed the game, reopened.

Bottom right says: MOD SUPEREPIC+1 (SUPEREPIC,TESTP)

I go into the game, only TEST is visible. Both levels are unedited versions of the levels I included in a previous post.

**Comment by larsiusprime** [comment]
![2017-02-26 21_11_40-defender s quest i](https://cloud.githubusercontent.com/assets/739064/23347468/34232fc2-fc68-11e6-82e1-f91c0a033f18.png)

Can't reproduce, at least not yet. I load two different mods, and both battles appear.

Can you verify that your two different mods ("SUPEREPIC" and "TESTP") both have the battles you want in them, and that when you load each mod by itself, the associated level appears correctly?

If not, zip up your mods and send them to me so I can try to repro.

**Comment by dqhol** [comment]
Ah, I hadn't thought to check them individually, so I just toggled them both on. It takes quite a while to load up the game, go to mods, apply a mod, reload the game, check if it's functional, close the game, go to level editor, modify something and repeat on my computer. So I tried to do both at once.

It turns out the reason SUPEREPIC wasn't appearing was either due to it's title length or blurb length. A title too long causes it to not display at all, though I'm not sure what the limit is. Should probably be capped to that in the level editor.

**Comment by larsiusprime** [comment]
Kay, I'll try to add some fixes for that.

I'll also try to add some options to the title screen when a mod is loaded:

- Unload mod
- Reload mod

I believe the original game had these features.

**Comment by dqhol** [comment]
I already fixed earlier the level by shortening the title, but if you want to load the bugged SUPEREPIC, it's the same as the one in this zip: https://github.com/larsiusprime/tdrpg-bugs/issues/1299#issuecomment-282428616

Any title too long just doesn't display in the bonus level select menu.

**Comment by larsiusprime** [comment]
Kay, that sounds like a pretty simple fix.

I've got new menu options in locally for unloading/reloading mods from the title screen with one click, and it speeds up the loop considerably.

**Comment by larsiusprime** [comment]
Added new title menu options.

I repro'd your glitch and it indeed stems from having a really long battle title. I'll fix this soon, but it won't make the launch.
