### ISSUE TITLE
Custom levels lack description text.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1301]
In level 1 my text is TEST. In level 2, my text is SUPER EPIC repeated 100 times.

Selecting either one in the mod list in-game presents the text 'Description goes here'

**Comment by dqhol** [comment]
Nevermind, I just realized that the 'Description goes here' isn't actually tied to anything you can actually edit. Only the level title and blurb in the BONUS level list.

Is there supposed to be a field to change that text?

**Comment by larsiusprime** [comment]
Looks like we didn't implement it yet. You can get at it directly in the settings.xml, but I agree it would be nice to have an option to edit it in the editor. Probably won't make the launch today, but I can get it in the next patc.
