### ISSUE TITLE
Can't pan overworld camera all the way upwards

### ISSUE THREAD

**Issue by Nicholas-Steel** [larsiusprime/tdrpg-bugs#1305]
With the Party located at any level near the bottom of the overworld map you will be unable to scroll the overworld map all the way up. Noticed in New Game and New Game+. I tried scroling up via Keyboard keys as well as dragging with the left mouse button.

Windows 10 x64
v2.1.5 (top option)
1920x1080 (Fullscreen)

**Comment by Garryl** [comment]
I've run into this problem myself, too. The further south Azra is on the world map, the more of the map's north end is cut off. At the southernmost battle dot (The God-King Walks Again), the northernmost battle dots, including the 1st level (The Half-Way World) are completely cut off, with the northernmost town dot (The Hospital) barely visible. One node north of that (The Face of Madness), the 1st level battle dot becomes barely visible. At the southernmost cave battle dot (Detonate The Mines), the trio of northern NG+ dots (the 2nd hermitage, The Sons of Krast, and Into the Shadows) become barely visible.

I'm running Mac OS 10.11.6 (El Capitan). My monitor has a resolution of 1680x1050, and my game is running in windowed mode at 1600x900. I am playing Defender's Quest Deluxe, 64-bit OpenGL, version Steam DQ1 2.1.5a.

**Comment by Nicholas-Steel** [comment]
Yes a very good explanation of the problem, thank you Garryl.

**Comment by codingthat** [comment]
Still an issue on latest normal channel on Steam (from January 2018) under 64-bit Linux Mint 18.2 at fullscreen 1920x1080.
