### ISSUE TITLE
DQ1 SLAC has a question mark instead of a face.

### ISSUE THREAD

**Issue by domitri** [larsiusprime/tdrpg-bugs#1306]
In the mission "Coliseum" in conversation, SLAC has a question mark instead of a face (russian localization).

Version 2.1.5
Windows 10 x64
1680x1050 (Fullscreen)
russian localization game
![untitled-1](https://cloud.githubusercontent.com/assets/24471323/23455385/13bc702e-fe78-11e6-94c5-267fd4326d97.jpg)

**Comment by domitri** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/24471323/23455242/8d691ea0-fe77-11e6-9b8c-28f2fa307688.jpg)

**Comment by ManDude** [comment]
what the heck that's a new sprite, never seen that before.

**Comment by larsiusprime** [comment]
Fixed in 2.1.7, patch coming soon.
