### ISSUE TITLE
Null Object Reference in second battle with XBOX360 USB controller

### ISSUE THREAD

**Issue by krelbel** [larsiusprime/tdrpg-bugs#1310]
Steps to repro: Using an XBOX360 USB controller, start the second battle, there's a repeatable crash in the transition in the middle of the second battle.  Only occurs when using a controller; no repro when I use mouse+keyboard to control the game.

Error report is below:

> SystemData
>{
>  OS : Windows 7 SP1
>  RAM: 16751704 KB (15.98 GB)
>  CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
>  GPU: NVIDIA GeForce GTX 1080, driver v. 21.21.13.7849
>}
>--------------------------------------
>game id:	DQ1
>filename:	DefendersQuest
>package:	com.leveluplabs.defq1
>version:	2.1.5
>tdrpg v:	2.1.4
>session ID:	DQ1_2017-03-02_00'02'06
>started:	2017-03-02 00:02:06
>--------------------------------------
>crashed:	2017-03-02 00:02:46
>duration:	00:00:40
>error:		UNCAUGHT ERROR : Null Object Reference
>stack:
>com.leveluplabs.tdrpg.Popup_Tutorial.injectGamepadButtonIcons (com/leveluplabs/tdrpg/Popup_Tutorial.hx line 1039)
com.leveluplabs.tdrpg.Popup_Tutorial.updateText (com/leveluplabs/tdrpg/Popup_Tutorial.hx line 628)
com.leveluplabs.tdrpg.Popup_Tutorial.onNext (com/leveluplabs/tdrpg/Popup_Tutorial.hx line 517)
com.leveluplabs.tdrpg.Popup_Tutorial.onActionDigital (com/leveluplabs/tdrpg/Popup_Tutorial.hx line 268)
com.leveluplabs.tdrpg.TDRPGState.sendActionDigital (com/leveluplabs/tdrpg/TDRPGState.hx line 171)
flixel.input.actions.FlxActionDigital.check (flixel/input/actions/FlxAction.hx line 59)
flixel.input.actions.FlxAction.update (flixel/input/actions/FlxAction.hx line 317)
flixel.input.actions.FlxActionSet.update (flixel/input/actions/FlxActionSet.hx line 269)
flixel.input.actions.ActionSetRegister.update (flixel/input/actions/FlxActionManager.hx line 704)
flixel.input.actions.FlxActionManager.update (flixel/input/actions/FlxActionManager.hx line 569)
flixel.FlxGame.updateInput (flixel/FlxGame.hx line 827)
flixel.FlxGame.update (flixel/FlxGame.hx line 736)
com.leveluplabs.tdrpg.Main.update (com/leveluplabs/tdrpg/Main.hx line 2235)
flixel.FlxGame.step (flixel/FlxGame.hx line 674)
flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 541)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 237)
openfl.display.DisplayObject.__broadcast (openfl/display/DisplayObject.hx line 243)
openfl.display.DisplayObjectContainer.__broadcast (openfl/display/DisplayObjectContainer.hx line 355)
openfl.display.Stage.render (openfl/display/Stage.hx line 761)
openfl.display.Stage.addRenderer (openfl/display/Stage.hx line 200)

**Comment by larsiusprime** [comment]
Sorting out these reports. Can't reproduce this in the latest version, hopefully that means it's been fixed for a while. Will go live in version 2.1.7, coming soon. Please re-open if it persists.
