### ISSUE TITLE
Game Window Starts Partly Offscreen

### ISSUE THREAD

**Issue by Garryl** [larsiusprime/tdrpg-bugs#1324]
When I start up Defender's Quest via Steam, once it finishes loading, it moves the window to a position partially offscreen. Roughly the bottom fifth and right fifth of the height and width are outside the screen. It's ultimately just an inconvenience, since all I have to do is manually recenter the window.

I'm running Mac OS 10.11.6 (El Capitan). My monitor has a resolution of 1680x1050, and my game is running in windowed mode at 1600x900. I am playing Defender's Quest Deluxe, 64-bit OpenGL, version Steam DQ1 2.1.5a.

![screen shot 2017-03-20 at 11 54 34 pm](https://cloud.githubusercontent.com/assets/3309272/24132553/c7890244-0dcc-11e7-8b39-6d33f04c2003.jpg)

Edit: To clarify, the initial window when starting the program is much smaller and is properly centered. The issue stems from the fact that when it finishes loading, it expands down and to the right, but does not recenter the window on the screen, leading it to expand beyond the bounds of the screen.

**Comment by larsiusprime** [comment]
Nice catch! Fixed it, you'll see it come through in patch version 2.1.7, coming soon.
