### ISSUE TITLE
[Balance] Healer's Group Heal Reduces Survivability

### ISSUE THREAD

**Issue by Garryl** [larsiusprime/tdrpg-bugs#1326]
In the Defender's Quest engine, each ability has a minimum amount of time to be activated based solely on the ability's animation and ignoring the defender's speed. Thus, no matter how fast a defender is, there is an upper limit to how fast they can use their abilities, especially low-boost abilities with low cooldowns. This is a particular issue for the Healer, whose single-target heal, Aid (boost 1), has the lowest cooldown of all defenders (except the Berserker with maximized Swiftness while wielding the speed-boosting Evni+ sword), while also having relatively long animations for higher-boost abilities. As a result, while the Healer theoretically has the throughput to keep fellow defenders alive through most situations, in practice they may be unable to do so when higher-boost abilities are enabled.

The way this comes up most often is with regard to the Group Heal (boost 3) ability. Group Heal has a slightly longer animation time than Aid, but heals dramatically less (approx 2/5 when both at level 1, scaling at approx 1/2 the rate per point). The AI prioritizes using Group Heal over Aid, even when only 1 or 2 nearby defenders are damaged. In such a situation, healing through put would be higher using Aid instead. Damage tends to concentrate on only one or two defenders, rather than being evenly spread across many, so this is the most common situation. In a high damage situation, the single-target healing loss caused by using Group Heal can be enough to let a defender die. This most often occurs with a Berserker attacking an enemy with thorns, such as a Cultist Priest+. Counterintuitively, disabling a healing ability improves healing enough for the Berserker to remain alive.

I would suggest the following as a possible solution. Increase Group Heal's cooldown and healing per cast such that each cast heals an amount comparable to a cast of Aid to each target. The total healing per second of the ability's cooldown need not change, just the healing per second of animation time.

**Comment by larsiusprime** [comment]
This is a known issue and a basic flaw in the original game's design. Given how old the design is at this point, I think I'm just going to leave it in, but we'll definitely try to avoid this kind of issue for the sequel.
