### ISSUE TITLE
Item List Scroll Up Button Partially Obscured

### ISSUE THREAD

**Issue by Garryl** [larsiusprime/tdrpg-bugs#1327]
When partially scrolled down a list of equippable items that is longer than can all be displayed at once on the screen, the button to scroll up and the indicator of how many more items there are above the ones displayed are partially hidden underneath the item list. In the screenshot below, I have a total of 14 books: 6 displayed, 6 below, and 2 above.

![screen shot 2017-03-21 at 1 21 40 pm](https://cloud.githubusercontent.com/assets/3309272/24160921/6a48697c-0e39-11e7-8125-4330ff4a2222.jpg)

I'm running Mac OS 10.11.6 (El Capitan). My monitor has a resolution of 1680x1050, and my game is running in windowed mode at 1600x900. I am playing Defender's Quest Deluxe, 64-bit OpenGL, version Steam DQ1 2.1.5a.

**Comment by larsiusprime** [comment]
This is fixed in version 2.1.7, due out soon.
