### ISSUE TITLE
Three Digit Attack Values Push Weapon Icon Into Defense

### ISSUE THREAD

**Issue by Garryl** [larsiusprime/tdrpg-bugs#1328]
When viewing the party screen for a defender with 6 or more characters of attack numbers displayed (most commonly 3 digits of base attack, a plus sign, and 2 digits of weapon attack), the small icon for the equipped weapon is pushed into the border between the two boxes of stats.

![screen shot 2017-03-21 at 1 25 17 pm](https://cloud.githubusercontent.com/assets/3309272/24161553/228857b2-0e3b-11e7-8014-4ce07e8f719b.jpg)

I suspect that if there were 7 total characters (for example, a 3 digit base attack value and a 3 digit weapon attack value), the weapon icon would be pushed further and would overlap the Defense value's shield icon. Likewise, I suspect the same issue is present for Defense and armor. Unfortunately, no such situations are possible in the base game, and the mod editor still not working for Mac means I can't easily create appropriate equipment myself.

I'm running Mac OS 10.11.6 (El Capitan). My monitor has a resolution of 1680x1050, and my game is running in windowed mode at 1600x900. I am playing Defender's Quest Deluxe, 64-bit OpenGL, version Steam DQ1 2.1.5a.

**Comment by ManDude** [comment]
Well, you know what they say. The best defense is good offense.
