### ISSUE TITLE
DQ1 journal is not translated into russian. (DX edition)

### ISSUE THREAD

**Issue by domitri** [larsiusprime/tdrpg-bugs#1331]
Page the journal Azra "9 day journeys" not translated into russian.

Version 2.1.7
Windows 10 x64
1680x1050 (Fullscreen)
russian localization game

![ea81655c-fe77-11e6-8cfe-e653c9f4810a](https://user-images.githubusercontent.com/24471323/27469901-326d3900-57fa-11e7-9ab0-63efb2fc1a4c.jpg)

**Comment by domitri** [comment]
![ea81655c-fe77-11e6-8cfe-e653c9f4810a](https://user-images.githubusercontent.com/24471323/27469838-0013845a-57fa-11e7-8b73-63d8132afc5f.jpg)

**Comment by larsiusprime** [comment]
Yes, unfortunately the Russian translation is currently incomplete (it was done by fans, so we've included whatever they have done so far). Ideally we'd like a full translation, but of course that's a lot of work and we're grateful for whatever the community provides. Perhaps we can make it more clear that the translation is not 100% complete somewhere to manage this expectation?

**Comment by domitri** [comment]
Hi :)
Can I translate this piece of text myself and send you a ready translation?
I send TXT file.
