### ISSUE TITLE
List of bugs

### ISSUE THREAD

**Issue by Jozrael** [larsiusprime/tdrpg-bugs#1333]
I apologize for not properly categorizing these, but since I doubt I'd follow through with making all of them in the proper format I figure this is better than nothing.

**Basic Info**

Windows 7
Steam, Download
Full Version
Version # 2.1.7
I am using a desktop, windowed mode, 800x600.

**Bugs**

1: Can cause game to lock in tutorial. Repro: Start a new game, get to the first battle screen, when Azra begins talking. Press any virtual mouse key [e.g. numpad directionals, or enter/escape whichever it is]. Game stops responding to input - mouse or keyboard. Note: doesn't occur on overland, when there is no text in battle, and at least some later battle text as well. Possibly just in the tutorial, I didn't exhaustively test this.

2: Spell description doesn't disappear as expected. Repro: When you hover over a spell with the cursor, i.e. not using a hotkey, the description appears. After clicking the spell and moving away, the description remains indefinitely, whether you complete the cast or not. A workaround is to go back and hover over any spell icon, and then move back off of it.

3: I have had the game crash twice. I apologize that I didn't grab the savefiles at the time. The second was at the beginning of a New Game+, during the movie "Practical Blood Feud", at the point of scene change from the dungeon to outside, where Ketta would begin talking.

4: Achievement toasts are only showing in the top right on client restart. I would expect them to toast when earned.

5: Some achievement text is truncated: "Endurance" under Medium, "Reach wave 100 on Endless Challenge 2 in the standard". I assume game would be here on a higher resolution.

6: Movie "Fish Sticks" [Act 2], the line "FISH LOOK UPON YOUR DOOM" - the dialog is not placed correctly. "FISH" is truncated to the left as the dialog bubble isn't drawn centered [only one in the game I've seen like this]. Again possibly resolution related.

7: Most journal entries run off their page, resolution related.

8: Can lock out a character from being summoned. Repro: Equip book of daring. Start battle. Recall hero. Exit battle. Unequip book of daring. Start battle. Cannot place hero. Only known workaround is client restart.

9: Entering secrets work very inconsistently. If I do a client restart and enter a secret, I can get it to work 100% of the time. But if you enter random other input and then a fresh secret, frequently it doesn't work. Sorry I no longer have a savefile without all secrets or I could do more easy testing here.

10: Why do max level characters have a partially filled XP bar. It's aggravating. Got me to actually open up the savefile and set their XP to 0 to stop it from drawing :p.

11: NOT a bug, but usability feedback: it is painful when you are doing a 50+ wave mission and don't struggle until near the end. Setting to 16x speed is INCREDIBLY useful, thank you - but my feedback here is on 'Send Wave'. In comparison, send wave is inconsequential speedup. I understand there'd be significant gameplay impact by allowing waves to stack...but come on there might be 40+ waves of completely inconsequential monsters. Pls figure out some rules to allow spamming 'next wave', or starting at a higher wave, or w.e. I understand monster stacking overpowers AoE abilities, but there must be a gameplay solution here somewhere.

12: New Game +, first challenge map: SEVERE lag, not seen a bit of lag in any other map in this game. 

13: Hovering over a wave name significantly lags the game. I would never have noticed this if not for #12, but it's a pretty sizeable speed reduction.

14: In New Game+, Challenge names are already yellow. Incomplete challenges by convention should be white. I completed them all in the first game by this point, so that's probably related.

**Comment by Jozrael** [comment]
And @larsiusprime, lmk if you need any more info for any of these. Thanks for your game!

**Comment by ManDude** [comment]
2 and (I believe) 13 have already been reported before, but thanks for your post anyway!

**Comment by larsiusprime** [comment]
@Jozrael Try the new hotfix, up on test_public now. Reopen if there's any issues not addressed here.

**Comment by Jozrael** [comment]
@larsiusprime :+1: will do when time arises this week. Thx again!
