### ISSUE TITLE
No LevelEditor.exe

### ISSUE THREAD

**Issue by Hy60koshk** [larsiusprime/tdrpg-bugs#1336]
> Windows 10
> Steam
> Full Version
> Version # 2.2.0

When I launch Mod Editor on Steam it is failing with "missing executable" error.

I tried to verify the cache, then switched to test build and verified the cache there. It’s still doesn’t download the LevelEditor.exe.

![image](https://user-images.githubusercontent.com/20334588/34454025-c07081cc-ed72-11e7-99d3-0680ce97683b.png)

**Comment by ManDude** [comment]
This feature hasn't been added yet, actually (at least not like this). You will have to mod it manually! It's not that bad though, it's a bunch of XML files.

**Comment by Hy60koshk** [comment]
I do actually, but right now I can't understand why custom item types ceased to work in 2.2.0, so I thought the Editor would shed some light upon it.

**Comment by larsiusprime** [comment]
No, the reporter is right -- I must have screwed up the level editor
somehow in the latest patch. Big patches always come with the risk of
regressions, thanks very much for reporting this issue.

I will recompile and resubmit the level editor with the next hotfix patch,
due out next week.

What's the issue with custom item types? Mods should have still been
working, if you can describe the issue I'll try to reproduce it. Do you
have some mod files you can share that used to work but now don't?

**Comment by Hy60koshk** [comment]
Sure, here's the mod: [http://steamcommunity.com/sharedfiles/filedetails/?id=915877239](http://steamcommunity.com/sharedfiles/filedetails/?id=915877239) (as attachment: [new_items_2_15b.zip](https://github.com/larsiusprime/tdrpg-bugs/files/1595038/new_items_2_15b.zip)).
When I load any saved game, DQ crashes with "can't get ItemList" error (see screenshot).

![image](https://user-images.githubusercontent.com/20334588/34460104-0b1eae58-ee16-11e7-9743-87fd0bab9cfa.png)

**Comment by ManDude** [comment]
Oh my bad, I didn't notice there actually was a level editor :P well then, have fun!

**Comment by larsiusprime** [comment]
This will be fixed in the next patch, 2.2.1, by the way.

**Comment by larsiusprime** [comment]
Should be fixed in 2.2.2. Reopen if not.

**Comment by Hy60koshk** [comment]
BTW, how do I reopen?

**Comment by larsiusprime** [comment]
Should be a button below your comment that says "Reopen." If not, you don't have the right permissions. In that case, I just sent you an invite to be a collaborator on this repo.

**Comment by Hy60koshk** [comment]
Eh... I guess, it's the second case.

![image](https://user-images.githubusercontent.com/20334588/35161970-dec39494-fd52-11e7-8065-4dc83d537a7b.png)

**Comment by larsiusprime** [comment]
Yeah, check your email for an invite then, it should appear once you accept it.

**Comment by Hy60koshk** [comment]
Have it now, thank you!
