### ISSUE TITLE
Weird text issue (Journal)

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1345]
I'm not quite sure what's going on here in the Journal (and ONLY the Journal, it seems), but most text looks slightly cut off at the bottom:

![image](https://user-images.githubusercontent.com/7569514/34622644-cc274816-f245-11e7-87e6-3c5b8cefc9a4.png)

Easy to notice, for example, in the first sentence there.
You can see that some letters correctly rendered but most aren't.

800x600, 2.2.1 Jan 3rd

**Comment by ManDude** [comment]
I tested on fullscreen 1366x768 and this rendering issue seems to be reduced but not nullified.

**Comment by larsiusprime** [comment]
It's a side effect of a new bitmap font rendering system. I'm not sure much can be done about this.

**Comment by ManDude** [comment]
Oh, I guess that might also explain why other text looks a bit weirder too:
![image](https://user-images.githubusercontent.com/7569514/34631128-e5d2d5f2-f266-11e7-8aa2-a46089b776bf.png)

Oh well, nothing too extreme anyways. Can just play at a higher resolution.
