### ISSUE TITLE
Scrap count in Overworld goes OoB on lower res

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1346]
![image](https://user-images.githubusercontent.com/7569514/34622911-fd57610e-f246-11e7-9079-f98110b119c8.png)

800x600. The old version avoided this by displaying this count in a smaller font size once it got past a certain amount.

Higher resolutions like 1366x768 don't have this issue since there is more space.

**Comment by larsiusprime** [comment]
Fixed in 2.2.2
