### ISSUE TITLE
Overworld map "hidden" area covers misplaced on higher resolutions

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1350]
The higher you set your resolution, the more apparent things like these become:
![image](https://user-images.githubusercontent.com/7569514/34645417-ee8e5ed0-f344-11e7-842f-8f36118950f7.png)
![image](https://user-images.githubusercontent.com/7569514/34645416-e601e5fc-f344-11e7-9a57-ea384773c39f.png)
The covers for the underground areas of the overworld map become more and more misplaced.

``2.2.1_1/3/2018 - full - steam - gl release``,
``2018 - full - steam - gl release, build 1) (Windows).zip``

**Comment by ManDude** [comment]
Okay somehow I believe that in-game story progress is related to this.

Also, those screenshots were from a new NG+ savefile. I don't know if this happens on a brand new file.

**Comment by larsiusprime** [comment]
I've observed it too, been meaning to fix for a while.

**Comment by larsiusprime** [comment]
Hmmm, I can't reproduce this now, but I know I've seen it before. Guess we just leave this open until we track down exactly what causes this.

**Comment by ManDude** [comment]
After playing on that same savefile for a while I stopped noticing it, and it doesn't even seem to show up bugged at all now. Maybe it's somehow related to game progress? A savefile bank would be useful for this.

**Comment by larsiusprime** [comment]
Yeah, maybe I'll dump all my various saves I've collected over the years on this very repo!
