### ISSUE TITLE
Weird Cheevos

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#1352]
From here:
https://github.com/larsiusprime/tdrpg-bugs/issues/1340

> Also, Lars, it might be of interest that on these hotfixes (the ones in 2018), I noticed that after installing that latest version on steam and starting a battle, and boosting a defender to level 5 for the first time, there is an achievement notification on my left bottom corner about it. This is probably a bug since I have definitely boosted many defenders to level 5 in this save file in 2017. Another achievement notification happened when I went to click the Tips and Tricks button (the Hit the Books achievement). Maybe this happens everytime the game is patched to a new version, the game 'forgets' the achievements? But when I go to the achievements tab under options, the achievements are all unlocked already.

**Comment by ManDude** [comment]
Can confirm. I believe this is happening with the accessibility/tips/controls achievements aswell.

**Comment by larsiusprime** [comment]
Fixed in 2.2.2 1/8 build.
