### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1353]
(I'm writing "possible" because I am not running the absolute latest version of the game, but this should still be worth reporting.)

The game will eventually crash after long periods of playtime. I played through the entire game on a blank savefile from start to finish UNTIL the scene where Niru finds the treasure cave. This is when I noticed that something was going on:
- The background for the "Cave" shop (the one right before Eztli's Right Hand) was non-existant. It was just a black screen, though the cutscene played just fine. Probably not loaded? It came back once I re-entered the shop, though.
- The cutscene after you leave said cave behaved weirdly until it actually crashed the game completely. Wrenna's cutscene sprite also became a black box, and once I clicked "next" on that scene everything went black and the game crashed.

Also, I feel like the game's performance is dropping gradually over time due to this. I don't have a beast PC which means that even the slightest drop in performance is easily noticeable (in fact, I don't believe I can play the game at 60fps at all during battles... but the speed options sure do hide that very well, I'll give them that). When I start the game up, battles at 16x are actually pretty smooth, but after a while I noticed that I wasn't getting quite the same smoothness during battles. It became especially atrocious when I tried to do the Super Sheep battle yesterday where near the end it was really *really* slow and choppy.

I will try to get as much info on this as I can, but it's quite hard due to how long it takes to have a major effect.

**Comment by ManDude** [comment]
I noticed that RAM usage kept going up as I kept selecting between "Advanced" and "Extreme" difficulty on the battle preview menu.

**Comment by larsiusprime** [comment]
Memory leak confirmed.

**Comment by larsiusprime** [comment]
Are there any other areas where you can get the memory use to creep up like that without being freed by doing something fairly simple and testable? (Like enter screen X, exit, do that 10 times, memory never goes back down).

**Comment by larsiusprime** [comment]
The Battle Preview memory leak is fixed in 2.2.2 1/11 build. Let me know if you find any other ones!

**Comment by ManDude** [comment]
Great! Thanks.

I messed around and found some spots where the memory did go up (i.e. repeatedly pressing the defender hotkey to select an un-summened defender, going back in forth in cutscenes, loading and quitting the game, etc.) but it went down after a bit, so I'm not sure if that counts or not.
