### ISSUE TITLE
"Steam Workshop" option in Modifications menu should be greyed out if Steam is not running/detected

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1357]
If Steam isn't running and you select this option:
![image](https://user-images.githubusercontent.com/7569514/34696170-ad28b4cc-f4c5-11e7-9fd4-3cd12ad73325.png)
(BONUS: Smeared filled circlebox bug?)

A couple of consoles will show up including one which just stays there and doesn't close automatically:
![image](https://user-images.githubusercontent.com/7569514/34696190-be016780-f4c5-11e7-9647-edacad2e49f6.png)

(It can still be closed manually and nothing happens, but it's still weird and this option shouldn't be enabled in the first place.)

**Comment by larsiusprime** [comment]
Test: when you're in this "steam is not running" mode, does the title say "Universal" (IE steam not detected), or "Steam" ?

**Comment by ManDude** [comment]
It says Universal for me, yes.

**Comment by ManDude** [comment]
![image](https://user-images.githubusercontent.com/7569514/34792300-7e3205bc-f63f-11e7-95ae-35ce8337e58c.png)
"Workshop" button should probably be greyed out here too.

**Comment by larsiusprime** [comment]
Fixed in next build.
