### ISSUE TITLE
Pointer hand is very obnoxious

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1358]
The pointer hand that tells you your currently-selected option is currently very obnoxious and a bit buggy when it comes to button positions (i.e. it appears in the top-left corner of the overworld for a split second when it opens). The way it's working now is that it's enabled by default until the game detects mouse movement, though I think it should either be always on, or only enabled when non-mouse devices are detected/used.

**Comment by larsiusprime** [comment]
The pointer hand is annoying for sure and I will fix it, but it's touchy enough I don't want to rush it. Next patch.
