### ISSUE TITLE
Large text size makes multiple stuff go out of bounds

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1360]
Multiple pieces of cutscene dialogue go out of bounds now (the speech bubbles can only contain up to 3 lines of text but many have 4) and enemy stats don't fit inside their menus in lower resolution:
![image](https://user-images.githubusercontent.com/7569514/34697029-118d31ce-f4c9-11e7-95c2-059cf9de189a.png)
![image](https://user-images.githubusercontent.com/7569514/34697497-41e54670-f4cb-11e7-8965-fa5362944398.png)

**Comment by larsiusprime** [comment]
- [ ] Cutscene bug in 2.2.2 1/9 build.
- [ ] Enemy description text overflows.

Not gonna worry much about the edge case about azra's stat text flowing over.

**Comment by larsiusprime** [comment]
Also this:

![2018-01-09 10_17_21-defendersquesti](https://user-images.githubusercontent.com/739064/34730910-5812653a-f526-11e7-9d29-ab5ce3d4b97a.png)

- [ ] Fix it

**Comment by larsiusprime** [comment]
Fixed in 2.2.2 1/9 build.
