### ISSUE TITLE
Text missing in the German journal

### ISSUE THREAD

**Issue by LarsMadeMeDoIt** [larsiusprime/tdrpg-bugs#1365]
I reported this about a year ago as part of another issue, but I guess it slipped through the cracks. So let give it a proper entry:

The last paragraph is missing from the "Third Dream" entry in the journal. See pic.

![blut](https://user-images.githubusercontent.com/20359621/34945767-b5409992-fa04-11e7-918c-77ebb16b7c7f.jpg)

Disclaimer: I don't speak German and only stumbled upon this issue while investigating another bug. This report is based on Google Translate.

**Comment by larsiusprime** [comment]
Thanks, I speak enough German to confirm the last graf is missing. It's probably there in the translation text but a format error is blocking it, I'll bet. Let me see...

**Comment by LarsMadeMeDoIt** [comment]
Nope, it's not there. Not anymore, at least. Here's the old bug I mentioned: #1216 

 Apparently that paragraph was originally on the right page (see [here](https://github.com/larsiusprime/defendersquest-loc/commit/edf4b5da99db1d8a72e7acfb4de8fedecff226ef#diff-971b2974d36787fac970df15b6cff9f9) and search for "ENTRY_JOURNAL_DREAM3_RIGHT_0_00") but instead of being moved to the left page it was simply deleted.

**Comment by larsiusprime** [comment]
Fixed in the next build. Double checked this time, thanks for being thorough!
