### ISSUE TITLE
Book Auto-equip can override Book of Secrets

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1367]
If the Book of Secrets is equipped to the first book slot, and the player goes to the ??? shop and buy a book and then auto-equip it, going back to the overworld will show Azra standing in the middle of the desert, since the book of secrets is no longer equipped.
![image](https://user-images.githubusercontent.com/7569514/35165703-3e4e00b8-fd47-11e7-889f-3009d621cbdd.png)

Interestingly, I can still click the location where the ??? pearl is supposed to be, and Azra will go there as if I had the book equipped, it's just the pearl is invisible (tfw issue #1 has been realized).

**Comment by codingthat** [comment]
Awesome that it resembles a fake bug.  :)
