### ISSUE TITLE
Crash on selecting battle after monastery

### ISSUE THREAD

**Issue by Zekzek** [larsiusprime/tdrpg-bugs#1377]
Operating System: Windows 10
Browser/Download: Download (Steam)
Demo/Full?: Demo
Version: Steam DQ1 2.1.7

Load the attached save game. Select the furthest level available (just after 'The Monastery') and click 'Battle'. An error popup appears with 'Null Object Reference' and the game crashes. This is 100% repeatable for me.

[save.zip](https://github.com/larsiusprime/tdrpg-bugs/files/2024873/save.zip)

**Comment by blackjack7960** [comment]
Also getting the same error

Operating System: Windows 10
Browser/Download: Download (Steam)
Demo/Full?: Demo
Version: Steam DQ1 2.1.7

Selecting the battle button after monastery crashes game prior to the difficulty selection.

This has happened 100% of the time and i have verified local steam files are not corrupted

[save.zip](https://github.com/larsiusprime/tdrpg-bugs/files/2300095/save.zip)

**Comment by andreaswimmer** [comment]
Same problem, crashing 100% of the time when I try to start the battle after the monastery. 

Operating System: Windows 10
Browser/Download: Download (Steam)
Demo/Full?: Demo
Version: Steam DQ1 2.1.7

[broken.zip](https://github.com/larsiusprime/tdrpg-bugs/files/3643272/broken.zip)

**Comment by codingthat** [comment]
This doesn't happen in the full version of the game using the above saves (on Linux, anyway)—probably related to "end of demo" code, I'm guessing, based on the location?

I can't get a stack trace because the "Download Demo" button doesn't seem to do anything in Steam, because I have the full version installed.

**Comment by andreaswimmer** [comment]
Here's the _error.txt log, not sure why it thinks I'm running Windows 10 Pre-release.
```
SystemData
{
  OS : Windows 10 (Pre-release)
  RAM: 16594620 KB (15.83 GB)
  CPU: Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
  GPU: Radeon RX 580 SeriesIntel(R) HD Graphics 4600, driver v. 26.20.13001.5000520.19.15.5058
}
--------------------------------------
game id:	DQ1
filename:	DefendersQuest
package:	com.leveluplabs.defq1
version:	2.1.7
tdrpg v:	2.1.6
session ID:	DQ1_2019-09-27_17'01'57
started:	2019-09-27 17:01:57
--------------------------------------
crashed:	2019-09-27 17:02:36
duration:	00:00:39
error:		UNCAUGHT ERROR : Null Object Reference
stack:
com.leveluplabs.tdrpg.Popup_MapPreview.calcWaveData (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 234)
com.leveluplabs.tdrpg.Popup_MapPreview.setupStars (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 395)
com.leveluplabs.tdrpg.Popup_MapPreview.setup (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 348)
com.leveluplabs.tdrpg.Popup_MapPreview.createAfter (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 115)
com.leveluplabs.tdrpg.TDRPGStateModule.createAfter (com/leveluplabs/tdrpg/TDRPGStateModule.hx line 325)
com.leveluplabs.tdrpg.TDRPGPopUp.createTDRPGPopUp (com/leveluplabs/tdrpg/TDRPGPopUp.hx line 91)
com.leveluplabs.tdrpg.Popup_MapPreview.create (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 94)
flixel.FlxState.resetSubState (flixel/FlxState.hx line 117)
com.leveluplabs.tdrpg.TDRPGState.resetSubState (com/leveluplabs/tdrpg/TDRPGState.hx line 370)
com.leveluplabs.tdrpg.State_Overworld.resetSubState (com/leveluplabs/tdrpg/State_Overworld.hx line 1687)
flixel.FlxState.tryUpdate (flixel/FlxState.hx line 174)
flixel.FlxGame.update (flixel/FlxGame.hx line 750)
com.leveluplabs.tdrpg.Main.update (com/leveluplabs/tdrpg/Main.hx line 2268)
flixel.FlxGame.step (flixel/FlxGame.hx line 674)
flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 541)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 237)
openfl.display.DisplayObject.__broadcast (openfl/display/DisplayObject.hx line 255)
openfl.display.DisplayObjectContainer.__broadcast (openfl/display/DisplayObjectContainer.hx line 358)
openfl.display.Stage.render (openfl/display/Stage.hx line 761)
openfl.display.Stage.addRenderer (openfl/display/Stage.hx line 200)
```

**Comment by angelrubio** [comment]
SystemData
{
  OS : Windows 10 (Pre-release)
  RAM: 24836468 KB (23.69 GB)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  GPU: NVIDIA GeForce GTX 1080 Ti, driver v. 26.21.14.4587
}
......................................................................
game id:	DQ1
filename:	DefendersQuest
package:	com.leveluplabs.defq1
version:	2.1.7
tdrpg v:	2.1.6
session ID:	DQ1_2020-05-30_10'57'08
started:	2020-05-30 10:57:08
......................................................................
crashed:	2020-05-30 10:57:32
duration:	00:00:23
error:		UNCAUGHT ERROR : Null Object Reference
stack:
com.leveluplabs.tdrpg.Popup_MapPreview.calcWaveData (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 234)
com.leveluplabs.tdrpg.Popup_MapPreview.setupStars (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 395)
com.leveluplabs.tdrpg.Popup_MapPreview.setup (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 348)
com.leveluplabs.tdrpg.Popup_MapPreview.createAfter (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 115)
com.leveluplabs.tdrpg.TDRPGStateModule.createAfter (com/leveluplabs/tdrpg/TDRPGStateModule.hx line 325)
com.leveluplabs.tdrpg.TDRPGPopUp.createTDRPGPopUp (com/leveluplabs/tdrpg/TDRPGPopUp.hx line 91)
com.leveluplabs.tdrpg.Popup_MapPreview.create (com/leveluplabs/tdrpg/Popup_MapPreview.hx line 94)
flixel.FlxState.resetSubState (flixel/FlxState.hx line 117)
com.leveluplabs.tdrpg.TDRPGState.resetSubState (com/leveluplabs/tdrpg/TDRPGState.hx line 370)
com.leveluplabs.tdrpg.State_Overworld.resetSubState (com/leveluplabs/tdrpg/State_Overworld.hx line 1687)
flixel.FlxState.tryUpdate (flixel/FlxState.hx line 174)
flixel.FlxGame.update (flixel/FlxGame.hx line 750)
com.leveluplabs.tdrpg.Main.update (com/leveluplabs/tdrpg/Main.hx line 2268)
flixel.FlxGame.step (flixel/FlxGame.hx line 674)
flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 541)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 237)
openfl.display.DisplayObject.__broadcast (openfl/display/DisplayObject.hx line 255)
openfl.display.DisplayObjectContainer.__broadcast (openfl/display/DisplayObjectContainer.hx line 358)
openfl.display.Stage.render (openfl/display/Stage.hx line 761)
openfl.display.Stage.addRenderer (openfl/display/Stage.hx line 200)
