### ISSUE TITLE
[meta/about this repo] MarkDown Formatting of Headings in README.md isn't working

### ISSUE THREAD

**Issue by DeeDeeG** [larsiusprime/tdrpg-bugs#1383]
Short summary: Heading formatting in the README.md isn't working, since GitHub's MarkDown interpreter requires spaces after the hash (`#`) marks.

Long version:

The README has some lines like this:

```markdown
#Instructions (for testers)

###1. Log in / Sign up for a Github account You'll need a Github account to report issues and bugs.
```

Which looks like heading/subheading formatting to me, but GitHub is not interpreting as such. It just displays all the hashes as plain text, like
- `#Instructions ` . . .
or 
- `###1. Log in` . . .

If spaces are added:

```markdown
# Instructions (for testers)

### 1. Log in / Sign up for a Github account You'll need a Github account to report issues and bugs.
```

It displays with heading formatting like this:

> # Instructions (for testers)
>
> ### 1. Log in / Sign up for a Github account You'll need a Github account to report issues and bugs.

**Comment by DeeDeeG** [comment]
Example how to correct this: https://github.com/DeeDeeG/tdrpg-bugs/tree/README-markdown-formatting
(this commit in particular: https://github.com/DeeDeeG/tdrpg-bugs/commit/f6496e4f7a578349c2a602f1b69007ed6f21aa25)

(I can submit my fix commit as a Pull Request if you'd like, but I don't mind either way.)

**Comment by ManDude** [comment]
Thanks for telling!
