### ISSUE TITLE
Buff does nothing.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1438]
It will continuously be cast without applying anything, or an icon.

**Comment by ManDude** [comment]
Also will be cast when anyone in range is hurt as it is a heal-type spell, even though it doesn't actually heal.

**Comment by dqhol** [comment]
I thought it only cast when an enemy was within range of a unit within range of attacking, so it didn't just endlessly cast it on idle units. You might be right, though.

**Comment by larsiusprime** [comment]
Fixed in next build.
