### ISSUE TITLE
x99% scrap

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1441]
![image](https://user-images.githubusercontent.com/19625520/47934742-93ca8900-deae-11e8-8ea4-44c4c8593b1b.png)

Not sure what might've triggered then. I moved scrap up and down and then back to 100% at the start, selected and unselected hero mode, just to see if the buttons worked.

**Comment by ManDude** [comment]
![image](https://user-images.githubusercontent.com/7569514/47943078-54bb2880-deec-11e8-8077-b45eca776eda.png)

**Comment by larsiusprime** [comment]
I reproduced this once but then could never get it to happen again. I'll throw in a guard that rounds the multiplier, just in case.

What's the bug displayed in the second screen shot?
