### ISSUE TITLE
Bosses should have DISTRACT immunity

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1447]

**Comment by larsiusprime** [comment]
I feel two ways about this; obviously the boss shouldn't be able to be straight up cheesed with the distract effect (currently functioning as a sort of super-stun).

That said, I wonder if there's another way. I generally hate it in games where the boss is immune to everything fun. But I don't want to nerf distract just to make it effective on a boss without being overpowered. Hmmm.

Well, I'll come up with something eventually. Might just go for the immunity and call it a day.

**Comment by larsiusprime** [comment]
The first thing I'm going to try here is a "learned immunity" system modeled after Dead Cells. Bosses that have this trait will receive the first dose of a particular flavor at full effect, then be invulnerable to it for a long cooldown (potentially forever). The learned immunity will kick in at some threshold of amount/time. So say "I can be frozen for at max 5 seconds before I am unfreezable for the next 2 minutes" or, "I will tolerate 100 points of poison damage before I am unpoisonable for the rest of the battle" or whatever.

We'll see how that affects things.

**Comment by larsiusprime** [comment]
Fixed. There's not any good visual feedback now, but here's what I've got.

- You can now add an "adapt" tag to enemies like this:
`<strong value="distract" effect="adapt" amount="10"/>`

Which will cause the enemy to be completely immune to that effect after being exposed to a certain amount of it. The rules right now about how "amount" is interpreted:

- DOT effects (poison / burn): % of max health
- Knockback: # of tiles knocked back
- Everything else: seconds the effect is active, regardless of strength

After the exposure reaches maximum, the enemy is completely immune to that status effect thereafter, and if they currently are inflicted with it, it is cleared away.

I applied this to the Black Hat Ship boss, so right now you get 10 seconds of distract before it becomes immune. We'll see if this works for people or not.
