### ISSUE TITLE
Some labels on keyboard shotcuts on Controls page missbehave

### ISSUE THREAD

**Issue by adasko1984** [larsiusprime/tdrpg-bugs#1450]
> Windows 10, 64 bit
> Downloaded (steam)
> Version: 0.0.0.

Steps: 
1. Go to Settings -> Controls
2. Take a look on "Spells" row (forth position).
3. Select some other preset and then go back to "Qwerty" one.
4. Manually update value of the fourth position on "Spells" row.

Actual:
Step2: Letters are: A, S, D, f10, F, G
Step3: Fourth position is kept from the other preset, ie if "Lefty" was selected after returning to "Qwerty" there will be "4".
Step4: After manually editing value some other shortcuts are getting blank.

Expected:
Step2: I would expect to see letters in order, ie: A, S, D, F, G, H
Step3: After returning to reset all shortcuts are updated.
Step4: If chosen character was used as some other shortcut, that old shortcut is removed (and only that, not some other shortcuts as well)

**Comment by adasko1984** [comment]
Screens for reference:
![step1](https://user-images.githubusercontent.com/25862457/48029505-9ea34900-e14e-11e8-9afc-3f07010057ee.jpg)
![step2](https://user-images.githubusercontent.com/25862457/48029508-9fd47600-e14e-11e8-9501-2f9ba384f909.jpg)
![step3](https://user-images.githubusercontent.com/25862457/48029511-a19e3980-e14e-11e8-931f-00bf9178252e.jpg)

**Comment by larsiusprime** [comment]
Fixed in next build.
