### ISSUE TITLE
Fancy cursor appears at first item on Controls screen

### ISSUE THREAD

**Issue by adasko1984** [larsiusprime/tdrpg-bugs#1451]
> Windows 10, 64bit
> Downloaded (steam)
> Version: 0.0.0.

Steps:
1. Go to Settings -> Controls
2. Select and click on any of "Presets".

Actual:
If you use standard cursor, the fancy cursor appears pointing at the top leftmost option. It disappears after you move your mouse.
But if you have "Fancy cursor" selected on Graphic tab, then the fancy cursor appears pointing at the top leftmost option and disappears from your current selection. It returns back to the correct place when you move your mouse.
Screen: 
![screen](https://user-images.githubusercontent.com/25862457/48029972-ebd3ea80-e14f-11e8-87a7-7d9743ef3a2f.jpg)

Expected:
There is no appearing from nowhere "fancy cursor" and cursor stays on it place.

**Comment by larsiusprime** [comment]
Believe I have this fixed in the next build. Thanks!
