### ISSUE TITLE
Tutorial for level up appears each time zerk level up

### ISSUE THREAD

**Issue by adasko1984** [larsiusprime/tdrpg-bugs#1458]
> Windows 10, 64 bit
> Downloaded (steam), full

In settings I have set: show tutorials on "new battles only".

Steps:
1. Start the game play till you obtain "Ranged unit".
2. Keep re-playing on the third map till your "Zerk" get another level (you can set exp to 300% to speed this up).

Actual:
Tutorial for leveling up is shown each time "Zerk" gets level on that level.

Expected:
When Tutorial settings are set as "New battles only".
Tutorial for level up appears only once, when the "zerk" character levels up for the first time.

**Comment by larsiusprime** [comment]
Fixed.
