### ISSUE TITLE
[DQ1]Game crashes when you try to recrut too many Dragons.

### ISSUE THREAD

**Issue by adasko1984** [larsiusprime/tdrpg-bugs#1462]
There is some kind of error that do not block recruiting Dragons when you have 6 of them.
When user tries to recruit 7th Dragon game crashes. 

screen: 
![dq1_crash](https://user-images.githubusercontent.com/25862457/48356146-e584c780-e695-11e8-9d21-ffcc53cb80d6.jpg)

logs:
[DQ1_2018-11-12_15'00'19_CRASH.zip](https://github.com/larsiusprime/tdrpg-bugs/files/2572407/DQ1_2018-11-12_15.00.19_CRASH.zip)

**Comment by ManDude** [comment]
Weird. Shouldn't even be *allowed* to hire a 7th dragon.
