### ISSUE TITLE
[DQ2] Lightning book event's "equip" option shows a book already equipped in slot 1

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1464]
After the first battle, or going into the second, I'm not sure, I got a popup saying I got the lightning book.  The options were Equip or Continue.  Hitting Equip, I was shown three slots where I could equip it, but the first had a red book with a yellow jack-o-lantern-esque face on it.  So I equipped the lightning book in the middle slot.

However, after the battle, on the party screen, that book is not there (nor was it on the party screen before the above happened.)  The lightning book is sitting in the middle slot still, with the first slot empty.  What was that book?  Where did it go?

**Comment by larsiusprime** [comment]
Fixed it.

The "other" book is actually the lightning book with the wrong graphic applied.

**Comment by codingthat** [comment]
Ah, OK...so it pre-chooses slot #1 for you when you pick "Equip"?

**Comment by larsiusprime** [comment]
Yeah, it's slightly confusing how it's presented right now.

Basically, the new system is that "spells" are now equippable. However, for the sake of the first tutorial, I really don't want the player to forget to equip the first spell as we're about to immediately teach them how to use it. So I force it to auto-equip it silently. If you don't press the button, it's still equipped. However, I still feel like it's important to show that equip button on the "you just got a new spell item" screen. Which can be a bit confusing.

Perhaps what I'll do is put in a tutorial right then to teach you how to equip it and guarantee you do for the sake of the next battle.

**Comment by codingthat** [comment]
Ah, now I see.  Yeah, that cover-both-bases approach sounds good :)  (But I'm sure if the graphic had been the same it would've been a chunk less confusing.)
