### ISSUE TITLE
[DQ2] Face appears with Taunt / $STATUS_DESC_TAUNT without explanation

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1465]
![image](https://user-images.githubusercontent.com/26723818/48918572-b50b0d80-ee8d-11e8-9813-dc911a920be7.png)

This is on the first level with the bouncer.

**Comment by larsiusprime** [comment]
Fixed in next build. The description now indicates that it attracts enemy attacks, and gives a X% bonus to defense.

**Comment by codingthat** [comment]
OK cool, but...where does it come from?  :)

**Comment by larsiusprime** [comment]
The Taunt skill itself you mean? It's one of the Bouncer's starting abilities, it's in the skill tree. Probably not very well tutorialized. Every time he uses his attack, it causes his taunt ability to activate.

**Comment by codingthat** [comment]
Yep...ah!  That makes sense.  Yeah, I think a tutorial would be good to include at some point :)  (Should I open another ticket for that?)
