### ISSUE TITLE
[DQ2] Variable name in text on boss fight mouseover

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1467]
![image](https://user-images.githubusercontent.com/26723818/48918943-1df38500-ee90-11e8-9dbb-981d57c4310a.png)

Or is this the sort of thing not to bother reporting?  (I wasn't sure, because I remember one of these in DQ1 a while back...)

**Comment by codingthat** [comment]
Also in the sidebar once spawned:  
![image](https://user-images.githubusercontent.com/26723818/48919020-9fe3ae00-ee90-11e8-9da7-18672b3d2933.png)

**Comment by larsiusprime** [comment]
Fixed in next build.
