### ISSUE TITLE
Steam Cloud Synchronization Bug

### ISSUE THREAD

**Issue by mu03019** [larsiusprime/tdrpg-bugs#1476]
windows 10/ steam download(play with deluxe Ver)/ FullVersion/ Ver2.2.6
When I pressed the start button on the main screen, a pop-up window called 'fix is missing element filter' was opened. And the game ended when I pressed the confirmation button on the pop-up window. However, this did not happen if Steam Cloud Sync was left off.

**Comment by larsiusprime** [comment]
Sounds like an XML parsing bug. Can you post your save files somewhere and link them?
I've never heard a report of this before, so I suspect it might be unique to your situation and the fact that leaving cloud sync off seems to prevent it.

Does the bug happen again if you put cloud sync back on?

In any case:

The default save location is C:\Users\YOURUSERNAME\AppData\Roaming\LevelUpLabs\DefendersQuest

I'd like to take a look at all of the .dfq and .xml files in that directory.
