### ISSUE TITLE
Some enemies give 0 juice

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1575]
Not sure if it's actually something between 0 and 1 (intentionally?) and it's just rounded down, but from a player perspective, some of these things don't give juice when the sparkles hit the meter:

![Peek 2019-08-12 19-22](https://user-images.githubusercontent.com/26723818/62884320-87753580-bd36-11e9-8e9c-60d261065278.gif)

**Comment by codingthat** [comment]
I think I figured it out: HARVEST (at least on the Zerk, if not also on the White Splash) seems to give *only* 20%, not *an additional* 20%.  Off-by-one error?  Sort of?  I.e. "(1+multiplier) * juice" instead of "multiplier * juice"?

I say this because taking away the HARVEST bonus from my Zerk character entirely seems to fix the problem.

**Comment by larsiusprime** [comment]
Ooh good catch. I'll be on the watch for this one as I test all the status effects.
