### ISSUE TITLE
Clicking "Export" results in two Save dialog boxes

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1587]
Actually, the very first time I did it, the game appeared to crash (window disappeared entirely, never came back.)  I hadn't launched it from the command-line though so I had no stack trace.  I tried to reproduce it launching that way, and got this bug instead.  Two identical Save dialogs, both seem to work normally, but still.

* * *

DQII, Windows version (Steam BuildID: 3645454) running on Proton 4.11-2 on Linux Mint 19 (64-bit) in windowed mode, 1704x960 on a 1920x1080 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment]
Apparently DQ2-specific.  Not sure if it has something to do with Proton.  DQ1 native shows a native-looking (Linux) dialog box called "zenity" and just one.  DQ2 under Proton shows two Windows-ish-looking dialog boxes both called "Save As".

**Comment by larsiusprime** [comment]
Don't remember when but I fixed this a long while back.
