### ISSUE TITLE
Loading a saved game causes the stars to change.

### ISSUE THREAD

**Issue by Thaliak** [larsiusprime/tdrpg-bugs#16]
Operating System: Windows 7 Professional 32-bit
Browser/Download: Download
Demo/Full?: Full Version
Version #: haxe_dq1_build_04_23_2014
Optional Info: I'm using a desktop and running the game at a resolution of 1024 by 768.

If I "play" a mission on a difficulty above casual, then quit to the main menu and restore my game, missions I completed on Normal, Hard or Extreme appear as if they were  completed on a lower difficulty.

To replicate this bug:
1. Start a new game in any slot.
2. Do the mandatory battles until you get to "The Coliseum." Complete it on "Advanced."
3. Quit to the main menu.
4. Load your game. The "Coliseum" battle should only have one star, not two.

**Comment by larsiusprime** [comment]
Looking into this... turns out that completing "the coliseum" on hard or advanced awards that progress to the first tutorial level for some reason. Looking into it.

**Comment by larsiusprime** [comment]
Fixed in DQ version 0.1.5

**Comment by larsiusprime** [comment]
...spoke too soon! This reoccurs in strange ways.

**Comment by larsiusprime** [comment]
Think I got it. Fixed in DQ version 0.1.6
