### ISSUE TITLE
DQ2: "Null Object Reference" when character "Long Shot" uses "Bomb Shot"

### ISSUE THREAD

**Issue by Nathan-P-B** [larsiusprime/tdrpg-bugs#1612]
game: Defender's Quest 2
operating system: Windows 10 (1809)
source: Steam
version: "Universal DQ2 0.0.3" (released 2019 October 7)

steps to reproduce: 
1. place Long Shot (archer)
2. boost twice (to Bomb Shot)
3. wait for Bomb Shot to fire
4. soon after shooting, crash

Due to when the character had enough XP to buy the ability, I first noticed this on the map where the bouncer was added to the party. Restarting the game and playing the same level resulted in the same crash. Restarting the game again and just placing Long Shot on the very first level crashed very soon after bomb shot was fired.

character long_shot from SAVE_SLOT_3.dfq :

    <class_entry value="long_shot">
        <character hero="true" handle="long_shot" name="Long Shot">
            <info xp="190" level="5"/>
            <skills points="1">
                <skill level="1" type="attack" id="basic shot"/>
                <skill level="1" type="attack" id="shrapnel shot"/>
                <skill level="1" type="attack" id="bomb shot"/>
                <skill level="2" type="passive" id="basic shot_strikethrough"/>
            </skills>
            <colors values=""/>
            <target chance="false" boss="true" effect="false" default="null" cheap="false"/>
        </character>
    </class_entry>

The attached _error.txt is from the third crash (which was on the first level).

[_error.txt](https://github.com/larsiusprime/tdrpg-bugs/files/3700694/_error.txt)

**Comment by codingthat** [comment]
Seeing that on my system too: Place only the Long Shot, boost twice, disable the first two attacks, and wait for an enemy to come in range.  Also crashes the same on the level before the town.

Interesting the only difference between our stack traces is the line number in one of the files.  I'm not sure how that could happen, even given that I'm running on Proton vs actual Windows.

![image](https://user-images.githubusercontent.com/26723818/66400354-9b10e580-e9e1-11e9-9dd8-35029e57299a.png)

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-6 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
Fixed in 0.0.4.
