### ISSUE TITLE
First town's "swords" screen says "no guns to craft" when out of stock

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1615]
![20191008152446_1](https://user-images.githubusercontent.com/26723818/66399448-e6c28f80-e9df-11e9-8904-2bf976b246ef.jpg)

(The "guns" tab does have guns.  When you buy them all, it also says "no guns to craft," which is correct in that case.)

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-6 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
Fixed in 0.0.4
