### ISSUE TITLE
Controls Options menu text displacement

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1618]
Happens only in 600p and 648p resolutions.
When the "Controls" menu in the Options menu is opened, all of the beacon text gets displaced downwards by 1 pixel almost immediately after it appears. Clicking any "Device" or "Presets" beacon will reset the displaced text back to where it is supposed to be displayed.

Bugged:
![image](https://user-images.githubusercontent.com/7569514/66431762-8a2d9780-ea14-11e9-9c48-e875a96fbc4b.png)

Fixed:
![image](https://user-images.githubusercontent.com/7569514/66431806-9c0f3a80-ea14-11e9-9c7a-8191b795a346.png)

Windows 10 64-bit, AMD Radeon Graphics card.

**Comment by larsiusprime** [comment]
What do you mean by "Beacon" here?

**Comment by ManDude** [comment]
my bad it's "radio" buttons not "beacon" buttons lol
