### ISSUE TITLE
A lot of text is cut off at the bottom

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1620]
Happens to all resolutions (up until 768p at least, higher ones might need testing) and to a ton of text all over the game.

![image](https://user-images.githubusercontent.com/7569514/66432770-bea25300-ea16-11e9-8197-f3e88a1f28e1.png)

**Comment by larsiusprime** [comment]
I found this was caused by non-whole-number values in bitmap text origin objects (typically 0.5 as an artifact of rounding).

It's surprisingly tricky to exterminate it in all places, but I think I've got the majority of the cases. If you see any more in 0.0.4, please let me know.
