### ISSUE TITLE
Janky rendering of range circle in 600p

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1621]
![image](https://user-images.githubusercontent.com/7569514/66433002-425c3f80-ea17-11e9-9650-d8df3b6a88e3.png)

**Comment by larsiusprime** [comment]
Bugged resolutions:
600p
720p

And face-palmingly:
1080p

**Comment by larsiusprime** [comment]
Cause: range preview not being on an integer location (ie, X or Y = 23.5 or whatever instead of 23.0)

**Comment by larsiusprime** [comment]
Fixed in 0.0.4.
