### ISSUE TITLE
Negative time effects in skill descriptions; ACID makes enemies invincible

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1625]
- [x] (Jumper) "PLACEHOLDER" adding Bleed to Flurry has negative time:
![image](https://user-images.githubusercontent.com/26723818/66623210-eba75f00-ebea-11e9-80ff-a7782d4adbf8.png)
- [x] (Jumper) Acid is particularly weird, not just about time:
![image](https://user-images.githubusercontent.com/26723818/66623170-c6b2ec00-ebea-11e9-8662-56f118b0c0c1.png)
- [x] (Collector) Inspire has negative damage:
![image](https://user-images.githubusercontent.com/26723818/67617962-f2d48c80-f7e8-11e9-8081-5526513cdd1b.png)

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-7 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment]
Acid, in battle, is also strange, in that the description says "deals -5 dmg and dissolves[double space but no number]armor..." and it makes the enemy's _HP_ bar go to -2147483648.

Actually, it also makes any enemy with enough HP to survive the initial double-hit effectively invincible, e.g. Tough Worm on Level 10 Normal.

**Comment by Nathan-P-B** [comment]
> it also makes any enemy with enough HP to survive the initial double-hit effectively invincible, e.g. Tough Worm on Level 10 Normal

I see this happening in Steam Windows DQ2 0.0.4 (released 2019 October 16).

![20191016222851_1](https://user-images.githubusercontent.com/2167433/66974371-da39d900-f068-11e9-96b0-bf450b20d9df.jpg)

**Comment by codingthat** [comment]
Yep, also there on native Linux on 0.0.4.

* * *

DQ2 Universal 0.0.4 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment]
The two Jumper ones are still present in 0.0.5, but the Collector one is fixed.
* * *

DQ2 Universal 0.0.5 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment]
ACID's gone and the other case is fixed, at least in 0.0.7.
