### ISSUE TITLE
Levels 8-10 Advanced difficulties have one wave of one enemy...

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1626]
Is this something I should bother reporting?  It's not one super-enemy, it's one super-easy enemy... safe to assume this is an unfinished part of a spreadsheet somewhere?

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-7 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
Yeah anything past the white hat sequence is completely unbalanced and not expected to be sensible. I'll address that in the next milestone.
