### ISSUE TITLE
Mouseover doesn't include effect text until you un-equip and re-equip

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1627]
![Peek 2019-10-11 06-27](https://user-images.githubusercontent.com/26723818/66624411-4abba280-ebf0-11e9-9288-8d3ddff47ca6.gif)

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-7 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
Fixed in 0.0.5!
