### ISSUE TITLE
Black-hat ship doesn't show weapons when selected, unlike white-hat ship

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1628]
![Peek 2019-10-11 06-43](https://user-images.githubusercontent.com/26723818/66624970-940cf180-ebf2-11e9-9988-828d38f27964.gif)
* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-7 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by Nathan-P-B** [comment]
I see the same thing in DQ2 0.0.4 Steam Windows.
