### ISSUE TITLE
[Proton-specific] Survey link causes game to freeze

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1629]
Menu stops responding, no longer repaints, never recovers.

![Peek 2019-10-11 06-49](https://user-images.githubusercontent.com/26723818/66625139-5f4d6a00-ebf3-11e9-88a8-c1fb20a7c1ea.gif)

Could be Wine/Proton-related given the console output.

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-7 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment]
I apparently _do_ have FreeType 2.8 already, but didn't have a 32-bit version installed, which is maybe what Wine needs here (on the other hand, I thought we're running a 64-bit Windows binary...via 64-bit Wine...)  Anyway, I ran `sudo apt install libfreetype6:i386` to install it.  Now trying again, the game still freezes when I click the survey link, exactly as above, except the console output on click is simply `003d:fixme:exec:SHELL_execute flags ignored: 0x00000100`.  I've started looking into `winetricks` but it fails on my system due to a missing `wineserver` and there some people recommend installing 32-bit Wine, but I'm not so sure about that given the context, and don't want to bork my working Proton setup.  Not sure what to try next.

**Comment by larsiusprime** [comment]
Super weird. 

The real long term solution here is just a native linux build, but it's good to know about these limitations.

**Comment by codingthat** [comment]
Interestingly, 0.0.4 behaves differently (still under Proton 4.11-7).  It also freezes, but then it crashes (OS-level "Wait" vs "Force quit" popup), and _after_ crashing, opens the URL correctly in the default browser.

**Comment by codingthat** [comment]
0.0.4 on native Linux works perfectly in this regard.
