### ISSUE TITLE
Null object reference

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1630]
I can't remember exactly what I was doing when this happened, but I noticed this crash report with a different stack trace than other times.  Hopefully with replay.fgr you can get back to the same state...if not, at least the stack trace itself might point to something that's clear once you look at it?

[DQ2_2019-10-11_06'30'33_CRASH.zip](https://github.com/larsiusprime/tdrpg-bugs/files/3715737/DQ2_2019-10-11_06.30.33_CRASH.zip)

I did have one strange crash during a battle, where I didn't get a null object reference popup, the game just stalled for a second or two (had been watching the battle at 16X) and then the window vanished.  Unfortunately I didn't have a console open and I had figured that the lack of a popup would mean no CrashDumper output...but maybe this was it after all?

* * *

DQ2 Universal 0.0.3, Windows version running on Proton 4.11-7 on Linux Mint 19 (64-bit) in windowed mode, 1152x648, on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
Hm, this looks like some kind of cascading failure.

The line that crashed was:
```haxe
PIX_X_PER_TIME = list_blocks[0].width/shortestWait;
```

The null object here would be the list_blocks[0] object, but for that to be empty something else would have had to fail earlier on, basically enemy waves failing to load properly. I'm hoping all these weird little bugs are proton-only. I'll but out a native linux build with the progress report and would appreciate circling back on these when we have that out.

**Comment by larsiusprime** [comment]
Linux build is out now for 0.0.4, can you reproduce this particular bug in that environment?

**Comment by codingthat** [comment]
I mean, it only happened once, and I wasn't able to repro it under Proton on 0.0.3.  But after a full playthrough on native with 0.0.4 it didn't happen either.  I'll definitely let you know if it happens again but initially I just wanted to give you a heads-up in case you found anything fishy.
