### ISSUE TITLE
"Null Object Reference" due to "White Splash" skill "Reflective juice" in com.leveluplabs.tdrpg.CreatureSprite.removeThorns (DQ2 0.0.4)

### ISSUE THREAD

**Issue by Nathan-P-B** [larsiusprime/tdrpg-bugs#1634]
![20191020005402_cropped](https://user-images.githubusercontent.com/2167433/67155105-8b917680-f2d6-11e9-8b02-0f49875201d9.jpg)
OS: Windows 10, version 1809
game version: DQ2 Steam 0.0.4

It is possible to consistently get a null object reference when White Splash's skill Reflective juice is used, but the timing varies. With White Splash, I had one point in all of the first three tiers of skills (1 point in 9 skills total), and the crash occurs. Removing a point from just reflective juice runs through a level without crashing. (The screenshot shows the non-crashing setup.)

Here is one `_error.txt`; all of them have the exact same stack trace.
```
--------------------------------------
game id:	DQ2
filename:	DefendersQuest2
package:	com.leveluplabs.defq2
version:	
tdrpg v:	0.0.0
session ID:	DQ2_2019-10-20_00'46'39
started:	2019-10-20 00:46:39
--------------------------------------
crashed:	2019-10-20 00:50:35
duration:	00:03:55
error:		Null Object Reference
stack:
com.leveluplabs.tdrpg.CreatureSprite.removeThorns (com/leveluplabs/tdrpg/CreatureSprite.hx line 3364)
com.leveluplabs.tdrpg.CreatureSprite.removeStatusEffect (com/leveluplabs/tdrpg/CreatureSprite.hx line 1301)
com.leveluplabs.tdrpg.CreatureSprite.updateStatus (com/leveluplabs/tdrpg/CreatureSprite.hx line 1120)
com.leveluplabs.tdrpg.CreatureSprite.updateFromModel (com/leveluplabs/tdrpg/CreatureSprite.hx line 2909)
com.leveluplabs.tdrpg.DefenderSprite.updateFromModel (com/leveluplabs/tdrpg/DefenderSprite.hx line 1569)
com.leveluplabs.tdrpg.BattleModel.updateDefenders (com/leveluplabs/tdrpg/BattleModel.hx line 4133)
com.leveluplabs.tdrpg.BattleModel.doUpdate (com/leveluplabs/tdrpg/BattleModel.hx line 2312)
com.leveluplabs.tdrpg.BattleModel.update (com/leveluplabs/tdrpg/BattleModel.hx line 1869)
com.leveluplabs.tdrpg.State_Battle.battleUpdate (com/leveluplabs/tdrpg/State_Battle.hx line 1992)
com.leveluplabs.tdrpg.State_Battle.update (com/leveluplabs/tdrpg/State_Battle.hx line 1716)
flixel.FlxState.tryUpdate (flixel/FlxState.hx line 172)
flixel.FlxGame.update (flixel/FlxGame.hx line 738)
com.leveluplabs.tdrpg.Main.update (com/leveluplabs/tdrpg/Main.hx line 2391)
flixel.FlxGame.step (flixel/FlxGame.hx line 668)
flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 538)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1234)
```

**Comment by codingthat** [comment]
[DQ2_2019-10-20_09'26'01_CRASH.zip](https://github.com/larsiusprime/tdrpg-bugs/files/3747547/DQ2_2019-10-20_09.26.01_CRASH.zip)

Seeing the same thing on Linux.  White Splash can have only one point used in Reflective Juice, nothing in any other skills, and you place just White Splash and a nearby defender, and there's a guaranteed crash.

* * *

DQ2 Universal 0.0.4 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.
