### ISSUE TITLE
Overworld not centered by default

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1645]
When you finish Level 10, Level 11 is off-screen when you come back to the map, because Level 10 is at the far right of the screen.

But also, if you restart the game entirely with your party on Level 10, the same view is used.  Centered in both cases would make much more sense, in my opinion.

* * *

DQ2 Universal 0.0.4 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by codingthat** [comment]
(After Level 11 is complete, the party is simply off-screen when the overworld loads.  I'd say this makes it an outright bug.)

**Comment by codingthat** [comment]
This would be nice to fix in the next milestone just to make testing easier. Gets in the way of trying out a bunch of different battles for the same bug.

**Comment by larsiusprime** [comment]
Fixed in 0.0.7
