### ISSUE TITLE
Collector's Refresh fires unexpectedly

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1655]
This _may_ be by design—because it's 100% reproducible—but I'm not sure.  If it _is_ intentional, it seems a bit inconsistent in a sense: Refresh fires on an automatic cycle, _but only once the Collector has engaged in battle_.  At first in the battle, once there are three healing units launched, they just stay there in a holding pattern, and Refresh doesn't need to fire after that, so it doesn't.  Once any battle happens, even if no healing is needed, one healing unit seems (or some healing units seem) to disappear every moment or so, necessitating a Refresh, which automatically happens:

![DQ2-collector-refresh-dips](https://user-images.githubusercontent.com/26723818/69496301-0733a400-0ed1-11ea-963f-1c7dedbe5980.gif)

Steps:

1. Launch Level 9 Normal
2. Drop a Collector
3. Boost to level 2
4. Go 16X and see the above play out
* * *

DQ2 Universal 0.0.5 native on Linux Mint 19 (64-bit) in full-screen mode on a 1366x768 single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
This should be fixed in 0.0.7 for sure, probably in 0.0.6, but not certain about that.
