### ISSUE TITLE
Haste cannon doesn't do what it says on the tin

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1741]
"Raises attack rate of ALL defenders," but it seems to only affect those within the smallish circle you use when the haste cannon is selected.  The fact that it has a circle (rather than working the way the similar one in DQ1 worked, where you could click anywhere on the map) suggests this is intentional and maybe just the description is outdated?

* * *

DQ2 Universal 0.0.16 native on Linux Mint 19.3 (64-bit) in full-screen mode at 1920x1080 on a single-monitor setup with an Intel HD Graphics 4400 chipset.

**Comment by larsiusprime** [comment]
You are correct! Fixing now.
