### ISSUE TITLE
Test sessions

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#1751]
John Kossa:
---------

Weird rendering artifact on linux

Expecting to make decision on level up of ship

Lightning arcing makes me wonder about targeting

Attacker enemies when first introduced never get to actually attack if you play optimally

Confused about level ups
- Ship goes from level 1 -> 2
- Zerk goes from level 2 -> 3

Use lock instead of ? on skills

First bonuses for the slash skill has 2 conditional bonuses which is confusing
Hesitant to pick a skill
believes skill points will be "gone"
Click +2 is not clear

Instinct says to save instead of buy because the special weapon is clearly better

There was a higher star rating on the previous level which makes me feel like I could go back and get that to earn more money to get the better weapon

Clicked equip button to go to party screen
Weird to have the party equip screen empty if you have 1 thing with show equipped unchecked by default

Tutorial keeps popping every time he goes back to the town
Not sure what the "2" emblem on the weapon buy screen means

Nit sure what the giant push back is about

To find out what status does, click speech bubble
Didn't think status bubble meant anything, thought it was just meaningless flavor

Didn't realize that bouncer had points (animate point bubble?)

Flip -- Haven't run across enemy with armor, but I wanna see the visual effect

White splash level -- Not sure why the ground is orange ---> oh, that's a nice snug fit.
Assume orange terrain is different but don't know how
Saw that white splash has no attack until boost level 2

Visual AOE attack is not super clear

Selecting a guy "turns him orange" didn't understand
Didn't realize he had lost his zerk unit

Lost White Splash x2 and Zerk x1
Put down bouncer but late in the battle
thought death juice was "purple smoke" = status ?

DIdn't realize he could withdraw and reallocate points
Feels more comfortable experimenting now that he can

Reflect feels more specialized but also more cool
Expecting a sell ability but there is none

Concerned about white splash's durability
Not always sure how branching paths works but knows that everything converges on final choke points

Strikethrough makes accelerating shots act weird

Boost button needs to have a better color

Long shot makes targeting an issue -- should the unit optimize for doing double damage, or not
Think's optimize effects is the closest but not clear that it would work

Not sure if he's seen the "flip" effect
Likes the word "permanently"
Saw the reflect effect applied didn't "feel it being useful"

Seeing the item rewards tempts towards advanced
Seeing special items feels more special than just money
Seeing an armor reward before shops award it feels tempting
Tempted to go back and play some advanced missions now
Seems to understand what the haste cannon reward would be for

Naturally feels inclined to finish a playersequence and then backtrack

strike through on long shot well outside of range is a pleasant surprise

Zerk seems kinda boring by comparison to all the other units
Zerk seems kinda less useful because long shot puts out tons of damage, Zerk doesn't have much range, zerk is kind of relegated to cleanup duty
Zerk is also the most lacking in interesting effects

Didn't really notice life drain on white splash

On auto-equip not sure what happens if you equip a guy

Bug-- map preview should mention the boss
Target boss is super confusing
appreciated the berserker a bit more with a specialization and using them in the boss fight

boss victory delay should be sliiiightly longer so you can actually collect the juice

Have never boosted past the # of attacks doesn't know if its worth it or not

Figured out the jumper pretty clearly
Noticed that money carries over -- wondering if equipment carried over, noticed item types don't match up

don't want the status button prompt for elminator to enforce a click

Wanted to see what jumper's range was on hovering the jump zone
Fire bomb is bugged

Kind of regret putting the eliminator at the end b/c he wanted to see the poison effect

-----------

ScytheDragon
------------

Second mission:
	Used laser cannon before they needed to and ran too fast losing the mission
	Replayed at 8x speed (even clicking the stuff)

Third mission:
	Tried advanced right away
	Put characters in ideal positions

Skill tree -- noticed you could revoke points but not necessarily obvious

generally plays at 8x, not necessarily noticiing damage indicators or special effects
"archers are still broken"

Purchased lower level equipment right away with no hesitation
"I could always go back and play the levels more"
"It's good to just get a basic thing and get it equipped"

Probably should put a "taunted" status on enemies that are effected by the taunt?

"Do you always play on 8x speed?"
"Normally I play on 16x"

Didn't allocate a point in the bouncer after the bouncer intro (notably the bouncer had not leveled up)

White hat level - perplexed by its level design, but put the white splash in the obvious place
Understood the dual range status of white splash
Lost the white hat level the first time
Second time still put the white splash in the optimal place
	Put the bouncer in front and the zerk behind (optimal)
	(Did much better)

At level 4 for long shot deallocated points for the 2-point strikethrough investment

"This is definiteyl a different game [from DQ1]"

Doesn't seem to understand that only the INNER range of the white splash is the assist range -- need more explicit ASSISTED / NOT ASSISTED markers

"I've always liked life drain because it means you can send guys off by themselves, you don't need to keep stuff closer together"

Thought you could buy more than one of an item

Jumper level, played 8x and had a few leaks
Thinks that the black hat characters are basically the same based on zerk having identical skills to jumper
Put eliminator at the start to take advantage of poison

Didn't expect a mission to auto-select advanced, maybe should be some indication

Collector picked the obvious location for them
When placing jumper was briefly confused why it wasn't summoning until realization that must place the jump zone too.

Missing outline graphic for wasps
Bug: false positive placement in ultimate level

-----------

MadPrism
-----------

Tried to use the Q shortcut in the tutorial and found it did not work
Hotkeys are not always working

Enemy spotlight -- "that's new, I like that"
Just the tutorial where spaces didn't work

"The laser cannon is a spell, basically"

Expecting skill trees from the first game notices there's no skill tree for the ship
Naturally picked normal difficulty

Didn't notice the "double damage" circle when it was off screen
Maybe put the text on top and bottom
It's a bit dark after a boost makes it hard to see
Can't leave the character selection right now

Can click both character placement and spell for maximum screwed up ness

Likes the bestiary popups because you get a general overview of what the enemy does in general, not just the specific level stats

The ranger is as strong as ever

Noticed naturally that strike-through requires two skill points, understood immediately
Make it more clear points can be re-specced at any time

A little sad he can't afford one of the better weapons just yet
"Oh lore! I love lore"
"If there was time, I'd read it right now"

Expecting green arrow up / red arrow down but doesn't see that here

"Basic weapon / basic armor" as empty is kind of confusing
Didn't expect that the items would disappear

"I don't understand what "taking aggro" means."

RE Deadly spotlight -- "Ooh, thanks for the information, I didn't realize that it had a ranged attack"

throwback animation is a little bit too much -- shouldn't scale that big
bubbles with the skillpoints are always nice -- keep them, keep them

White splash -- "assist, hm that's new"
Noticed the blue lines that shows him where the assist range is

Played on 4x speed with pause a lot

I try to unlock all skills as soon as possible

Lightning shot --> "I didn't notice until now that it also makes bolts"

Hovering over the skill itself 
Lightning shot + damage increase stat is a bug

Equip screen --> I expect to see who can equip and if it will better

Forgot to boost and took some hits

"I like to put the healer first because it's the one I orient all the other characters around"

"I don't like critical as much as debuffs, would rather have debuffs or raw damage than critical for some reason, just my personal preference"

Didn't realize you couldn't go over the maximum amount of starting juice
RE Collector -- "Oh I like that graphic, there's something satisfying about orbs that just go around someone"
"Freeze is really practical when combined with the cloud skill because it freezes lots of enemies"
"Eliminator can *really* take a hit"

Collector not attacking -- look into it

Ultimate comes in at boost level 2? I didn't expect that.

I am waiting fot the big boss to spawn before placing the ultimate because I don't want to be surprised by it

Spawny should one - shot the mcguffin

Octopus is lacking outlines

The Ultimate is actually ultimate
"How can I see if something is melee or ranged"

White hats -- I can see them when I go back to their part of the map, right?
White splash -- can't see ranged designation of skill until I am in battle

Feels a little bit weird about chain lightning having no range limitation

"Active abilities is less my taste than equipment with passive effects for my troops"

Penetrator detonation didn't happen because it's death was presented by other defenders on the map

Armor is absorbed by all of the enemies, makes him think that his attack is not working
Seems to understand that the penetrator is "not as special as a real tower"

I don't like niche attacks really (Critical but ONLY vs some kinds of enemy types)

---------
BobbyBurt
----------
Thinks boosting is temporary
"The White Hats" --> not sure what that means
Thinks scrap is money

Missing enemy name for low xp ants in laser cannon level
Lost the laser cannon level (1 hit kill)
Forgot to boost the Zerk
Realized it on loss that they needed to boost the Zerk

I'm guessing "White Hats" is the team
"A hero for the white hats" --> that's my team, okay

Sees two stars wonders what that means

Not starting levels by pausing
Doesn't know which way enemies are going to go on forking path

Wondering if 3 bars in bestiary popup means "3 hits"
"Oh I gotta slow down"
"Maybe I should slow the game down

Didn't place long shot ideally
"Assuming I'll get more (spell) abilities"
"Assume these are always available to me"
Uses the laser cannon a lot
Boosted both long shot & zerk in long shot level

Saw that could disable attacks "no reason to disable attacks"

Learned about targeting priority
Saw simple/advanced logic
Not worrying too much about targeting logic

Just realized their defenders have HP
"Not sure what makes it go down though"

Sees the recall button. "Oh that's what that does"
Attackers killed his zerk "Oh that's not good"

Didn't realize that defenders had their own health. Used to bloons.
Wasn't sure what the bar above the characters head meant.

Need to put point notification down where rest of points is
Understands the zerk's skill tree

"Got some ways to equip stuff, expect that to come later"
Thinks points are fungible between characters
Not sure if leaving the screen will lock points in or not

<Make "Equip" on town screen to "Go to Equip">
"Oh that was a town, I missed that at first"
Thought towns would appear before each battle

One-shot from the second level makes him confused about perfect status, doesn't believe it's caused by damage

Misread the bouncer level and put bouncer far away
Can't figure out how to recall (in fact did it before)
Figured it out finally
Wondering what the cost/refund basis for recalling a unit was, figured it out

Didn't boost the bouncer

The splash screen catches him off guard

Hasn't noticed the long shot's double damage
Hasn't figured out how to sue the bouncer

Noticed his guys have points but finds it a little strange
Associates points as a reward for winning

Expecting the gun to show up in the box below
"Actually liking it more now, less things to pay attention to"
Disclose that I'm feeling some information overload

"Wasn't paying attention to the bouncer at first"
"Oh shoot I gotta figure out"
"I still don't understand what the bouncer does"
"I have to see what the bouncer is doing"
"This is hard I've only got one of each person"
"I just don't have enough people"
Boosting Zerk but not Bouncer
Long Shot is being attacked and dying
"The Bouncer seems the same as the first guy (Zerk)"
"I'm so confused about that"
"Okay I gotta get juice faster"
"I don't feel like there's a lot of guys to work with here"
"I feel like I want more guys in the center getting at all of them"
"Maybe if I put all my guys there"
"I juice guys I think have to deal more than the other guys"
"They have to protect the ship more"
"What is that emoticon thing?" --> how would you find out --> I don't know? --> eventually figured it out

Bouncer bounces --> "whoa! That's really helpful"
Makes the Zerk seem a little weak in comparison now actually
Just noticed that the enemies were being pushed backwards because the screen was so busy
"Stranger survived unharmed" --> understands perfect status now
Realizes now that points belong to each character, not to a global pool

Just realized the star is not your "ranking" --> it's not showing all three stars --> 3 stars is a bit confusing

Placed white splash optimally
Zerk needs to go where he has the most coverage, but he doesn't have a lot of range

Toughy needs to say that it also has armor
Thinks the white splash is a healer (doesn't realize it's also a buffer)

Can't unclick the spell, can't figure out how to unclick
(Clicking the spell should unclick)
Clicking the defender when there is a spell that can't affect them

Not realizing to place bouncer on square with white splash and zerk
"I have a lot of juice so I should use that"
White splash gets killed by the deadlies

Artifact appears on wasp in end of white splash level when moused over with laser

Thought bonuses would only unlock when you unlocked the next main attack

Confusing that the white splash came with a pre-assigned point
Can't afford cannon --> "Gonna save up until I can!"

Should probably start with the battle paused before anything happens

On the square tripath is not boosting their guys fast enough
"Thinking more that laser is more of a last resort"
"Maybe I just have to supercharge him?"
"Gotta rememver to supercharge!"
Puts everyone together on the red top path, getting the idea but not a perfectly ideal placement

Toughies are missing an outline

Not boosting enough despite having plenty of juice
Now that a lot stuff is happening I'm geting juice a lot faster
Zerk is not doing a lot of damage against toughies
(Maybe nerf toughies by a level)

Middle lanes are causing a lot of confusion this early on in the battle

Feeling more frustrated now that I'm getting a lot more juice back in
Not feeling like it's something that just goes away and I don't get back

Did not expect Zerk to be doing the most damage so neglected boost for that
Doesn't know what an ATTACKER type enemy is necessarily
Rememver the FAST enemy type though

Picked harvest upgrade
Hard to get use out of the healing because it has to be super close
And I don't think about the character's health too much
Health management is a bit of an information overload
Not thinking about character's health too much in the moment
NOT noticing that the white splash has an inspire boost
"For 2 seconds though, but when does that activate" --> connected the sound effect with the inspire

"I don't have enough for that cannon"
"I'm thinking that putting characters on a corner or an intersection is better than putting them just beside the straightaway"

Outlines don't scale with the enemy when they get shake or when they get bounced
level before boss, did really well
Level 6 --> "Now that I get it I'm getting a lot more out of the whole experience"
"Okay, I know what I'm doing"
"I can have a strategy that I'm confident in"
"It was harder to enjoy [when he was flailing]. It felt like trial and error"

Selecting the more advanced difficulty is confusing
"It's clearly more useful because it costs more juice"
Bought the frenzy cannon

Boss fight --> Thinks the S's represent a point where it will attack the ship

I feel a bit of a panic with the way the time works
Haven't touched keyboard once in this game
Did not know what the speed controls where

Recalling a unit when it's paused and not getting the refund is confusing
Didn't notice until just now that juice was going to the juice bar

Not placing optimally against boss but still kinda holding up
Character's dying is ALWAYS a surprise
(But they are noticing when characters do die)
"The archer doesn't need to be right beside the path"

Hadn't realized that the bouncer has a lot more health
Consistently not boosting guys
Thought boosting was temporary
Make it say "Boost X: X00 juice"

Have to hit spacebar twice to unpause
Time is the only thing I wanna use keyboard for everything else I wanna use mouse
Haste needs to be grid based

Recalled guys and that resets the boost --> caused thinking that boos is temporary

"I think we're eventually going to join forces"
Hadn't realized until Black Hat level 1 what the boost doodad above head was for
Figured out how to use the fire bomb

"I like that the first skill is just increase the damage, I like having the safe bet"
"I assume it's just temporary, but it would be cool if the map started from a different position because you're a different team" (as in the map wasn't connected)

"These guys are sweating" --> "oh no that's poison"

The laser from the ship makes him think he's boosted guys when he hasn't
Thinks jumper gains health automatically because of the tutorial

Nobody is really noticing text statuses

really excited about the jumper
eliminator "we're starting to get into effects" --> didn't realize from tutorial there was poison, learned that from gameplay
black hats --> these guys are a bit more technical
Expecting the boss fight to be the white hats

**Comment by JohnKossa** [comment]
To clarify on "On auto-equip not sure what happens if you equip a guy"

The uncertainty was on what happens if you equip a guy with auto-equip when he already has an equipped item of that type.
