### ISSUE TITLE
SortInventoryByType not 100% working.

### ISSUE THREAD

**Issue by ProG4mr** [larsiusprime/tdrpg-bugs#181]
Calling Main.OMNI.party_data._inventory.sortInvetoryByType(itemClass, category, false);
Results in a list of items that randomly changes everytime the function is called (is not always the same)

This causes in the list of items of the shop to change everytime the list is refreshed (specially noticeable when selling items).

**Comment by larsiusprime** [comment]
Here: http://api.haxe.org/haxe/ds/ArraySort.html

Try replacing haxe.ds.ArraySort() instead of Array.sort() and see if the results are better.

**Comment by larsiusprime** [comment]
Okay, yeah, haxe.ds.ArraySort() totally fixes this.
