### ISSUE TITLE
Items names are not correctly fetched by firetongue.

### ISSUE THREAD

**Issue by ProG4mr** [larsiusprime/tdrpg-bugs#183]
At some point item names are requested using:

```
item.get_name()
```

It returns the correct item locale tag with a wrong '_name' suffix: eg: ```$$ITM_W_SWORD_2_NAME``` instead of the item english name: ```Metal shiv``` because fire-tongue rightly fails to find the locale tag with the wrong suffix.

**Comment by larsiusprime** [comment]
So I need to modify firetongue to build custom flags from roots & suffixes, which I apparently was doing in its AS3 predecessor!

**Comment by larsiusprime** [comment]
Actually this was already implemented. Seems the problem was it was looking for the item name in the "items" context, but the locales/index.xml was storing it under the "ui" context.

Fixed locales/index.xml to store it in "items" context instead, seems to work now.
