### ISSUE TITLE
"Talk" button in towns

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#211]
Towns will show a "talk" button if the associated town XML entry has a cutscene it can show.

Clicking on that "talk" button launches said cutscene.

**Comment by ProG4mr** [comment]
I think this is working already, the condition to show the talk button is the following:

```
Main.OMNI.gameProgress.isTownCutsceneUnlocked(town_id, data.list_cutscenes[0])```
```

It checks GameProgress.list_town_cutscenes_unlocked  which has zero entries for some reason (the list of cutscenes passed seems right), thats why the talk button never shows.

I can remove the condition and always show the talk button if (data.list_cutscenes[0]) has some entry, sounds good?

**Comment by larsiusprime** [comment]
Ah, cool, thanks. In that case leave it as is, the real issue in this case
is to get new-game+ mode working, which is the mode in which the cutscenes
at the towns will get unlocked.
