### ISSUE TITLE
Cutscene bugs

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#258]
To reproduce:

- Compile in CPP mode (since flash cutscenes don't have assets and won't work)
- Open the cutscene "strange new friend"
- Get to the part where Slak is about to leave on the right side of the screen
- Click next, and watch him start to slide to the right
- Quickly, click previous (back) TWICE.

What should happen:

- When you click back the first time, Slak should stop exiting and warp back to his previous standing position & line (see legacy game build of this cutscene).
- When you click back the second time, it should display the previous line & poses said before that

What happens instead:

- Slak turns into an image not found and slides off the LEFT side of the screen!

Happy bug hunting :)

**Comment by ProG4mr** [comment]
Umm i updated both tdrpg-haxe and DFQ1 and when i try to compile windows or flash target i get the error:

```Could not find asset path "assets/gfx/tiles/hd/work"```

I check for it and i can't find it too.
Also flashdevelop shows no libraries, that usually happen when there is something wrong with the compile file, can you commit the latest work so maybe i can skip this problem without too much trouble?

**Comment by ProG4mr** [comment]
Okay sorry, commented out ```assets path="assets/gfx/tiles/hd/work" exclude="*.*"``` and its giving me now other more standard compiling errors which Ill look into tommorow.

**Comment by ProG4mr** [comment]
So far added a next / back button guards to prevent multiple commands which works nicely, also almost understand where the bug is coming from, it has to do with the image alias placed on top of a mess and the asset "ber_sooo.png", hopefully will be fixed soon.

**Comment by larsiusprime** [comment]
Great, good work on that.

Just discovered a new one:

-Character says a line
-Next, another character appears

What should happen:
-The speech bubble should immediately disappear when "next" is pressed.

What happens instead:
- The speech bubble stays, is not removed until the character appears.

Visually, whenever a character's mouth is closed, there should not be a speech bubble. When you hit "next" after a line command, the speech bubble should always disappear, and not wait for the next command to resolve/finish before disappearing/changing.

**Comment by ProG4mr** [comment]
Sent you an email, there are ways to solve the the image_not_found bug, one is to name the lights with the same name as the image on aliases.xml, the other is to store the image id's before transforming them with aliases().

The xml one is more trivial, the other one is not much complicated too, however i tried it and i got issues elsewhere but should be doable.

**Comment by larsiusprime** [comment]
I think the alias system should be the one we use as we use that already
elsewhere to reduce the number of assets the game uses. That requires a bit
more book-keeping but I think it's the way we should go. Do you need more
information about the alias system or is it straightforward enough?

**Comment by ProG4mr** [comment]
Think i got it, won't be too hard probably, next time i may ask how to get the flash target working as it makes it easier with the debugger in these situations.

**Comment by larsiusprime** [comment]
Yeah, right now the issue with the flash target is it's hitting an asset
limit. Basically all I'm doing is excluding cutscene assets as they put us
over the limit.

There's two solutions:

1) Bug Joshua to fix it so you can embed arbitrary number of assets in
flash target
2) Selectively let enough assets through to not go over the limit but still
have enough to test a representative cutscene or two.

On Fri, Mar 13, 2015 at 3:09 PM, TiagoLr <notifications@github.com> wrote:

> Think i got it, won't be too hard probably, next time i may ask how to get
> the flash target working as it makes it easier with the debugger in these
> situations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/258#issuecomment-79328406>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ProG4mr** [comment]
Ah thanks, didn't knew, no problem then.

**Comment by larsiusprime** [comment]
Bugs still remaining:

- [ ] Foreground shows up too large in original graphics mode
- [ ] Bubble does not disappear when next is pressed
