### ISSUE TITLE
Text is off-button.

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#269]
DQ1 0.1.1 Build 4, Windows version.

First thing I did when I started up the game (oh yeah that locale crash bug is fixed btw) was test the new video resolutions. There are some problems with 854x480 (never really liked that resolution anyway):
![image](https://cloud.githubusercontent.com/assets/7569514/6879222/16937fc0-d4e7-11e4-812b-11bdcb450dda.png)
As you can see, the text goes off the buttons if the text in them is too big (the text should also kind of scale too). It also just looks... bad. The New Game and Import text also looks bad in 1024x768
Oh and the game should warn you when you're changing a resolution too (that's a suggestion).

**Comment by larsiusprime** [comment]
That is... weird! Thanks for the bug report.

On Fri, Mar 27, 2015 at 8:11 PM, ManDude <notifications@github.com> wrote:

> DQ1 0.1.1 Build 4, Windows version.
>
> First thing I did when I started up the game (oh yeah that locale crash
> bug is fixed btw) was test the new video resolutions. There are some
> problems with 854x480 (never really liked that resolution anyway):
> [image: image]
> <https://cloud.githubusercontent.com/assets/7569514/6879222/16937fc0-d4e7-11e4-812b-11bdcb450dda.png>
> As you can see, the text goes off the buttons if the text in them is too
> big (the text should also kind of scale too). It also just looks... bad.
> Oh and the game should warn you when you're changing a resolution too
> (that's a suggestion).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/269>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
>Oh and the game should warn you when you're changing a resolution too (that's a suggestion).

Do me a favor and open that as a new issue so I don't forget?

**Comment by larsiusprime** [comment]
This is fixed now. It should show up in tonight's nightly build. (should be 0.1.2 build 8)

**Comment by ManDude** [comment]
Yup, it's fixed here too.
