### ISSUE TITLE
Weird white square of annoyance

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#270]
There's a white square in the title screen image that really bothers me. It seems to be part of title screen image itself, as it won't go away no matter what resolution or HD setting I check:
![image](https://cloud.githubusercontent.com/assets/7569514/6879413/5ad8cf28-d4ec-11e4-8734-e1587036570f.png)

**Comment by ManDude** [comment]
Also, why is there a small box with a 1 in it during battles?

**Comment by larsiusprime** [comment]
Whoops, that's a debug thing I added. It'll be gone in the next release,
thanks for the report.

What "small box with a 1 in it" ?

On Fri, Mar 27, 2015 at 8:48 PM, ManDude <notifications@github.com> wrote:

> Also, why is there a small box with a 1 in it during battles?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/270#issuecomment-87140986>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
During battles, on the top-left corner.

**Comment by larsiusprime** [comment]
Removed title screen box.

I noticed the little white box with a "1" in it once, but now I can't get it to appear again. I'm putting this bug under "Verify."

With build 0.1.2 (new build on the server) do either of these happen anymore?
