### ISSUE TITLE
Battles are unwinnable

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#272]
F2 doesn't auto-win battles, so you can't proceed after starting the 1st level.

**Comment by larsiusprime** [comment]
To do:

- [ ] Simple popup after battle that says "Victory!" and "OK" or whatever
- [ ] After victory, transition to the victory screen
- [ ] Enable victory mode in party screen, show victory / failure stuff

**Comment by larsiusprime** [comment]
This will be fixed in tonight's builds. I also added back "F2 for instawin." It was disabled before b/c these builds are release mode instead of debug mode. (Release is faster/better but has no debugging internal structure)

**Comment by ManDude** [comment]
Was a new build supposed to be up by now?

**Comment by larsiusprime** [comment]
Not sure what time zone it's supposed to be set to. If it's not working
it'll be in the next day's build.

On Fri, Apr 3, 2015 at 7:30 PM, ManDude <notifications@github.com> wrote:

> Was a new build supposed to be up by now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/272#issuecomment-89472815>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
I'm running a new build right now manually, should be up in ~ 20 minutes.

On Fri, Apr 3, 2015 at 8:08 PM, Lars Doucet <lars.doucet@gmail.com> wrote:

> Not sure what time zone it's supposed to be set to. If it's not working
> it'll be in the next day's build.
>
> On Fri, Apr 3, 2015 at 7:30 PM, ManDude <notifications@github.com> wrote:
>
>> Was a new build supposed to be up by now?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/larsiusprime/tdrpg-bugs/issues/272#issuecomment-89472815>
>> .
>>
>
>
>
> --
> www.fortressofdoors.com -- Games, Art, Design
>



-- 
www.fortressofdoors.com -- Games, Art, Design
