### ISSUE TITLE
DQ2 pre-order page has wrong estimates

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#279]
In DQ2's<sup>1</sup> pre-order page, the Alpha and Beta invite sections say that the estimated release is 2014, whereas it should be 2015 (at best) because they weren't "released" yet.

<sup>1</sup> - _Here I am using DQ2 for the sake of being short and because I'm used to it._

P.S.: https://github.com/larsiusprime/tdrpg-bugs/milestones/3DS%20Release Oops? I doubt DQ2 is ready to release on the 3DS. ;)

**Comment by larsiusprime** [comment]
Thanks for the catch!
Fixed and fixed :)
