### ISSUE TITLE
'HD' Resolutions Mislabeled 

### ISSUE THREAD

**Issue by Rythe** [larsiusprime/tdrpg-bugs#329]
DefQ1 0.1.2 Build 7, Win 7.

Under 'Game Window Size', you've got HD vs Standard when what I believe you want is Wide vs Standard since you're dealing with aspect ratios there.

'HD' classically being given to 1280x720 and 1920x1080 rather than, say, 854x480.

So that 'HD (16:9)' should probably be relabeled to 'Wide (16:9)' or 'Widescreen (16:9)'

And now that I look at it, the aspect ratio labels can probably be shifted to the right a bit. It looks like they hang a bit far left of the radio buttons.

![resolutions](https://cloud.githubusercontent.com/assets/11690153/6990096/deed7e6a-da2a-11e4-8cb2-45af866464f3.png)

**Comment by ManDude** [comment]
Build 8's the same.

**Comment by larsiusprime** [comment]
Ah, that's a good point.

On Fri, Apr 3, 2015 at 7:28 PM, ManDude <notifications@github.com> wrote:

> Build 8's the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/329#issuecomment-89472681>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
