### ISSUE TITLE
Equip menu in party screen

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#375]
To start with:
- [x] Create basic stub of party screen equip menu

- [x] Clicking one of the two equip buttons turns on equip mode (show equip, hide skills)
- [x] When a character is selected, update the equip menu if an equip button is selected (like if its the top button, berserker shows swords, ice mage shows staffs)
- [x] Show a list of all items of the given type
- [x] Only show equipped items if the checkbox is checked
- [x] Have scroll buttons that let you go up and down
- [x] Items can be selected in the menu
- [x] "Equip" button is disabled unless something is selected
- [x] "Unequip" button is disabled unless something is equiped
- [x] "Equip" button tells that character to equip that item and updates the menu
- [x] "Unequip" button tells that character to unequip whatever they have in that slot and updates the menu
- [x] Try to re-use the stuff we built for the town menu (Merchandise class?), it has most of this functionality already

NOTE: 
* No skinning is required for now, but you should show icons and all text with the correct localization strings
* Legacy had a confusing and hacky setup for equip logic because it always assumed slot 1 = weapon and slot 2 = armor. In the new version we just have numbered item slots per character that correspond directly to the equip buttons.

**Comment by larsiusprime** [comment]
Also, there are two new classes, UI_SkillsMenu and UI_EquipMenu, that correspond to the "equip" and "skills" group in state_party. These are basically just regular FlxUIGroups (not FlxUI's) that have been extended so that you can put logic directly in them to keep things cleaner. Anything that is part of the "skills" or "equip" group in the state_party.xml will automatically be in one of those classes' "members" array

**Comment by ProG4mr** [comment]
Nice mechanism with the CustomUIGroup, to get things going I'm thinking of going thro all gems when the state is changed to "equip" or "skills" and showing the item icons (if its equip mode) or showing the progress bar (otherwise).

![image](https://cloud.githubusercontent.com/assets/2106619/8272185/f99f654a-1830-11e5-9738-074377996f38.png)

Let me know if i shouldn't deal with this first.

**Comment by larsiusprime** [comment]
No that's great. Go ahead and do that!

On Sun, Jun 21, 2015 at 10:18 AM, TiagoLr <notifications@github.com> wrote:

> Nice mechanism with the CustomUIGroup, to get things going I'm thinking of
> going thro all gems when the state is changed to "equip" or "skills" and
> showing the item icons (if its equip mode) or showing the progress bar
> (otherwise).
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2106619/8272185/f99f654a-1830-11e5-9738-074377996f38.png>
>
> Let me know if i shouldn't deal with this first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/375#issuecomment-113912814>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ProG4mr** [comment]
Hey, the equip menu is mostly complete however ive run into an issue:

1 - Azra equip a book in both slots.
Whenever a book is equipped on azra slot 0 or 1, the same book appears in both slots.

![image](https://cloud.githubusercontent.com/assets/2106619/8763177/d40b86a2-2d88-11e5-817d-1ca33d5ee0bb.png)

the code to fetch the items is the following:
```haxe
// get char weapon item
var weapon:Item = null;
char.charClass == "mcguffin" ?
	entry = Main.OMNI.party_data.getEquippedItem(char, 0):
	entry = Main.OMNI.party_data.getEquippedItem(char, null, ItemClass.Weapon);
if (entry != null) {
	weapon = Main.OMNI.party_data.fetchItem(entry);
}

// get char armor item
var armor:Item = null;
char.charClass == "mcguffin" ?
	entry = Main.OMNI.party_data.getEquippedItem(char, 1):
	entry = Main.OMNI.party_data.getEquippedItem(char, null, ItemClass.Armor);
if (entry != null) {
	armor = Main.OMNI.party_data.fetchItem(entry);
}
```


Other than that things seem to be ok (the other cpp bug i mentioned before had to do with the save file after all).

**Comment by larsiusprime** [comment]
Hmmm, thanks for this. I'll have to take a look at the code tomorrow. It
probably has something to do with the fact that in DQ1-legacy slot 1 was
always a weapon and slot 2 was always an armor, but in DQ1-HD any slot can
be anything, and for Azra books are weapons... (actually just checked!
They're "Accessory" class, something new to DQ1-HD.)

Anyways I'm sure the change has made things a little complicated. Keep
working on achievements if you need something to do and I'll see if I can
sort it out.

On Sat, Jul 18, 2015 at 2:20 PM, TiagoLr <notifications@github.com> wrote:

> Hey, the equip menu is mostly complete however ive run into an issue:
>
> 1 - Azra equip a book in both slots.
> Whenever a book is equipped on azra slot 0 or 1, the same book appears in
> both slots.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2106619/8763177/d40b86a2-2d88-11e5-817d-1ca33d5ee0bb.png>
>
> the code to fetch the items is the following:
>
> // get char weapon itemvar weapon:Item = null;
> char.charClass == "mcguffin" ?
>     entry = Main.OMNI.party_data.getEquippedItem(char, 0):
>     entry = Main.OMNI.party_data.getEquippedItem(char, null, ItemClass.Weapon);if (entry != null) {
>     weapon = Main.OMNI.party_data.fetchItem(entry);
> }
> // get char armor itemvar armor:Item = null;
> char.charClass == "mcguffin" ?
>     entry = Main.OMNI.party_data.getEquippedItem(char, 1):
>     entry = Main.OMNI.party_data.getEquippedItem(char, null, ItemClass.Armor);if (entry != null) {
>     armor = Main.OMNI.party_data.fetchItem(entry);
> }
>
> Other than that things seem to be ok (the other cpp bug i mentioned before
> had to do with the save file after all).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/375#issuecomment-122583112>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
I figured it out, it was just two missing lines of code. You did a really good job here from the looks of it!

The only thing that was missing was that the slot parameter was not being passed into two functions, so it was using the old behavior of returning the first item that matches the class/type, which caused slot confusion.

The two places were:
* UI_EquipMenu.refreshItemsFromChar() : the call to party_data.getEquippedItem() had null for the slot
* Inventory.getItemOwnedBy(): didn't have a parameter for slot, so I added one, and made PartyData pass it along in getEquippedItem().

Seems to work now!

I've merged this into the main branch for tdrpg-haxe. What more do you have left here or is it time for me to skin it?

**Comment by ProG4mr** [comment]
Hey, i think I'll have it ready in a couple of hours.

**Comment by ProG4mr** [comment]
Okay, I've sent more changes to party screen branch. I think its mostly ready to be skinned, let me know if you find any glitches.

A few notes on things that may need improvement:

* Equip button stays pressed down after equipping item.
* Unequip button stays pressed down after unequipping item.
* I managed to get some localization flags by adding `_NAME` suffix, not sure if its supposed, see the commit changes.

By the way let me know if you want me to merge the branches.

**Comment by larsiusprime** [comment]
Yeah, that might be a poorly documented thing in firetongue. The first line of the file has a list of suffixes for each of the fields that get automatically applied. If it's just two fields, flag and value, it doesn't do that.

**Comment by larsiusprime** [comment]
I'll take a look tomorrow and merge if things are playing nicely, so keep on its own branch for now.
