### ISSUE TITLE
InventoryEntry.owner names do not reflect renamed characters

### ISSUE THREAD

**Issue by ProG4mr** [larsiusprime/tdrpg-bugs#394]
InventoryEntry.owner contain the name of the owner of the item (if the item is equiped).

In my save i have renamed a few characters. On both Party Screen and Shop Screen, if i show equipped items, some characters will not be found because the name on the item entry does not reflect the actual character name.

**Comment by ProG4mr** [comment]
Most likely i can fix it later by updating the equipped item entries when a character is renamed.

**Comment by larsiusprime** [comment]
The NAME or the HANDLE of the character? The .handle property of a character is the unique identifier and never changes. Name can be changed any time and is purely for display purposes.

**Comment by ProG4mr** [comment]
Its the handle, this operation fails (owner is null at the end):

```haxe
var split = itmEntry.owner.split("_");
var owner = Main.OMNI.party_data.getCharacter(split[0], split[1]);
```

where split[0] is "berserker" and split[1] is "slak" which has been renamed to another name.
