### ISSUE TITLE
Back button in cutscenes doesn't quite work

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#398]
The "Next" button works perfect.

![en7jvs0](https://cloud.githubusercontent.com/assets/7569514/8467684/8e585950-2059-11e5-8763-4c4602f6ee49.png)
![hh5usy6](https://cloud.githubusercontent.com/assets/7569514/8467685/8e5b680c-2059-11e5-8026-3e8e23c2f538.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/7569514/8467688/9b5d5a1a-2059-11e5-96d7-f8f62d013a54.png)
You get the point. DQ1 0.1.7 (Windows) @ 800x600 resolution (HD everything)

EDIT: I must say, I do like the placeholder bkg, hopefully it becomes some sort of special art.

**Comment by larsiusprime** [comment]
Please try 0.1.7 build *3*, which just went up last night, and let me know if this is still happening.

**Comment by larsiusprime** [comment]
Getting ready to close -- Please verify whether this is still happening in 0.1.7 build 3.
