### ISSUE TITLE
Cutscenes - tons of bugs (part 2!)

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#399]
* Characters (not their shading though) randomly shrink.
* Characters can sometimes move out of bounds.
 * Which makes text boxes go out of the screen.
* Some scenes aren't inserted.
* #398 

There may be more, as this was on 800x600 with HD everything.

**Comment by larsiusprime** [comment]
Please try 0.1.7 build *3*, which just went up last night, and let me know if this is still happening.

**Comment by larsiusprime** [comment]
- [ ] FIXED: Characters (not their shading though) randomly shrink.
- [ ] FIXED : Which makes text boxes go out of the screen.
- [ ] FIXED: #398

- Characters can sometimes move out of bounds.
**When and where?**

- Some scenes aren't inserted.
**What does this mean?**
