### ISSUE TITLE
Battle bugs

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#400]
![fpmnzof](https://cloud.githubusercontent.com/assets/7569514/8467781/fe25dac2-205a-11e5-8b28-7fa2e92298d6.png)

**Comment by ManDude** [comment]
Also, enemies that come from the blue lane are invincible and invisible.

**Comment by larsiusprime** [comment]
There's no blue lane on this map... do you mean the second battle?

**Comment by ManDude** [comment]
In any battle with a blue lane.
