### ISSUE TITLE
Resolution fixes

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#425]
- [x] Fix button offset glitch in video menu
- [ ] Add fullscreen options:
  - [ ] Screen position offset
  - [ ] Screen dead space
  - [ ] Monitor resolution
  - [ ] Game canvas resolution
  - [ ] Smoothing on/off

**Comment by joaociocca** [comment]
Fullscreen could be made into windowed borderless, can't it? It's really boring how the game minimizes  when you focus out of it (like alt+tab) - specially bad if you have multiple displays like me.
