### ISSUE TITLE
Remove the command window popups when changing resolution

### ISSUE THREAD

**Issue by meganbednarz** [larsiusprime/tdrpg-bugs#430]
When you change the screen resolution, or any time the program restarts, it flashes several command windows that might be abrupt/confusing to players. I recommend removing them in the final release.

**Comment by larsiusprime** [comment]
Good idea

On Tue, Aug 4, 2015 at 9:39 PM, Megan Bednarz <notifications@github.com>
wrote:

> When you change the screen resolution, or any time the program restarts,
> it flashes several command windows that might be abrupt/confusing to
> players. I recommend removing them in the final release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/430>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
I'm just removing crashdumper for now until I can fix it up properly.
