### ISSUE TITLE
Gameplay blocked: Cannot play past second level ("Caravan of the Dead")

### ISSUE THREAD

**Issue by tdrpg-fan** [larsiusprime/tdrpg-bugs#456]
The second level of the game has dialog between Azra and Slak. However, Azra's first dialog line contains only a speech balloon and no 'Next' button. The player is unable to proceed past the first line of dialog and cannot play the level.

#### Repro steps:
1. Start a new game and beat the first level
2. On the world map, click the 'Battle' button on the second jewel
3. Click 'Begin' to load "Caravan of the Dead"
4. See Azra's line of dialog ("Slak! It worked!") has no buttons, and no way to continue to playing the level.

![alpha - caravan no next button](https://cloud.githubusercontent.com/assets/14085556/9623146/20981b2c-50fa-11e5-8f48-3797ab25c530.png)

**Expected behaviour:** The dialog should give the player *some* means to continue and play the level.

I tried pressing `enter`, `space bar`, and using the arrow keys, but nothing seems to get me past this screen.

I would attach a save game file to get you past the first game level for faster repro of this bug, but the Export feature doesn't seem to work right now (see #455 ).

--
**System Info**

Operating System: Windows 7, 32-bit
Build: 0.2.1 build 3
Game Version: DQ1 0.2.1
Screen size: 800x600; Windowed mode

**Comment by tdrpg-fan** [comment]
@larsiusprime Again, do you even want gameplay-related bugs right now, or should I hold off? Would it be worth writing a quick FAQ on what types of things should have bugs filed? Or is that likely to change too quickly?

**Comment by tdrpg-fan** [comment]
If I change my video settings to 1024x768 the 'Next' button then does display on my screen. I can get past the first bit of dialog. However, further bits of the tutorial are still blocked off and are not visible. So it looks like mainly the tutorial system simply hasn't been set up to move inside the bounds of the screen yet.

**Comment by larsiusprime** [comment]
Thanks!

Yup, this is all related to 454. I'll have it sorted soon, and will appreciate a confirmation once I mark this as complete.

**Comment by larsiusprime** [comment]
Needs #457 and #197

**Comment by larsiusprime** [comment]
This should be fixed now.
