### ISSUE TITLE
Start Screen: Import button does not function

### ISSUE THREAD

**Issue by tdrpg-fan** [larsiusprime/tdrpg-bugs#459]
After pressing Start on the Title screen, clicking on the 'Import' button doesn't do anything yet.

#### Repro steps:

1. Launch the game
1. At the Title Screen, click Start
1. Click the 'Import' button beside any empty save slot (if you don't have any empty slots, click the 'Delete' button and then click 'Yes' to clear a slot)
1. The import button appears to do nothing

**Expected behaviour:** The 'Import' button would open an 'open file' dialog to let me import my saved game

--
**System Info**

Operating System: Windows 7, 32-bit
Build: 0.2.1 build 3
Game Version: DQ1 0.2.1

**Comment by larsiusprime** [comment]
Fixed in tonight's build.

**Comment by tdrpg-fan** [comment]
Confirmed fixed in 0.2.1 build 5. Thanks Lars!
