### ISSUE TITLE
Battle screen: space bar does not pause

### ISSUE THREAD

**Issue by tdrpg-fan** [larsiusprime/tdrpg-bugs#460]
If you press the `space bar` while fighting a battle, nothing happens. It would be great if `space bar` would pause the game (and then unpause!)

#### Repro steps:

1. Launch the game
1. At the Title Screen, click Start
1. Start a new game or continue any existing game
1. Enter any battle
1. After any pre-battle cutscenes and tutorials have finished, advance time so that enemies are approaching Azra
1. Press the `space bar`
1. Notice that the game does not pause; enemies continue plodding onwards unstoppably towards death

**Expected behaviour:** Pressing `space bar` during battle should pause the game if time is advancing, and unpause the game if currently paused.

Note that clicking on the `||` double-bar 'pause' icon *does* currently work.

--
**System Info**

Operating System: Windows 7, 32-bit
Build: 0.2.1 build 3
Game Version: DQ1 0.2.1

**Comment by larsiusprime** [comment]
Fixed in tonight's build. Also the +/- keys (or whatever hotkeys you bind to speed up/down) should work now, too.

**Comment by tdrpg-fan** [comment]
Confirmed fixed in 0.2.1 build 5, and the +/- keys work too. Thanks!
