### ISSUE TITLE
Feature Request: Speed controls on credit screen

### ISSUE THREAD

**Issue by tdrpg-fan** [larsiusprime/tdrpg-bugs#468]
This is very minor and not game related, but what do you think about adding some controls on the Credits screen to let players fast-forward, pause, and possibly rewind? This would make it much easier to read the credits at my own pace. Sometimes it's nice to pause and read everything. Sometimes it's nice to skip to a certain section.

**Comment by ManDude** [comment]
This is a great suggestion in my opinion. :)
