### ISSUE TITLE
Ranger combat

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#479]
- [x] Launch the attack on sweet frames
- [x] Generate the projectile's visuals
- [x] Generate the projectile's model object
- [x] Move the projectile over time in the model
- [x] Create the visuals in the right location
- [x] Resolve the final collision correctly
- [x] Simple projectiles
- [x] Targeted projectiles
- [x] Untargeted projectiles
- [x] Spread projectiles
- [x] Prevent unwanted piercing
- [x] Sound
- [x] "rapid fire" multiple attacks
- [x] "black out the sun" style attacks

**Comment by tdrpg-fan** [comment]
I would just like to say: Woo! Rangers! :D
