### ISSUE TITLE
Trouble showing Unicode path name in options dialog

### ISSUE THREAD

**Issue by kwi-dk** [larsiusprime/tdrpg-bugs#50]
### Basic info

 OS: Windows 7
 Version: DQ2 0.0.4 TTDRPG 0.0.5

### Steps to reproduce

1. Have a Windows user account named "Søren Løvborg", and thus a profile folder path with funny characters in it.
2. Go into the Miscellaneous options menu.

### What I expected to happen

My "Save files" and "Mod files" path to be rendered correctly, or at most with a replacement [?] glyph in place of the "ø"s.

### What happened instead

I find the path to be quite unreadable, though the game successfully saves in the correct location.

![unicode-problems](https://cloud.githubusercontent.com/assets/1167359/3321668/ab898ad8-f73a-11e3-8179-e24d3df3ede9.jpg)

**Comment by larsiusprime** [comment]
This should FINALLY be fixed now :)
