### ISSUE TITLE
Fix glitch in FlxText.applyMarkup

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#500]
Reproduction:

- Take some text that's got an existing default format, say, white.
- Call applyMarkup() with "some text like @this@"
- Use it with a FlxTextFormat that's green in color

Expected: "some text like" should be white and "this" should be green.

Results: on flash, it works. on cpp, the entire text is green.

You can see this phenomenon in the current version of the skill descriptions in cpp mode only. Most likely it is a glitch with the underlying cpp implementation of applyMarkup() -- when the formats are cleared probably the default format is not properly preserved. Likely this is a bug in FlxText and not tdrpg-haxe, but I'm not sure.

**Comment by tiagolr** [comment]
Hey, I'm testing this bug but i cannot reproduce it, perhaps its fixed. I'm using latest openfl and lime from master branch, here is the result i get:

![image](https://cloud.githubusercontent.com/assets/2106619/10717498/a7d4ccbc-7b51-11e5-8e4d-2e2c05d22668.png)

This is cpp target, the text formatting seems to be working.

**Comment by larsiusprime** [comment]
Interesting. As of last week it was still happening to me, but glad to hear it's not happening for you. I'll test it again on monday and we'll get to the bottom of it.

**Comment by larsiusprime** [comment]
Argh, this is still happening to me with the latest lime, openfl, hxcpp, and flixel.

Here's the save file I'm using: (rename to .dfq)
[SAVE_SLOT_2.txt](https://github.com/larsiusprime/tdrpg-bugs/files/20948/SAVE_SLOT_2.txt)

Open the party screen and inspect Azra's lightning spell, for instance, or any of the berserkers' skills. All the text is green for me. Is it the same way for you?

**Comment by larsiusprime** [comment]
Also, are you using -Dnext ?

**Comment by larsiusprime** [comment]
Okay, I've tracked it down to this --
https://github.com/openfl/openfl/issues/905

Do you get the same results when you run that sample?

**Comment by tiagolr** [comment]
AAh, no I was not using -Dnext here. Okay I'll see if i can find the source of this problem.
.

**Comment by larsiusprime** [comment]
I decided to just work around this with a hack. It's in UU.applyMarkupHack

**Comment by tiagolr** [comment]
Wow, okay, i narrowed this problem to openfl._internal.renderer.cairo.CairoTextField

Besides that the current implementation uses only a single text format, that is why there is only a single color. Glad you found a workaround because implementing a fix for this one will be like implementing an openfl feature and would take some time.

**Comment by larsiusprime** [comment]
Yeah I say punt on this for now, I talked it over with Joshua and it
requires some serious surgery to TextEngine. I'll have some new tasks for
you on Monday -- I think it's about time we implemented the Journal and
Bonus screen interfaces.

On Sun, Nov 8, 2015 at 3:18 PM, TiagoLr <notifications@github.com> wrote:

> Wow, okay, i narrowed this problem to
> openfl._internal.renderer.cairo.CairoTextField
>
> Besides that the current implementation uses only a single text format,
> that is why there is only a single color. Glad you found a workaround
> because implementing a fix for this one will be like implementing an openfl
> feature and would take some time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/500#issuecomment-154874648>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by tiagolr** [comment]
Great, looking forward to it.

**Comment by larsiusprime** [comment]
I put some new issues up and assigned them to you -- redesign / rename menu
functions in the party menu. After that we'll look into the bonus menu and
journal.

On Mon, Nov 9, 2015 at 11:14 AM, TiagoLr <notifications@github.com> wrote:

> Great, looking forward to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/500#issuecomment-155128893>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
