### ISSUE TITLE
Crash on startup of DQ1

### ISSUE THREAD

**Issue by ahanses** [larsiusprime/tdrpg-bugs#524]
Operating System: Windows 10
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : 0.2.31
Optional Info** : First time trying to run the game.

STEPS:
1) Start DQ1

EXPECTED:
Run Game

WHAT HAPPENED INSTEAD:
Crash

CPU: Name=Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
GPU:Name=AMD FirePro W7000  DriverVersion=15.201.1151.0
OS:Microsoft Windows [Version 10.0.10240]
MEMORY:TotalVisibleMemorySize=33522648

![dq1 crash](https://cloud.githubusercontent.com/assets/15395122/10837761/782d9a08-7e7a-11e5-9724-ef4cbcfeeef9.png)

**Comment by ahanses** [comment]
Note: DQ2 v0.0.5 tdrpg v0.0.8 starts up fine on the same system.

**Comment by ahanses** [comment]
Also of note, Mode Next test file on GDrive runs fine on my system while Mode Legacy crashes.

**Comment by ahanses** [comment]
Regression tested all the way back to 2.2.15.  All the builds I tried crash.

**Comment by ahanses** [comment]
0.2.3.31 crashes instantly on my Surface Pro 3 as well.

**Comment by larsiusprime** [comment]
Really interesting. To be clear, versions before 2.2.15 did not crash, or you didn't check back any further?

**Comment by ahanses** [comment]
I did not check back any further than 2.2.15.  If you have any specific build you would like me to try to repro with, let me know.

**Comment by larsiusprime** [comment]
Can you try this survey? It has links to various simple demo builds designed to isolate where exactly the crash is originating.

https://t.co/YQQT5gdJg9

**Comment by ahanses** [comment]
So, good news and bad news.  Both the same.

The latest build of the game now works on both my systems and all the tests pass.

Running 0.2.4.15 for DQ1

Coming from a software background myself, I imagine that is bad news as well since you might not understand wtf went wrong in the first place.

If you need me to regression test any other builds or run anything else, let me know.

**Comment by larsiusprime** [comment]
Actually, we know exactly what went wrong -- I've been in touch with the OpenFL team and we recently rooted out a low level compatibility issue from one of the define flags we were using with thread local storage.

One of those rare instances where we have some idea what's happening!
