### ISSUE TITLE
Party "redesign" menu

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#536]
This is pretty much exactly like the "recruit" menu, except that you're not purchasing a new character, you're just changing colors & name of an existing character.

- [x] Re-use the UI_Recruit menu
- [x] Put it inside of a TDRPGPopup (see Popup_QuickEquip as an example)
- [x] Make "Hire" button just say $MISC_OK
- [x] Hide cost, scrap, and class tabs. Do still show other character icons down below for context.
- [x] If cancel, (x button) close the menu and do nothing
-[ ] If okay, close the menu, update the character's colors in the party data, save the game, and refresh the releveant level up gem (by calling show() again on the current character to update the portrait)

**Comment by tiagolr** [comment]
Ok, its working, the only thing missing is a confirmation popup when the user clicks ok.

**Comment by larsiusprime** [comment]
Great, thanks a lot for all this. Your next task will be to do the "bonus"
mission popup interface and map preview. I'll write a spec for you now.

On Thu, Nov 19, 2015 at 8:11 AM, TiagoLr <notifications@github.com> wrote:

> Ok, its working, the only thing missing is a confirmation popup when the
> user clicks ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/536#issuecomment-158068117>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
