### ISSUE TITLE
Party "rename" menu

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#537]
- [x] Create a new class, Popup_Rename
- [x] Extend Popup_Confirmation
- [x] Set your own _xml_id in constructor after calling super(), like "ui/popup_rename"

You can use the "inject" tag in flixel-ui so you can copy what's in popup_confirmation.xml, and then only add what's different:

```xml
<inject name="ui\popup_confirmation"/>
<new_stuff value="blah"/>
<new_stuff value="blah"/>
<new_stuff value="blah"/>
```

- [x] Add an input text field to this description and position it in the middle of the text field
- [x] Make the Popup_Rename class take a default input as a parameter and return whatever is in the input text field when the use r hits okay

- [x] Generally make the rename popup work the same as in the original game
- [x] After rename, update the character's NAME field (not handle), save the game, and update the level up gem and call show() on the current character in the party menu.

**Comment by tiagolr** [comment]
Ok its working, just a note:

* Unlike in legacy version, Input accepts lowercase characters, currently the name is capitalized at the end (eg: azZrRa is turned to Azzrra). Same happens in the recruit screen.

**Comment by larsiusprime** [comment]
that's fine for now
