### ISSUE TITLE
Bonus mission interface

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#545]
- [x] Track BonusProgress
  - This should be basically the same as the original game and is probably a straight port.
  - If bonus data is not being processed yet, you might have to port the synchBonusData() function from as3 version
  - let me know if you have questions here

----------

- [x] Make the "bonus" button appear on the overworld if any are available
- [x] Check bonus requirements for unlocked bonus missions

----------

- [x] Create Popup_BonusMissions that extends TDRPGPopup
- [x] Create a basic xml layout for it,  ui/popup_bonus
    - Tall chrome backdrop
    - Close button at bottom
    - Blue star icon and text field next to it (to count # of blue stars earned)
    - Gold star icon and text field next to it (to count # of gold stars earned)
    - Title text at the top with loc flag "$UI_BONUS_BONUS_LEVELS"
    - Region object specifying the area below the title but above the stars/close button (where the rest of the interface will go)

----------

- [x] Create UI_BonusLine class, extends FlxUIGroup
   - Similar to one from legacy, but make it pass in the six individual elements it needs, perhaps in an object struct "{thing:thing,stuff:stuff}"
    - The five elements are: title text, button, button_disable, star_gold, star_blue, star text
    - (Passing in the elements like this lets us control the layout / styling in xml later)
    - UI_BonusLine will assume that the elements are already positioned correctly relative to one another
     - UI_BonusLine will have these functions/setters:
         - title (change the title text)
         - locked (show regular button or locked button, change text color between white or gray)
         - starColor (blue or gold, update the star accordingly)
         - numStars (number of stars needed to unlock, update the star text accordingly)
      - Clicking on the unlocked button will send an event to Popup_BonusMissions to open the map preview for that bonus level

----------

- [ ] Add a new mode to Popup_MapPreview to preview bonus levels
    - Same as before, but don't show "select challenge"
    - Show a rewards interface:
       - Rewards title
       - Record line for endless battles
       - object (class UI_BonusRewardLine) to display each reward tier
          - pass/perfect for normal levels
          - reach wave X, reach wave Y for endless levels
          - Two pieces of text and an icon (pass in the constructor)
             - Title: "Reach wave 35",  "PASS", "PERFECT", etc
             - Reward itself: "2000 XP", "Light of Judgment"
             - If reward is an item, display icon to the left of the reward text
          - Functions should allow you to change the title, reward, and icon, and lock/unlock (show text grey or white).

**Comment by tiagolr** [comment]
Hey, I think i could use some advice here, basically Popup_MapPreview depends on a PearlData object to set its UI components and start the level once user clicks to start.

While i can show the MapPreview without the pearl data, bypassing setups and showing/hiding different UI elements, I'm not sure how can i start a new level without a pearlData object or how can i fill some UI elements like : Waves, Enemy levels, and Types.

Any tips on how to start the level and fill those data fields without the pearlData object are appreciated, thanks.

**Comment by larsiusprime** [comment]
Just sent you an email!
