### ISSUE TITLE
Ketta Boost causes her to no longer attack at all

### ISSUE THREAD

**Issue by Marakk** [larsiusprime/tdrpg-bugs#552]
Windows 7
Download
Defender's Quest 1 HD Demo
Version # 0.2.6

Steps to reproduce:

1. Summon Ketta (or a generic Ranger) - one who has learned Rapid Shot but does not yet have Spread Shot.  Obviously, this was happening to me at character levels 5-9.
2. Boost her to Level 3.
3. Set her Targeting Options to "Target Strongest" and "Cheapest".
4. Now Boost her to Level 4.
5. Ketta/Ranger no longer attacks at all.  Changing targeting options doesn't help.  You have to Recall her and re-Summon her in order to get her attacking again.
6. This seems to be an issue on any battle, but I was able to get her to "freeze up" every single time by doing steps 1 thru 4 on the "Old Friends, New Enemies" battle for this report.

**Comment by ManDude** [comment]
Step 2 and 3 are unnecessary.

**Comment by larsiusprime** [comment]
This should be fixed in the latest version (0.3.1). Please re-open if it persists.
