### ISSUE TITLE
Options menu in battle is non-functional

### ISSUE THREAD

**Issue by Marakk** [larsiusprime/tdrpg-bugs#554]
Windows 7
Download
DQ1 HD Beta
Version # 0.2.6

Steps to reproduce:

1. Start any battle.
2. Click on the green Options button in the lower-right corner of the screen.
3. Nothing happens.
4. This means you can't abort a battle short of cranking the speed up and dying, and simply restarting the battle is impossible.
5. Semi-related: there used to be a hotkey to open the menu - default was Escape.  Escape is now set as the default for "Back" (read: cancel selection) and there is no hotkey to open the Options Menu, nor is there an option in the Controls Menu to set one.  As someone who is used to hitting Escape-Click on Restart Battle when trying to do Advanced/Extreme battles when underleveled, this is very frustrating.

**Comment by larsiusprime** [comment]
This is fixed, I'll open 5 as a new issue.
