### ISSUE TITLE
Healer skill Ether Flash causes battles to momentarily pause upon cast

### ISSUE THREAD

**Issue by Marakk** [larsiusprime/tdrpg-bugs#555]
Windows 7
Download
DQ1 HD Beta
Version # 0.2.6

Steps to reproduce:

1. Summon a Healer that has learned Ether Flash
2. Boost him to Level 2.
3. Wait for enemies to get within range.
4. Chug, chug, chug.  The game literally hiccups for a split-second whenever Ether Flash is cast - everything on-screen pauses as the animation first starts to play, then the battle proceeds as normal until the next Ether Flash cast/hiccup.
5. Seems to get worse on higher speeds - 16x was acting like 8x until I recalled my Healer, due to the constant stream of cast/hiccups at that speed.
6. Disclaimer - may be related to playing on an underpowered, 3-year-old laptop, but otherwise the game runs at a steady 50-55 FPS, even at 8x and 16x battle speed, even with a screen full of Ranger Arrows and Berserker swords a-swinging.  Only Ether Flash gives it any problems.

**Comment by larsiusprime** [comment]
I think I have fixed this now in more recent builds. I'm closing for now, but feel free to re-open if it's still present after tonight's builds.
