### ISSUE TITLE
Music looping

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#556]
battle.mp3/ogg has some looping issues. The file has silence at the start and at the end (I have fixed it locally myself).

**Comment by larsiusprime** [comment]
Thanks, I'll look into this :)

**Comment by larsiusprime** [comment]
The mp3 version cannot be fixed, but the ogg version can. It should be fixed in version 0.3.3+ (the cpp build uses ogg, so that's all we should have to worry about).

**Comment by larsiusprime** [comment]
Fixed for me. 

Please check version 0.3.3 when it goes up and let me know if it's fixed for you.
