### ISSUE TITLE
Clicks on weapon/armor equip bleed through to Skills

### ISSUE THREAD

**Issue by camperdarB** [larsiusprime/tdrpg-bugs#558]
Operating System: Windows 7 Home Premium SP1
Browser/Download: Download
Demo/Full?      : Demo Version
Version #       : 0.2.7
Optional Info : 1920x1080 Full Screen Resolution

Steps to Reproduce:

1 - Enter party menu.
2 - Select character with unassigned skill points.
3 - Click weapon or armor slot to bring up equip menu.
4 - Click on a weapon or armor with mouse hovering over position where a selectable skill icon was before changing to equip menu.

Expected: Equips new weapon/armor.
Actual: Equips new weapon/armor *AND* assigns skill point to the skill at mouse cursor position as if the skill pane was in front.

**Comment by larsiusprime** [comment]
Should be fixed in next version. Please re-open this issue if it recurs.
