### ISSUE TITLE
Best Chance (%) target selections exits with 'Null Object Reference'

### ISSUE THREAD

**Issue by camperdarB** [larsiusprime/tdrpg-bugs#562]
Operating System: Windows 7 Home Premium SP1

Browser/Download: Download

Demo/Full?      : Demo Version

Version #       : 0.3.0a

Optional Info : 1920x1080 Full Screen Resolution

Steps to Reproduce:

1 - Summon any hero.

2 - Change target method to Best Chance (%).

3 - Wait.

Expected: Battle proceeds.

Actual: After an amount of time game exits to dialog box "Error: Null Object Reference". Have not been able to deduce exact timing of exit, some battle condition interacting the Best Chance logic causes it sometimes within seconds, sometime after several waves.

**Comment by larsiusprime** [comment]
But you can confirm that if you don't select that targeting method, it never crashes? If you run the game from the command line, do you get any stack trace output?

**Comment by camperdarB** [comment]
Yes, battles run fine without choosing that target method. First 
discovered this crash when attempting the Ozimal fight on Expert to 
force rangers to choose him instead of armored skels.  Afterwards tried 
it on all maps, could not complete any map with either berserkers or 
rangers with Best Chance chosen.

Command-line output on Null Reference exit:
C:\Games\DefendersQuestHD_Demo_0_3_0a>Called from ApplicationMain::main 
ApplicationMain.hx line 155
Called from ApplicationMain::create ApplicationMain.hx line 67Called 
from lime.app.Application::exec lime/app/Application.hx line 221
Called from lime._backend.native.NativeApplication::exec 
lime/_backend/native/NativeApplication.hx line 129
Called from lime._backend.native.NativeApplication::handleRenderEvent 
lime/_backend/native/NativeApplication.hx line 346
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 750
Called from openfl.display.Stage::render openfl/display/Stage.hx line 649
Called from openfl.display.DisplayObjectContainer::__broadcast 
openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast 
openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent 
openfl/events/EventDispatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 546
Called from flixel.FlxGame::step flixel/FlxGame.hx line 704
Called from com.leveluplabs.tdrpg.Main::update 
com/leveluplabs/tdrpg/Main.hx line 1538
Called from flixel.FlxGame::update flixel/FlxGame.hx line 763
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 176
Called from com.leveluplabs.tdrpg.State_Battle::update 
com/leveluplabs/tdrpg/State_Battle.hx line 760
Called from com.leveluplabs.tdrpg.State_Battle::battleUpdate 
com/leveluplabs/tdrpg/State_Battle.hx line 873
Called from com.leveluplabs.tdrpg.BattleModel::update 
com/leveluplabs/tdrpg/BattleModel.hx line 902
Called from com.leveluplabs.tdrpg.BattleModel::doUpdate 
com/leveluplabs/tdrpg/BattleModel.hx line 1230
Called from com.leveluplabs.tdrpg.BattleModel::updateCollisions 
com/leveluplabs/tdrpg/BattleModel.hx line 1985
Called from com.leveluplabs.tdrpg.BattleModel::updateDefenderCollisions 
com/leveluplabs/tdrpg/BattleModel.hx line 2102
Called from com.leveluplabs.tdrpg.DefenderSprite::onOverlap 
com/leveluplabs/tdrpg/DefenderSprite.hx line 616
Called from com.leveluplabs.tdrpg.DefenderSprite::considerAttack 
com/leveluplabs/tdrpg/DefenderSprite.hx line 212
Called from com.leveluplabs.tdrpg.DefenderSprite::isBetterTarget 
com/leveluplabs/tdrpg/DefenderSprite.hx line 2008
Called from com.leveluplabs.tdrpg.DefenderSprite::isBetterTarget_chance 
com/leveluplabs/tdrpg/DefenderSprite.hx line 2264
AL lib: (EE) alc_cleanup: 1 device not closed

- Brad

**Comment by larsiusprime** [comment]
Okay I think I found the issue and put in a null check. When the next build goes up let me know if it happens again, and if so re-open this issue.
