### ISSUE TITLE
[DQHD] Crash on launch

### ISSUE THREAD

**Issue by ivanpu** [larsiusprime/tdrpg-bugs#563]
# Basic Info

```
Operating System: ArchLinux
Browser/Download: Download
Demo/Full?      : Demo Version
Version #       : DQ1
```

# Steps to Reproduce:
I've configured the game to run in fullscreen, changed controls to "Dvorak", played the game once until the river cross after prison break. Quit the game. Then opened it again.

# What I expected to Happen:
The game would launch, and I'll see the main menu screen.

# What happened instead:
The game crashed after the colorful intro/loading screen, with following output in the terminal:
```
Called from ApplicationMain::main ApplicationMain.hx line 155
Called from ApplicationMain::create ApplicationMain.hx line 67
Called from lime.app.Application::exec lime/app/Application.hx line 221
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 129
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 346
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 750
Called from openfl.display.Stage::render openfl/display/Stage.hx line 649
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 546
Called from flixel.FlxGame::step flixel/FlxGame.hx line 704
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx line 1538
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 639
Called from com.leveluplabs.tdrpg.State_Title::create com/leveluplabs/tdrpg/State_Title.hx line 61
Called from com.leveluplabs.tdrpg.TDRPGState::create com/leveluplabs/tdrpg/TDRPGState.hx line 68
Called from flixel.addons.ui.FlxUIState::create flixel/addons/ui/FlxUIState.hx line 190
Called from flixel.addons.ui.FlxUIState::loadUIFromData flixel/addons/ui/FlxUIState.hx line 369
Called from flixel.addons.ui.FlxUI::load flixel/addons/ui/FlxUI.hx line 819
Called from flixel.addons.ui.FlxUI::_loadSub flixel/addons/ui/FlxUI.hx line 897
Called from flixel.addons.ui.FlxUI::_loadThing flixel/addons/ui/FlxUI.hx line 1811
Called from flixel.addons.ui.FlxUI::_loadSprite flixel/addons/ui/FlxUI.hx line 4179
Called from flixel.addons.ui.FlxUISprite::new flixel/addons/ui/FlxUISprite.hx line 55
Called from flixel.FlxSprite::new flixel/FlxSprite.hx line 225
Called from flixel.addons.ui.FlxUISprite::loadGraphic flixel/addons/ui/FlxUISprite.hx line 126
Error : Null Object Reference
```

**Comment by larsiusprime** [comment]
a stack trace! Glorious!

Your configuration files will be stored... somewhere. Not sure where ARCH linux will dump them, but it's going to be ultimately generated by this call:

https://wiki.libsdl.org/SDL_GetPrefPath

```
SDL_GetPrefPath("LevelUpLabs", "DefendersQuest")
```

So.... if you find a folder like that, and delete the "config.xml" file you'll restore your settings to normal. Normally a button in the game takes you right there (the folder with a wrench in the save slot screen), but if you can't even launch the game that's no help.

**Comment by ivanpu** [comment]
Configurations... this word did cause me to think about something:

The workaround for #565:
The game does not crash now while I do launch it with secondary monitor disabled.
And the version is `DQ1`?

BTW, configurations directory is `~/.local/share/LevelUpLabs/DefendersQuest`.

**Comment by ivanpu** [comment]
Oh, forgot to mention, this:
> Normally a button in the game takes you right there (the folder with a wrench in the save slot screen)

Does not work for me.
There is a selection of Linux commands to open a folder, which one are you using?
Also... should this be moved to separate issue?

**Comment by larsiusprime** [comment]
Yes, probably should be it's own issue. Do you happen to know what such linux commands might be? I'm probably using the wrong one.

... Ha! the code says this:

```
public static function openOSWindow(path:String):Void {
	#if sys
	var command:String = "";
	#if windows
		command = "explorer";
	#elseif mac
		command = "open";
	#elseif linux
		//TODO: add a shell script, properly detect/switch between nautilus/dolphin/whatever for GNOME/KDE/ETC
	#end
	
	if (command != "") {
		var p:Process = new Process(command, [path]);
	}
	#end
}
```

So it's a no-op, no wonder it doesn't work.

**Comment by larsiusprime** [comment]
Okay, so seeing as the stack trace crashes on loading a sprite, I'm suspecting the root cause is a size 0x0 screen, this would cause it to create degenerate BitmapData's that would fail as soon as the first sprite tries to load. I can't confirm this quite yet, but I'll try to hook up my own linux build to a dual monitor setup and see if I can repro.

This one might take a little while to close.

**Comment by larsiusprime** [comment]
Is this still happening in 0.3.7?

**Comment by ivanpu** [comment]
0.3.7 works good :)

**Comment by larsiusprime** [comment]
Great :)
