### ISSUE TITLE
Ubuntu 15.04: Full Screen Results In Black Screen

### ISSUE THREAD

**Issue by ezacharyk** [larsiusprime/tdrpg-bugs#566]
Operating System: Ubuntu 15.04 64Bit
Browser/Download: Download
Demo/Full?      : Demo
Version #       : 0.3.0
Optional Info** : 9Gig RAM, GeForce GTX 660M video card (NVIDIA driver version 352.63 from nvidia-352 proprietary)

Steps To Reproduce:

1: Start Program.
2: Enter Options Menu.
3: Enter Video Settings.
4: Select Full Screen Option.

Game goes full screen but goes completely black. Mouse cursor is still visible and music still plays, but no graphics display.

**Comment by ezacharyk** [comment]
Also, I have two additional monitors connected to my laptop for a total of 3 screens. One connected via HDMI and one connected via VGA. 

Finally, it seems to only happen on my secondary screens and not my primary. However, the primary screen results in a very small (about quarter of the screen size, maybe smaller) video settings window with all resolution options no longer visible.

I noticed you have another one similar to this so I will let you decide what to do with mine.

**Comment by larsiusprime** [comment]
I'll treat this as a separate issue for now. What happens if you disable the other monitors and just use the one? Does the bug still happen?

**Comment by larsiusprime** [comment]
I believe this is now fixed, please verify:

Version 0.3.7 (fixed): 

https://drive.google.com/file/d/0B82nNNq_hucHZm1sZWpzRWdub2c/view?usp=sharing

Version 0.3.6 (before the fix, should be broken):

https://drive.google.com/file/d/0B82nNNq_hucHU0VXRkZUeEUwWDQ/view?usp=sharing

**Comment by larsiusprime** [comment]
Closing this out.
