### ISSUE TITLE
Cutscene back button remains on first slide

### ISSUE THREAD

**Issue by ezacharyk** [larsiusprime/tdrpg-bugs#567]
Operating System: Ubuntu 15.04 64Bit
Browser/Download: Download
Demo/Full? : Demo
Version # : 0.3.0
Optional Info** : 9Gig RAM, GeForce GTX 660M video card (NVIDIA driver version 352.63 from nvidia-352 proprietary)

Steps to reproduce:

1: Enter a cutscene.
2. Advance passed the first slide.
3: Click the back button until back on first slide.

Back button should disappear when on first slide, but remains.

**Comment by larsiusprime** [comment]
Should be fixed in 0.3.2.
