### ISSUE TITLE
Game Crashes in First Battle When selecting Berserker

### ISSUE THREAD

**Issue by ezacharyk** [larsiusprime/tdrpg-bugs#568]
Operating System: Ubuntu 15.04 64Bit
Browser/Download: Download
Demo/Full? : Demo
Version # : 0.3.0
Optional Info** : 9Gig RAM, GeForce GTX 660M video card (NVIDIA driver version 352.63 from nvidia-352 proprietary)

Steps To Reproduce:

1) Enter first battle.
2) Click through the tutorial until you can select the berserker.
3) Click the berserker's image to try to place him on the battlefield.
4) Game crashes.

Should be able to select and then place the berserker on the battlefield.

**Comment by larsiusprime** [comment]
I've had several reports of this. By any chance does it seem to be tied to a specific resolution and/or art mode? (HD Sprites vs Original Sprites).

Also, if you run the game from the command line, do you get any stack trace output?

**Comment by ezacharyk** [comment]
Looks like the game runs just fine with the original sprites. So the crash only happens with the HD sprites. I will test out resolutions.

**Comment by ezacharyk** [comment]
Running from command line gives me the following error when it crashes:

Floating point exception (core dumped)

That is the only output there.

**Comment by ezacharyk** [comment]
Running it at 4:3 800x600 the game works just fine. It crashed when running at 16:9 1600X900 and similar resolutions. However, it works with 720 and 1080 resolutions.

**Comment by larsiusprime** [comment]
Heh, so it only crashes on resolutions I don't happen to test very open. Of course.

**Comment by ezacharyk** [comment]
And only when using the HD sprites. The Original sprites work fine in those resolutions.

**Comment by larsiusprime** [comment]
Okay thanks gonna try and fix this now. Happens to lots of people should be easy to repro, hopefully.

**Comment by larsiusprime** [comment]
Hmmm, doesn't happen on:

- (Windows7+HD_Sprites+1600x900+DebugMode)
- (Windows7+HD_Sprites+1600x900+ReleaseMode)

This must really be a linux-specific bug. I'll boot up my Kubuntu machine and see what we get there.

**Comment by larsiusprime** [comment]
Okay, reproduced it on Kubuntu using your settings:

* (Kubuntu+HD_Sprites+1600x900+ReleaseMode)

I'm also noticing that a lot of UI elements appear jaggy/rough in Linux, but not in Windows. I'm guessing this is because the scaling is parking them at fractional x/y positions and the linux OpenGL renderer doesn't treat that the same way the Windows GL/ANGLE renderer does.

**Comment by larsiusprime** [comment]
WTF, doesn't happen in debug mode. Of course.

**Comment by larsiusprime** [comment]
Fixed it. I was using Std.int() to generate the size of a scaled bitmap in one place and Math.round() in another. (Std.int() is the equivalent of floor()).
