### ISSUE TITLE
#DQ1 cinematics don't fit the screen

### ISSUE THREAD

**Issue by Teovald** [larsiusprime/tdrpg-bugs#569]
### Basic Info

```
OsX
DQ0.3.0
windowed 1280x720 (changing the resolution does not help though)
MBP 2015
```
<img width="1440" alt="screen shot 2015-12-20 at 10 36 02" src="https://cloud.githubusercontent.com/assets/1502975/11917392/7e6501dc-a705-11e5-9355-6e3a0ec9331a.png">

The storyboards don't fit the screen.

**Comment by larsiusprime** [comment]
Do you happen to have a retina monitor or something?

**Comment by Teovald** [comment]
I don't have an external monitor connected, but the laptop's one is retina yes.

more exact model (apple suck at precisely naming its products) :  MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by larsiusprime** [comment]
On second thought, this might not be related to Retina support. 

I just uploaded a new Mac build, can you try again and tell me if the problems are persisting? And if so, can you post a screenshot of a scene with characters and a background image as well?

**Comment by Teovald** [comment]
here, I have just test 0.3.1, same behavior. I took a bunch of screenshots :

<img width="1440" alt="screen shot 2015-12-22 at 16 38 12" src="https://cloud.githubusercontent.com/assets/1502975/11958830/76d1b8d6-a8ca-11e5-8f44-6e24d4a35af4.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 38 14" src="https://cloud.githubusercontent.com/assets/1502975/11958828/76d0b706-a8ca-11e5-9e23-0a8f6f5b0e70.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 38 19" src="https://cloud.githubusercontent.com/assets/1502975/11958829/76d0d9e8-a8ca-11e5-90db-e7e55f569bd7.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 37 41" src="https://cloud.githubusercontent.com/assets/1502975/11958831/76d23ba8-a8ca-11e5-8502-8655cd5ed680.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 37 48" src="https://cloud.githubusercontent.com/assets/1502975/11958832/76d5582e-a8ca-11e5-9cc9-299387b5d0da.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 37 53" src="https://cloud.githubusercontent.com/assets/1502975/11958833/76d6c9c0-a8ca-11e5-9647-89036b074613.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 37 57" src="https://cloud.githubusercontent.com/assets/1502975/11958834/76e6ded2-a8ca-11e5-8b07-0d2be55c959c.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 38 00" src="https://cloud.githubusercontent.com/assets/1502975/11958836/76e7fd3a-a8ca-11e5-9081-76e4dc6dcfae.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 38 04" src="https://cloud.githubusercontent.com/assets/1502975/11958835/76e77f72-a8ca-11e5-8756-c2a9e78fc1c5.png">
<img width="1440" alt="screen shot 2015-12-22 at 16 38 08" src="https://cloud.githubusercontent.com/assets/1502975/11958837/76e8181a-a8ca-11e5-8206-50d1f2025c0e.png">

**Comment by larsiusprime** [comment]
Excellent work, so this very much is indeed a retina issue.

It's interesting how selective this problem seems to be. For instance, the background, and buttons are correct, but the UI chrome (off-screen), characters, speech bubbles, and text are not.  Looks like battles are correct, though.

Can you go into a town and tell me if the backgrounds there are behaving or not as well?

**Comment by larsiusprime** [comment]
Ah, think I might have found the problem.

In the cutscene screen, and only in the cutscene screen, the scaling values are calculated based on `Lib.current.stage.stageWidth/Height` whereas everywhere else in the game they're using `FlxG.width/height`, I bet you the former returns a different kind of value in retina mode than the latter.

**Comment by larsiusprime** [comment]
If I'm right, this will be fixed in 0.3.2, which I will post in about 20 minutes.

**Comment by larsiusprime** [comment]
Version 0.3.2 for mac, can you verify whether it's fixed?

https://drive.google.com/file/d/0B82nNNq_hucHNUtKTkZQR0tPYUU

**Comment by Phildo** [comment]
Mac OSX Yosemite (10.10.5) on 2012 Macbook Pro, Retina screen. Looks fixed here. :)

**Comment by larsiusprime** [comment]
Excellent. :D Either of you may feel free to re-open if it reoccurs, but I'm closing for now.

**Comment by Teovald** [comment]
fixed for me as well :)
I have been able to complete the 'preview' campaign without encountering another major bug.
