### ISSUE TITLE
"Open" command on Linux

### ISSUE THREAD

**Issue by ivanpu** [larsiusprime/tdrpg-bugs#574]
Continuing from #563 
>Yes, probably should be it's own issue. Do you happen to know what such linux commands might be?

One that I'll recommend is [xdg-open](http://linux.die.net/man/1/xdg-open).

From [ArchLinux Wiki](https://wiki.archlinux.org/index.php/Xdg-open):
> **xdg-open** is a desktop-independent tool for configuring the default applications of a user. Many applications invoke the xdg-open command internally.
>
Inside a desktop environment (like GNOME, KDE, or Xfce), xdg-open simply passes the arguments to those desktop environment's file-opener application (eg. gvfs-open, kde-open, or exo-open). which means that the associations are left up to the desktop environment.
>
When no desktop environment is detected (for example when one runs a standalone window manager like eg. Openbox), xdg-open will use its own configuration files.

But in any case, you can create an array with common "open" commands, and check at runtime which is present on the system.

**Comment by larsiusprime** [comment]
This works for me and should be fixed in 0.3.3+.  Please let me know what you see when that version goes up.
