### ISSUE TITLE
Archer kills enemy in melee range

### ISSUE THREAD

**Issue by erik-harrison** [larsiusprime/tdrpg-bugs#579]
#####BASIC INFORMATION:
```
Operating System: MAC OS X 10.11.2
Browser/Download: Download
Demo/Full?      : Demo
Version #       : 0.3.4
Optional Info : Using the HD demo downloaded via link in blogpost
```
#####STEPS TO REPRODUCE:
```
1. Level "return to the coliseum"
2. Difficulty to Normal
3. Place Ketta directly to the right of Azra
4. Place Slak right by the Red spawn point
5. Get the both boosted three times.
6: Some revenants from the next to the last wave will make it to Azra
7. Ketta will shoot some of these Revenant, inside her "donut hole"

Note: it's possible that Ketta is firing at the Death Worms that are spawning in the final wave. I've never quite been able to tell. It's possible this is a subtle "fire through occupied squares" effect that is supposed to happen, in what case, ignore this.

```

#####WHAT I EXPECTED TO HAPPEN:
```
I expected Ketta to be able to do nothing.
```

*Knowing what you were actually expecting to happen is much more helpful than only knowing what the error was.*

#####WHAT HAPPENED INSTEAD:
```
When I exited the first battle, the first and second levels were connected. 
When I exited the second battle, however, the second and third battles were NOT connected. 
I could still click on the third battle and move there, 
but there was no visual road connection. 
```

**Comment by erik-harrison** [comment]
Apologies for the weirdness in the bug report - I don't really speak markdown, my fault. 

Attached see screenshot which sorta demonstrates the issue. You can see the mark that the revenant in the square directly in front of Ketta has been hit, despite being in the donut hole.
<img width="800" alt="dq bug" src="https://cloud.githubusercontent.com/assets/7537154/12080490/d59fa252-b229-11e5-8814-c7409917cd87.png">

**Comment by ManDude** [comment]
It's definitely attacking the death worms. Rangers were programmed so that their arrows will damage any enemy regardless of where it is.

**Comment by larsiusprime** [comment]
I believe this is consistent with the original game -- Rangers can't *target* enemies that are too close to them, but they can hit them. 

I guess this needs to be checked against the original version of the game, and we'll match whatever that is doing.

**Comment by ManDude** [comment]
I can confirm that this is how it works in the original. :)

**Comment by larsiusprime** [comment]
In that case I'll close this, thanks ManDude! Also thanks erik-harrison for reporting this, even though it was a false positive I wasn't 100% sure myself that it wasn't a bug :)
