### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Lulero** [larsiusprime/tdrpg-bugs#583]
# Basic Information

Windows 7

Versions : 
- nightly build 0.3.5b15 (last of 2015)
- nightly build 0.3.6b20 on compatibility mode "windows 7"

Was in windowed mode, 800x600.

All default options but for experience penalties (-100% on failure, 0% for absence).

**Note :** Newer builds (from b16 to b20) don't work for me unless running them in compatibility mode. Except b16, this one always crash on startup. Find more details in the nightly builds forum thread.

# Step to reproduce (maybe)

1. Start the game
2. Play about 15-20 games, not skipping cut-scenes

# What I expected to happen

What you would expect from the game, sprites, background, the classic. Memory usage starts around 120Mb I wouldn't expect it to raise above 200Mb.

# What happened instead

With each movie and/or battle memory usage went up. After about 15 maps it reached 1.3Gb before starting having display issues during cut-scenes (sprites replaced with black boxes or being boxed in about 75% transparent ones).

![all in one](https://cloud.githubusercontent.com/assets/2311904/12160396/edd97ad6-b4eb-11e5-8ad3-80c68f5583e0.png)

**Note:** Lars, if you are wondering why people are not adding labels to their reports, seems that at least I can't do it. Seems you need to be a contributor for that and you are the only one.

**Comment by larsiusprime** [comment]
Okay I found the memory leak! It was an issue with transitions not destructing themselves properly, and thus keeping entire scenes in memory for the life of the game! 

This will be fixed in version 0.4.1

**Comment by larsiusprime** [comment]
Recently applied even more fixes. Should be plugged in 0.5.9
