### ISSUE TITLE
*Traveling to the hospital* crashes with HD sprites

### ISSUE THREAD

**Issue by Lulero** [larsiusprime/tdrpg-bugs#584]
# Basic Information

Windows 7

Versions : nightly build 0.3.6b20 on compatibility mode "windows 7"

Was in windowed mode, 800x600.

All default options but for experience penalties (-100% on failure, 0% for absence).

**Note :** Newer builds (from b16 to b20) don't work for me unless running them in compatibility mode. Except b16, this one always crash on startup. Find more details in the nightly builds forum thread.

# Step to reproduce

1. Start the game (HD sprites)
2. Reach *Traveling to the hospital* stage. Alternatively load a save that reach that far and turn dialogue to always show in options.
3. Start the battle.
4. Press *next*

# What I expected to happen

The usual.

# What happened instead

Following picture talks for itself:

![last issue](https://cloud.githubusercontent.com/assets/2311904/12160478/a42420f2-b4ec-11e5-8b30-490a1cc7dfd1.png)

**Note:** It's possible that's due to me experiencing heavily with the memory leak issue I reported as well. But it happens even when I close and restart the game, no matter the build (from b15 and up). I didn't try to reach that stage again with a fresh save to see the outcome.

**Comment by Lulero** [comment]
For the record, here's what happens with original sprites:

![traveling to the hospital - expected behavior 1](https://cloud.githubusercontent.com/assets/2311904/12160570/982941f0-b4ed-11e5-9265-6f048de68b41.png)
![traveling to the hospital - expected behavior 2](https://cloud.githubusercontent.com/assets/2311904/12160572/9ce64364-b4ed-11e5-99bd-a2a33704c01e.png)

**Comment by larsiusprime** [comment]
This should be fixed now in 0.4.2

**Comment by ManDude** [comment]
This isn't HD sprites. I think you mean original graphics.

**Comment by larsiusprime** [comment]
No he's right, the earlier screenshots are using hd graphics, and nothing appears at all (in that version). The original graphics he shows later have incorrect offsets, but they do at least work. So it's an additional bug + the original one.

In either case this should be fixed in 0.4.2, I'm closing for now -- feel free to re open if it manifests again post 0.4.2.
