### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#591]
(Sorry if I should've just re-opened an old issue.)

Instant crash as soon as I launch DefendersQuest.exe. Just downloaded the latest build (0.3.8 b30) and it's the first time I'm putting it on my computer. System specs (from the batch files):

CPU: AMD A4-6210 APU with AMD Radeon R3 Graphics
GPU: AMD Radeon(TM) R3 Graphics (driver version 15.201.1101.0)
RAM: 3603336 bytes
OS: Windows 10.0.10586
OS language is en-US.
Running DQ from the command prompt doesn't print out anything. I've also tried running it as administrator, no dice.

Also, unrelated, there is a map called "valley" that I don't think is ever used anywhere in the game. Huh?

**Comment by larsiusprime** [comment]
Let me try to reproduce.

And "valley" file can be deleted, I think it was once used for testing something a million years ago.

**Comment by larsiusprime** [comment]
Confirmed, I'm building correct stuff locally but the server has bad settings. Let me inspect / clean up. Can you test the next build the server produces?

**Comment by larsiusprime** [comment]
Okay, I just fixed some version control settings on the server, hopefully it will build clean stuff again. Can you check in about 30 mins?

**Comment by ManDude** [comment]
It works now.
