### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by Y30NN1** [larsiusprime/tdrpg-bugs#594]
Operating System: Windows 7 Ultimate
Browser/Download: Download
Demo/Full: Demo
Version #: 0.3.9
Windowed 1024x768, all other settings default.

Reproducing:
1. Start any map, on any difficulty. 
2. Set up one or more units. Select any random unit on the map.
3. Set speed to x8. 
4. Let Azra die. In the moment when she dies, click "upgrade" on the selected unit.
Espected result: Nothing.
Result: Crash with message "Null Object Reference"

Other info:
I was able to reproduce this repeatedly on any map, difficulty and using any units. However only on x8 speed. It might ofc be that there's some timing that has to be hit, that I could only manage on that speed.

Note: I suddenly realized that I habitually upgraded the unit once first; I can't remember if I tried this for the first upgrade. But it happened if I clicked the second and third upgrade in any case.

**Comment by larsiusprime** [comment]
Hmmm, this is strange, I've been trying to reproduce this but can't. Perhaps something else I did fixed it?

As specific as this bug is I'm going to leave it open until you have a chance to try tonight's build 0.4.2.
