### ISSUE TITLE
Crash when taking screenshot

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#597]
If I use the F1 shortcut to take a screenshot, the game will crash.

It won't crash if I'm at the start menu, however.

**Comment by larsiusprime** [comment]
Please clarify? Which screens cause crashes and which don't? And by start menu do you mean the Title screen, or the Save screen? And when it doesn't crash, does it also successfully take a screenshot, or not?

**Comment by ManDude** [comment]
I can save and take a screenshot in the title screen, but everywhere else it crashes right when I press F1 (also it asks you where you want to save the screenshot so it doesn't get to save anything when it crashes).

**Comment by larsiusprime** [comment]
Thanks, I think I know what's causing this.
