### ISSUE TITLE
Weird "new spell!" text

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#599]
Just got the lightning spell and the "Azra has learned a new spell!" text looks weird.
![dq2](https://cloud.githubusercontent.com/assets/7569514/12463375/1673ecd6-bfbb-11e5-8b22-b10a6d99fa1b.png)

800x600 - HD everything

**Comment by larsiusprime** [comment]
To be sure, your character's name is not in fact "Azzzzzzra" ?

**Comment by ManDude** [comment]
Oops yeah I named her Azzzzzzra so that everyone sounds like they're mentally ill (I'm a terrible person).

**Comment by larsiusprime** [comment]
I can't reproduce this on my machine (even with that name), so it might be an annoying driver issue, but I went ahead and put some rounding logic in there in case the text is on a non-integer position, that fixes it for people sometimes.

Let me know if it's still happening in version 0.4.2 when that goes up.
