### ISSUE TITLE
Fancy cursor is always the default cursor

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#601]
No matter what setting you choose, the Fancy cursor will always be the one selected until you load up a save file.
![dq4](https://cloud.githubusercontent.com/assets/7569514/12463488/aab16310-bfbb-11e5-8445-c890539b3caf.png)

(with default I don't mean the Windows one, I mean that it's the default setting)

**Comment by larsiusprime** [comment]
This should be fixed in 0.4.9

**Comment by IBwWG** [comment]
On 0.5.2 full, I saw that even with "Default" selected, sometimes (not just now when I checked, but I noticed it earlier...) in battles you get the fancy cursor, but on the map, the default.

**Comment by IBwWG** [comment]
Ah yes, it's fairly consistent (twice after failed battles now on 0.5.3, win7x64): the post-battle screen shows the fancy cursor.

**Comment by IBwWG** [comment]
Also consistent: if you click the Party button from the main map, it has the non-fancy cursor as it should.
