### ISSUE TITLE
"Lightning" spell doesn't scale up with Azra's attack stat

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#605]

**Comment by larsiusprime** [comment]
Does it do this in the original game?

**Comment by ManDude** [comment]
Nope. The original game has Lightning's damage go up with Azra's attack stat. Plus that would mean Lightning would get ridiculously weak rather early on in the game.

**Comment by larsiusprime** [comment]
Okay, I'll try and fix this

**Comment by larsiusprime** [comment]
Fixed in 0.4.2 -- there was logic for this, but it wasn't working properly. It's fixed now!
