### ISSUE TITLE
Achievement completion % overflow

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#606]
![dq7-1](https://cloud.githubusercontent.com/assets/7569514/12489055/648e7b1a-c066-11e5-8925-b5a553382c66.png)
![dq7-2](https://cloud.githubusercontent.com/assets/7569514/12489056/64911f14-c066-11e5-906a-e09484c99753.png)
![dq7-3](https://cloud.githubusercontent.com/assets/7569514/12489054/648cecaa-c066-11e5-8dcf-ef77eabbb16f.png)

800x600 - HD everything - 0.4.0 b2

**Comment by larsiusprime** [comment]
Can you send your save file?

**Comment by larsiusprime** [comment]
This looks fixed now.
