### ISSUE TITLE
Look into spawned enemy "jump" bug

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#629]

**Comment by ManDude** [comment]
Is this related to enemies like Mad Ghouls spawned from the Cultist enemies being spawned not where the Cultist actually was?

**Comment by larsiusprime** [comment]
Sure. Is that still happening?

**Comment by ManDude** [comment]
Yeah (easy to notice in the Eztli-Tenoch battle). Spawned enemies from Zelemir-targeting parent enemies also get confused and go towards Azra for a second (will make issue for this later).
