### ISSUE TITLE
Consistent Glow on Characters

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#630]
- [ ] Azra
  - outside: solid white, then yellow
  - [ ] cutscenes
  - [ ] portrait
- [ ] UnAzra
  - outside: solid white, then yellow
  - [ ] cutscenes
  - [ ] portrait
- [ ] Zelemir
  - outside: solid white, then yellow (red?)
- [ ] Cultists
  - outside: solid white, then red

**Comment by larsiusprime** [comment]
Who cares!

**Comment by ManDude** [comment]
Aww I thought they were nice effects. They could've probably been done manually to each image of a character in not much time using Photoshop really.
