### ISSUE TITLE
"Character" text in Controls is cut off

### ISSUE THREAD

**Issue by Gama11** [larsiusprime/tdrpg-bugs#647]
With 1704x960:

![](http://i.imgur.com/zBKU873.png)

Seems to be more noticable in fullscreen, and not an issue at all with smaller resolutions (e.g. 1152x648).

**Comment by larsiusprime** [comment]
Likely because I didn't specify a default width, which means it's using 100 pixels no matter the resolution...

Okay quick fix, one moment.

**Comment by larsiusprime** [comment]
Fixed. Next CI build should have it.
