### ISSUE TITLE
Some tutorial arrows are cut off

### ISSUE THREAD

**Issue by Gama11** [larsiusprime/tdrpg-bugs#648]
In the Coliseum level:

![](http://i.imgur.com/LMRNqdk.png)

![](http://i.imgur.com/ex8LnUw.png)

Potentially a duplicate of #596.

**Comment by ManDude** [comment]
#596 was a different issue.

**Comment by larsiusprime** [comment]
This bug is basically caused by there not being enough buffer space in flixel-shapes to deal with the effects of rotation.

**Comment by larsiusprime** [comment]
It still happens but Meh. I have bigger fish to fry.
