### ISSUE TITLE
"RANGE" text looks bad

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#652]
![dq1](https://cloud.githubusercontent.com/assets/7569514/14176402/b648ebe8-f748-11e5-82d3-663f225ea3f5.png)
Only happens to this text box.

800x600 - HD everything.

**Comment by larsiusprime** [comment]
Attempted fix for this in the next build, just trying to round everything in tooltips.

Let me know if it's fixed in the next build?
