### ISSUE TITLE
Ability names cut off at the bottom

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#653]
![dq2-1](https://cloud.githubusercontent.com/assets/7569514/14176424/cbfcea84-f748-11e5-9b9b-2c790217fd2e.png)
![dq2-2](https://cloud.githubusercontent.com/assets/7569514/14176516/4741930c-f749-11e5-8dd6-6f5a5e3789f5.png)
Happens to all abilities (didn't check traits).

800x600 - HD everything.

**Comment by larsiusprime** [comment]
Can you still reproduce this in the latest builds?

**Comment by ManDude** [comment]
Tested on the 3 lowest resolutions and it seems fixed.
