### ISSUE TITLE
Typo in Journal entry.

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#654]
![dq3](https://cloud.githubusercontent.com/assets/7569514/14176442/e2bdfefc-f748-11e5-85b2-8d2931bbd052.png)

800x600 - HD everything.

**Comment by larsiusprime** [comment]
I checked the source text and it looks like this isn't actually a typo -- the text rendering is just drawing it wrong. I've switched the continuous integration to use my fork of OpenFL which includes a patch to text rendering, can you check if the next build sorts this issue out?
