### ISSUE TITLE
Azra cutscene sprite issue

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#655]
![dq4-1](https://cloud.githubusercontent.com/assets/7569514/14176453/f4f045b2-f748-11e5-8ff3-b8c94bb35da0.png)
![dq4-2](https://cloud.githubusercontent.com/assets/7569514/14176455/f80e1b5c-f748-11e5-9f2d-1b6824712b04.png)
Azra cutscene sprite moves a bit between the first and 2nd screenshots.

800x600 - HD everything.

**Comment by larsiusprime** [comment]
Will be fixed in 0.5.2
