### ISSUE TITLE
Important tile blocked off in 1366x786

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#656]
![dq5](https://cloud.githubusercontent.com/assets/7569514/14176481/1b2d436a-f749-11e5-9275-266eda03737f.png)
The tile marked in the red box is blocked off by nothing at 1366x786, rendering it useless since you can't place a defender there. The image was taken at 800x600 since F1 doesn't seem to be working.

**Comment by larsiusprime** [comment]
Whoa, what a weird bug. Great catch!

**Comment by larsiusprime** [comment]
Okay, fixed. It was miscalculating the location of Azra's crater (which normal defenders can't stand on), ONLY in this resolution, likely because of a weird rounding error. I fixed up the logic and now it works.

Fixed in 0.4.7+
