### ISSUE TITLE
Hilight typo

### ISSUE THREAD

**Issue by nospoone** [larsiusprime/tdrpg-bugs#662]
# Basic Info
```
OS: Windows 10 (TH2)
Version: 0.4.5-1-g7f78dd9 - demo, build 1
```
Fullscreen at 2560x1440

# Steps to Reproduce:

1. Open the Video Options

# Happened
Highlight is spelled as _Hilight_

# Expected
Highlight to be spelled as _Highlight_

![image](https://cloud.githubusercontent.com/assets/708588/14321530/961db0a8-fbe7-11e5-9a6d-f4241b84ff24.png)

**Comment by ManDude** [comment]
That's not necessarily a typo. Just a different way to write highlight. (High is usually typed just Hi when you want to save space or whatever).

**Comment by nospoone** [comment]
You're right. It just seemed out of place for me!

**Comment by larsiusprime** [comment]
No problem. Better to have too many reports than too few. Gonna close this for now :)
