### ISSUE TITLE
Frenzy skill bonus text highlight misplaced

### ISSUE THREAD

**Issue by nospoone** [larsiusprime/tdrpg-bugs#663]
# Basic Info
```
OS: Windows 10 (TH2)
Version: 0.4.5-1-g7f78dd9 - demo, build 1
```
**Windowed** at `1600x1200`
**Fullscreen** at `2560x1440`

# Steps to Reproduce:

1. Start a new game
2. Level up until you can get Frenzy
3. Try to put a skill point in Frenzy

# Happened
The bonus highlighting for Frenzy is offset by some pixels. This isn't a problem at 800x600, but as you increase the resolution, the "offset" becomes larger.

![image](https://cloud.githubusercontent.com/assets/708588/14321704/4ac6aa32-fbe8-11e5-9208-771ed829e9e9.png)

# Expected
The correct characters to be highlighted

**Comment by larsiusprime** [comment]
This is an artifact of using the wrong openfl branch, if I use the larsiusprime/openfl fork with the "allfixes" branch then that has a patch that resolves this. Will use that from now on in CI.

**Comment by larsiusprime** [comment]
This should be fixed now
