### ISSUE TITLE
Perfect! label typo

### ISSUE THREAD

**Issue by nospoone** [larsiusprime/tdrpg-bugs#664]
# Basic Info
```
OS: Windows 10 (TH2)
Version: 0.4.5-1-g7f78dd9 - demo, build 1
```
**Windowed** at `1600x1200`

# Steps to Reproduce:

1. Start a New Game
2. Complete a Perfect battle

# Happened
The "Perfect!" label has a + after the !
![image](https://cloud.githubusercontent.com/assets/708588/14322003/5e99f0cc-fbe9-11e5-8b19-8ad016266bca.png)

# Expected
Not having a + after the ! (?)

**Comment by larsiusprime** [comment]
Ah, strange. The "+" should only appear in the final battle under certain conditions, apparently it's leaking into the regular game. Does it appear in the after-battle rewards screen too, or not?

Also -- noticing some artifacting in that text. Is it just in this popup or does it appear elsewhere too?

**Comment by nospoone** [comment]
It does appear everywhere, and the artifacting is everywhere, either in windowed at 1600x1200 or fullscreen at 2560x1440.

**Comment by larsiusprime** [comment]
Does the artifacting appear in 1080p ?

Are you running this exclusively in super hi res modes? IE, > 1080p? I don't have such a monitor so I'm impressed it actually works :P

**Comment by nospoone** [comment]
I am, yes. I'll report a different issue for artifacting!

**Comment by larsiusprime** [comment]
Fixed in the next CI build.
