### ISSUE TITLE
High resolution causes artifacting

### ISSUE THREAD

**Issue by nospoone** [larsiusprime/tdrpg-bugs#666]
# Basic Info
```
OS: Windows 10 (TH2)
Version: 0.4.5-1-g7f78dd9 - demo, build 1
```
**Windowed** / **4:3** at `1600x1200` (and I assume higher)
**Windowed** / **16:9** at `1920x1200` and higher (until `2560x1440`, and I assume higher)

# Steps to Reproduce:

1. Open the Video options
2. Set a resolution of `1600x1200` or higher for **4:3** or 1920x1200 or higher for **16:9**.

# Happened
Artifacts appear on all graphics.

![image](https://cloud.githubusercontent.com/assets/708588/14322306/53a42344-fbea-11e5-9fb2-564924b4f45e.png)

# Expected
Clean lines! :smile:

**Comment by larsiusprime** [comment]
So from what I can tell the game caps out a max resolution at 1080p and then scales up the canvas from there, probably using something like bilinear filtering, which obviously isn't sufficient.

I'll up the theoretical maximum to 1200p, because that's as high as the assets themselves can natively tolerate, and that fixes that use case. It will continue to scale up from there, and I'll try some other filtering setting.

**Comment by larsiusprime** [comment]
Okay, from what I can tell the best way to deal with this is to get a FXAA shader implementation and apply that to camera if we're scaling up. Unfortunately I'm too stupid to write that myself so I'm gonna have to find someone in the community to help me. Hoping @mrcdk will be interested

**Comment by larsiusprime** [comment]
Okay @nospoone I'm trying something out -- when the resolution is higher than 1200, it applies an Hq2x upscaling filter to smooth things out (FXAA had artifacts).

I'm not sure if this will do the trick or not, but if you could check in builds version 0.4.8+, to see how it looks. If it's too blurry, I can try another filter. If the filtering does not remove the artifacts at all, however, then I might need to try an entirely different method.

To enable the effect, simple use graphics in HD mode and set resolution to something higher than 1200 vertical pixels.

**Comment by larsiusprime** [comment]
0.6.0 will have a potential fix for this. Let me know what you think!
