### ISSUE TITLE
More navigation options for the dialogue and menus

### ISSUE THREAD

**Issue by sruloart** [larsiusprime/tdrpg-bugs#667]
- Add an option to move the dialogue right (`next`) and left (`previous`) with:
  - The arrow keys.
  - The mouse wheel.
  - Gamepads may require additional thought.
- Related: Add more options to advance the menus in general (`accept`, but `next` is similar) except for the `Enter` key, `Space` for example.
- Add more options to exit the menu (`close`, `back`). `Escape` (for anything not in-game) comes to mind.
- Maybe consider auto-advancing the dialogue (as an option) based on a formula of some sort (the amount of words per second? I dunno).
- A more advanced scrolling option would be an actual (tiny) scrollbar (beneath the dialogue box and between the buttons) with some numbers to tell you where you're at (`13/16` for example).

**Comment by daveschaefer** [comment]
+1 vote to make `Esc` / Escape close menu keys. some repro steps below if that helps. I can file that as a separate bug if that makes any difference. And see also #1275 for other UI requests.

Repro steps:

- Launch the game on any computer
- At the main menu click 'Options'
- Click any menu option, such as 'Audio'
- Notice that pressing the Esc (escape) key does not close the window; you must click the Cancel button

Game version: Universal DQ1 2.2.1c c
