### ISSUE TITLE
Linux 64 segfault

### ISSUE THREAD

**Issue by ibilon** [larsiusprime/tdrpg-bugs#668]
Hi,

I get a segfault at startup when running "Defender's Quest I (0.4.5-1-g7f78dd9 - full, build 1) (Linux 64-bit)" (latest right now)

here's the backtrack I got from gdb:
```
#0  0x00000000017a8162 in free_root ()
#1  0x00007ffff5f94768 in lime::lime_audio_load(_value*) () from ./lime.ndll
#2  0x000000000093c5ab in lime::audio::AudioBuffer_obj::fromBytes(hx::ObjectPtr<haxe::io::Bytes_obj>) ()
#3  0x0000000001750e5f in DefaultAssetLibrary_obj::getAudioBuffer(String) ()
#4  0x00000000009cf202 in lime::Assets_obj::getAudioBuffer(String, hx::Null<bool>) ()
#5  0x0000000000728c02 in openfl::Assets_obj::getSound(String, hx::Null<bool>) ()
#6  0x0000000000b1ca0e in flixel::_system::FlxSplash_obj::create() ()
#7  0x00000000017726e4 in flixel::FlxGame_obj::switchState() ()
#8  0x000000000177584f in flixel::FlxGame_obj::create(Dynamic) ()
#9  0x0000000001770c71 in flixel::__FlxGame_objcreate(hx::Object*, Dynamic const&) ()
#10 0x00000000017f23ee in hx::CMemberFunction1::__run(Dynamic const&) ()
#11 0x00000000017a0cf5 in openfl::events::EventDispatcher_obj::__dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) ()
#12 0x000000000178fba8 in openfl::display::DisplayObject_obj::__dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) ()
#13 0x000000000179ed8c in openfl::events::EventDispatcher_obj::dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) ()
#14 0x000000000175c06e in DocumentClass_obj::__construct() ()
#15 0x000000000175c381 in DocumentClass_obj::__Create(Array<Dynamic>) ()
#16 0x00000000017e6ff8 in hx::Class_obj::ConstructArgs(Array<Dynamic>) ()
#17 0x00000000016fefa8 in Type_obj::createInstance(hx::ObjectPtr<hx::Class_obj>, hx::ObjectPtr<hx::ArrayBase>) ()
#18 0x00000000017a3f20 in ApplicationMain_obj::start() ()
#19 0x00000000017a4487 in ApplicationMain_obj::init() ()
#20 0x00000000017a4549 in __ApplicationMain_objinit() ()
#21 0x00000000017f2357 in hx::CStaticFunction0::__run() ()
#22 0x00000000009d1580 in lime::app::Event_Void_Void_obj::dispatch() ()
#23 0x00000000009505d9 in lime::app::Preloader_obj::start() ()
#24 0x00000000005cb500 in openfl::display::Preloader_obj::display_onComplete(hx::ObjectPtr<openfl::events::Event_obj>) ()
#25 0x00000000005caab0 in openfl::display::__Preloader_objdisplay_onComplete(hx::Object*, Dynamic const&) ()
#26 0x00000000017f23ee in hx::CMemberFunction1::__run(Dynamic const&) ()
#27 0x00000000017a0cf5 in openfl::events::EventDispatcher_obj::__dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) ()
#28 0x000000000178fba8 in openfl::display::DisplayObject_obj::__dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) ()
#29 0x000000000179ed8c in openfl::events::EventDispatcher_obj::dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) ()
#30 0x000000000170abd6 in NMEPreloader_obj::onLoaded() ()
#31 0x00000000005cb91b in openfl::display::Preloader_obj::start() ()
#32 0x000000000095052c in lime::app::Preloader_obj::create(Dynamic) ()
#33 0x00000000017a391c in ApplicationMain_obj::create() ()
#34 0x00000000004a9d42 in ApplicationMain_obj::main() ()
#35 0x00000000004aa4f9 in main ()
```

**Comment by ibilon** [comment]
Same thing with the 32bits build,
but in 32 I also get:
```
Could not find primitive lime_drop_event_manager_register__prime.
Could not find primitive lime_window_set_maximized__prime.
```

**Comment by larsiusprime** [comment]
Excellent, much thanks, I'll try to track these down.

On Thu, Apr 7, 2016 at 3:48 PM, Valentin Lemière <notifications@github.com>
wrote:

> Same thing with the 32bits build,
> but in 32 I also get:
>
> Could not find primitive lime_drop_event_manager_register__prime.
> Could not find primitive lime_window_set_maximized__prime.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/668#issuecomment-207081747>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ibilon** [comment]
I re-looked at the backtrace from the 32 bits version (btw same things on the demo) and I realized it was picking my own lime.ndll.

After removing lime from haxelib I get this in 32:
```
Called from cpp.Prime::_loadPrime /home/travis/haxe/std/cpp/Prime.hx line 38
Error : Could not load module lime@lime_font_get_ascender__prime
```
and no message just segfault on 64.

**Comment by larsiusprime** [comment]
Looks like an issue with openfl and cffi prime; I should double check
whether I'm using the dev version in my CI and whether they just introduced
that; in any case I can put out a debug build perhaps and see if it gives
more information.

On Thu, Apr 7, 2016 at 3:55 PM, Valentin Lemière <notifications@github.com>
wrote:

> I re-looked at the backtrace from the 32 bits version (btw same things on
> the demo) and I realized it was picking my own lime.ndll.
>
> After removing lime from haxelib I get this in 32:
>
> Called from cpp.Prime::_loadPrime /home/travis/haxe/std/cpp/Prime.hx line 38
> Error : Could not load module lime@lime_font_get_ascender__prime
>
> and no message just segfault on 64.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/668#issuecomment-207083861>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ibilon** [comment]
Updated lime dev and recompiled the ndll, after that (since the game picks it up) I got the original error on full,64.

With that on full,32 and demo,32 I managed to finish the first battle (didn't tested more).

**Comment by larsiusprime** [comment]
So 32 bit worked after you replaced the dll, but 64 bit did not?

**Comment by ibilon** [comment]
Seems I did it wrong, both worked after I copied the newer ndll.

Although I needed the Linux64 ndll even for the 32 bits version.
```
~/Downloads/Defender's Quest I (0.4.5-1-g7f78dd9 - full, build 1) (Linux 32-bit)> ldd DefendersQuest 
        linux-vdso.so.1 (0x00007ffcb0096000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f270be66000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f270bc5e000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f270b956000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f270b64e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f270b436000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f270b086000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f270c086000)
```

I'm not sure if the 32 bits executable really is 32 bits, but I'm also unsure that I successfully recompiled lime for 32.

**Comment by larsiusprime** [comment]
Okay, well, I'll run both binaries on my linux machine to test myself.

**Comment by larsiusprime** [comment]
After much testing we determined this was the result of your drivers, and seems specific to your machine in a way not easy for us to fix. Closing for now, let us know if you see more crashes.
