### ISSUE TITLE
Still crashing on mac

### ISSUE THREAD

**Issue by Arcanus73** [larsiusprime/tdrpg-bugs#670]
When I started the demo it immediately crashed. All important information is in the crash log, but I'll put some of the header info here.

Process:               DefendersQuest [15953]
Path:                  /Applications/Games/DefendersQuest.app/Contents/MacOS/DefendersQuest
Identifier:            com.leveluplabs.defq1
Version:               0.4.5-1-g7f78dd9 - demo, (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DefendersQuest [15953]
User ID:               501

Date/Time:             2016-04-10 16:27:13.615 -0400
OS Version:            Mac OS X 10.10.5 (14F1605)
Report Version:        11

[DefendersQuest_2016-04-10-162714_Arcanus73s-Computer.crash.zip](https://github.com/larsiusprime/tdrpg-bugs/files/211987/DefendersQuest_2016-04-10-162714_Arcanus73s-Computer.crash.zip)

**Comment by larsiusprime** [comment]
I believe I've fixed this crash in version 0.4.6, but that's apparently not on the servers yet. Thanks for the heads up while I try to fix that...
