### ISSUE TITLE
demo doesnt start under linux

### ISSUE THREAD

**Issue by farmboy0** [larsiusprime/tdrpg-bugs#673]
OS: Gentoo AMD64
Demo version 0.4.5-1-g7f78dd9 - demo, build 1

Start fails with error:
Called from sys.net.Host::__init__ /home/travis/haxe/std/cpp/_std/sys/net/Host.hx line 46
Called from cpp.Lib::load /home/travis/haxe/std/cpp/Lib.hx line 34
Error : Could not load module std@socket_init__0

Looking at the binary and its libraries one finds
* a 64 bit binary
* 32 bit dso libraries

Why not release 32 bit and 64 bit in one package.
No one uses 32bit anymore.

**Comment by larsiusprime** [comment]
Have you tried a more recent version from here?
https://drive.google.com/drive/folders/0B82nNNq_hucHOEV1eF9pQ1B1eXM

Version 0.5.0 should go up shortly and I think might fix this issue.

**Comment by farmboy0** [comment]
Works for (0.5.1 - demo, build 1) (Linux 64-bit).
Havent checked out the 32 bit build.

**Comment by larsiusprime** [comment]
Thanks, I'll close this for now, and we'll open a new issue if any linux builds are determined to not be working. I'll be sure to do more test passes personally as we approach launch.
