### ISSUE TITLE
crashes when changing resolution

### ISSUE THREAD

**Issue by cocoajam** [larsiusprime/tdrpg-bugs#675]
When changing to 1280 x 960 and then pressing cancel an error message appears. It reads " Error! Scale must be positive & > 0! (Scale was at 0)" followed by the entire program crashing.

**Comment by larsiusprime** [comment]
Thanks, i'll look into this. 

What kind of monitor are you using? Does it happen everytime? Does it matter what resolution you had before?

**Comment by cocoajam** [comment]
It has happened every time I have tried it, and one time I was on Min Res, and once I was one Max Res. I use a wide screen Dell monitor

**Comment by larsiusprime** [comment]
Cool, it's probably a general error that I might be able to reproduce pretty easily, but just to be sure -- What's your monitor's native resolution?

**Comment by cocoajam** [comment]
1920 x 1080

**Comment by larsiusprime** [comment]
I unfortunately can't reproduce this bug in the latest build. 

Some more questions:
- What version were you seeing the crash in? 
- Do you have sprite art set to HD sprites or original art sprites?

If it's not too much trouble, can you post another video showcasing this particular crash? That last one was very helpful.

**Comment by cocoajam** [comment]
Sprites are set to HD, so are the Cut Scenes, version is 0.2.6 and it is set to auto update.
[Uploading Res Crash.zip…]()

**Comment by cocoajam** [comment]
[Res Crash.zip](https://github.com/larsiusprime/tdrpg-bugs/files/224975/Res.Crash.zip)

**Comment by larsiusprime** [comment]
Oh wow version 0.2.6? I think we're up to around 0.4.9 now! Have you tried downloading the latest version? Is there an old link somewhere I need to update?

**Comment by ManDude** [comment]
Haha I knew this issue sounded familiar. This was posted long ago. ;)

**Comment by cocoajam** [comment]
Auto update just must not have worked. I opened up the file I already had from a while ago, not thinking I should go online for a new file. Downloaded the new one, and feel silly to say the least. no issues

**Comment by larsiusprime** [comment]
Ah, I haven't put an auto-update into these dev builds just yet :), I forgot that people using the old version would be used to that feature!
