### ISSUE TITLE
Launch crash error "Expected </data>" after updating from 0.4.5 to 0.4.8 on Win7x64

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#680]
I had been using the 0.4.5 from the blog, then updated to (0.4.8-6-g1df24eb - demo, build 1) (Windows).  I deleted the old version then launched the new one (didn't delete save data or anything, just the old program directory), and before the game initially finished loading, got:

![dq1hd-crash10](https://cloud.githubusercontent.com/assets/16719964/14646071/6bfe401e-0658-11e6-8983-7c3e1ca9ca8d.png)

Unfortunately it's quite reproducible for me.  ;)  Am I supposed to only use "-1" of the latest point release, or the sanity check release, or...?

**Comment by larsiusprime** [comment]
Okay so this is weird, can you grab your save data files from %appdata%/LevelUpLabs/DefendersQuest and post it here? That's clearly an xml parsing error.

**Comment by IBwWG** [comment]
Also happens on the previous day's "-5" build.

Sure, no prob:

[demo.zip](https://github.com/larsiusprime/tdrpg-bugs/files/226297/demo.zip)

**Comment by larsiusprime** [comment]
Okay, build 0.4.9, whenever it next churns through, should have this fixed. It should show up in a few hours I think.

**Comment by larsiusprime** [comment]
Thanks for catching this so quickly!

**Comment by IBwWG** [comment]
Cool!  No prob, more of a happenstance than a jumped-on-it situation.  Thanks likewise for fixing it so quickly!

**Comment by larsiusprime** [comment]
Yeah as it turns out this wasn't anything wrong with your data, it was a stupid typo I introduced in how it chops down the map index for the demo build, resulting in invalid XML. And of course I was only testing the full version locally.

Three cheers for beta testers and continuous integration!

**Comment by IBwWG** [comment]
Confirmed this is fixed in 0.5.1.  Thanks!
