### ISSUE TITLE
Ice mage class (and beyond) missing if going from HD demo exported save to non-HD full game

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#683]
Couldn't wait for 0.5.2 of the HD builds, so I fired up the full non-HD game (1.1.52, Win7x64, first time playing it) and tried moving my save over.  It loaded OK, except that the next battle had a tutorial character for the ice mage, but no ice mage class.  I completed a few more battles, still no new class.  In the next town, the recruit tab says "class is full" for the ice mage sub-tab, and the bottom of it shows all my bezerkers.

Is there some tweak to the save file I can make so I can play this way?  Or are the HD/non-HD versions meant to stay rather separate?

**Comment by IBwWG** [comment]
Ah, so that was just copying the file directly, because I hadn't noticed the import/export buttons.  I tried a proper export from the HD demo and import into the full non-HD, and it seems to hang at "Please Wait...".  I tried again from the command line, but it seems to return to prompt immediately upon starting the game, and there's no additional output at the time of Please Wait.

**Comment by IBwWG** [comment]
I tried beating the last demo battle again, and it didn't help.  The save file doesn't have anything different in the ice mage ("sorcerer", yes?) class than a new save file made only by the full game.

**Comment by IBwWG** [comment]
Thought I'd run ahead, and the Knight class exhibits the same thing.  The first battle with the knight, he's there with the name "$KNI" (I think the ice mage was "$MAG") and his class is missing, I still only have the original three.

**Comment by IBwWG** [comment]
I just noticed that on this non-working save, it's not just the classes that are missing, the cutscenes also don't trigger after a battle.

**Comment by larsiusprime** [comment]
Okay so a word of warning -- DQHD is forwards compatible with the original DQ legacy, but I don't think I can guarantee that it's backwards-compatible. I should probably add a patch to DQ legacy to signal this.

**Comment by IBwWG** [comment]
No worries for me personally, by now I've gone beyond the original save I was trying to transfer.  I just thought I should report it, because I had remembered reading on your blog something about how you were trying to make it as painless as possible for folks to buy/upgrade/whatever.

**Comment by larsiusprime** [comment]
Yeah it's something I'll look out for.

**Comment by larsiusprime** [comment]
- [ ] Verify DQDX demo --> DQDX full
- [ ] Verify DQlegacy demo --> DQDX full

**Comment by larsiusprime** [comment]
Okay something I don't quite understand here is how you could have Ice Mages go missing in the first place in the HD demo, because the demo is supposed to end before you even get there.

Anyways, 0.7.4 builds are going up in the next hour. These have an auto-import function, so you just load the full version and it will prompt you to import the demo save. Do you have the same issue?

**Comment by IBwWG** [comment]
Can't test just yet but just to clarify, I meant that, at the end of the demo, if you take the save and import it into the non-HD full version, when you play the next part of the game in the full version the ice mage class is missing.  I'm not sure if it would indicate a problem with the HD demo exporter or with the full non-HD version importer, or maybe both.

**Comment by larsiusprime** [comment]
Oh I see. Do you have any of these save files from the end of the demo you can share with me?

**Comment by IBwWG** [comment]
I'm pretty sure the file I had I uploaded on another issue somewhere here...trying to think of how to find it.

**Comment by IBwWG** [comment]
[export.zip](https://github.com/larsiusprime/tdrpg-bugs/files/290416/export.zip)
This I have around from Apr 24 when I opened the thread...hopefully it's the one?

**Comment by IBwWG** [comment]
The file from https://github.com/larsiusprime/tdrpg-bugs/issues/680 might help too...

**Comment by IBwWG** [comment]
I took this save file [SAVE_SLOT_1_DEMO.zip](https://github.com/larsiusprime/tdrpg-bugs/files/290422/SAVE_SLOT_1_DEMO.zip) and plunked it into 0.7.8 HD, played the current level on Normal, pressed F2 to beat it, played the next level, and she showed up as WRENNA in the battle tutorial, and I could place her on the map.

But with legacy 1.1.52, the same file, passed the current level on Normal, and then the next level looks like this:


![dq-legacy-imported-from-hd-demo](https://cloud.githubusercontent.com/assets/16719964/15664903/e5b8c09e-2707-11e6-8116-16ea991ceb6e.png)

You can see the $MAG and also the missing character class in the right-hand pane.
