### ISSUE TITLE
Tooltip stuck when switching characters and new character has a different class

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#685]
1.1.52, win7x64

0. pick a defender
1. mouse over a target strategy
2. press , or . (on dvorak layout...not sure what the equiv is on qwerty, but it cycles through all characters regardless of class) until you're on a character with a different class than the one you started
3. even if you move the mouse away...the old tooltip stays there, sometimes blocking target strategies so you can't see/select them

**Comment by larsiusprime** [comment]
I can't reproduce. Can you reproduce this in the latest builds?

**Comment by IBwWG** [comment]
![dq-legacy-tooltip](https://cloud.githubusercontent.com/assets/16719964/15664981/57485530-2708-11e6-8db5-7170bbaa6eb2.png)

This is (and was, in the OP...not sure if you noticed :) ) on 1.1.52 legacy...if you did mean legacy, where can I get a newer build to try out?  If not I'm not sure this happens on HD, I'll have to try.

**Comment by larsiusprime** [comment]
OH yeah we don't update legacy any more.
