### ISSUE TITLE
Dvorak layout has duplicate keys

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#686]
, and . for cycle defenders and for class selection.  Win7x64.

This is true in the original full 1.1.52 and build 0.5.2; however, in the original you notice it more because sometimes pressing . gives one effect, sometimes another.  I didn't notice any such behaviour while playing the demo.

**Comment by larsiusprime** [comment]
This should be fixed in 0.5.7 maybe, definitely in 0.5.8

**Comment by IBwWG** [comment]
I'll have to try the new default, because something interesting happened just now: I went to the options, dvorak was already loaded--with the old, conflicting default.  I clicked the cycle defender comma, and pressed a new non-conflict key (num+).  It then loaded all of qwerty except for my new num+.

**Comment by IBwWG** [comment]
BTW, I had gotten used to playing without these keys, so I only remembered to try them now, and...they don't seem to do anything (num-/num+).  In the old game this would select the next defender.
