### ISSUE TITLE
Settings lost upgrading to full HD build 0.5.2

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#687]
Shouldn't they import from the demo?  Win7x64.

**Comment by larsiusprime** [comment]
Yes they should, this isn't implemented yet.

The game should be doing the following:

- Look for save data from DQDX demo build, import settings/save prompt
- Look for save data from DQ legacy (demo and/or full build), import settings/save prompt

**Comment by IBwWG** [comment]
Ah, OK.  I thought this was already implemented for demo->full in the original, so I was surprised.  Guess you went for a full rewrite with the HD version, eh?  :)

**Comment by larsiusprime** [comment]
It's sort of a full rewrite. Most of the core business logic ported itself over semi-automatically, but anything touching File I/O and things like that had to be rewritten, and this falls under that rubric.

**Comment by larsiusprime** [comment]
- [ ] Accessibility settings
- [ ] Video / control settings

**Comment by larsiusprime** [comment]
Version 0.7.5 will prompt you to import your settings from the demo
