### ISSUE TITLE
Setting keyboard layout during battle doesn't change class selectors, causes crash

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#692]
Started a battle, went to options and changed to Dvorak from QWERTY.  In the battle, QWERTY is still showing for the classes, but AOEUID is showing for the defenders.  0.5.2 full on win7x64.

Also, then no keyboard shortcuts seem to work (whether qwerty or dvorak).

Finally, typing randomly in the main (letter/punct) area of the keyboard to see if anything would do anything, null object ref:

```
FlxUIButton name = movies_btn
FlxUIButton name = music_btn
FlxUIButton name = sfx_btn
FlxUIButton name = party_btn
FlxUIButton name = btn_journal
FlxUIButton name = btn_town
FlxUIButton name = tips_btn
FlxUIButton name = btn_battle
FlxUIButton name = exit_btn
FlxUIButton name = options_btn
FlxUIButton name = menu_btn
FlxUIButton name = bonus_btn
Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/Na
tiveApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_back
end/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 677
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/Di
splayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObje
ct.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDi
spatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 529
Called from flixel.FlxGame::step flixel/FlxGame.hx line 662
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx lin
e 1462
Called from flixel.FlxGame::update flixel/FlxGame.hx line 751
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 168
Called from com.leveluplabs.tdrpg.State_Battle::update com/leveluplabs/tdrpg/Sta
te_Battle.hx line 868
Called from com.leveluplabs.tdrpg.State_Battle::battleUpdate com/leveluplabs/tdr
pg/State_Battle.hx line 985
Called from com.leveluplabs.tdrpg.State_Battle::inputJunk com/leveluplabs/tdrpg/
State_Battle.hx line 1588
```

**Comment by larsiusprime** [comment]
Reproduced. This is a pretty obvious case of just not refreshing the hotkeys properly, both in the UI and in the game itself.

As for the crash you managed to hit, this one's pretty hilarious:

```Haxe
else if (FlxG.keys.pressed.C && FlxG.keys.pressed.R)
{
	//let's crash!
		
	trace("CRASH TIME!");
	var array = []; 
	var danger:Dynamic = array; 
	danger.zone ();
}
```

Man, how long has THAT been silently lurking in the code waiting to explode?

**Comment by larsiusprime** [comment]
Okay, this is interesting:

Start with QWERTY
Start battle
QWERTY works
Change to DVORAK
Doesn't work

Start with DVORAK
Start battle
DVORAK works
Change to QWERTY
Does work, but UI is messed up.

WTF?

**Comment by IBwWG** [comment]
I had a similar button testing out crashdumper in my game :P

**Comment by larsiusprime** [comment]
Okay -- conclusions.

- the not updating the buttons thing is purely visual
- the issue with dvorak not working after in-battle update is a collision between comma and period being defined for different actions. The checker short-circuits and only checks for one action, not both, b/c it assumes (correctly) that only one key can map to one action.

**Comment by larsiusprime** [comment]
BTW looks like 0.5.7 might have just successfully compiled on the server :D

**Comment by larsiusprime** [comment]
- [ ] Fix collisions in dvorak layout
- [ ] Update character class tab labels on hotkey change
- [ ] Update character button labels on hotkey change
- [ ] Figure out why space/pause isn't working for dvorak

**Comment by larsiusprime** [comment]
Okay this all seems to work now. 0.5.8.
