### ISSUE TITLE
Wave count out of sync...and battle ends early

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#693]
0.5.2 full HD on win7x64:

![dq-wave-count](https://cloud.githubusercontent.com/assets/16719964/14820909/ef7be854-0bc8-11e6-82b5-edaa4c3a8f0c.png)

Unfortunately, I'm not sure when this happened during the battle.  I only noticed it at the end.

**Comment by IBwWG** [comment]
I just had this happen (on 0.5.2 full) when there were still two waves in the queue, beating the ozimal's coat battle on extreme at 16x way too early:

![dq-wave-count2](https://cloud.githubusercontent.com/assets/16719964/14821782/505264e8-0bcc-11e6-8f57-ba4ea8ef6466.png)

**Comment by larsiusprime** [comment]
On the last one, did you kill Ozimal? If you kill him, it kills the rest of the waves. They're supposed to fade out and disappear, which might be confusing you here.

**Comment by IBwWG** [comment]
Ohh...that's possible.  I guess if you don't see him there, that's what I must've done.  However I think there's still an issue in the OP, no?  Unless that level has a similar mechanic.

**Comment by larsiusprime** [comment]
There's no boss in that level, but I can't see any enemies either. In any case, those wave blocks need to fade when Ozimal dies, so at least that needs to be fixed to close this.

**Comment by IBwWG** [comment]
In the Royal Records Room just now, I noticed as the screen faded out after the battle (which I won) that it still said wave 14/15.

**Comment by IBwWG** [comment]
[export-wave-count.zip](https://github.com/larsiusprime/tdrpg-bugs/files/244049/export-wave-count.zip)

**Comment by larsiusprime** [comment]
Okay this looks simply like a visual glitch. The fade-out rate of the waves is tied to the regular framerate rather than the accelerated x16 speed. So it's fading out but the pop up appears well before it's done fading.

Probably a similar effect applies to the wave counter.

**Comment by larsiusprime** [comment]
This is fixed in 0.6.5

**Comment by IBwWG** [comment]
0.8.4, win7x64, HD mode@1704x960windowed

On the second battle with Zelemir (where he says "Well fought, Azra" afterwards) just as it ended, I didn't have a chance to take a screenshot, but I had done it on Advanced in NG+, and the wave count said 14/12.  Only one wave or maybe two had come through, I really blitzed him.
