### ISSUE TITLE
0.5.2 full pretty laggy

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#694]
win7x64, 0.5.2 full.

I noticed this build feel quite laggy at the same resolution (just under 1920x1080) compared to the last build I was on (0.5.1) but it was also the demo instead of the full.  I'm not sure if that would contribute to it.  E.g. there were many moments during the battle when I had to press a key a second time, and press it a little longer than normal (B for boost, say) to get it to react.

Even the level up screen after the battle has a laggy cursor, and doesn't react to a quick click on the continue button.  I have to hold the mouse button down, although the screen following that is much more responsive again (when you get new gear from adv/extr).  Then when you go to equip, it's again quite slow.

**Comment by larsiusprime** [comment]
Does the FPS counter display a different measurable result? Or is it just
input lag?

On Tue, Apr 26, 2016 at 9:13 AM, IBwWG <notifications@github.com> wrote:

> I noticed this build feel quite laggy at the same resolution (just under
> 1920x1080) compared to the last build I was on (0.4.9 I think) but it was
> also the demo instead of the full. I'm not sure if that would contribute to
> it. E.g. there were many moments during the battle when I had to press a
> key a second time, and press it a little longer than normal (B for boost,
> say) to get it to react.
>
> Even the level up screen after the battle has a laggy cursor, and doesn't
> react to a quick click on the continue button. I have to hold the mouse
> button down.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/694>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
Hmm...not sure what it was on the demo.  Have to check...

**Comment by IBwWG** [comment]
On equip screen it's about 7-8 for the right-hand number, which I assume is an avg?

**Comment by IBwWG** [comment]
This lag is also when the battle is paused.

**Comment by larsiusprime** [comment]
Wow those are some pretty severe frame drops. If you use the original art mode for sprites instead of HD does it pick up? I hope CI hasn't been posting debug builds instead of full. If this is definitely a recent regression (or related to # of defenders on screen) then it's something I should seriously look into. I haven't done a memory leak sweep in a while.

Also does 0.5.3 fare any differently?

**Comment by IBwWG** [comment]
I'll give both a shot...

**Comment by IBwWG** [comment]
0.5.2 seemed not so bad just now...FPS similar but definitely more responsive.  Maybe there was some rogue background process on my computer, but I thought that's what all these separate cores they have nowadays were supposed to help with.

**Comment by IBwWG** [comment]
Also the later battle (which had it worse than the one I compared with the demo, and also had a lot more defenders), a lot better, 7 / 10.  Not perfectly responsive but not terrible.

**Comment by IBwWG** [comment]
0.5.3 seems more responsive.  Still a bit sticky under fire.  Will try without HD graphics next.

**Comment by larsiusprime** [comment]
I wonder if was simply all the crashes leaving zombie OpenAL process around? I've always wondered what that error is about...

**Comment by IBwWG** [comment]
Maybe, except I didn't restart since then...

**Comment by IBwWG** [comment]
IIRC, after a null reference error, while the error popup is still on screen, you don't get that AL line yet.  As soon as you OK it and the window disappears, you get the AL error.

**Comment by IBwWG** [comment]
Indeed, just checked.

**Comment by IBwWG** [comment]
Without HD graphics, 0.5.3 was a bit better, more like 7/11 for FPS.

**Comment by IBwWG** [comment]
Also, I noticed that the post-battle screen being laggy depends on how laggy the battle was.  For instance, first battle on a new game, 24/24 FPS, post-battle screen is quite smooth.  After a later battle with 7/13 FPS, post-battle is quite laggy too.  Is the battle still loaded in the background during the post-battle screen?

**Comment by IBwWG** [comment]
Also on 0.5.7 it's fairly slow (3/7), I even killed some other running apps so it's mainly DQ and explorer windows.

**Comment by IBwWG** [comment]
I just did a cold boot and without anything else running first, it was better, but still had some response lag to it.

**Comment by IBwWG** [comment]
With *just* this firefox window open with github, for instance, I'm showing 2/6 or 3/6 with the game paused, and having trouble boosting by pressing B.  But initially I had many things going on, even my own multi-hundred-meg haxeflixel game testing in the background, and it was still OK.  Maybe I just wasn't far enough along to have so many defenders?  It seems more related to that number than the number of attackers on screen.

**Comment by larsiusprime** [comment]
It's entirely possible we could be sucking down memory when the screen gets crowded. Could you run some quick tests for me, compare these situations:

|  Resolution  |  Sprite Mode  | # Heroes | # Generics | Result on pause | Result on 1x speed |
|---------------- | ----------------- | ------------ | --------------| -------------------- | ------------------------ |
| 1920x1080  | HD                  | 6              | 0               | (your FPS)         | (your FPS)              |
| 1920x1080  | HD                  | 0              | 6               | (your FPS)         | (your FPS)              |
| 1920x1080  | HD                  | 6              | 30             | (your FPS)         | (your FPS)              |
| 1920x1080  | original           | 6              | 0               | (your FPS)         | (your FPS)              |
| 1920x1080  | original           | 0              | 6               | (your FPS)         | (your FPS)              |
| 1920x1080  | original           | 6              | 30             | (your FPS)         | (your FPS)              |

(For 0 heroes, 6, generics, that means, 1 generic of each class.)

Obviously, more of everything can potentially make things slower, but I want to find the bottleneck. My hypothesis is that the slowdown only really occurs in HD sprite mode, and that it scales with the number of generic units.

**Comment by IBwWG** [comment]
OK, this is with FF running with one tab, and thunderbird, command prompt used to start dq, and dq.

For the record, before doing these tests, I was always running one under 1920x1080, in windowed mode, because otherwise I cannot use my second monitor thanks to graphics card bugs that intel & friends have made a low priority since like a decade ago.

So, this is 1920x1080 fullscreen, HD:

7/7 (although average went up while minimized: when I returned, it said 7 / 15) | 6-10 / 15
6-10 / 15 | same
5-8 / 14 | same

**Comment by larsiusprime** [comment]
Wow those are some pretty terrible framerates! So you're getting only 10 or less frames no matter how many defenders you've got milling around? How old is your computer?

**Comment by IBwWG** [comment]
It's a medium-low-end Dell, about 3 y.o.

```
SystemData
{
  OS : Windows 7 SP1
  RAM: 4098104 KB (3.91 GB)
  CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
  GPU: Intel(R) HD Graphics Family, driver v. 8.15.10.2361
}
```

**Comment by larsiusprime** [comment]
Hm, Intel graphics, eh. Well, I definitely want the game to perform well on specs like this. It shouldn't be a performance-intensive game. I'm gonna try to profile and see if there's any obvious rendering bottlenecks.

**Comment by IBwWG** [comment]
Cool, good to know.  BTW the post-battle screen is also quite laggy even on non-HD, windowed mode just now.

**Comment by IBwWG** [comment]
Oi.  On Unwelcome Guests on extreme just now, I had it just near the end (on 2X) slow down to 2 / 5, and then a couple times, it even froze altogether (temporarily) and the cursor changed to the windows 'loading' spinner.

**Comment by IBwWG** [comment]
Although, it may be a mem leak issue, this particular one with the loading cursor.  Azra survived unharmed but maybe not the game...it's taking 1.6 GB of ram and that seems to be the limit at least for haxeflixel games.

**Comment by larsiusprime** [comment]
The good news is, something this egregious should stick out on a profile

**Comment by IBwWG** [comment]
Cool.  Also just to note, I tried on 800x600, windowed mode, non-HD for both options just now and it's still laggy, even just on the Party screen (even straight from the map rather than post-battle), nothing else running.

**Comment by larsiusprime** [comment]
One memory leak found -- battles would clear out stashed references at the BEGINNING, but not at the END.

This means they were keeping a reference to any still existing enemies after the battle was finished. After a big battle this could be significant.

Now it clear at the end of the battle, too. Not sure how much that will help by itself, but it should be a decent chunk. Will be in 0.5.9, working on finding more...

**Comment by larsiusprime** [comment]
Added a few more memory leak checks. Things should definitely be better now, let me know what your results are. 

Caveat: anything above 1x speed is going to be running multiple ticks per update (ie, frame rates are expected to drop, *particularly* at 4x and 16x) so I'm mostly interested in framerates @ 1x speed.

**Comment by IBwWG** [comment]
On 0.6.0 the lag on the post-battle screen is still there, feels about the same.

**Comment by IBwWG** [comment]
0.6.0.win7x64, HD mode@1704x960windowed

Just tried a battle on extreme.  Mem got up to 1.5 GB, and then this happened (FPS, flixel logo):

![dq-slowdown-flixel](https://cloud.githubusercontent.com/assets/16719964/14975281/5b5cf3ba-1100-11e6-9abd-da312a2772c0.png)

This is the second time I've seen the flixel logo in-battle like this, but the first time I managed to get a screenshot of it.

**Comment by larsiusprime** [comment]
1.6 GB, definitely a memory leak. Well, once more into the breach, my friends. Something is gobbling up memory and not giving it back.

**Comment by larsiusprime** [comment]
Okay, I just did a *very* interesting test.

I tried this battle with and without "show AOE highlight" (or whatever it's called) turned on. When it's turned off, I couldn't get memory to climb to any significant degree, even in fullscreen + HD graphics @ x16. When I turned it on, however, memory slowly crept up throughout the whole battle. I'm guessing this is the culrpit -- I'm not properly disposing the pixels used to create those highlight effects.

I'm going to do another test and run it through HxcppObjectGraphViewer just to be sure.

**Comment by larsiusprime** [comment]
Oh wow, I may have found the cause.

So I use object pooling for a lot of things, but it looks like in the special case of Splash Effects I had decided to go back on that. They were originally pooled, but it looks like I had found out it was better in practice to just create fresh ones each time and destruct the old ones when they were used up. However, I was calling kill() and then removing them from the list, not destroy()! So... they were being created once, and then incompletely trashed, and fresh ones created afterwards. Kind of a worst-of-both-worlds situation between object pooling and just-make-new-instances-each-time.

Let me clean this up and see if it helps.

**Comment by larsiusprime** [comment]
Okay, think I've gotten it, or at least given it a good smacking.

So, with my latest changes to immediately and carefully destruct splash effects (the visuals that accompany an AOE attack, including the flashy sprites as well as the optional hilight), memory climb seems stable -- fluctuating between 400 and 500 MB without any upward trend. 

Before this change, I had your behavior mostly reproduced -- memory would climb up to at least 700 MB by the end of the battle.

This change will be in 0.6.1 and is important enough that I'm going to go ahead and push it right away.

**Comment by larsiusprime** [comment]
@IBwWG did it work?

**Comment by IBwWG** [comment]
Not sure...I may not have a chance to get to this right away.  Busy week prepping for a busy month.

**Comment by larsiusprime** [comment]
You've done more than enough already! :P Whenever you have time

**Comment by IBwWG** [comment]
This does seem better on 0.6.2, a more steady 7-9 FPS.  Post-battle lag is still there.

**Comment by larsiusprime** [comment]
I'm starting to wonder if your graphics card might be forcing the game to run in software mode.... I should put in some sort of notification if that's detected.

**Comment by IBwWG** [comment]
That might be handy...I have no idea.  It's windowed, doesn't that force software anyway?  I'm pretty ignorant on that topic.

Anyway just now at 11 FPS I found the controls still a bit unresponsive--I unpaused the game and then had to hit spacebar 4 times before it finally took the input and paused again.

**Comment by larsiusprime** [comment]
So, software rendering means no hardware acceleration -- windowed vs. fullscreen has nothing to do with it. I seem to recall a while back I threw in a safeguard to force software rendering if hardware support was not detected, because I figure having the game run slow is better than having it not run at all. But, if you're among one of those "lucky" users it needs a notification to warn you that your computer basically sucks, and to maybe consider just playing the game in original art mode.

**Comment by IBwWG** [comment]
Ah, OK, I wasn't sure if you could have hardware accel in a window.

Computer basically sucking is quite a possibility here :)

**Comment by larsiusprime** [comment]
Still, I like to be able to support low end machines. If you are in software mode, there's very little that can be done beyond notifying the user. If you ARE hardware accelerated and we still have crappy FPS, then we have a serious problem that's very likely my fault.

**Comment by larsiusprime** [comment]
Yup, here we go, it's in flixel's initialization code:

```Haxe
	private static function initRenderMethod():Void
	{
		renderMethod = BLITTING;
		
		#if (!lime_legacy && !flash)
			if (!Lib.application.config.windows[0].hardware)
			{
				renderMethod = BLITTING;
			}
			else
			{
				renderMethod = switch (stage.window.renderer.type)
				{
					case OPENGL, CONSOLE:      DRAW_TILES;
					case CANVAS, FLASH, CAIRO: BLITTING;
					default:                   BLITTING;
				}
			}
		#else
			#if web
				renderMethod = BLITTING;
			#else
				renderMethod = DRAW_TILES;
			#end
		#end
		
		renderBlit = renderMethod == BLITTING;
		renderTile = renderMethod == DRAW_TILES;
		
		FlxObject.defaultPixelPerfectPosition = renderBlit;
	}
```

Okay, let me rig up a test + prompt.

**Comment by larsiusprime** [comment]
0.6.6 will include a startup prompt that will tell you if you're running software mode or not.

**Comment by IBwWG** [comment]
On 0.6.6 I didn't get a prompt...

**Comment by IBwWG** [comment]
Also on 0.7.8 I didn't get a startup prompt.

Running fullscreen 1920x1080 the post-battle screen still is very laggy re: the cursor and the fade.

**Comment by IBwWG** [comment]
0.7.8, win7x64, HD mode@1704x960windowed

![dq-lag](https://cloud.githubusercontent.com/assets/16719964/15678340/49453106-274e-11e6-88c6-1171c5ddb066.png)

At this point the game appeared to freeze: the windows "waiting" cursor came up, and it was maybe 10-15 seconds before it unfroze.  By then I had the task manager open, and saw the cpu was pegged, but the memory was at 1.2 GB.  When it unfroze it was suddenly down to 1.0 GB.

**Comment by IBwWG** [comment]
A little bit later (paused a long time, just resumed now, and after a few seconds: ) again it was at 1.2 GB with the waiting cursor and frozen game.  Again after about 15 seconds it went to 1.0 GB and resumed.

**Comment by IBwWG** [comment]
![dq-lag2](https://cloud.githubusercontent.com/assets/16719964/15691806/2b91a38c-278b-11e6-9620-27be80474581.png)

Happened 2 more times.  I'm not sure how it's managing to recover, but it will certainly take a long time to churn through the remaining 32 waves this way.  It runs for about 5 seconds between freezes.

**Comment by ManDude** [comment]
Is there any way to tune down the FPS? I don't have a beast PC but it can barely run the game at 30FPS, let alone 60.

**Comment by dqhol** [comment]
I wonderif it's the 60 FPS that makes the game lag like hell for me, or just my terrible computer. I always assumed my computer. DQOld lagged for me, a problem I could fix by just placing and selling a unit and not clicking any other units, but that no longer works here.

**Comment by larsiusprime** [comment]
What speed are you trying to play on? And what is the symptom you're getting, framedrops?

**Comment by ManDude** [comment]
It's just the overall game that runs slow. No framedrops or anything, just slowness. The game runs at about 1/3-1/2 speed at the 1x setting. The recent updates that reduce effects the higher the speed setting did help, too.

**Comment by IBwWG** [comment]
0.8.4, win7x64, HD mode@1704x960windowed

On that same Bonus 1 level in the screenshots, I just tried again and made it more or less smoothly through about 38 waves with the memory fluctuating between 1.0 and 1.4 GB, then the loading cursor came up, and it crashed.  So close!  :)

**Comment by dqhol** [comment]
Terrible slowness here too on any speed. No real framedrops.

**Comment by ManDude** [comment]
Will there be an option to tune the FPS down? I don't think the game was even made for 60FPS, so having a 30FPS on 60FPS just seems like a waste of resources. Of course, if this is not the case, an option to tune it down could be very handy too. :V

**Comment by larsiusprime** [comment]
What settings are you guys playing at? Fullscreen with HD graphics?

And yeah I can look into a "low framerate" option. If it doesn't try to
maintain 60 FPS I wonder if it will run faster. It's already supposed to
interactively drop frames if it has to though...

On Tue, Jun 7, 2016 at 8:49 PM, ManDude <notifications@github.com> wrote:

> Will there be an option to tune the FPS down? I don't think the game was
> even made for 60FPS, so having a 30FPS on 60FPS just seems like a waste of
> resources. Of course, if this is not the case, an option to tune it down
> could be very handy too. :V
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/694#issuecomment-224465157>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-FGNiatv_gdMqj2DeG4ITAdBpwFRks5qJh-rgaJpZM4IP_db>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
I'm playing at 800x600 in HD graphics. I also tested at normal graphics but the overworld was pretty laggy. Only the battles seem to run terribly. 1x speed feels like 1/4x speed.

**Comment by larsiusprime** [comment]
Hmmm, alright. I'll see what I can do. How do the battles feel in normal
graphics mode?

On Tue, Jun 7, 2016 at 9:32 PM, ManDude <notifications@github.com> wrote:

> I'm playing at 800x600 in HD graphics. I also tested at normal graphics
> but the overworld was pretty laggy. Only the battles seem to run terribly.
> 1x speed feels like 1/4x speed.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/694#issuecomment-224471305>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-BmMEtOQsa44PupowHvSpvQaBcYWks5qJim0gaJpZM4IP_db>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Still pretty laggy.

**Comment by ManDude** [comment]
The higher you set the battle speed, the more frames it starts to drop (obviously).

**Comment by joaociocca** [comment]
I dunno which version I'm running, but I think it's the first that came out on Steam. Last night I finally got my 201 gold star, so I decided to try the Marathon challenge this morning. Started playing around 8am, left for work around 2:30pm (hibernated the pc), came back 10:30pm... I'm currently on wave 83 and geez, is this thing slow. No idea how many FPS it's doing, but I can clearly see every frame of every animation done...
If I pause the game (hovering mouse, waiting for pause button to bright up, hold mouse button until it pauses), everything comes back normal - I can enter options and the reaction time is a little low, but nothing damaging. If I unpause... everything slows down again.
Running on windowed mode @ 1600*900 (btw, did you guys know that, even if you have greyed out the Video button on options, you can still access it through Accessibility?), with an NVidia GeForce GTX 650 TiBoost on Windows 10, main display LG Ultrawide display @ 2560*1080

**Comment by IBwWG** [comment]
Re: the video options I'm going to open a separate ticket...

**Comment by ManDude** [comment]
> btw, did you guys know that, even if you have greyed out the Video button on options, you can still access it through Accessibility?

Oh god!

**Comment by IBwWG** [comment]
Yesterday I went to play DQ a bit, and remembered that on the Linux Mint netbook, it still doesn't run, but that at some point I had downloaded 1.1.52 DQ legacy onto it.  So I ran it.  I have to say that legacy seems way snappier in general on this low-powered netbook, compared to the HD version (with legacy graphics for cutscenes and sprites, and the same resolution, 800x600) on the other differently-spec'd-but-similarly-low-powered netbook running Ubuntu 14.04, but surprisingly, also on [this machine](https://github.com/larsiusprime/tdrpg-bugs/issues/694#issuecomment-215855045) which is, while still low-end, quite a bit beefier in general.  I.e. legacy on a cheap 32-bit linux netbook outperforms HD-with-legacy-graphics even on a 64-bit windows laptop.  Maybe it's just a limit of OpenFL vs original Flash?

**Comment by larsiusprime** [comment]
How does version 2.0.3 feel?

**Comment by IBwWG** [comment]
As I said in the other thread, a dream to play!!  Now on the post-game screen, I am finally assigning all these saved-up stat points, that was such a pain before, now it's super-responsive, boom-boom-boom.  Thanks!!

**Comment by IBwWG** [comment]
2.0.3a seems a lot more responsive on the Mint machine, although not quite as much so as the original.  Still, it's a netbook, maybe you can't expect to play on it, if you already consider my beefier Windows laptop to be low-end.  :)

**Comment by ManDude** [comment]
I noticed a performance boost in battles too. Nice job!
