### ISSUE TITLE
Book tooltip off-screen

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#695]
0.5.2 full, win7x64, res just under 1920x1080.

![dq-book-tooltip](https://cloud.githubusercontent.com/assets/16719964/14821318/90f61fd2-0bca-11e6-8a43-20711ce3118c.png)

**Comment by larsiusprime** [comment]
I was wondering where the tooltips were!

**Comment by IBwWG** [comment]
Found em!  ;)

**Comment by larsiusprime** [comment]
Fixed in 0.5.6
