### ISSUE TITLE
Furious Start book doesn't appear to have an effect until unpaused

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#696]
On 1.1.52 full, it was working, but on 0.5.2 HD full, newly placed defenders (at least at the start of a battle) are not frenzied.  win7x64.

**Comment by IBwWG** [comment]
Sorry, my bad.  They actually are, but they don't have the icon until you unpause.  In the original they do, I think it's clearer that way.

**Comment by larsiusprime** [comment]
Okay I'll look into this.

**Comment by larsiusprime** [comment]
Fixed in 0.5.4
