### ISSUE TITLE
Azra spell icon timer overlays not visible

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#697]
On 1.1.52 original full, you could see a clock-like timer overlay on the frenzy icon after using it, so you know when you could use it again.  On 0.5.2 HD full, the icon merely goes dark until it's available again.  win7x64.

Ah, this is also true on lightning.  Probably generally true.

**Comment by larsiusprime** [comment]
Hmmm, there should be a clock timer overlay, wonder what's wrong with it.

**Comment by larsiusprime** [comment]
Okay fixed the pie dial. A few remaining issues:

- The dial should immediately turn dark after use, not one frame after (so it updates when cast during pause)
- Crystal doesn't seem to have any cooldown

**Comment by larsiusprime** [comment]
Fixed and fixed. Expect in 0.5.5

**Comment by IBwWG** [comment]
Now the dials are dark when they shouldn't be (0.5.7):

![dq-grey-spell](https://cloud.githubusercontent.com/assets/16719964/14917624/573c89a4-0e20-11e6-98c7-e345dde37031.png)
