### ISSUE TITLE
Perma-frenzy?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#700]
See screenshot at #699 (everyone is frenzied, yet the 2 spell icon is not dark, indicating I could use it.)  Or is this just how the Furious Start book works and I never noticed?

**Comment by larsiusprime** [comment]
The Furious start book starts everyone off with a bit of Frenzy.

As for the spell, there might be a bug where it still has a cooldown after casting, but the countdown clock shade isn't being drawn. Could you remove the book if you have it equipped and see if you can narrow down which case it might be?

**Comment by IBwWG** [comment]
Per #697 casting the spell gives it a darkened/pressed look, just without the overlay, so that's how you can see from the screenshot that it's available to be used.

OK, so with the book, it should wear off...

**Comment by IBwWG** [comment]
On 0.5.3 this is still here.  I'm on wave 12/21 on the level I've screenshotted a lot lately, and they're still frenzied, I never cast the spell.

**Comment by larsiusprime** [comment]
Can you click on the defenders and look at the frenzy tooltip? Mousing over it will tell you how long is left on the effect.

**Comment by IBwWG** [comment]
Never noticed that before!

720 seconds left.  Is it just that I've leveled up her frenzy to max?  It never seemed to last *that* long before.  Does the book give you whatever your leveled up frenzy is, times some multiplier?

**Comment by larsiusprime** [comment]
It should just give you one dose of frenzy that matches the spell, IIRC. 720 seconds??? Something is going on there.

**Comment by IBwWG** [comment]
Oh yeah, it's also 1125% speedup.  No wonder this one seemed so easy on extreme, even with my uberparty here.

**Comment by larsiusprime** [comment]
Just to be sure, what are the stats on your normal Frenzy spell? If it's a nice whole number divisor (like 72 seconds / 112.5% speedup) then there's our answer, I missed a decimal spot.

**Comment by IBwWG** [comment]
I have 15 levelups, for 24 seconds @ 75%.

**Comment by larsiusprime** [comment]
I've found the cause. It's pretty convoluted. It's getting the status effect stats at that level up, and then "leveling it up" 15 times by applying all those stats again, or at least something very much like that :P

**Comment by larsiusprime** [comment]
Okay, fixed it. Another bug lies right behind -- the effect is being applied *twice*. I think if I can move it from being applied at summon time to at place time, then it should fix this bug & be better w/ more immediate feedback.

**Comment by larsiusprime** [comment]
Okay fixed the other bugs too!

Now it applies the spell -- *with the correct stats* -- **once** -- to the selected defender, as soon as they are placed, and for good measure plays the frenzy spell sound effect too :)

**Comment by larsiusprime** [comment]
Expect the fix in 0.5.4
