### ISSUE TITLE
Azra suddenly slain?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#706]
![dq-failed](https://cloud.githubusercontent.com/assets/16719964/14833738/fe6b6cee-0c00-11e6-8f50-2996be8abb36.png)

0.5.3.  Either I *really* wasn't paying attention, or suddenly her health went from full to nothing without anyone getting through...trying to reproduce...

**Comment by IBwWG** [comment]
![dq-failed2](https://cloud.githubusercontent.com/assets/16719964/14833965/18e3baa8-0c02-11e6-9263-1b014d304445.png)
Yeah, this happened again just now.  Just after clicking OK I got the screenshot here.  As you can see, there's nobody around, and none of the nearby defenders are doing anything.

**Comment by larsiusprime** [comment]
Dump the save file for me and I'll try my best to repro. Thanks for all these great bug reports by the way!

**Comment by IBwWG** [comment]
[export-suddenly-slain.zip](https://github.com/larsiusprime/tdrpg-bugs/files/237939/export-suddenly-slain.zip)

No prob, happy to help :)

**Comment by larsiusprime** [comment]
This is really tough for me to reproduce!

So, if your patience isn't totally exhausted, here's my best strategy -- in 0.5.7, the starting layout will be saved with your save file. If and when you see this happen again in a battle post 0.5.7, go ahead and send me the save file, which should include the starting positions of all your defenders prior to the first wave being sent. Then hopefully I can use that to cut down the reproduction time / complexity.

**Comment by IBwWG** [comment]
No worries, I just wait around for the next build before playing, it gives me some good auto-spacing so I don't play too obsessively (or work too obsessively, when it's available, I get a distraction from my own game.  :) )  Will do with 0.5.7.

**Comment by IBwWG** [comment]
Now the only thing is, for some reason 0.5.3 is the last build out there.  (I'm not sure if it needs mentioning...I imagine TCI gives you notifications when this happens, but maybe not?)

**Comment by larsiusprime** [comment]
If the new build is not up, it almost certainly means I haven't pushed working code to my constellation of repos... I'll check the logs and try and get a clean build triggered right now.

**Comment by IBwWG** [comment]
Ah, whoops, I should've said something earlier.  0.5.3 was like that too, there were several days between it and the previous build, but I thought I had remembered you saying something broke.  Oh well, looking forward to the latest.  :)

**Comment by larsiusprime** [comment]
Okay, CI has been failing for the last 4 or 5 tags, finally figured out that it was a compile error I introduced that only happened on release mode (and was only testing debug locally).

*Should* be fixed now, I issued a fresh build to the server and will watch it like a hawk for errors.

**Comment by IBwWG** [comment]
Cool.  Now a windows build is up, but none of the others (before it was making 2 linux, 2 windows, 1 mac, for each version).  But I'm only testing on windows ATM anyway.

**Comment by larsiusprime** [comment]
Were you ever able to reproduce this?

**Comment by IBwWG** [comment]
Not since the battle layout saver, I wasn't.  I'd like to try again, but I forget which level this is...do you think there's room in the UI (or maybe with the FPS overlay?) to include the map name when playing a battle, so that it's easy to tell from a screenshot in the future?  I know I'd suggested putting it in the options menu previously, but maybe this would be even handier.

**Comment by IBwWG** [comment]
OK, I found the map.  I'm playing it now, but now that I think of it, it's probably fixed, since eventually I managed to beat it on Extreme.

**Comment by IBwWG** [comment]
Wasn't able to reproduce just now.
