### ISSUE TITLE
Missing journal entries near game start, & a wording touch-up

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#707]
Journal jumps from Night 1 to "Day 3 - addendum" after first starred battle on new game, 0.5.3

"Hilight" should be "Highlight" on video options

**Comment by IBwWG** [comment]
Actually, that first one might be a separate actual bug...content-wise I think there are days missing in the journal, not just a mis-numbering.

**Comment by IBwWG** [comment]
The save game in #708 demonstrates the missing journal entries, even after moving on.

**Comment by larsiusprime** [comment]
I don't think any journal entries are actually missing; there's not always a journal entry for every day, it's supposed to represent the passage of time. Also, some journal entries are exclusive to New Game+.

Hmmm. I wonder if maybe the obvious gaps in the UI (where the NG+ entries go) is the culprit for this expectation. Maybe I should space them out evenly in regular game.

**Comment by IBwWG** [comment]
Oh, OK.  Could be.  Also just one entry after that I find the hierarchy itself a bit confusing...why are there two Day 3 entries?  If I think for a bit it makes sense because the indented ones are just addendum, but looking just at the dates/times first, it seems strange.  Also maybe I've just never written in a journal this particular way.
![dq-journal](https://cloud.githubusercontent.com/assets/16719964/14855621/0812c6c2-0c95-11e6-8ff2-52b23e49a326.png)

**Comment by larsiusprime** [comment]
Yeah, I get that.

For what it's worth, it's no *less* confusing than in the original version of the game, which uses this exact format.

**Comment by IBwWG** [comment]
LOL OK no problem then :)  Now that I know it's meant to be that way, it's easier to look at it differently.

**Comment by IBwWG** [comment]
Another wording touchup on Day 9: "thisjournal"

**Comment by IBwWG** [comment]
Ha, I was going to say, on Night 17 - The Fox, elegy should be eulogy, but I learned a new word, thanks :)
