### ISSUE TITLE
Virtual mouse click doesn't seem to actually work, just flash the sidebar

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#709]
I find clicking wears out one's wrists sooner than typing.  Since often when placing defenders I have one hand on the keyboard anyway to hit class and defender shortcuts, it'd be nice to cut down on clicks with a "place defender at currently moused location" shortcut.

Which, I just noticed, should already be possible with the virtual mouse.  Unfortunately, when I tried placing a defender with it (default: ENTER), it responds only by briefly removing the defender radius, but it doesn't place the defender.  0.5.3 win7x64.

Also, trying to use the virtual mouse click to do a lightning attack does the same thing--flashes the sidebar as if something is supposed to happen, but doesn't actually do a lightning attack.  (0.5.7win7x64)

**Comment by larsiusprime** [comment]
Let's knock this one out. Sounds easy to fix and important to do.

**Comment by larsiusprime** [comment]
Well that took nearly an entire day and required me to massively refactor my core TDRPGState class.

One tiny feature + a giant pile of hidden technical debt = fun.
