### ISSUE TITLE
Sidebar for current defender covered by Azra's spell info

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#712]
![dq-sidebar-overlap](https://cloud.githubusercontent.com/assets/16719964/14886620/f6c7e63c-0d51-11e6-93a2-280a481c396f.png)

Set up, started the battle at 16x, paused, picked lightening, struck with it, then clicked "1/4X" speed.  After a few frames, selected defender, saw what you see above, also after a few pause/unpauses to let some frames go by.  0.5.3 win7x64.

Clicking away then clicking defender again does not fix it, nor does changing the speed setting again.

Only way I found to fix it was to select lightening again, then click in the area of Azra's other spells to unselect it.  Then it seemed to function normally again.

**Comment by larsiusprime** [comment]
This is really hard to reproduce. Can you do it consistently? Did you select the spell with the mouse, or a hotkey? Are you using a tablet or a real mouse?

**Comment by IBwWG** [comment]
I haven't seen it often.  I'm not sure what I originally selected the spell with.  Real mouse though.

**Comment by IBwWG** [comment]
This is still present on 0.6.2, not sure about later.  Again I'm not sure what I originally selected the Frenzy spell with, because I only noticed it later when I was trying to select characters and can't see anything after selecting them via keyboard.

**Comment by larsiusprime** [comment]
I got this to happen and then -- infuriatingly -- couldn't reproduce it. I might just put in a potential safety fix and hope for the best.

**Comment by ManDude** [comment]
This is still happening, by the way. I don't know what I'm doing to reproduce it, it just happens.

**Comment by larsiusprime** [comment]
I just reproduced it myself. If I can get it to happen consistently, I'll
fix it.

On Wed, Jun 8, 2016 at 3:12 PM, ManDude <notifications@github.com> wrote:

> This is still happening, by the way. I don't know what I'm doing to
> reproduce it, it just happens.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/712#issuecomment-224712931>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-KXLEeCBE-lCTjKo4m8QXublng8yks5qJyIngaJpZM4IR5Nr>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Hasn't happened to me in a while.

**Comment by larsiusprime** [comment]
The latest build I'm on has fixes to explicitly deal with this, and I haven't seen it in a while either. Gonna close for now.
