### ISSUE TITLE
No difference between casual and normal for some battles?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#713]
For example, Return to the Coliseum.  I checked by going into the battle, each wave seems to have identical stats.

Maybe also for the battle before the first prison, but I didn't go into the battle, just noticed that the description (except the perfect bonus) seems the same from the outside.  0.5.3win7x64

**Comment by larsiusprime** [comment]
Enemies are supposed to have significantly less health in casual mode. I think the rest of the stats might be the same. Can you confirm that there's no difference whatsoever? If so then it's a bug.

**Comment by IBwWG** [comment]
Yep, confirmed.  21, 21, 38, 35, 150 for HP on RtTC.

**Comment by larsiusprime** [comment]
Okay observations:

 - Tooltip staps in map preview are accurate
 - Wave bar (in battle) tooltips are inaccurate in casual, accurate in easy
 - Actual battle HP for enemies in casual is neither what it should be nor what is correct for easy

**Comment by larsiusprime** [comment]
Alrighty, a fairly easy fix -- apparently difficulty settings weren't filtering down to the level of enemy waves, leading to a lot of weird stat calculations in battle.

**Comment by larsiusprime** [comment]
Fixed in 0.5.8 (+ I just pushed the files to the server, forgot to do that over the weekend)
