### ISSUE TITLE
Screen stays too dark after placing a defender while paused

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#714]
I noticed this a bit lately, but I'm not sure which version it started in.  When you place a defender, some maps, like...the one I'm on...(maybe you could show the title when you click Options?)...just after the town where you can recruit rangers, it's so dark you can hardly tell between the path and the stone wall, which makes it naturally kinda hard to tell where you might want to place the next one.  You have to unpause and wait a few frames for the darkness to fade again.

0.5.3win7x64

**Comment by larsiusprime** [comment]
seems fixed now
