### ISSUE TITLE
Frenzy spell has "WAIT" on cursor when actually ready

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#717]
0.5.7win7x64, saw this a few times but not always, when switching to the frenzy spell (by pressing 2 on the keyboard) it says WAIT but it's been ready for a while and it lets me click.

Also (not sure if it's related) the cursor at the end of the battle stays as an Azra spell cursor (if that's what it was at that point) even though it's no longer applicable.

**Comment by IBwWG** [comment]
Also just now I saw it happen that it says "WAIT" and also the timer has a tiny slice left, but actually it's over, the defs' frenzy icons are gone already since a few frames ago.

**Comment by IBwWG** [comment]
![dq-wait-frenzy](https://cloud.githubusercontent.com/assets/16719964/14911761/d4d33b16-0df7-11e6-8cbd-f59e9c5e4ba1.png)

**Comment by IBwWG** [comment]
A couple frames later it let me, when I also unselected the spell and reselected it.  Previously I had already tried an unpause-pause, and it didn't help (hence the "already since a few frames ago" above.)

**Comment by IBwWG** [comment]
Just had this happen with the healing spell too.

**Comment by larsiusprime** [comment]
The cooldown time for a spell and the duration of its effect are two different things (even after frenzy timer runs out on the dudes, the spell will probably have cooldown time left)

So in your second comment, that's not a bug. Frenzy just hasn't cooled down yet. I wonder if switching between spells using hotkeys might make one erroneously show the cooldown status of the other spell, that could be a legit bug.

**Comment by larsiusprime** [comment]
Okay, found the bug:

1. Pause the game
2. Cast a spell, any spell
3. Select a different spell with a hotkey or with the mouse

The "wait" status will be that of the original spell you cast, not the currently selected spell. If you run the clock forward the wait status will update correctly.

**Comment by larsiusprime** [comment]
- [ ] Fix incorrect "wait" text carry-over
- [ ] Make spells un-dark at start

**Comment by larsiusprime** [comment]
Fixed and will be available in 0.6.2
