### ISSUE TITLE
Ranger's "black out the sun" has no animation?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#720]
On 0.5.7 just looks like this the whole time:

![dq-black-out-the-sun](https://cloud.githubusercontent.com/assets/16719964/14918891/6766bc5e-0e26-11e6-8fcd-24c2c03cbe70.png)

Intentional?

**Comment by larsiusprime** [comment]
Are you running it on x1 speed? Some animations that have a particular pattern of frames can wind up in a "synched" state with higher speeds such that you get a pattern where every frame except one is skipped for the purpose of animation and it looks like they just stand still. I just tried this and the illusion only happens on x8 and x16 speed

**Comment by IBwWG** [comment]
Whoops...shouldn't've cropped.  I forget.  I think it was on 1x or slower though, actually...otherwise I normally don't even notice the animations much because there's so much happening.
