### ISSUE TITLE
Saved layout offset wrong switching between windowed and fullscreen between battles...with fun side effects

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#724]
See screenshot at #723.  That could be gamed :)  0.5.7win7x64

Just noticed Azra's on there twice.  Could be another duplication bug, eh?

Also the crystals on the path, I don't think that's normally allowed.

**Comment by IBwWG** [comment]
Also, this:  whee!

![dq-whee](https://cloud.githubusercontent.com/assets/16719964/14927320/59208a00-0e51-11e6-8899-9c552f48e4a6.png)

**Comment by IBwWG** [comment]
BTW still exhibiting #716 in this scenario.  Pretty reproducible here...

**Comment by larsiusprime** [comment]
Double Azra's is a side effect of battle layouts (fixed in 0.5.8 I believe) where she literally *summons herself*.

I'll look into the rest of it, that's pretty hilarious out-of-the-box thinking on the part of the enemies.

**Comment by IBwWG** [comment]
Is 0.5.8 the same as 0.5.7-2-g6332571?  A win build showed up for that one now too, but no 0.5.8 per se.

**Comment by larsiusprime** [comment]
No, I just got a message the 0.5.8 build is broken. Let me fix it...

**Comment by larsiusprime** [comment]
Hang on...

> Uploaded 'Defender's Quest I (0.5.7-2-g6332571 - demo, build 1) (Windows).zip' at 7.7 MB/s, total 123.6 MB
> Discovering tests...OK
> Build success

Um, weird. The label's wrong but I think it might be 0.5.8? Open it up and check out the title menu.

**Comment by larsiusprime** [comment]
Duh! I forgot the github tag.

So that IS 0.5.8, the title screen should have the right number. 0.5.9 is also on its way, BTW.

**Comment by larsiusprime** [comment]
Fixed in 0.6.3, thanks for catching this! Also walking around the edge is fixed too, as levels are properly padded now when we're in original art mode.
