### ISSUE TITLE
New defender circle stays red even once you have enough psi to place

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#725]
...and the spot is valid.  And you click and it works.  :)  0.5.7win7x64  (Like, get ready to place someone when you're out of psi, earn some psi...you're now able but it looks like you're not because it's red.)  It does stop saying "need psi" though, and if you move a tile and back again it's fine.

**Comment by larsiusprime** [comment]
This is fixed in 0.6.4
