### ISSUE TITLE
Sheep dying animation replays forever

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#726]
Sprite leak? ;) 0.5.7win7x64.  Just start on extreme, and kill the white sheep.  (Wait a bit when they first come out then place some defenders, so you'll have a few isolated ones that aren't part of the first-contact defender's heap.  Isolated and heap ones will replay forever.)

**Comment by IBwWG** [comment]
Unfortunately, this has the side effect of taking up 1.6 GB of RAM and then crashing, about half way through.

**Comment by IBwWG** [comment]
Also seen on Advanced.

**Comment by IBwWG** [comment]
![dq-sheep](https://cloud.githubusercontent.com/assets/16719964/14937804/f4746abe-0f12-11e6-93ce-cace3f4041e7.png)
...which also has a weird wave count.  Also, near the end, even though I have no ice mages there, near the dragon all the sheep stopped and waited politely to be killed.  Also, it's just sitting there, no more sheep are coming but the level is not registering as done and letting me leave.  Thankfully on Advanced it didn't crash because it (only?) took up 1.2 GB.

**Comment by larsiusprime** [comment]
Whooopsie. I'm gonna take a giant guess that the "loop" value for these animations was not set to false.

**Comment by IBwWG** [comment]
Seems reasonable.  Stop the mutton mayhem!  ;)

**Comment by larsiusprime** [comment]
Yup. Fixed in 0.6.0.
