### ISSUE TITLE
Crash near end of level...but not full memory

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#728]
Sorry, I'm not sure how to reproduce this exactly, and it's a bit weird in that it's not when the memory is full.  Is the Windows crash data of any use?  (It's not to me yet but maybe you know what to do with it.)  0.5.7win7x64, the frame rate wasn't even too slow just before it crashed.  I had just unpaused a few frames earlier, had nothing else running at the same time.

![dq-crash-not-over-mem](https://cloud.githubusercontent.com/assets/16719964/14941558/28513de8-0fa0-11e6-8913-126bb7f210c2.png)

**Comment by IBwWG** [comment]
Argh, never mind, somehow I didn't copy the crash data right anyway.

**Comment by IBwWG** [comment]
I wonder if it's an infinite loop it gets into.  I had this again on a later battle, 1.4 GB taken up, CPU pegged at 25:

![dq-crash-not-over-mem2](https://cloud.githubusercontent.com/assets/16719964/14942042/7189cbb8-0fb1-11e6-9599-27d730047c00.png)

**Comment by IBwWG** [comment]
Both times you can see it was near the end of the battle.

**Comment by IBwWG** [comment]
This time when it finally crashed (it seemed to take longer than last time from hanging to crashing):

> Description:

>   A problem caused this program to stop interacting with Windows.
> 
> Problem signature:
>   Problem Event Name:	AppHangB1
>   Application Name:	DefendersQuest.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	57228419
>   Hang Signature:	42bd
>   Hang Type:	0
>   OS Version:	6.1.7601.2.1.0.768.3
>   Locale ID:	4105
>   Additional Hang Signature 1:	42bdd6509e282f73da2726c34266bb57
>   Additional Hang Signature 2:	08ad
>   Additional Hang Signature 3:	08ad13884910c435ae95f9e6cf795427
>   Additional Hang Signature 4:	42bd
>   Additional Hang Signature 5:	42bdd6509e282f73da2726c34266bb57
>   Additional Hang Signature 6:	08ad
>   Additional Hang Signature 7:	08ad13884910c435ae95f9e6cf795427
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\windows\system32\en-US\erofflps.txt
>

**Comment by IBwWG** [comment]
Although, with the very limited numbers seen in #735's screenshot, I just had this happen, and was about to copy the crash info again when suddenly that window disappeared and the game resumed.

**Comment by larsiusprime** [comment]
This is probably just a general symptom of memory issues. I should just try to plug the leak first and see if it helps, I guess.

**Comment by larsiusprime** [comment]
Does the (hopefully improved) memory leak in 0.5.9 mitigate this at all?

**Comment by IBwWG** [comment]
0.6.0.win7x64, HD mode@1704x960windowed

I'm not sure if this was solved... c.f. https://github.com/larsiusprime/tdrpg-bugs/issues/694#issuecomment-216441974 which was on the same level, and I wasn't able to get anywhere near the end.  Also the same behaviour of being in an "almost crashed" state was showing itself.  I would click the window, the windows spinny loading cursor would come up, but then go away and the game would render a frame, like it couldn't decide whether it was time to officially crash or not.

**Comment by IBwWG** [comment]
0.6.5, win7x64, HD mode@1704x960windowed

Just redid the same level as the first screenshot above on extreme, and at the end of the battle, mem usage was ~800MB, so no crash.  :)

**Comment by IBwWG** [comment]
0.6.5, win7x64, HD mode@1704x960windowed

Second screenshot level, on extreme, after placing almost all my defenders, started battle at >700 MB.  At the end it was around ~1 GB but I beat all the waves without a crash.  Yay!  :)

**Comment by larsiusprime** [comment]
That's still a heck of a lot of memory to be used, but I'm glad it's not crashing.

**Comment by larsiusprime** [comment]
The high memory use is actually indicative of software rendering mode, come to think, because it literally just blits a bunch of pixels rather than treating things as textured quads.... hmmm. Let me get an updated build that will just pop up a notice for software mode on startup so we can confirm.

**Comment by IBwWG** [comment]
Hmm, this is strange, I just finished the super sheep, equipped the golden fleece, clicked Continue, the screen went blank (except for the fancy cursor) and stayed that way.  I couldn't even call the window to the front by clicking it in the taskbar, instead I had to minimize other windows, and then I couldn't move the window by dragging its title bar.  Memory is 1,146,000 K and processor is pegged at 25.

**Comment by IBwWG** [comment]
After a minute or so, I got this (actually one frame before, but it took about 5 attempts at taking a screenshot before one took, I guess with the system under load this makes sense?):

![dq-slow-fade](https://cloud.githubusercontent.com/assets/16719964/15056799/e7787f30-1313-11e6-89ce-aa9f0806feaa.png)

**Comment by larsiusprime** [comment]
When I forced software rendering locally, I got terrible performance on
transitions, too. I'm going to disable the screen wipes in software mode in
0.6.7

On Thu, May 5, 2016 at 3:52 PM, IBwWG <notifications@github.com> wrote:

> After a minute or so, I got this (actually one frame before, but it took
> about 5 attempts at taking a screenshot before one took, I guess with the
> system under load this makes sense?):
>
> [image: dq-slow-fade]
> <https://cloud.githubusercontent.com/assets/16719964/15056799/e7787f30-1313-11e6-89ce-aa9f0806feaa.png>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/728#issuecomment-217275993>
>



-- 
www.fortressofdoors.com -- Games, Art, Design
