### ISSUE TITLE
??? desert location not showing on map

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#729]
On 0.5.7, I got to the same point I had gotten with my previous save.  On the previous one, the ??? shows, but on this one, there's no way to get to it.  I even beat the Zelemir Appears battle on extreme.  However, that might be it: first I beat it on Casual, then jumped to extreme after beating a few later levels.  In the previous save I believe I beat it only on Normal.
[no-desert-vs-previous.zip](https://github.com/larsiusprime/tdrpg-bugs/files/244110/no-desert-vs-previous.zip)
I have the book of secrets equipped and have seen the puzzle indicators a few times already.

**Comment by IBwWG** [comment]
Going back and beating Zelemir Appears on Normal did not help, but maybe there's some logic hook in there that only checks when you first beat the battle?

**Comment by larsiusprime** [comment]
To see the ??? desert locations you must fulfil these requirements:

- [ ] Have the book of secrets equipped
- [ ] Have the Zelemir appears battle beaten on any difficulty
- [ ] Be playing in New Game+ mode. It doesn't show up in the regular game.

**Comment by IBwWG** [comment]
Then that's a bug of a different sort: I was able to see them in the regular game.  In those two saves you see, the "previous" one is one where I had never seen NG+ yet, and that's the one I can see ??? on.  It's also the one I had imported from the full non-HD version of the game, maybe that had something to do with it.

**Comment by larsiusprime** [comment]
Hm, maybe I'm wrong and it is supposed to be in the standard game! I forget these things sometimes.

**Comment by larsiusprime** [comment]
Yup, your set of save files reproduces it, and you have the book equipped. Weird.

**Comment by larsiusprime** [comment]
Took a while but I fixed it. Fixed in 0.6.5
