### ISSUE TITLE
Treasure Chamber graphics cover text

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#730]
0.5.7 on 1 below 1920x1080, windowed, HD mode:

![dq-guardian-of-the-what](https://cloud.githubusercontent.com/assets/16719964/14942100/fd7e183a-0fb2-11e6-96f2-383e05fb7e90.png)

**Comment by IBwWG** [comment]
Oh, and it only let me buy one of those.  Is that normal?

**Comment by larsiusprime** [comment]
Guardian of the fountain is a unique item, so yeah, you can only have one of those :)

I should probably indicate somehwere that it's unique, and deal with that text field size. I think the most obvious solution is the icons just shouldn't be allowed to scale that big (they look smudgy at high resolutions anyway)

**Comment by IBwWG** [comment]
I think a unique indicator is a good idea...it's doubly unique (I think...) in that it's the only one you can buy in a shop...at least on the first playthrough.

**Comment by larsiusprime** [comment]
Made the item icons smaller + added a "(unique)" indicator to the name in shops.

0.6.5
