### ISSUE TITLE
Cultist level 2nd part has placeholder for High Priest text

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#731]
0.5.7win7x64, on Normal.  (I can't do Extreme on these latter levels right now, because the game always runs out of memory and crashes by the end.)

![dq-cultist-placeholder](https://cloud.githubusercontent.com/assets/16719964/14942182/45bdbc16-0fb5-11e6-8ce4-ee3fe40f33b8.png)

**Comment by larsiusprime** [comment]
This is fixed in 0.6.0
