### ISSUE TITLE
Sprites sometimes FlipX'd

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#733]
0.5.7

The High Priest character from #731, after he rounds the bend, does the moonwalk.  And I've seen a few characters do this.  But it's more general: on the battle "charge into the middle" (don't know the proper name, I'm still in the battle), I just saw an arrow flying backwards.  Unfortunately, the pause button didn't register in time for a screenshot.

**Comment by IBwWG** [comment]
Ah, here's an example, the ghoul that just came from the blue portal:

![dq-ghoul-moonwalk](https://cloud.githubusercontent.com/assets/16719964/14942414/d205692e-0fbc-11e6-9958-354951ec8382.png)

**Comment by larsiusprime** [comment]
Can you reproduce this consistently? I've seen this several times myself and it's maddeningly hard to get it to happen consistently on demand in a reasonable amount of time.

**Comment by larsiusprime** [comment]
Fixed in 0.6.5
