### ISSUE TITLE
Restore bulldog mode

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#734]
No cursor change, and it doesn't stay pressed in when I click it.  How do you set the target?  0.5.7win7x64

**Comment by larsiusprime** [comment]
Not implemented yet. :) 

I've been meaning to get around to this though so I might as well do it now. I'll also be restoring "bulldog mode" from the original game.

**Comment by larsiusprime** [comment]
- [ ] Restore "bulldog mode" : HIGH priority
- [ ] Implement "target specific" : LOW priority

**Comment by larsiusprime** [comment]
- [ ] Restore bulldog mode button
- [ ] Enable bulldog mode functionality
