### ISSUE TITLE
Ending animation

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#736]
0.5.7   So I went to the level in #735 and pressed F2 to beat it, since I could hardly get very far even on Normal without a hang.  The ending animation had two quirks:
- [ ] when Z draws his sword, instead of moving towards ET, he moves diagonally down-left.  then suddenly he's at ET.
- [ ] the particle animation is super super slow.  like 1 FPS.

**Comment by larsiusprime** [comment]
Does the diagonal motion only happen in a 16x9 aspect ratio?

**Comment by IBwWG** [comment]
It did happen that way but I've only seen it once so far.  Will check

**Comment by IBwWG** [comment]
0.6.0.win7x64, HD mode@1704x960windowed
Happens still, and particle animation dropped the FPS from ~60 to ~1.
At 800x600, no diagonal motion, and the FPS only drops to ~9 for the particle.

**Comment by larsiusprime** [comment]
Fixed in 0.6.7

**Comment by larsiusprime** [comment]
Two nitpicks:
- [ ] Fading/faded enemy waves still show tooltips
- [ ] Eztli's dying shockwave effect not centered
