### ISSUE TITLE
Null Object Reference Crash (Bakal Healing Bug)

### ISSUE THREAD

**Issue by BlaQSRk** [larsiusprime/tdrpg-bugs#738]
When Bakal Heals on the First Stage he's introduced (The one with Ozimal). For some reason when he heals Slack, the game crashes, plays the healing sound, then gives me a "Null Object Reference" popup, and then crashes.

**Comment by BlaQSRk** [comment]
Here's an image of it. version 0.45 for windows. http://i.imgur.com/0TrrG8I.png

**Comment by larsiusprime** [comment]
Ooops, I've forgotten to update that blog post haven't I? We fixed this a while back. We're on version 0.5.8 now.

Thanks for the report! The blog post is updated now with current links to our nightly build server. Thanks for the report in any case, this is precisely the sort of details we like to see.
