### ISSUE TITLE
Text rendering strange only for "scene" labels in Movie

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#739]
0.6.0.win7x64, HD mode@1704x960windowed
![dq-text-render-glitch](https://cloud.githubusercontent.com/assets/16719964/14974797/c35de3ea-10f9-11e6-90a9-4b48fde4c13c.png)

**Comment by larsiusprime** [comment]
This happens ocassionally in certain resolutions when I don't take care to make sure that text is at a whole-number screen coordinate. Std.int() to the rescue...

**Comment by larsiusprime** [comment]
I can't reproduce this one myself, but I put in some potential fixes for it, let me know if it occurs again in 0.6.2.

**Comment by IBwWG** [comment]
Looks great on 0.6.5.
