### ISSUE TITLE
Issues I've noticed

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#741]
- [x] Arrows can reverse direction if target goes null
- [x] Fire effect is too high on splitters & some other enemies
- [x] Death effect is too low for sheep
- [x] Frozen enemies can still attack
- [x] Defender thorns hitting projectile attackers (should only be melee)
- [x] Frozen enemies walk in place? (armored revenant)

**Comment by IBwWG** [comment]
Oh, I thought that first one was from #733 but maybe it was appearances only :)
