### ISSUE TITLE
Fallen knight falls off the screen

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#742]
0.6.5.win7x64, HD mode@1704x960windowed

I had just paused because I saw this knight moving very quickly down the screen, when I noticed that he fell right past a dragon who didn't bother to attack, and appears to be falling through the bottom wall:

![dq-knight-falling](https://cloud.githubusercontent.com/assets/16719964/15053467/23a26248-1303-11e6-8d70-7a0c3e2911e4.png)

Unfortunately I unpaused at 16X instead of slower, so the very next thing I saw, he disappeared into a "155" marker.

**Comment by larsiusprime** [comment]
By "knight" I assume you are referring to the "fallen knight" enemy and not
one of the defenders? If it's the former I have a good idea what might be
happening, if it's the latter things are *super* broken!

On Thu, May 5, 2016 at 1:52 PM, IBwWG <notifications@github.com> wrote:

> 0.6.5.win7x64, HD mode@1704x960windowed
>
> I had just paused because I saw this knight moving very quickly down the
> screen, when I noticed that he fell right past a dragon who didn't bother
> to attack, and appears to be falling through the bottom wall:
>
> [image: dq-knight-falling]
> <https://cloud.githubusercontent.com/assets/16719964/15053467/23a26248-1303-11e6-8d70-7a0c3e2911e4.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/742>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
Yes, the attacker.

Just saw another one, and also his info sidebar has some overlapping number displays:

![dq-knight-falling2](https://cloud.githubusercontent.com/assets/16719964/15053601/9fb7ae9c-1303-11e6-9f73-a8015d0986fd.png)

**Comment by larsiusprime** [comment]
It's almost certainly a glitch with "knockback".

On Thu, May 5, 2016 at 1:55 PM, IBwWG <notifications@github.com> wrote:

> Yes, the attacker.
>
> Just saw another one, and also his info sidebar has some overlapping
> number displays:
>
> [image: dq-knight-falling2]
> <https://cloud.githubusercontent.com/assets/16719964/15053601/9fb7ae9c-1303-11e6-9f73-a8015d0986fd.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/742#issuecomment-217242453>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
I wonder if that was related to the other bug about the rangers shooting at nobody, because right now the rangers are still shooting in his direction.

Glad you figured it out.  :)

**Comment by larsiusprime** [comment]
Can't reproduce lately, think maybe I fixed it? Please re-open if you see it again.
