### ISSUE TITLE
Ranger able to shoot outside range

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#743]
0.6.5, win7x64, HD mode@1704x960windowed

Actually, I guess this was also seen in #742...how could they be targeting the offscreen enemy from the top of the screen?

Anyway, here's a screenshot of targeting a too-far-away onscreen enemy:

![dq-super-ranger](https://cloud.githubusercontent.com/assets/16719964/15053955/65fa3e3e-1305-11e6-968e-c1cffc7f62ef.png)

They do have a lot of range upgrade stat points, but if so, that should be visible in the overlay, right?

In fact the ice mage in the upper left corner is also lobbing ice balls in the same direction, you can sort of see in the screenshot but the ball is under a boost meter.

**Comment by larsiusprime** [comment]
Rangers are allowed to *hit* things outside their range (arrows just keep on going if the original target dies or the arrow misses), but they're not allowed to *target* things outside they're range. Can you confirm that it's the latter and not the former?

**Comment by IBwWG** [comment]
I'm pretty sure it's targeting...

**Comment by larsiusprime** [comment]
Okay that's a legit bug then. Looking into it.

On Thu, May 5, 2016 at 2:45 PM, IBwWG <notifications@github.com> wrote:

> I'm pretty sure it's targeting...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/743#issuecomment-217256646>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
Ah, got it in a screenshot.  I just had to lightening the upper-left baddies so there was nobody else to shoot at, and soon she was shooting at the lower-right ones (but not immediately...so there might be a limit to her range still.)  Not sure if that helps any though.

![dq-super-ranger2](https://cloud.githubusercontent.com/assets/16719964/15055220/b086b79c-130b-11e6-98a8-6f6c9c942d7c.png)

**Comment by IBwWG** [comment]
Also observed on the sheep level on extreme.  There it's a bit easier to see because you can have rangers not able to reach the one portal, nor the sheep's current location, firing at the super sheep.  (*Worms* ref, btw?  :) )

**Comment by larsiusprime** [comment]
It's been so long since we made the sheep level I forget who's idea it was originally... it was an obvious joke level, probably some combination of Worms + Cow level from diablo II.

**Comment by larsiusprime** [comment]
I wonder if this is a recycle bug -- she's "targeting" an enemy in valid
range, it dies, then it respawns somewhere else as a new monster and she's
still got a pointer to it? Hmm. Well, time to debug at any rate.

On Thu, May 5, 2016 at 3:41 PM, IBwWG <notifications@github.com> wrote:

> Also observed on the sheep level on extreme. There it's a bit easier to
> see because you can have rangers not able to reach the one portal, nor the
> sheep's current location, firing at the super sheep. (*Worms* ref, btw?
> :) )
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/743#issuecomment-217272239>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
In the sheep level case, wouldn't that make her fire at the normal sheep, not the super sheep?

**Comment by larsiusprime** [comment]
You're right, she almost certainly clears the pointers. Hmm, guess I'll just add some break points and see.

**Comment by larsiusprime** [comment]
Okay, so this is a case of the ARROWS THEMSELVES retargeting to find a target, any target, when their original target dies. Naturally, this leads to some *wonky* arrow trajectories!
