### ISSUE TITLE
Placeholders shown instead of real text

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#745]
0.6.6, win7x64, HD mode@1704x960windowed

See description in lower-left.  Also on EPIC HALITOSIS, $FLAV_POISON.

![dq-placeholder](https://cloud.githubusercontent.com/assets/16719964/15078877/ad701ef4-13b5-11e6-955c-e3b55566e362.png)

**Comment by IBwWG** [comment]
Also on all the bottom branch of the rangers, except RANGE FOCUS.

**Comment by IBwWG** [comment]
And the ice mages, the bottom two, plus ICE SPEAR.

**Comment by IBwWG** [comment]
Knights: the two armor ones, STUN STAB, and HARD KNOCK.

**Comment by IBwWG** [comment]
Bezerkers: MADNESS, RAGE.

**Comment by IBwWG** [comment]
Healers: ZEAL, BLINDING.

**Comment by IBwWG** [comment]
Also in this tooltip:

![dq-placeholder-tooltip](https://cloud.githubusercontent.com/assets/16719964/15081559/c878fe1a-13c3-11e6-8147-ac4cb3d213d7.png)

**Comment by larsiusprime** [comment]
I just screwed up all the status_effects localization files, so this is a
temporary regression. Will be fixed in the next build.

On Fri, May 6, 2016 at 12:51 PM, IBwWG <notifications@github.com> wrote:

> Also in this tooltip:
>
> [image: dq-placeholder-tooltip]
> <https://cloud.githubusercontent.com/assets/16719964/15081559/c878fe1a-13c3-11e6-8147-ac4cb3d213d7.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/745#issuecomment-217512920>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
Also achievements on latest 0.6.7, win7x64, HD mode@1704x960windowed

![dq-placeholder-achievement](https://cloud.githubusercontent.com/assets/16719964/15091411/cb5fb45e-1448-11e6-98b8-e35b5a8a35c9.png)

**Comment by larsiusprime** [comment]
Should all be fixed in 0.6.8
