### ISSUE TITLE
Text on new weapon popup has strange margin / is cut off

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#746]
0.6.6, win7x64, HD mode@1704x960windowed
![dq-text-margin](https://cloud.githubusercontent.com/assets/16719964/15080815/23079fca-13c0-11e6-9fe8-1029971a244c.png)
Not sure if this is related, but I noticed on quite a few journal entries that the bottom line of the left page has only one word, even though the next few words on the right page would have fit there.

**Comment by larsiusprime** [comment]
Yeah there's some errors that sometimes occur in large blocks of text, I suspect it's an OpenFL bug.

I can work around it by aggressively inserting manual line breaks.

**Comment by larsiusprime** [comment]
Confirmed, argh. And it only happens in some resolutions so it's not gonna be easy to monkey hack around. Let's check openfl for updates to text rendering I guess...

**Comment by larsiusprime** [comment]
Okay, can't fix it, but I narrowed it down to a minimal repro case in OpenFL, and posted there. Hopefully this should help it get patched?

https://github.com/openfl/openfl/issues/1123

**Comment by larsiusprime** [comment]
Monkey patched in my local OpenFL fork. Fixed in 0.7.3.
