### ISSUE TITLE
First four "target" hotkeys missing from Dvorak layout

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#748]
0.6.7, win7x64, HD mode@1704x960windowed

7890 would be fine like it was before :)  Right now they're just blank.  Unfortunately the customization bug makes it impossible to fix it yourself: assigning a key reassigns all the other keys to default, and whether you assign the next there or click Dvorak first, either way it forgets, so you can only assign at most one custom key to the dvorak layout.

**Comment by larsiusprime** [comment]
- [ ] Fix missing DVORAK keys
- [ ] Assigning custom keys should use your current layout as the default
