### ISSUE TITLE
Latest Mac build crashes during cut scene

### ISSUE THREAD

**Issue by erik-harrison** [larsiusprime/tdrpg-bugs#758]
During the second cut scene (before the first battle) when Slak appears for the first time in ghostly form ("What?! Where the - wiggedywah...?!"), clicking Next causes the app to crash. There is a wipe transition to black first, like the cutscene is continuing. This is the console output.

Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 761
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 530
Called from flixel.FlxGame::step flixel/FlxGame.hx line 663
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx line 1471
Called from flixel.FlxGame::update flixel/FlxGame.hx line 713
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 623
Called from com.leveluplabs.tdrpg.State_Battle::create com/leveluplabs/tdrpg/State_Battle.hx line 169
Called from com.leveluplabs.tdrpg.State_Battle::postCreate com/leveluplabs/tdrpg/State_Battle.hx line 4029
Called from com.leveluplabs.tdrpg.State_Battle::buildModel com/leveluplabs/tdrpg/State_Battle.hx line 1391
Called from com.leveluplabs.tdrpg.BattleModel::new com/leveluplabs/tdrpg/BattleModel.hx line 97
Called from com.leveluplabs.tdrpg.BattleModel::init com/leveluplabs/tdrpg/BattleModel.hx line 2225
Called from com.leveluplabs.tdrpg.BattleModel::initStartLocs com/leveluplabs/tdrpg/BattleModel.hx line 2256
Called from com.leveluplabs.tdrpg.BattleModel::placeDefender com/leveluplabs/tdrpg/BattleModel.hx line 952
Error : Null Object Reference

**Comment by erik-harrison** [comment]
Gah, hit submit before finished.

OS 10.11.4 
2.3 GHz Intel Core i7
8 Gigs Ram
Intel HD Graphics 4000 1536 MB

**Comment by erik-harrison** [comment]
Starting the game afterward and reloading the save file allows you to continue

**Comment by larsiusprime** [comment]
Fixed in 0.7.4
