### ISSUE TITLE
Tutorial highlights wrong skill when Slak levels up

### ISSUE THREAD

**Issue by erik-harrison** [larsiusprime/tdrpg-bugs#759]
The first time Slak levels up, after the explanation of which skills do what, the tutorial says "Click on the skill to upgrade it" but instead of highlighting (and pointing an arrow at) Swiftness, the arrow and highlight indicate Resiliance, which can't be upgraded till Swiftness is

**Comment by larsiusprime** [comment]
Okay, got this fixed now. 0.7.4 will have the fix.
