### ISSUE TITLE
Bulldog enabled by default in latest build

### ISSUE THREAD

**Issue by erik-harrison** [larsiusprime/tdrpg-bugs#760]
Trying the latest Mac build and bulldog mode seems enabled by default on all characters.

<img width="163" alt="bulldog" src="https://cloud.githubusercontent.com/assets/7537154/15491189/084c9b16-213c-11e6-9f5a-56e1a3221d49.png">

**Comment by larsiusprime** [comment]
Thanks! This should be fixed in today's build, 0.7.4
