### ISSUE TITLE
Selecting a defender in the defender window (on the right side of the battle GUI) should deselect current defender

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#767]
Otherwise once you select a defender you HAVE to place it and then recall it which is dumb and can actually ruin the battle for you since you've used up some psi.

Edit: Looks like you can simply click a different class to cancel this. Still.

**Comment by larsiusprime** [comment]
Good catch, thanks!

On Fri, May 27, 2016 at 4:21 PM, ManDude <notifications@github.com> wrote:

> Otherwise once you select a defender you HAVE to place it and then recall
> it which is dumb and can actually ruin the battle for you since you've used
> up some psi.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/767>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-AZtZA7Gh5Orfj6zVXL7R9IRJK8Mks5qF2BGgaJpZM4Io36K>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
You can also press [esc] to deselect a defender. But yes, I agree, "still."

Tasks:
- [ ] Deselect defender by clicking on their button
- [ ] Keep defender's info open while they're selected

**Comment by larsiusprime** [comment]
Fixed in 0.7.8
