### ISSUE TITLE
Artifacts in defender stat menu (battle)

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#768]
![dq05](https://cloud.githubusercontent.com/assets/7569514/15621554/a33ec28c-2459-11e6-9836-1dc7ff09222e.png)
Notice the artifact in the "+40". Happens to all defenders/weapons.

**Comment by larsiusprime** [comment]
What resolution? 800x600?

On Fri, May 27, 2016 at 4:23 PM, ManDude <notifications@github.com> wrote:

> [image: dq05]
> <https://cloud.githubusercontent.com/assets/7569514/15621554/a33ec28c-2459-11e6-9836-1dc7ff09222e.png>
> Notice the artifact in the "+40". Happens to all defenders/weapons.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/768>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-PRZaAwgjze2KyXK92P2BD27rloTks5qF2DpgaJpZM4Io4BG>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Whoops. I forgot to mention, but it happens to these resolutions:
- 960x544
- 1067x600

**Comment by ManDude** [comment]
Those resolutions don't exist anymore lol.
