### ISSUE TITLE
Crash when accessing journal in certain resolutions

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#769]
![dq02](https://cloud.githubusercontent.com/assets/7569514/15621574/be2b7810-2459-11e6-9233-fb470a75b656.png)
HD everything, 960 x 544. Happens to NG+ journal too.

100% reproducable.

**Comment by larsiusprime** [comment]
Wow, that's pretty bad!

**Comment by larsiusprime** [comment]
Fixed by disabling 960x544 resolution for now. Turns out it's only there for testing PSVita resolution, I'll get back to that later.
