### ISSUE TITLE
Lag when boosting

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#770]
Boosting seems to lag out the game while trying to create all those lines (SPECIALLY in the Eztli-Tenoch battle). Maybe tune them down slightly?

**Comment by ManDude** [comment]
The game will constantly freeze for about half a second because of the lightning spell since Zelemir uses it 100 times every second at 16x speed (hyperbole but you get the idea).

**Comment by ManDude** [comment]
Actually, the game will have these lags pretty much every time it draws a new attack (gets only a bit better as you lower particles but still happens).

**Comment by larsiusprime** [comment]
I think I have an extremely inefficient way of drawing lightning, and I think I need to make particle / effect visual counts depend on the playback speed as well -- ie, don't show lightning bolts at all at x16 speed, and show only a fraction of the particles.

**Comment by larsiusprime** [comment]
- [ ] Auto-scale down lightning in terms of detail & colors
- [ ] Auto-scale down particles in terms of playback speed

**Comment by larsiusprime** [comment]
Should be improved in 0.7.9
