### ISSUE TITLE
Mispositioned stats

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#771]
![dq06](https://cloud.githubusercontent.com/assets/7569514/15621908/389d5468-245c-11e6-882e-7a9cf88d6118.png)
The stats are lower on the screen than they should.

HD everything, 960x544.

**Comment by larsiusprime** [comment]
What resolution is this in?

On Fri, May 27, 2016 at 4:42 PM, ManDude <notifications@github.com> wrote:

> [image: dq06]
> <https://cloud.githubusercontent.com/assets/7569514/15621908/389d5468-245c-11e6-882e-7a9cf88d6118.png>
> The stats are lower on the screen than they should.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/771>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-Hc5JLreANUOLnli7vwTgxPZYPt6ks5qF2U-gaJpZM4Io4to>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
The post says 960x544. ;)

**Comment by larsiusprime** [comment]
ah right

On Fri, May 27, 2016 at 5:08 PM, ManDude <notifications@github.com> wrote:

> The post says 960x544. ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/771#issuecomment-222263845>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-BIhlQZL3Tss5DE733vVBTN4qvDXks5qF2tegaJpZM4Io4to>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
I've also only noticed it now but looks like the stat numbers have artifacts too (you can see them in the image).

**Comment by ManDude** [comment]
Resolution no longer supported, I'll close this for now.
