### ISSUE TITLE
ITEM ITEM issue

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#773]
![dq01](https://cloud.githubusercontent.com/assets/7569514/15622088/9eb0fb0a-245d-11e6-807a-09ec0799e525.png)
Great. I love me some ITEM ITEMs.

**Comment by larsiusprime** [comment]
Does this happen with all the "goodie" popups, or just in this one particular screen?

**Comment by ManDude** [comment]
This one only.

**Comment by larsiusprime** [comment]
- [ ] Make missing button appear
- [ ] Suppress "item item"
- [ ] Make sure goodie state is properly saved
