### ISSUE TITLE
Mini-Tenoch

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#774]
![dq07](https://cloud.githubusercontent.com/assets/7569514/15622298/4e2a9446-245f-11e6-9b30-f5e371efd46d.png)
Eztli-Tenoch's sprite here is... small, duh.

HD everything, 960x544.

**Comment by larsiusprime** [comment]
Cute, but not something I'm gonna worry about for a resolution we've cut anyway :P

**Comment by ManDude** [comment]
Actually it looks like it happens to every resolution:
![image](https://user-images.githubusercontent.com/7569514/35163557-10e7bcca-fd3f-11e7-9c03-ac579b211f68.png)
(600p)

![image](https://user-images.githubusercontent.com/7569514/35163632-5375fda4-fd3f-11e7-8962-547591186307.png)
(640p)

![image](https://user-images.githubusercontent.com/7569514/35163654-6ccac744-fd3f-11e7-97a3-3d5cc4d6cfb9.png)
(720p)

etc.
