### ISSUE TITLE
Books will have their stats compared if they're at the top of the list

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#777]
![dq00](https://cloud.githubusercontent.com/assets/7569514/15623704/6c1631f8-246f-11e6-9831-de0bade53152.png)
Haven't tested other books.

**Comment by ManDude** [comment]
This happens to whatever book is at the top of the list:
![dq00-1](https://cloud.githubusercontent.com/assets/7569514/15623713/b1bdb41a-246f-11e6-9552-c1a22c22dc14.png)
![dq00-2](https://cloud.githubusercontent.com/assets/7569514/15623714/b1c25056-246f-11e6-948f-59e94f589d32.png)

**Comment by larsiusprime** [comment]
Fixed in 0.9.5
