### ISSUE TITLE
NG+ bugs

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#778]
![dq00](https://cloud.githubusercontent.com/assets/7569514/15623868/7655925a-2472-11e6-94da-2a21f20c9583.png)
HD everything, 800x600.

This is a brand new NG+ game (from a previous version if that matters).
- Mispositioned tutorial arrow and highlight. Makes it unable to proceed the battle until you press F1 (which is supposed to take a screenshot... make up your mind, mr. devs).
- All defender classes are unlocked and can be used.

**Comment by larsiusprime** [comment]
You're doing an excellent job, by the way. I'll do my best to have all
these fixed real quick.

On Fri, May 27, 2016 at 7:27 PM, ManDude <notifications@github.com> wrote:

> [image: dq00]
> <https://cloud.githubusercontent.com/assets/7569514/15623868/7655925a-2472-11e6-94da-2a21f20c9583.png>
> HD everything, 800x600.
>
> This is a brand new NG+ game (from a previous version if that matters).
>
>    - Mispositioned tutorial arrow and highlight. Makes it unable to
>    proceed the battle until you press F1 (which is supposed to take a
>    screenshot... make up your mind, mr. devs).
>    - All defender classes are unlocked and can be used.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/778>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-MqyREz0rypsWBfBpbp-A_rWC_f1ks5qF4wPgaJpZM4Io88q>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Fixed in 0.7.8
