### ISSUE TITLE
Health bar artifact

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#779]
![dq02](https://cloud.githubusercontent.com/assets/7569514/15623986/d39643b8-2474-11e6-8f9f-686e75771417.png)
This health bar bobs up and down, and it gets artifact'd when it goes down.

HD everything, 800x600.

**Comment by ManDude** [comment]
Doesn't seem to bob in some resolutions but it still gets artifact'd when Ozimal is at certain y-planes of the map.

**Comment by ManDude** [comment]
Seems to be fixed with the new way HP bars are handled. Cool!

**Comment by larsiusprime** [comment]
Sweet!

On Mon, Jun 27, 2016 at 8:04 PM, ManDude <notifications@github.com> wrote:

> Seems to be fixed with the new way HP bars are handled. Cool!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/779#issuecomment-228920625>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-J8NDs-fAtkvfVe8gHHDSlwt82Iwks5qQHMFgaJpZM4Io9GZ>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
