### ISSUE TITLE
Defenders not disabled in levels that disable defenders

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#781]
![dq04](https://cloud.githubusercontent.com/assets/7569514/15624509/2081fa76-2481-11e6-8fce-0a33d003765b.png)
This is "Following Zelemir", a level in which Rangers are disabled.

"The Way Out"  is supposed to disable Berserkers, Ice Mages, Healers and Dragons but you can still place them.

**Comment by larsiusprime** [comment]
This is fixed, and will be updated in the next continuous integration build.

On Fri, May 27, 2016 at 9:08 PM, ManDude <notifications@github.com> wrote:

> [image: dq04]
> <https://cloud.githubusercontent.com/assets/7569514/15624509/2081fa76-2481-11e6-8fce-0a33d003765b.png>
> This is "Following Zelemir", a level in which Rangers are disabled.
>
> In contrast, "The Way Out" is supposed to disable Berserkers, Ice Mages,
> Healers and Dragons but you can still place them.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/781>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-FISjDgh9a3nzNdZqYsmhWpsXGUoks5qF6O3gaJpZM4Io-M9>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
