### ISSUE TITLE
"Azra" instead of Azra's name in "What Now?"

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#782]
![dq05](https://cloud.githubusercontent.com/assets/7569514/15624554/29033c2c-2482-11e6-8aef-f1ed408af039.png)
I have named Azra "Azzzzzzra", not "Azra".

**Comment by larsiusprime** [comment]
Fixed in 0.7.9

**Comment by ManDude** [comment]
![dq10](https://cloud.githubusercontent.com/assets/7569514/15871126/e7f0ce72-2cea-11e6-8b12-5225cce5c99a.png)
Now it's broken.

Also, Ketta appears as Ketta instead of Ketta's name in this cutscene too.

**Comment by larsiusprime** [comment]
Fixed in 0.9.0
