### ISSUE TITLE
Buggy save file importing from DQOld to DQNew

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#783]
When I import that into DQ XD it says have 90/90 gold stars on the main menu. I load up Play+ and it says I have 111 gold stars in the Bonus menu. Back to the main menu, 90/90. Neither are the correct star count.

Marathon achievements are both buggedat 6200% as well.

http://www.speedyshare.com/pJ6ke/dqsave.zip

**Comment by larsiusprime** [comment]
Thanks, excellent bug report :D

**Comment by larsiusprime** [comment]
Okay, so this looks like the save file is importing fine, it's a display/calculation issue.

By manual count, you have:
- 90 gold stars in regular game
- 111 gold stars in new game+
- 201 gold stars total

Diagnosis:
- The save slot menu is only counting regular game stars
- The regular game bonus menu is only counting regular game stars
- The new game+ menu is only counting new game+ stars

Simple fix in the works. Expect it in 0.7.8.

Thanks for this good report!

**Comment by larsiusprime** [comment]
- [ ] Fix star count
- [ ] Fix marathon display bug

**Comment by larsiusprime** [comment]
Not sure what happened, but the marathon achievements are displaying correctly on my machine...

**Comment by larsiusprime** [comment]
Fixed in 0.7.8

**Comment by dqhol** [comment]
The endurance/marathon achievements are now 6400% for me. Wtf? It went up by 200%? I wonder why.
