### ISSUE TITLE
Fire Ball's ability info menu (or whatever) is a mess

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#784]
![dq00](https://cloud.githubusercontent.com/assets/7569514/15630260/ad17f694-252a-11e6-841b-ad360e2c0d48.png)

**Comment by larsiusprime** [comment]
In all resolutions or just some?

On Sat, May 28, 2016 at 5:19 PM, ManDude <notifications@github.com> wrote:

> [image: dq00]
> <https://cloud.githubusercontent.com/assets/7569514/15630260/ad17f694-252a-11e6-841b-ad360e2c0d48.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/784>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-BtprM2g7r0H2qVW5YABDlUBKwbtks5qGL-KgaJpZM4IpKzm>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
800x600 only.

Also, it will always says Splash does 0 damage for 0 tiles regardless of skill points put into it.

**Comment by dqhol** [comment]
Wrenna's Ice Splash is also 0 dmg, 0 tiles.

**Comment by larsiusprime** [comment]
This should be fixed in 2.2.1
