### ISSUE TITLE
Can select defender to place even though they're already placed

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#788]
0.7.8, win7x64, HD mode@1704x960windowed

![dq-place-already-placed](https://cloud.githubusercontent.com/assets/16719964/15676234/bfad453a-2745-11e6-88b2-ec5568ae1171.png)

As you can see, Ketta is already there, next to where I'm about to place her.

I can also select the second one.  Both selections are via keyboard, in Dvorak layout.

**Comment by IBwWG** [comment]
Actually, it's a bit worse than that.  I hadn't tried actually clicking to activate it.  It works: I have three Kettas:

![dq-place-already-placed2](https://cloud.githubusercontent.com/assets/16719964/15676286/f749df9e-2745-11e6-9781-4635b5819d65.png)

Also clicking to select works, even though it doesn't look like you've selected the defender in the pane, but you get the defender cursor in the battlefield (as you can see in the first screenshot.)

**Comment by IBwWG** [comment]
In fact, this lets you place as many copies as you want, even beyond the normal max of 6 per class:

![dq-place-already-placed3](https://cloud.githubusercontent.com/assets/16719964/15676430/7398a378-2746-11e6-8c0b-6879434b6669.png)

Also works with knights, too.  Possibly all classes.

**Comment by larsiusprime** [comment]
Haha. Wow. Confirmed, this was real easy to reproduce.

**Comment by larsiusprime** [comment]
Fixed. Man. What a bug.
