### ISSUE TITLE
Text touchups

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#789]
Journal Day 4 - Education:

- [x] "it's thickness" should be "its"
- [x] "Filled with what..." paragraph should be non-italicized I think, because it's back to Azra's voice

Markos' Name
- [x] "cathedral and shut down" should be "had"

**Comment by ManDude** [comment]
I found some more "it's" instead of "its" in some of the dev journal entries, too.

**Comment by IBwWG** [comment]
- [ ] "hiscourtship" in Fourth Dream

**Comment by IBwWG** [comment]
- [ ] in Evni, "Slak, seated nearby and believing herself..." I think is supposed to be Ketta here...

**Comment by larsiusprime** [comment]
Fixed the it's vs its things. James has to use text-to-speech software because of a nerve injury, so I'm not surprised there's little homophone errors like this here and there.
