### ISSUE TITLE
Possibly not actually a bug, but recruit order is different from DQOld to DQNew

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#794]
![dqqqq](https://cloud.githubusercontent.com/assets/19625520/15679932/baa38d0c-2721-11e6-9849-caddec1f1c96.png)

My only concern is, does this result in any unintended bugs elsewhere?

**Comment by larsiusprime** [comment]
Thanks for being careful -- this is simply a display difference on this one screen. Recruit number 2 is still number 2 internally, we just show them in a different location now. Their order should still be the same in the battle menu and their internal handles should still be consistent.
