### ISSUE TITLE
Poison sound file is corrupt / painful to listen to?

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#795]
In DQ1, there was an easily ignoreable sound effect that played every time an enemy spawned with the Book of Blood/Plague equipped. Now it's a very loud, very distinct, spammable BZW BZW BZW.

**Comment by larsiusprime** [comment]
I'll look into it, hopefully it's a quick fix.

**Comment by dqhol** [comment]
God it's agonizing when you have an archer with high Poison. Just listen to it in DQ Old on Endless with an archer with 9 poison, then listen to it in DQ New. It's subtle in DQO, grating in DQN.

**Comment by larsiusprime** [comment]
Yeah I'll try to address it, just up to my ears trying to solve the memory
leak.

On Wed, Jun 22, 2016 at 9:47 PM, dqhol <notifications@github.com> wrote:

> God it's agonizing when you have an archer with high Poison. Just listen
> to it in DQ Old on Endless with an archer with 9 poison, then listen to it
> in DQ New. It's subtle in DQO, grating in DQN.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/795#issuecomment-227935651>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-OiFSNUZ5vM0Aahl5b2nWdrs1Wf5ks5qOfOzgaJpZM4Iqq52>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Oh I thought this was the bleed sound effect.

**Comment by ManDude** [comment]
Did not run many tests but I don't think this is happening anymore.

**Comment by larsiusprime** [comment]
We had some tweaks to our sound effects in the last build, also I put in a limiter to make sure the same sound doesn't stack.

**Comment by ManDude** [comment]
That's nice. Closing it, then.
