### ISSUE TITLE
Final map layout changed, Zelemir gets scalped.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#796]
![ze](https://cloud.githubusercontent.com/assets/19625520/15680782/f1d20148-2724-11e6-9d06-63dfa0ef6b39.png)

The top of Zelemir's head gets cut off in the final battle due to him being adjusted up one tile. Unless this was an intentional change to keep things symmetrical between Azra and Zelemir on the map? :P I guess it also makes the battle .01% harder, due to enemies having one less tile to reach him. If it's an intended change, disregard.

**Comment by larsiusprime** [comment]
Oh this is *not* an intentional change, I knew something felt off. Let's fix this.

**Comment by larsiusprime** [comment]
Fixed in 0.7.9
