### ISSUE TITLE
Zelemir gets wounded by Eztli-Tenoch's Dragonfire, + ET's Dragonfire says 0 dmg.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#797]
1. Start the battle, plunk a defender down, watch and wait. Zelemir goes from 745 to 545 HP.

2. Mouseover ET's spellbook. Dragon Fire: 0 dmg.

**Comment by larsiusprime** [comment]
- [ ] ET spellbook tooltip, Dragon fire has wrong stat
- [ ] ET can target zelemir/azra with lightning
- [ ] ET can target zelemir/azra with dragonfire

**Comment by larsiusprime** [comment]
Fixed in 0.7.9
