### ISSUE TITLE
Bakal out of line in A Bittersweet End.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#798]
![ze](https://cloud.githubusercontent.com/assets/19625520/15681571/b5aa5e60-2727-11e6-8a98-c02ccfac34ff.png)

Looks much less cool. :(

As an aside, why does ET explode into giant balls instead of dust/fragments now in the best ending, when Zelemir stabs him? It looks... weird.

**Comment by larsiusprime** [comment]
It's an optimization. Performance is utterly, utterly terrible if it's single pixels. I can tweak it, but it's going to have to be bigger bits than just individual pixels.

**Comment by larsiusprime** [comment]
Fixed in 2.0.8b
