### ISSUE TITLE
Shell Beast missing colors in preview and in battle

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#800]
![ze](https://cloud.githubusercontent.com/assets/19625520/15682325/2217ed80-272b-11e6-9eb1-a22b7396ec40.png)

**Comment by dqhol** [comment]
Bizarrely, this only appears during Play's Bonus map, not Play+. During Play+ it's filled in as normal. Why...?

**Comment by larsiusprime** [comment]
Probably because enemies in normal and NG+ are technically different and I forgot this one's colors...

**Comment by larsiusprime** [comment]
Fixed in 0.7.9
