### ISSUE TITLE
"3x stone skull" gives "equip" option but a single stone skull "cannot be equipped"

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#802]
0.7.8, win7x64, HD mode@1704x960windowed

Beat "Old Friends, New Enemies" on Extreme (NG+) on the first time playing the level within NG+.  The post-battle popup gives the 3x stone skull first...rest is in the title :)

**Comment by IBwWG** [comment]
0.8.0, win7x64, HD mode@1704x960windowed
Happened on Ozimal, I earned the bronze, then the stone, and the bronze had the equip option.

**Comment by IBwWG** [comment]
Also, beating Sons of Krast on extreme just now gave me only a bronze skull popup, no stone skull popup.

**Comment by Geardan** [comment]
Yeah, this seems to happen any time you get multiple rewards by skipping the next-to-last star. I'm playing on Heroic Mode, but I doubt that changes it.

**Comment by IBwWG** [comment]
Exactly :)
