### ISSUE TITLE
"Azra learned a new spell" on NG+ after Laksos

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#803]
0.7.8, win7x64, HD mode@1704x960windowed

Just what the title says.  Got the popup for the healing spell, which I already have...

**Comment by IBwWG** [comment]
Likewise after The Monastery Gates, I got to name Bakal...but he's already part of the troupe.

**Comment by larsiusprime** [comment]
Hmmm, I need to check what the behavior is in the original game. Does is suppress the spell get notices? I bet it does.

As for Bakal, the name cards are supposed to show up in NG+. Does his just show up late?

**Comment by IBwWG** [comment]
Might be on time, I had hit skip in this case.  I do really enjoy the storyline but I was focusing on testing the battles just now :)

**Comment by ManDude** [comment]
Happened with Lightning at the start of the 2nd battle for me.

I have Tutorials and Dialogue set to "New Battles Only", by the way.

The spell description also assumes Azra is at LV 1, even if she is at LV 36.

**Comment by ManDude** [comment]
not actually fixed

**Comment by larsiusprime** [comment]
Fixed in 2.2.2 1/8 build.
