### ISSUE TITLE
Bizarre borders on DQ Old Widescreen.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#806]
It seems like the borders  outside the normal game field should be black, but they're just replaced by cobblestone in many of the maps. Even the maps that should take place on the river.

Except in one of the maps I found, whereit's filled in around the edges...?

![ze](https://cloud.githubusercontent.com/assets/19625520/15696382/dc20b61a-277d-11e6-9334-77cda078828d.png)

**Comment by dqhol** [comment]
Additionally, the wider your screen gets, the less of the world map you can actually see. Intended?

![ze](https://cloud.githubusercontent.com/assets/19625520/15696470/8f48040a-277e-11e6-8d60-6175aced2bc0.png)

**Comment by dqhol** [comment]
Eesh, this level looks really bad on super wide screen. It really needs black borders, or something that isn't level terrain. (How many people will play with Old Graphics and wide resolution, though?)
![ze](https://cloud.githubusercontent.com/assets/19625520/15696510/0f99169e-277f-11e6-9dd7-ce07c94a574e.png)

**Comment by dqhol** [comment]
This looks a bit silly, but again, not many people gonna play like this. :P

![ze](https://cloud.githubusercontent.com/assets/19625520/15696563/97592574-277f-11e6-8c3e-65671e62cee2.png)

**Comment by larsiusprime** [comment]
It's a known issue, I'm working on a fix for it.

On Tue, May 31, 2016 at 9:32 PM, dqhol <notifications@github.com> wrote:

> This looks a bit silly, but again, not many people gonna play like this. :P
>
> [image: ze]
> <https://cloud.githubusercontent.com/assets/19625520/15696563/97592574-277f-11e6-8c3e-65671e62cee2.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/806#issuecomment-222876828>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-J2HUaOuVL09lzwgM1dwWbDw649-ks5qHO9OgaJpZM4IrIKw>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
I might actually play old graphics (if I knew that helped FPS) and wide res, because I have a low-powered computer.  But by wide I mean HD @ 1920x1080.  Do you mean a higher one?

**Comment by larsiusprime** [comment]
The borders issue only really comes into play when you've got a level that's less than 1920x1080 using the original art. At 1920x1080p we've got just enough size to double scale the pixels so we don't have to pad the level borders

**Comment by larsiusprime** [comment]
- [ ] Fix levels with stupid or broken borders
- [ ] Fix double scale speech bubble

**Comment by larsiusprime** [comment]
Fixed in 0.8.3

It's not *perfect* -- like some of the river levels have rivers that are cut off on the sides when ideally they should continue, but I've got bigger fish to fry at the moment so as long as it's not horribly horribly ugly this will have to do.

The idea is to pad out the empty space with *something* that doesn't affect the integrity of the level (ie impassable walls). This will only show up for the minority of players who play using original art at a resolution higher than 800x600 but lower than 1920x1080
