### ISSUE TITLE
x16 Speed + PSI Shield = Stuck, blank white screen when Azra dies.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#811]
PSI Shield makes the screen flash white when she gets hit. On x16 speed, the screen remains white when the 'Azra Died' message pops up. But the popup is under the flash. If I blindly click around I can still manage to hit the 'okay', at least.

![ze](https://cloud.githubusercontent.com/assets/19625520/15696978/b9b5af30-2783-11e6-97cb-e459126bbd1f.png)

**Comment by larsiusprime** [comment]
Fixed in 0.8.1
