### ISSUE TITLE
Unable to use lightning with Shock Lightning equipped.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#812]
![ze](https://cloud.githubusercontent.com/assets/19625520/15697006/f42f0b34-2783-11e6-832f-c4271d482de2.png)

**Comment by dqhol** [comment]
I can use it if I click on a crystal, but not enemies. Strange.

**Comment by larsiusprime** [comment]
Both of them seem to work now, but neither of them is applying the appropriate effect...

- [ ] Make shock lightning work
- [ ] Make chain lightning work
- [ ] Ensure they work together

**Comment by larsiusprime** [comment]
Fixed in 0.9.5
