### ISSUE TITLE
Sorceress became lazy in the transition to DQNew, does nothing in final bonus battle.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#813]
![ze](https://cloud.githubusercontent.com/assets/19625520/15697183/c28eda1c-2785-11e6-8e72-432128156c90.png)

She isn't animated anymore, she doesn't fight with you by casting spells, she doesn't even want to be boosted anymore. Shame on her! :(

**Comment by larsiusprime** [comment]
- [ ] Show correct animation
- [ ] Should participate in battle
- [ ] Show boost button

**Comment by larsiusprime** [comment]
Fixed in 0.8.3
