### ISSUE TITLE
After restore formation, clicking defender buttons does nothing

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#815]
0.8.0, win7x64, HD mode@1704x960windowed

NG+

Gone Fishing, extreme.

Place dragon.

Restart battle.  Yes, sure.  Yes, restore.

Now, clicking dragons 2-6 shows the button press in during mousedown, but does not select them.

**Comment by IBwWG** [comment]
Workaround, select dragon class (even though it's already selected, seemingly) and then it works.

**Comment by larsiusprime** [comment]
Fixed in 0.8.1
