### ISSUE TITLE
Royal Records Room map really wonky with spawners and decoration.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#817]
![ze](https://cloud.githubusercontent.com/assets/19625520/15703672/9d21f05a-27b4-11e6-8690-b0cf9dc9a93e.png)

Terrain decoration appears on the pathway, which I've seen appear nowhere else. (But  monsters don't walk there, so is it really the pathway...?)

Also the slots where monsters spawn on the sides are filled in.

I'm starting to think it might be worth comparing all the DQOld maps with DQNew to spot any irregularities like Zelemir's spot in the last level and this.

**Comment by larsiusprime** [comment]
Fixed in 0.8.1
