### ISSUE TITLE
Azra instantly takes damage on Sons of Krast level, no enemies visually spawn.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#818]

**Comment by larsiusprime** [comment]
Whoops, forgot to chop the sidequests down from 15 pixels to 14 pixels (the original game had a "dummy" layer of tiles that lived underneath the wave bar that is not entirely extraneous).

This results in a level with no valid path to Azra, thus the enemies just teleport to her directly!

Fixing in 0.8.1...
