### ISSUE TITLE
Buggy Book: Furious End

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#820]
In DQ Old, Furious End had no record of Furious End being active as an icon in the unit's stats. But it did have the Frenzy icon above it. Not sure if it actually was active at all.

In DQ New, Furious End has no record as being active in the unit stats or on the unit itself. The Frenzied icon no longer appears.

**Comment by larsiusprime** [comment]
Fixed in 2.0.7
