### ISSUE TITLE
Summon / Boost animations end in a sharp line on top, something cut off?

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#825]
I only really noticed this when pausing the game to check stats when summoning units, others might not notice it. Or it could be intentional. :P

![ze](https://cloud.githubusercontent.com/assets/19625520/15735902/1fefc970-286a-11e6-9db9-59860eb8e20e.png)

**Comment by ManDude** [comment]
This is probably intencional since it's always been a thing ever since pretty much the first e ver release of the game.

**Comment by larsiusprime** [comment]
Yeah it's kind of an artifact of the way the animator made the art in the
first place.

On Thu, Jun 2, 2016 at 8:39 AM, ManDude <notifications@github.com> wrote:

> This is probably intencional since it's always been a thing ever since
> pretty much the first e ver release of the game.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/825#issuecomment-223294221>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-IqJoB0Rq42GuVkRRf43WAsOlDiTks5qHt0YgaJpZM4IsPly>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
