### ISSUE TITLE
Defenders missing their equipment

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#826]
0.8.1, win7x64, HD mode@1704x960windowed

I'm still trying to figure out when exactly this happens, but I earlier had two Bezerkers with no swords equipped, but I was sure that wasn't correct.  I thought, maybe that's because I upgraded what they were carrying before, which then got unequipped.

Just now, possibly related, my second ice mage had no armour equipped on the main screen, but when I clicked on her, it showed something in the upper display for her armour (A+B).  I should've taken a screenshot, now I can't get it to do it--unequipping makes it look correct now.

**Comment by larsiusprime** [comment]
Hm, sorry to hear about this. Let me know if you see anything more concrete with this.

And what is the "main screen" (battle screen?)

**Comment by IBwWG** [comment]
Sorry, the main screen being the party screen, where you can pick a defender to equip or skill-upgrade.

**Comment by larsiusprime** [comment]
Ah thanks. I wonder if it's just a display bug, but if you can make it happen again in an easily describable way then I'll be sure to fix it.

**Comment by IBwWG** [comment]
![dq-senna-weapon](https://cloud.githubusercontent.com/assets/16719964/15788139/3e87ca10-29c6-11e6-84a2-0b84fa306acc.png)
0.8.2, win7x64, HD mode@1704x960windowed

So you can see Senna's button on the right side shows she has no weapon, but on the left side it shows she has something for 90+47 (although the empty Weapon button is also there on the left), but actually that belongs to my renamed Wrenna, who was the last one selected.

I think there are two display issues happening here, but possibly also something else, i.e. why is she missing her weapon in the first place?  (She definitely had something before, not that I could tell you exactly what it was.)

**Comment by IBwWG** [comment]
OK, I think the missing weapon thing is just a logical error on my part.  You upgrade a weapon at the hermit, it gets auto-unequipped.  I just hadn't thought about it.

So I think maybe the only real issue is that the weapon in the upper-left shows whatever the previously selected defender had equipped, when the newly selected defender does not have a weapon equipped.

**Comment by ManDude** [comment]
Still happening.

1. Equip weapon.
2. Upgrade it in any Hermitage.
3. (I used Kozomon's Scepter to test this) Bam:
![dq02](https://cloud.githubusercontent.com/assets/7569514/15912856/bfb53ee0-2dce-11e6-9fc0-1cef55d00d2b.png)
The item was not unequipped properly, as the stats still say base attack + upgraded weapon's attack. I wonder if this happens to armor too.

**Comment by larsiusprime** [comment]
@ManDude -- I think I fixed this. Make sure you're running 2.0.7b
