### ISSUE TITLE
Book of Synergy does nothing with water. [Does nothing with Play+ water creeps, as intended, disregard]

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#827]
Water creeps still can't be burned, even though BoS says "ice, water and  fire no longer cancel."

I assume the "Immune to Burn" tag takes priority.

**Comment by larsiusprime** [comment]
Do you mean to say -- enemies with an immunity to burn can't be hit with fire, or *enemies that are physically in the water* can't be hit with fire?

The former would not be a bug, because "immune to burn" is a property of the enemy itself unrelated to the environment, the latter *would* be a bug.

**Comment by dqhol** [comment]
Oh, I was confused. Because I thought that all enemies capable of getting in the water were immune to burn, therefore BoS was meant to override 'Immune to Burn' for water creeps...

But they're only immune to burn in Play+. In normal play they aren't, which I forgot about. Nevermind, then.
