### ISSUE TITLE
Null Object Reference during "The Monastery Gates" Cutscene for Original Cutscenes setting

### ISSUE THREAD

**Issue by gibsonk** [larsiusprime/tdrpg-bugs#829]
# Basic Info
Windows 7 x64
Download
DQ1DX demo
Version 0.8.1 Build 1

# Steps to Reproduce

1. Turn on Original Cutscenes setting
2. Go to cutscene for "The Monastery Gates"
3. After the line "Indeed, for there are many dangers in the pit.", click next.

# What I expected to happen

Cutscene continues as normal

# What happened instead

Game crashes with Null Object Reference. Same line does not crash for HD cutscenes.

**Comment by larsiusprime** [comment]
Thanks!

**Comment by larsiusprime** [comment]
Fixed in 0.8.2
