### ISSUE TITLE
Speed Up/Down Hotkey Setting change not applying

### ISSUE THREAD

**Issue by gibsonk** [larsiusprime/tdrpg-bugs#830]
# Basic Info
Windows 7 x64
Download
DQ1DX demo
Version 0.8.1 Build 1

# Steps to Reproduce

1. Go to Controls Setting
2. Change hotkey settings for -speed and +speed to 'Z' and 'V'
3. Go to a battle and press 'Z' and 'V'.

# What I expected to happen

'Z' reduces battle speed, 'V' increases battle speed.

# What happened instead

Both 'Z' and 'V' have no effect. Original hotkeys '-' and '+' still work.

**Comment by larsiusprime** [comment]
Fixed in 0.8.2!
