### ISSUE TITLE
Eztli-Tenoch may have a right hand man, but all his other bros abandoned him.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#835]
Applies in both Play and Play+, on Casual and Normal.

![ze](https://cloud.githubusercontent.com/assets/19625520/15767008/54b81114-2912-11e6-8222-8fc0482b8dae.png)

Also in battle this means there's only two waves, the hand and then one wave of normal revenant. Nothing come after them.

**Comment by larsiusprime** [comment]
Fixed in 0.8.3
