### ISSUE TITLE
[Edited]  ET's  super dude doesn't have a black box for his "Make me your child" text.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#836]
![ze](https://cloud.githubusercontent.com/assets/19625520/15767168/ecb49d60-2913-11e6-9a70-02191d39418a.png)

Where in the world did this come from? o_O This is an entirely new line not found in DQOld. Is it even translated in the other languages?

**Comment by larsiusprime** [comment]
Not a bug, it's an intentional line that's been added. I should double
check whether it's meant to be shown in "magic symbols or not" -- but if
you're playing NG+ it'll show up in normal text.

On Thu, Jun 2, 2016 at 9:47 PM, dqhol <notifications@github.com> wrote:

> [image: ze]
> <https://cloud.githubusercontent.com/assets/19625520/15767168/ecb49d60-2913-11e6-9a70-02191d39418a.png>
>
> Where in the world did this come from? o_O This is an entirely new line
> not found in DQOld. Is it even translated in the other languages?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/836>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-CzTj-sQUNp5A_k1k6Qr9_xJE1Izks5qH5XNgaJpZM4ItKEq>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by dqhol** [comment]
Yeah, it's in magic runes in Normal, but he lacks the black speech bubble that every other (I think) bit  of magic runey / evil speech has.

**Comment by larsiusprime** [comment]
It's an oversight, and it's still there, but it's not something I'm gonna worry about fixing at this point.
