### ISSUE TITLE
Colours swapped on dragons (except Niru)

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#838]
0.8.1, win7x64, HD mode@1704x960windowed

![dq-colour-swap](https://cloud.githubusercontent.com/assets/16719964/15771551/d96a8eb0-296b-11e6-9ba5-039b2000c8ec.png)

I'd just placed "E" and she looks different on the map than in the group--green and red are swapped, it looks like.  Niru doesn't have that but "Dragon O" does.  U and I only have one colour.  D also has a colour swap too if I go to place her.

**Comment by larsiusprime** [comment]
Do you get this bug with the original art as well, or just the HD art? And if not, what color does the green/red dragon have for her skin in the original art?

**Comment by IBwWG** [comment]
HD art only.  Original looks fine.

**Comment by larsiusprime** [comment]
Cool, and what's the "right" color scheme, so I know which layers to swap
in the HD art?

(Ie is the skin supposed to be green or red for that dragon?)

On Fri, Jun 3, 2016 at 1:21 PM, KJB <notifications@github.com> wrote:

> HD art only. Original looks fine.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/838#issuecomment-223654746>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-JVluWZFVcb0GXxydbRoChcxEfWBks5qIHCfgaJpZM4ItRCr>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
I believe it's the one on the right side.  In the original art both are like that (green wings, red belly) IIRC.

**Comment by larsiusprime** [comment]
Okay, so the sprite needs to match the icon, not the other way around. Got it.

**Comment by larsiusprime** [comment]
Fixed in 0.8.3
