### ISSUE TITLE
Original art showing on redesign screen despite HD sprite setting

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#841]
0.8.2, win7x64, HD mode@1704x960windowed
![dq-redesign](https://cloud.githubusercontent.com/assets/16719964/15789160/15003f9c-29cb-11e6-93aa-64ff5f839e36.png)

**Comment by IBwWG** [comment]
The six along the bottom there...

**Comment by larsiusprime** [comment]
That's the HD art, wonder if it's positioning/rendering artifacts.

**Comment by IBwWG** [comment]
Oh, whoops.  Sorry.  Looked pretty pixelicious...

**Comment by larsiusprime** [comment]
Still possibly a bug, put in a potential fix, who knows if it will work...

0.8.3
