### ISSUE TITLE
CI build out of order & duplicates

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#844]
The full builds of the game seem to come in twins.  Today there was something even stranger, a build of 0.8.3 dated later than the 0.8.4 builds:

![dq-ci](https://cloud.githubusercontent.com/assets/16719964/15798732/862c4fd0-2a43-11e6-9311-0e98bdc15900.png)

**Comment by larsiusprime** [comment]
It rebuilds every time I push to the server. Sometimes I cancel a build or re-run one for a testing purpose. The version numbers should still be reliable. If there's more than one for a version number, go with the latest timestamp.
