### ISSUE TITLE
Dragon Fire does set damage on x16, otherwise random damage.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#845]
Tested vs Super Sheep:

Dragonfire, consistently 389 and 292 damage, alternating. On lower speeds, it's a vast spectrum of burn damage numbers.  Looks like x16 screws with the RNG.

**Comment by dqhol** [comment]
So, I did more testing, after clueing in that it probably wasn't just Dragon Fire but Burn in general. Let's test Niru's burn, shall we?

1/4: Switching from 1/2 to 1/4 had one tick of 1220, then permanent 1225
1/2: Switching from 1 to 1/2 had one tick of  1215, then permanent 1225
x1: Permanently 1225
x2: Permanently 1225
x4: Permanently 1225
x8: 1306, 1143
x16: 1306, 980

Looks like the 'vast spectrum' of damage I saw earlier was just flickering through the speed options, which makes the less fast options do + or - a small  amount of damage for one tick after  the change. Is this speed/damage fluctuation unique to Burn, I wonder, or does it affect all sources of damage?

Also: "Just two testers -- IBwWG & dqhol -- have contributed well over 80% of the bug reports not authored by me."

We counting my many, many dozens of reports on the forum in that? :D

**Comment by IBwWG** [comment]
Yeah I was LTTP eh?  ;)

**Comment by larsiusprime** [comment]
Yeah hollow's been the most long term. Mandude rounds out the top 3.

**Comment by larsiusprime** [comment]
Wonder if this is a display error or a real one. how are you calcing? adding up the damage numbers, or looking at before/after hp? rounding's probably involved somehow

**Comment by dqhol** [comment]
I'm just looking at the numbers that pop up when burn is applied. Let's try looking at the actual HP...

x16 Speed:
Sheep has 49923902 HP.
Takes 1306 burn. 49922595 HP.
Difference of 1307 HP.

Switching to x1 Speed:
Sheep has 49922595 HP.
Takes 980 burn. 49921616 HP.
Difference of 979.

Next tick:

Sheep has 49921616 HP.
Takes 1225 burn. 49920391 HP.
Difference of 1225.

Yeah. Speed is influencing the damage taken by burn, both visually and in actuality. Not just a display error.

**Comment by ManDude** [comment]
Possibly ending way too soon. I'm back on a computer so I'll get to test more.

**Comment by larsiusprime** [comment]
Okay it looks like this isn't as bad as it used to be, but there's still a rounding error creeping in somewhere.

Using dragon fire on the super sheep with an end game max level save results in the following:
1x: 6,757
2x: 6,765 (+8)
...
16x: 6,804 (+47)

And interestingly enough, the extra damage seems like it is entirely accounted for in the very first DOT damage indicator, which is higher than all the rest by the exact amount of the discrepancy. It's easy to see on 2x, on 16x it flashes by too fast.

The amount that it's off by is always the same, and is totally based on the game speed. This makes me hopeful I can fix it.

**Comment by larsiusprime** [comment]
Okay, figured it out.

My fancy fixed timestep does not good if I use the main global flixel update loop rather than my special controlled update loop!

Moved enemy update logic from "update()" to "updateFromModel()" and now their elapsed times are correct and free from errors.

**Comment by larsiusprime** [comment]
Fixed in 0.9.2
