### ISSUE TITLE
Unable to see gear information without placing unit.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#846]
In DQOld, you could select a unit and then mouseover their weapon/armor icon to see it's name and stats.

In DQNew, mousing over gear no longer gives any information without placing the unit first.

**Comment by larsiusprime** [comment]
What version has this bug?

**Comment by dqhol** [comment]
0.8.4
![ze](https://cloud.githubusercontent.com/assets/19625520/15799504/f27e20da-2a2c-11e6-805a-e6ed0e9e9ddb.png)

This is what I'm talking about.

**Comment by larsiusprime** [comment]
This is fixed in 0.9.2
