### ISSUE TITLE
Tutorial level randomly generated terrain is waaay out of bounds.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#848]
![ze](https://cloud.githubusercontent.com/assets/19625520/15799552/71ee2274-2a2e-11e6-8f27-a19b0c940f9a.png)

Well, the good news is that in Tutorial 2 it's where  it should be... just... almost non-existent.

![ze](https://cloud.githubusercontent.com/assets/19625520/15799567/e75eb442-2a2e-11e6-99e4-0c18eeadf963.png)

**Comment by ManDude** [comment]
I feel like this is some graphical glitch/oversight with the HD tilesets since I get way more rocks and bumps with orig gfx compared to HD gfx.

**Comment by larsiusprime** [comment]
It's actually not really a "bug" -- those are rocks and stuff on top of the black cliff tileset. It's just different than the old style. There's plenty of genuine nitpicks to be made with DQDX's art direction, but I'm just gonna move forward on DQ2 rather than noodle on this forever.
