### ISSUE TITLE
After recruiting Slak on a new file, names don't change in movies/map.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#850]
I made a new file. Named Azra Werdup. Recruited Slak, changed her name to Vvvvhftn.

In the description text of the next stage, it called her Werdup. In the next cutscene, she was Werdup. When I select her in battle she's Vvvvhftn, same in the party menu.

Slak's name is frozen as Slak too, even though I've renamed him to gibberish. I don't think this affects older save files.

It seems that specifically recruiting Slak triggers this, Azra's name can be successfully changed up until you get him?

**Comment by IBwWG** [comment]
I noticed this too, after renaming Wrenna a second time (the first time as prompted in NG+, later just in the party screen).  For a few cutscenes, her name was still the old name.  At some point it caught up automatically.

**Comment by IBwWG** [comment]
Also a related issue, after winning in NG+ on "the way out", the final slide of the cutscene had "$MCG" in it instead of Azra's name.

**Comment by dqhol** [comment]
Actually, you  don't even have to recruit Slak, I see.

Start new file, rename Azra to Azratest, close party menu, click first stage. Still calls her Azra.

**Comment by larsiusprime** [comment]
Appears to be fixed in latest build.
