### ISSUE TITLE
Capitalization errors in certain journal entry

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#852]
![dq03](https://cloud.githubusercontent.com/assets/7569514/15799985/0bc0efc6-2a66-11e6-8a24-3dbce6d99af0.png)
The names highlighted in there are not written in full caps unlike every other time Slak writes to Azra's journal.

**Comment by larsiusprime** [comment]
Not only that, somewhere along the line I managed to delete everything but the default text font. 

Fixing....

**Comment by larsiusprime** [comment]
- [ ] Fix missing bold text
- [ ] Fix case

**Comment by larsiusprime** [comment]
Fixed in 0.9.2
