### ISSUE TITLE
Enemy stats don't update live

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#855]
![dq05](https://cloud.githubusercontent.com/assets/7569514/15800101/b29b9d8a-2a68-11e6-8ff5-3b46ecfc9391.png)
River Ghouls have 1 speed point. Since this River Ghoul has the Happy status effect, the stats menu for the River Ghoul should say it has 1.15 speed.

**Comment by ManDude** [comment]
Happens with any status effect and enemy, not limited to just Happy or just River Ghouls.

**Comment by larsiusprime** [comment]
Not actually a bug, the game doesn't update the core stats menu based on temporary status effects. Defender's don't have speed updated when they're frenzied, for instance.

I might consider adding something to indicate temporarily modified stats in the future, but not at the moment.

**Comment by ManDude** [comment]
Really? This was a thing for enemies in DQOld, though.

**Comment by larsiusprime** [comment]
Are you sure? If you can confirm it did this in DQOld I'll update it for
DQDX.

On Wed, Jun 8, 2016 at 12:15 PM, ManDude <notifications@github.com> wrote:

> Really? This was a thing for enemies in DQOld, though.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/855#issuecomment-224662868>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-K9BDwFuZcis7y6ldBxSHPFZ2Ervks5qJvi9gaJpZM4IuI9a>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Yep.
![dq01-1](https://cloud.githubusercontent.com/assets/7569514/15903963/14aea38c-2da7-11e6-9a15-c9bc97da88d3.png)
![dq01-0](https://cloud.githubusercontent.com/assets/7569514/15903964/14afb894-2da7-11e6-9f13-45672671b1a0.png)
The Chill slows down by 65%.
