### ISSUE TITLE
Journal entries shared across savefiles?

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#858]
![dq08](https://cloud.githubusercontent.com/assets/7569514/15800289/06a300e0-2a6d-11e6-81b3-26ad8180e6f0.png)
I'm not sure if this is intentional, but I have just started a new NG+ game and already have the Evni entry unlocked (may be a bit hard to see). This is on savefile 2, savefile 1 is at Eztli-Tenoch in NG+.

**Comment by ManDude** [comment]
Progressed a bit on this new savefile. Journal looks weird now:
![dq16](https://cloud.githubusercontent.com/assets/7569514/15800556/742088fc-2a74-11e6-9c4c-48fdf9a6f6a8.png)

**Comment by larsiusprime** [comment]
I think this is because the unlock requirement for Evni is simply to have the item, which you do in NG+. Weird, but not worth fixing.

**Comment by ManDude** [comment]
I noticed this with other entries like the Super Sheep one but yeah it's not really a big issue.
