### ISSUE TITLE
Can use classes in NG+ whose hero hasn't been (re)discovered yet.

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#859]
1. Start a new NG+ game.
2. Enter first level.
3. You can place all classes despite having only met Slak yet.

**Comment by larsiusprime** [comment]
Fixed in 0.9.2

**Comment by IBwWG** [comment]
Oh, you weren't supposed to be able to do that?  NG+ is gonna be way harder :P
