### ISSUE TITLE
Achievements that check for stars have broken progress

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#863]
Very similar to #862 in that it shows the amount of stars I have * 100 instead of an actual percentage.
![dq11-0](https://cloud.githubusercontent.com/assets/7569514/15800430/ea924a7e-2a70-11e6-9322-e57e709ef840.png)
![dq11-1](https://cloud.githubusercontent.com/assets/7569514/15800431/ea95bc22-2a70-11e6-959c-812111fbe32b.png)

**Comment by larsiusprime** [comment]
Fixed in 0.9.2
