### ISSUE TITLE
Sidequest 1's layout seems wrong

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#864]
![dq13](https://cloud.githubusercontent.com/assets/7569514/15800457/2a62bc1e-2a72-11e6-8c3e-50a8278f0cae.png)
Blue spawn point near Azra, I think Azra's in the wrong position too (I think she was at the bottom-left) and the yellow space is at the bottom left instead of bottom-center.

I don't actually have the old DQ1 to test this right now but this does not look right at ALL.

**Comment by larsiusprime** [comment]
You're right, this is messed up. The blue spawn point needs to be on the bottom, and the yellow spot & Azra are switched.

**Comment by larsiusprime** [comment]
Fixed in 0.9.0
