### ISSUE TITLE
Phased out enemies don't get affected by spell/attack

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#865]
This one is quite severe.

Crystal, dragon fire, and pretty much every other AoE attack doesn't work on phased out enemies.

**Comment by larsiusprime** [comment]
What was the behavior in the original game?

**Comment by ManDude** [comment]
In DQOld, Pushback and Dragon Fire could hit phased enemies. In DQNew, they can't be hit by anything.

**Comment by larsiusprime** [comment]
Kay, I'll fix it so spells can target them.

What about AOE from the Healer, sleet/blizzard from ice mage, and splash
from ice splash/fireball? Did those work in DQOld?

On Tue, Jun 7, 2016 at 10:46 PM, ManDude <notifications@github.com> wrote:

> In DQOld, Pushback and Dragon Fire could hit phased enemies. In DQNew,
> they can't be hit by anything.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/865#issuecomment-224479970>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-B2dQ8DR-DkcYqVqIz-qwGGFYphQks5qJjsDgaJpZM4IuJ3H>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Healer AoE worked; Sleet worked; Ice Splash splash did not; Blizzard worked; Roar worked; Fire Ball splash did not.

**Comment by larsiusprime** [comment]
- [ ] Pushback should work on phased
- [ ] Dragon fire should work on phased
- [ ] Lightning should NOT work on phased
- [ ] Crystals should work on phased
- [ ] Healer AOE should work on phased
- [ ] Ice mage AOE should work on phased

**Comment by ManDude** [comment]
Crystals did not work on phased in DQOld.

**Comment by larsiusprime** [comment]
Fixed in 0.9.2

Now any splash attack that comes from a skill that has the "area" flavor will be able to hit phased enemies. I tested it and crystals do not work on phased, but this might make roar, fireball, ice splash affect phased enemies now, which I would be fine with.
