### ISSUE TITLE
Slak is an incredibly soothing influence on text

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#868]
And by that I mean that line appears artifacted:
![dq18](https://cloud.githubusercontent.com/assets/7569514/15800945/8a876e26-2a7e-11e6-973c-b329daa2c2d7.png)
800x600, HD.

**Comment by IBwWG** [comment]
0.8.2, win7x64, HD mode@1704x960windowed didn't notice at that resolution.  Might be specific to 800x600
