### ISSUE TITLE
Recruit Substate

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#87]
Stage 1:
- [x] Basic flixel-ui elements, unskinned

Stage 2: 
- [x] Show correct classes available in this town as tabs
- [x] Fetch correct class names & descriptions via firetongue

Stage 3:
- [x] Show the correctly drawn character icon
- [x] Randomly generate colors/name for the initial character by using CultureBucket
- [x] Show the color selection interface (borrow from the color swatches used in flixel-editors' "Animator")
- [x] Let the user choose new colors, update the sprite

Stage 4:
- [x] When character clicks "buy" money is checked & character is recruited
- [x] Recruiting character shows a "you got" state and adds them to party
- [x] Recruited character has the correct color choices
- [x] Cost of the next character increases correctly according to the data formulas

**Comment by ProG4mr** [comment]
Here are some bugs and things TODO in recruit substate:

- [ ] `charGraphics.get_skin().list_color_features` only works properly for berserker class
- [ ] `Main.OMNI.party_data.getRecruitCost()` is returning a (temporary) fixed cost
- [ ] for some reason defender.tsv has zero entries inside firetongue
- [ ] nothing is happens if we confirm hire and there is a name collision (same as legacy)

**Comment by larsiusprime** [comment]
Great, I'll look at this

On Mon, Mar 9, 2015 at 7:33 PM, TiagoLr <notifications@github.com> wrote:

> Here are some bugs and things TODO in recruit substate:
>
>    -  charGraphics.get_skin().list_color_features only works properly for
>    berserker class
>    -  Main.OMNI.party_data.getRecruitCost() is returning a (temporary)
>    fixed cost
>    -  for some reason defender.tsv has zero entries inside firetongue
>    -  nothing is happens if we confirm hire and there is a name collision
>    (same as legacy)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/87#issuecomment-77974189>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Great, I'll look at this. 

1. I think I found the defender.tsv bug, it was being stored under the "defender" id, so I moved it to "ui" where everything else is.
