### ISSUE TITLE
Enemy description bug

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#870]
![dq20](https://cloud.githubusercontent.com/assets/7569514/15801177/ef23a65a-2a84-11e6-9f1e-7159e9869955.png)

**Comment by ManDude** [comment]
![dq20-1](https://cloud.githubusercontent.com/assets/7569514/15801203/3c443f4e-2a85-11e6-9067-2064cc411833.png)
800x600, HD.

**Comment by larsiusprime** [comment]
Good catches :) Thanks!

**Comment by larsiusprime** [comment]
- [ ] Fix armored spitter
- [ ] Fix cultist @ 800x600

**Comment by larsiusprime** [comment]
Fixed in 0.9.2
