### ISSUE TITLE
Roar has a square range

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#872]
![dq24](https://cloud.githubusercontent.com/assets/7569514/15801927/fce7d43e-2a9b-11e6-95bf-e3ddc2fcf816.png)
Niru just used Roar and, as you can see, it uses a square range instead a circle one.

**Comment by larsiusprime** [comment]
Wow, unexpected benefit of the AOE highlight. You can confirm this isn't just a visual glitch, ie, enemies outside the square (but where a circle might be) definitely don't get hit, and every enemy in the square (ie, the corners where an interior circle might not be) does get hit?

**Comment by ManDude** [comment]
The square is the same range as the meelee range (which is what Roar uses), so it doesn't seem to cause any bad things.

**Comment by larsiusprime** [comment]
Fixed for some time now.
