### ISSUE TITLE
Sidequest 7 boss has wrong name

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#873]
![dq25](https://cloud.githubusercontent.com/assets/7569514/15802114/8d6dd8f6-2aa0-11e6-8171-d81e3b09fc46.png)
Should be saying Revenant++, not Revenant+. All of its boss spawns (probably) don't have ++, only +.

**Comment by larsiusprime** [comment]
Fixed in 0.9.2
