### ISSUE TITLE
"Passed (Normal)" instead of "Passed (advanced)"

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#875]
![dq26](https://cloud.githubusercontent.com/assets/7569514/15802246/00ccb9b8-2aa4-11e6-96ce-20692fb521bf.png)
Every other difficulty name is written in lowercase in this screen.

**Comment by dqhol** [comment]
I was about to submit this. One of those is supposed to be Advanced, I think? This is passing a level for the first time on Extreme.

![ze](https://cloud.githubusercontent.com/assets/19625520/15803441/ea05dba8-2aab-11e6-8e84-df3751952e45.png)

And this is passing one on Advanced.

![ze](https://cloud.githubusercontent.com/assets/19625520/15803464/cc38cbde-2aac-11e6-95c9-c23c82a288be.png)

It's either that, or Advanced rewards aren't displaying in the rewards screen.

**Comment by dqhdbughunter** [comment]
related bug: When winning a battle on Advanced difficulty, the additional rewards are shown as (Normal), for example "Passed (Normal)" instead of "Passed (Advanced)"

**Comment by ManDude** [comment]
Hmm, battles don't have a reward for passing on normal. Good catch.

**Comment by ManDude** [comment]
Still unfixed, renamed title to something more accurate.

**Comment by larsiusprime** [comment]
Fixed in the next build.
