### ISSUE TITLE
Achievement popup doesn't like asterisks.

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#876]
![dq27](https://cloud.githubusercontent.com/assets/7569514/15802262/55ea539c-2aa4-11e6-86af-14f198f77fad.png)

**Comment by larsiusprime** [comment]
Also this asterisked bit is totally redundant now that hero mode is an
explicit option with tooltips, so I should just remove it.

Also I seem to recall achievement popups had non-scaling text.... (ie at
1080p the text is proportionately tiny) ... is that still a problem?

On Sat, Jun 4, 2016 at 4:33 PM, ManDude <notifications@github.com> wrote:

> [image: dq27]
> <https://cloud.githubusercontent.com/assets/7569514/15802262/55ea539c-2aa4-11e6-86af-14f198f77fad.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/876>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-LRLJ_F1y97eLbfK9Pei3hJcciBIks5qIe8hgaJpZM4IuOU_>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
This computer only allows 3 16:9 resolutions and 1 4:3 resolution so it's a bit hard.

**Comment by larsiusprime** [comment]
np, i'll just check it on monday

On Sat, Jun 4, 2016 at 5:15 PM, ManDude <notifications@github.com> wrote:

> This computer only allows 3 16:9 resolutions and 1 4:3 resolution so it's
> a bit hard.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/876#issuecomment-223781168>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Je-ek7diyiPNIBIbgrWQxMW1CVOks5qIfjlgaJpZM4IuOU_>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Fixed the scaling and also fixed the asterisks.

**Comment by larsiusprime** [comment]
Fixed in 0.9.2, also fixed the scaling font.
