### ISSUE TITLE
Ketta is considered a male

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#878]
![dq28](https://cloud.githubusercontent.com/assets/7569514/15802475/8f03ad48-2aab-11e6-9072-f8400f9c5fc8.png)
huh

**Comment by larsiusprime** [comment]
yeah that code doesnt actually do anything to my knowledge, might be
defaulting. i'll fix it anyways

On Sat, Jun 4, 2016 at 5:25 PM, ManDude <notifications@github.com> wrote:

> [image: dq28]
> <https://cloud.githubusercontent.com/assets/7569514/15802475/8f03ad48-2aab-11e6-9072-f8400f9c5fc8.png>
> huh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/878>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-A6TWBlYcIPWTep6eb-g6_5tK2EGks5qIftCgaJpZM4IuO4d>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
I'm just removing this variable for now, since we're not even using it.
