### ISSUE TITLE
Sheep+ uses Swift Sheep sprite

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#879]
![dq22](https://cloud.githubusercontent.com/assets/7569514/15802736/0609faec-2ab5-11e6-8cf4-59f76ef86a71.png)

**Comment by larsiusprime** [comment]
@Mandude, what is your email address again? I get usernames mixed up. I
wanna talk to you about something :)

On Sat, Jun 4, 2016 at 6:32 PM, ManDude <notifications@github.com> wrote:

> [image: dq22]
> <https://cloud.githubusercontent.com/assets/7569514/15802736/0609faec-2ab5-11e6-8cf4-59f76ef86a71.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/879>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-N_UAVSWxzPgpiNgYUx1HSnqiKdsks5qIgsigaJpZM4IuPkY>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Sure. Sent an e-mail to the e-mail address on your github profile. ;)

**Comment by larsiusprime** [comment]
Fixed for a while
