### ISSUE TITLE
Anonymous status is appearing on all difficulties.

### ISSUE THREAD

**Issue by xfullmetal17** [larsiusprime/tdrpg-bugs#880]
Steps to reproduce:
1. Load a game or start a new one, making sure Anonymous Book is available and equipped.
2. Start a level, not on Extreme.
3. Characters have the Anonymous icon and status in description.

As a side-effect, characters' names show up even on Extreme, instead of everyone being called "Anonymous" as before, which I'm sure was part of the joke of the item.

Version 0.8.4- according to the menu.

**Comment by larsiusprime** [comment]
Fixed in 0.9.5
