### ISSUE TITLE
Bizarre Null Crash I can't recreate: Learn heal, party, place point in heal, continue, cancel, undo, crash.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#887]
The exact steps I took are in the title. Not sure what triggered it. :(  But it must be really rare, few people would take the steps I did.

**Comment by larsiusprime** [comment]
Did this ever happen again?

**Comment by dqhol** [comment]
Not that I could ever recreate, though I only tried once. No clue what caused it.
