### ISSUE TITLE
Bad kerning: This well-fashioned lamellar hamess...

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#888]
Weird, harness looks fine two lines lower.

![ze](https://cloud.githubusercontent.com/assets/19625520/15803511/5beb67ee-2aaf-11e6-86f2-826e37b92fb3.png)

**Comment by larsiusprime** [comment]
Not something I can really fix until we take a stronger whack at OpenFL's underlying text rendering.

**Comment by larsiusprime** [comment]
(This also means it's a general error not specific to any area of text in the game, when we fix the underlying text rendering -- sometime after launch -- I'll be able to clear these all out in one go)
