### ISSUE TITLE
No dots connecting to the Knight's Fort.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#889]
It's there with the old graphics, but not new. Unless the distance is too short to warrant the larger dots, in which case nevermind.

![ze](https://cloud.githubusercontent.com/assets/19625520/15803540/cefa8a7a-2ab0-11e6-9c0e-0f1d4d042e2c.png)

**Comment by ManDude** [comment]
Assets like towns and stuff appear over the dots. They're there, you just can't see them.
