### ISSUE TITLE
Crystals missing / way out of place in Tunnel Escape.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#891]
These are on casual, but the lone crystal is far up  in the left corner uselessly on all difficulties in DQNew

![ze](https://cloud.githubusercontent.com/assets/19625520/15805071/434c6f52-2aec-11e6-8cea-26668a156521.png)

**Comment by dqhol** [comment]
Same with Detonate The Mines. Both pictures on Casual.
![ze](https://cloud.githubusercontent.com/assets/19625520/15805093/1eee0106-2aed-11e6-8a56-69d789ccab94.png)

**Comment by larsiusprime** [comment]
Fixed in 0.8.9

**Comment by dqhol** [comment]
@larsiusprime Was it a bug that Detonate The Mines had no crystals in DQO on Advanced or Extreme? In every other level they get smaller and smaller, but here they vanish outright.
