### ISSUE TITLE
The Markos/Ketta Bad Ending still plays 1 second of the sad song, then loads the normal ending music.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#892]
I thought this had been fixed a few times in DQold. How does this keep popping up? :P

**Comment by larsiusprime** [comment]
Fixed in 0.9.5

**Comment by dqhol** [comment]
Reopened in 0.9.8. The normal ending music plays in NG+, without even a blip of the sad song anywhere.

**Comment by toni3m** [comment]
```
Operating System: Linux
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : DX 2.2.2 (hotfix 18276) (gog.com)
Optional Info   : -
```
Bug reproduced.
Bad ending credits will play sad.ogg for a second, then switch to ending_credits.ogg.
