### ISSUE TITLE
Maximum Boost on Azra remains clickable.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#893]
![ze](https://cloud.githubusercontent.com/assets/19625520/15805257/8d45ab54-2af2-11e6-8002-9b003dc83f35.png)

**Comment by larsiusprime** [comment]
Does it do anything? And is maximum boost clickable on regular defenders too?

**Comment by dqhol** [comment]
Nope, just Azra / Sorceress. And it doesn't do nothing, but it's permanently locked down in DQO when maxed.
