### ISSUE TITLE
Zelemir single-handedly carries the final battle for around 25 waves, also can shock ET now.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#895]
In EQOld, Zelemir couldn't shock ET. Now he can. Also, in this battle I didn't place a single unit, didn't cast a single spell. I just pressed x16 speed and watched. Zelemir destroyed everything for 25+ levels. There has to be a bug there. This was WITH him being distracted by shocking ET. Without ET to shock, he probably could have killed enemies for many more levels to come.

![ze](https://cloud.githubusercontent.com/assets/19625520/15805319/5504820e-2af4-11e6-9bbb-7ad09dea68b9.png)

**Comment by ManDude** [comment]
Seeing as Azra has taken quite a lot of damage already, I think it's safe to assume this is more or less intentional (also what difficulty is that), the real bug is shocking Eztli-Tenoch.

**Comment by dqhol** [comment]
She only started taking damage at around wave 20, until then she was untouchable. Being effectively  invincible without any units down for 20 waves seems very, very wrong.

Also, it's on extreme.

**Comment by larsiusprime** [comment]
What's the comparable behavior from the original game?

**Comment by dqhol** [comment]
On x4 speed in DQOld, I died on wave 7 on Extreme in Normal Play.

**Comment by dqhol** [comment]
Okay, I think it's due to the x16 speed that's causing Zelemir to go super saiyan with his lightning.

**Comment by larsiusprime** [comment]
Now that I've fixed the speed bug this shouldn't happen anymore, and doesn't seem to in my tests.

**Comment by larsiusprime** [comment]
- [ ] Fix speed bug
- [ ] Zelemir should not be able to target ET (just make ally spells not target bosses)

**Comment by larsiusprime** [comment]
Fixed in 0.8.9

**Comment by ManDude** [comment]
Question about the server: Does it upload separate builds for 32-bit and 64-bit?
