### ISSUE TITLE
Who's able to damage for 16,000+ points in one hit?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#897]
0.8.4, win7x64, HD mode@1704x960windowed

![dq-16815](https://cloud.githubusercontent.com/assets/16719964/15805340/4c8fd460-2b27-11e6-8581-f8accd8fa329.png)

Is it the ice mage?  She's only level 47, is she able to do that much damage?  It seemed the enemies in the lower left were dropping very suddenly...

**Comment by dqhol** [comment]
That looks like a critical hit. Is she using the staff that does x3 damage to worms? What's your normal ice mage damage to worms?

**Comment by ManDude** [comment]
That's a critical hit. It's quite awesome when you can pull off such huge amounts of damage. I didn't know Ice Mages could pull off critical hits, though. What weapon is she wearing?

**Comment by IBwWG** [comment]
@dqhol indeed, I am.  Wow!  That packs a punch.  It's "The Beast's Weapon+".

**Comment by ManDude** [comment]
Ah. That weapon is insane and I always give it to Wrenna because it's so useful and powerful.
