### ISSUE TITLE
[Suggestion, not a bug] Improve New Game+ message.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#898]
From the point of view of a new player, I would see this and think: "So it's the same game again, but harder..." Most games have a very boring  NG+, where they just multiply the stats of enemies and call it a day.

Really sell it, eh? Get them itching to see what truly awaits them.

"Congratulations! You can now start a new adventure with your old party! Enemies gain new abilities, infuse your equipment with amazing new powers, stock your library with many new books. Engage in numerous new side-quests with additional cutscenes and story, unlock developer commentary, translate Eztli-Tenoch's speech, meet new characters and so much more!'

![ze](https://cloud.githubusercontent.com/assets/19625520/15805380/4d528fc2-2af6-11e6-8f98-cdd4b9f91434.png)

**Comment by ManDude** [comment]
This sounds like a great idea. It's definitely something I'd like to see in the game. Where should this message display, though? I thought about putting it after the credits scene.

**Comment by dqhol** [comment]
The depicted screenshot already pops up after you proceed past the party menu after the final battle. I'm just suggesting the first paragraph sell NG+ harder to the player. Better written than I have, but still. :P

**Comment by ManDude** [comment]
Wait, what? I've never seen that message before (I think?). I thought that was a mock up haha.

**Comment by larsiusprime** [comment]
Not a bad idea.

**Comment by larsiusprime** [comment]
Fixed in 0.8.9, pending @dqhol's permission (otherwise I'll use similar but different wording)
