### ISSUE TITLE
Casting Healing spell makes no effects appear

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#900]

**Comment by larsiusprime** [comment]
Care to elaborate?

**Comment by ManDude** [comment]
In DQOld, casting spell or Frenzy made an effect that covered the whole battle area. Doiesn't happen in DQNew.

**Comment by larsiusprime** [comment]
I just tested, it works. Is your "Flashing effects" turned off in
accessibility settings?

On Wed, Jun 8, 2016 at 12:18 PM, ManDude <notifications@github.com> wrote:

> In DQOld, casting spell or Frenzy made an effect that covered the whole
> battle area. Doiesn't happen in DQNew.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/900#issuecomment-224663587>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-LQqZhG3904xn_0bsJM9ttk2XJxxks5qJvlPgaJpZM4IuWHB>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Oops, I did have then disabled.

**Comment by ManDude** [comment]
Not an issue.
