### ISSUE TITLE
"Charlatan's Staff+" description doesn't tell it's special "+" ability

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#901]
0.8.4, win7x64, HD mode@1704x960windowed
![dq-plus](https://cloud.githubusercontent.com/assets/16719964/15805498/de0aa33e-2b2c-11e6-9b23-f87123b8d160.png)

**Comment by IBwWG** [comment]
Meanwhile before equipping #790 applies here too.  So now that I've bought the upgrade I can't tell what it does anymore.  :)

**Comment by dqhol** [comment]
Same in the skull shop. 'Special' section is completely blank.

**Comment by larsiusprime** [comment]
Fixed
