### ISSUE TITLE
Long equipment names spill out of purchase-after-equip box.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#902]
This probably doesn't really need fixing, most people won't notice since it's a minor thing, but reported all the same.

![ze](https://cloud.githubusercontent.com/assets/19625520/15805535/acd18d9a-2afb-11e6-9a74-cf791e433963.png)

Also, out of curiousity, could Azra equip books after purchasing them in DQOld?

**Comment by ManDude** [comment]
I don't think she could, but it's still an interesting addition.
