### ISSUE TITLE
Spending gold skulls doesn't take them away (not just a display bug) in NG+

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#904]
0.8.4, win7x64, HD mode@1704x960windowed

Had gold x4.  Bought the book of synergy.  Still said x4 but figured it was a display thing like #792 .  Went and obtained another from the desert monument, went back into the desert monument shop, and now I have 5 gold skulls to spend...

**Comment by IBwWG** [comment]
Yep, it just let me buy the remaining two books at 3 gold skulls each, using the 5 I had.  *then* the indicator jumped to 0x.  Although that may be a display bug.

**Comment by larsiusprime** [comment]
- [ ] Properly debit skulls
- [ ] Display skulls correctly
- [ ] Don't screw up upgrades
- [ ] Don't screw up regular shops

**Comment by larsiusprime** [comment]
Fixed in 0.8.9
