### ISSUE TITLE
Guardian of the Fountain and GotF+, both?

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#906]
0.8.4, win7x64, HD mode@1704x960windowed

Had GotF from my first run.  In NG+, upgraded it at the hermit's to the + version.  Then, at the cave near the end, the shop had GotF for sale, so I bought it.  Now I have both, but I thought it's supposed to be unique, even across having the + version or not.

**Comment by IBwWG** [comment]
Also with Evni, it's available to buy even though I bought it and made Evni+ from it.

**Comment by IBwWG** [comment]
Further, with the second Evni, the hermit would let me upgrade it (if I had a skull to spend...there may not be enough of them to go around, but this does mean that you could leave something else un-upgraded and get two of the same "unique" item.)

**Comment by larsiusprime** [comment]
Okay fixed. You can't buy Evni or Guardian of the Fountain if you have already purchased them, OR if you have the upgraded one(s).

0.9.0
