### ISSUE TITLE
Strange Monument no longer has ??? button to enter store

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#907]
0.8.4, win7x64, HD mode@1704x960windowed

It was there before.  I got a skull to spend there, but can't...

![dq-no-store](https://cloud.githubusercontent.com/assets/16719964/15806524/3c18c0ec-2b45-11e6-9523-2db76c46cc24.png)

Repeatable bug using this save file:

[export-no-store.zip](https://github.com/larsiusprime/tdrpg-bugs/files/299395/export-no-store.zip)

**Comment by dqhol** [comment]
I think you need enough skulls to buy something before it appears. Nothing appeared when I had 1 gold skull or 2, but when I had 3 it appeared.

**Comment by IBwWG** [comment]
But I do have an unobtanium...

**Comment by dqhol** [comment]
But what I'm saying is, you need enough to actually buy something for it to appear, it seems. Get the other unobtanium and the ??? will appear.

Of course it should appear if you only have even one, but currently it doesn't work that way.

**Comment by IBwWG** [comment]
Oh, the item costs 2.  I had misremembered.  Now I understand.  Thanks :)
