### ISSUE TITLE
Severe memory leak on "Following Zelemir"

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#909]
0.8.4, win7x64, HD mode@1704x960windowed

1.5 Gb after only a few seconds at 16X, with almost no defenders.  Had just placed a dragon.  While I was writing this it recovered and continued (just under 1.5Gb), so this screenshot is slightly later:

![dq-mem-leak](https://cloud.githubusercontent.com/assets/16719964/15807449/e93a8da0-2b5e-11e6-9835-3a4300861e97.png)

But then trying to click on dragon O to place it, it again gives the windows waiting cursor and seems stuck.

**Comment by IBwWG** [comment]
Huh, couldn't reproduce the second time.  Strange...

**Comment by IBwWG** [comment]
But the third time, yes:

![dq-crash-zelemir](https://cloud.githubusercontent.com/assets/16719964/15817685/83271c06-2bd9-11e6-81cc-60814b4234cf.png)

I don't think I was clicking anything just then, I was waiting to be able to boost Slak.

**Comment by larsiusprime** [comment]
I can reproduce this without too much trouble. Time to pop out HXCCPOBJECTGRAPHVIEWER.

**Comment by larsiusprime** [comment]
I've made some speculative improvements in 0.8.6, let me know if it's any better at all. I suspect this will take several passes.

**Comment by IBwWG** [comment]
0.9.0, win7x64, HD mode@1704x960windowed
Seems a lot better now.  I did have one moment placing a bezerker near the beginning, just hitting the keyboard shortcut had a 5-10 second windows-waiting-cursor moment, but the mem usage was only 700mb.  Prolly some system crap going on, not the game.  :)

**Comment by larsiusprime** [comment]
@IBwWG can you test version 2.0.3 next chance you get (either on steam test_public or the build server) and let me know if it fixes this issue once and for all?

**Comment by IBwWG** [comment]
I would, but I'm not on steam yet, and the build server only has Mac and Linux 64-bit (in vanilla and steam, with duplicates...that's 4 combos but there are 7 files for 2.0.3.)  Not on itch?

**Comment by IBwWG** [comment]
OK, I set up a steam account, but I don't see 2.0.3 on there, or the test_public area you mention.  In the game's community hub I see patch #2 but not this.  Do I need an unlimited user account to be able to see test_public?  Or am I just missing it?

**Comment by IBwWG** [comment]
OK I see the news about the 2.0.3 patch, now it's on the main page.  But it's the same article and doesn't say how to actually get at this test_public thing.

**Comment by IBwWG** [comment]
Oh, it's already there if I just install via steam.  Sorry.  I was confused by the test_public thing.

WOW!!!!!!!!!!  This is AMAZINGLY fast compared to before, on my Windows laptop.  At 16X the battle ZOOMED and was totally responsive the whole time.  There was only one temporary hiccup where the game froze for about a second, but there used to be tonnes of those.  Sweet!  Can't wait to try this on Linux when you get it on 32-bit on itch!

**Comment by ManDude** [comment]
Baaahhh the build server ain't updating so I can't enjoy this speed!!
