### ISSUE TITLE
Knights devour

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#910]
0.8.4, win7x64, HD mode@1704x960windowed

OK I'm on "the way out" (no dragons allowed); not a memory issue because only 700mb is taken up, and my knight just "nom"'d someone.

**Comment by ManDude** [comment]
Does he have Evni+? I think that adds Devour.

**Comment by larsiusprime** [comment]
Yeah, that's got to be what it is.

**Comment by IBwWG** [comment]
Ah!  Yep.  Didn't realize.  Thanks!
