### ISSUE TITLE
The big list of minor party menu bugs.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#913]
![ze](https://cloud.githubusercontent.com/assets/19625520/15817579/a88c8f7c-2ba6-11e6-9123-3455f0ca36d5.png)

1 I heard someone claim that roar was working in a square, reported as a bug. Seems in DQOld roar was always square-based as opposed to circle-based. Anyhow, DQNew doesn't explain what the radius is, though the Ice Mage AoE spells don't list exact radius in DQOld or DQNew.

2 EXP no longer shows when the next level up is, only current EXP.

3 Exact speed no longer listed by decimal.

4 All dragons lose 1 defense?

5 Same as 3, but with Regen.

![ze](https://cloud.githubusercontent.com/assets/19625520/15817721/6520fd80-2ba7-11e6-8d14-e7f8de093347.png)

6 Knights and Ice Mages are still flipped when importing save files.

![ze](https://cloud.githubusercontent.com/assets/19625520/15817820/e1cb43d6-2ba7-11e6-9d76-4cb64355cc16.png)

7 Slak got faster?

![ze](https://cloud.githubusercontent.com/assets/19625520/15818214/05cdc6f8-2baa-11e6-81bb-c38f83efc2e4.png)

8 Skills no longer signify when maxed

**Comment by ManDude** [comment]
Does it show EXP/blah if your level is not 60?

**Comment by dqhol** [comment]
Doesn't show the /blah even if they're not maxed,  no.

**Comment by codingthat** [comment]
Skills now signify when maxed (yellow highlighting).

**Comment by codingthat** [comment]
1-5 and also 7 are still as originally reported, though.

Haven't checked 6.
* * *
DQ 1 version 2.2.6_6/1/2018 on Linux Mint 19 (64-bit) in fullscreen mode on a 1920x1080 single-monitor setup with an Intel HD Graphics 4400 chipset.
