### ISSUE TITLE
Double "Azra was unharmed" popup at the end of Following Zelemir

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#914]
I think I mentioned it in another issue already, but i had that happen again just now

0.8.4, win7x64, HD mode@1704x960windowed

Reminds me of once you had mentioned that there were two Azras by accident?  Maybe that's still happening on some level?

**Comment by IBwWG** [comment]
@ManDude I also had experienced it before, but it doesn't seem to be on *every* level...unfortunately I forget which other one or two I saw it on. Have you noticed any kind of pattern?  Or maybe it's just intermittent...

**Comment by larsiusprime** [comment]
If there's a pattern I bet it's related to playback speed. I recently
introduced a sort of bug where after the popup battles don't end
immediately, bet that's related.

On Mon, Jun 6, 2016 at 12:32 PM, KJB <notifications@github.com> wrote:

> @ManDude <https://github.com/ManDude> I also had experienced it before,
> but it doesn't seem to be on *every* level...unfortunately I forget which
> other one or two I saw it on. Have you noticed any kind of pattern? Or
> maybe it's just intermittent...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/914#issuecomment-224029761>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-EfsNdDOFY03PVVdWCyXdBQdpDzYks5qJFnEgaJpZM4IuwQT>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
This should be fixed in 0.8.8
