### ISSUE TITLE
Nearly every piece of equipment is visually wrong or mechanically wrong, or does nothing.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#915]
I'm sorry, Lars. I told you the end was near. You trusted me that the pain was almost over. ;'( The well has no bottom. This is my biggest, buggiest report yet.

These numbers are comparing the difference from DQOld to DQNew, picture reference at the bottom.

Platinum Fleece: Doesn't give the +10% evade it says it does anymore.

Tiger Skin Vest: +20% physical evade

Chieftain's Tunic: -60% damage resist

Assassin's Folly: Only saves vs physical at 80%+ HP now, not 20%+

Warrior Monk's Habit: -20% mag dmg resist

Master of Archers: -20% evade ranged

Archsheperd Stave: No longer gives +25% HP

Charlatan's Staff: No longer gives +25% evade

Strength of  Wocolan: -20% physical resist

Horseman's Lamellar: -40% magic resist

Glory of War: +60% dmg resist vs boss. Oh, I actually tested this one using Ozimal Kaz, by the way. Wrenna took 328 dmg per hit in DQOld. 390 in DQNew. Placed another ice mage, with one defense higher. That's funny, I thought, the boss's atk is  390. Let's try Ketta, 49 defense, 390. Archer with 0 defense, 390. What about  Markos, who gets armor from Armor Training? 390. Armor does nothing. ... Actually this warrants it's own entry, putting this up as it's own report after this.

_(Additionally,  I'm not sure if it even did anything in DQOld...resisting 40% boss damage, on top  of her armor, should've made her take WELL less than 328 a hit.)_

Executioner's Bludgeon: No longer gives +25% attack. Also doesn't list what it gives.

Lord Warden Harness: +50% HP save vs physical/magic

Keeper of the Flame: Everything appears to check out here... pardon me if I don't believe you, game. Let's try you vs Ozimal Kaz. DQNew does -65% speed,  10 seconds. DQOld does -75% speed, 6 seconds. DQNew no longer slows enemeis more, but adds 4 additional seconds. Wtf?

Given my lack of access to the code, I can't tell just how many of these are visual, mechanical or broken. Lars is going to have  to go over every piece of unique equipment and make sure it's functioning as it says, I fear. I only really could test the vs BOSS and +Freeze ones easily.

![untitled](https://cloud.githubusercontent.com/assets/19625520/15820586/64748134-2bb8-11e6-8038-a58a6b15ec2f.png)

**Comment by larsiusprime** [comment]
So, I just fixed the big "defense" bug.

On to the rest of this -- I believe that for a lot of these, the descriptions were wrong in DQOLD -- they were screwing up X% vs (100-X%), IIRC, but I'll have to confirm.

**Comment by larsiusprime** [comment]
Okay, tiger skin vest, DQOld from data_items.xml:


```xml
<armor type="light" lvl="16" bonus="39" name="$ITM_A_LIGHT_16_NAME" cost="7" cost_type="skull:1" special="unique:strong(physical,dodge,0.40)" description="$ITM_A_LIGHT_16_DESC"/>
```

Here it is in DQNew from items.xml:

```xml
	<armor type="light" lvl="16" bonus="39" name="$ITM_A_LIGHT_16_NAME" cost="7" cost_type="nonequip,skull,1" description="$ITM_A_LIGHT_16_DESCRIPTION"
		special='{
			"unique":"true",
			"values":[
				{
					"value":"strong",
					"type":"evade",
					"amount":0.4,
					"flavor":"physical"
				}
			]
		}'
	/>
```

The stats are the same. Clearly here the correct reading is that 40% of the time the character should be able to dodge. DQNew has the wrong display but I suspect the underlying behavior is correct.

**Comment by larsiusprime** [comment]
- [ ] Armor display glitch
- [ ] Verify item stat boost
- [ ] Verify item flavor augments
- [ ] Verify armor dodges
- [ ] Verify armor thorns
- [ ] Verify armor absorbs
- [ ] Verify armor saves

**Comment by dqhol** [comment]
So, I had some suspicions after seeing that vs BOSS didn't work in DQOld. None of this is for DQNew, just satisfying my curiousity.

Horseman's Lamellar reduces magic damage by 70%? K, let's place two knights, same HP, and have Zelemir shock the heck out of 'em.

With Lamellar: 910 damage taken, 1952 max.
Without Lamellar: 913 damage taken, 1952 max

Broken. :(

How about Strength of Wocolan, 60% damage resist vs physical? Using Ozimal Kaz.

165 dmg taken with, 327 without. It works! :D

Assassin's Folly? Actually saves from death.

Chieftain's Tunic? 80% damage resist from physical? Bakal's taking 278 damage out of a maximum 390... doesn't seem like 80% resisted there.

I wonder how many pieces of upgraded gear just boosted DEF in DQOld?

**Comment by larsiusprime** [comment]
Man, well, might as well fix these bugs now!

**Comment by ManDude** [comment]
@dqhol 165/327 = ~50%, not ~60%. It's broken.

**Comment by dqhol** [comment]
By without, I meant without that specific bonus. That's after damage reduction from defense.

**Comment by larsiusprime** [comment]
@ManDude -- no, because it also has a normal linear armor absorb as well. So it's applying the multiplier first, then applying the raw damage bonus. So that math probably works out.

I've fixed the rest of the bugs, as far as I can tell. It'll be in the next build.

**Comment by ManDude** [comment]
Ah okay, good to know.
