### ISSUE TITLE
Defense does nothing.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#916]
From my equipment report;

Glory of War: +60% dmg resist vs boss. Oh, I actually tested this one using Ozimal Kaz, by the way. Wrenna took 328 dmg per hit in DQOld. 390 in DQNew. Placed another ice mage, with one defense higher. That's funny, I thought, the boss's atk is  390. Let's try Ketta, 49 defense, 390. Archer with 0 defense, 390. What about Markos, who gets armor from Armor Training? 390. Armor does nothing.

^ So, yeah. That'd explain  why my characters were taking such a pounding. Eesh.

**Comment by larsiusprime** [comment]
Wow, great catch. Let's fix this.

**Comment by larsiusprime** [comment]
Fixed in 0.8.5
