### ISSUE TITLE
Unequiping Book of Secrets while on the Strange Monument pearl causes things

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#919]
![dq02](https://cloud.githubusercontent.com/assets/7569514/15843522/ad9fdc58-2c5a-11e6-988c-8b3c34062c8e.png)
Note that Azra is not stuck, she can move to that next pearl. I expected the game to put me at that battle pearl (Zelemir Appears) when I unequip the Book of Secrets and go back to the overworld.

**Comment by dqhol** [comment]
Same thing happened in DQOld.
