### ISSUE TITLE
Ability timing issues

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#922]
![dq01](https://cloud.githubusercontent.com/assets/7569514/15844350/793d60dc-2c61-11e6-9475-29676563bd83.png)
I set game speed to 16x placed a Healer and boosted it to boost 5, then waited about 10 seconds. Zeal (and possibly every other ability for every defender) is being cast way too fast.

**Comment by ManDude** [comment]
I think the ability timer is assuming it's running at 60FPS when in reality that's not the case.

**Comment by larsiusprime** [comment]
Are you saying you get different timings on different playback speeds, or
that you get the same timings that are all off by a constant factor (like
everything is too fast) regardless of the playback speed?

On Mon, Jun 6, 2016 at 9:43 PM, ManDude <notifications@github.com> wrote:

> I think the ability timer is assuming it's running at 60FPS when in
> reality that's not the case.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/922#issuecomment-224152641>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-LeDtO1ywPF-9d4qPPSJQPwWec9jks5qJNrbgaJpZM4IvgCm>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
It's a bit hard to know, but it seems to be fine at 1x speed. 2x speed I can notice desyncs ability cooldowns.

**Comment by larsiusprime** [comment]
Okay, likely it's reading the wrong elapsed variable on updates. Not too
bad to fix.

On Mon, Jun 6, 2016 at 10:07 PM, ManDude <notifications@github.com> wrote:

> It's a bit hard to know, but it seems to be fine at 1x speed. 2x speed I
> can notice desyncs ability cooldowns.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/922#issuecomment-224157949>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-NntGbmd2PrNesRK1UZwsL6DkDdiks5qJOBqgaJpZM4IvgCm>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Okay, I think I found it. I am using a fixed timestep for each update cycle, but certain functions were using the multiplied time dilation.

IE, x16 speed should be "16 updates per regular update, all at the same speed" and then inside the update function it's also like "this update, do things 16x faster!!!!"

So.... yeah.

**Comment by larsiusprime** [comment]
Fixed in 0.8.8
