### ISSUE TITLE
Fire Ball's splash uses square range

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#923]
![dq02](https://cloud.githubusercontent.com/assets/7569514/15844423/2bb8bef0-2c62-11e6-81a5-ba0c0fa8a749.png)
Ice Splash's splash uses a circle range, like it should.

**Comment by larsiusprime** [comment]
Almost certainly because it's grabbing the dragon's zone shape, which is a double circle, and then hitting a default in a switch case somewhere because it's expecting a "circle", not a "double_circle".

**Comment by larsiusprime** [comment]
yuuuuuuuuuuuuuuuuuuuuup.

Fixed in 0.9.2
