### ISSUE TITLE
Not getting 100% Psi back even if recalling before 1st wave

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#924]
1. Place Berserker.
2. Recall berserker.

You only gained 21 Psi from recalling the berserker, instead of the 25 the button says.

**Comment by larsiusprime** [comment]
I get full PSI on recall. Do you perhaps have a book equipped that comes with a PSI tax?

But good you filed this bug anyway, because the boost price isn't considered part of the refund, and it should be.

- [ ] Fix boost recall

**Comment by ManDude** [comment]
Whoops, I forgot I had Book of Synergy equipped, which does have Psi Tax.

**Comment by larsiusprime** [comment]
Fixed the "boost doesn't count for refunds" glitch in 0.8.9
