### ISSUE TITLE
Many ET stat/spell display issues

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#933]
![ze](https://cloud.githubusercontent.com/assets/19625520/15848103/cee12914-2c58-11e6-8c4a-e840681f6436.png)

![ze](https://cloud.githubusercontent.com/assets/19625520/15848200/878bc79e-2c59-11e6-9d71-dc85c0a29e1b.png)

1 ET no longer shows how many shields he has.

2 ET has one less immunity, fire. I assume fire is just fire damage in generla, like fireball? Odd that he was ever immune to that.

3 ET now has a visible level. 18? Puny god. Hulk smash. On a related note, Zelemir is now a level  50 sorcerer too. No level in DQold.

4 ET, in DQOld and DQNew, has an attack radius of 20. Which is weird considering he has no physical attacks to use it with and no visible attack value. Or does he have unused attack animations in the game to smack around the people surrounding him?

5 Frenzy frenzies for 34 more seconds

6 Dragonfire does 10 less damage.

7 DQNew's ET has a green healing wave. DQOld had cool purple/diseased looking healing wave.

8 Not necessarily a bug, but I noticed in DQOld and DQNew that ET will never cast lightning if no one is adjacent to him. Maybe that's what the attack radius is for...?

**Comment by dqhol** [comment]
![ze](https://cloud.githubusercontent.com/assets/19625520/15848645/274af762-2c5c-11e6-85b5-fad8d5750dab.png)

Both DQOld and DQNew showed boss levels in the battle preview screen, likely a bug considering ET's ??? level in battle.

Zelemir is visibly level 16 in both DQOld and DQNew in the previous battle, for reference, so it's only ET that's supposed to be concealed. ... Really, Zel? You grinded 36 levels in the time between one battle? Dang, dude. Someone's on +30000% EXP mode with no failure penalty.

**Comment by larsiusprime** [comment]
- [ ] Fire was a synonym for BURN, it was totally redundant.

**Comment by ManDude** [comment]
Notice how Frenzy says "+54 speed" instead of "+54% speed".

**Comment by larsiusprime** [comment]
- [ ] Notice how Frenzy says "+54 speed" instead of "+54% speed".

**Comment by larsiusprime** [comment]
All fixed in 2.0.8
