### ISSUE TITLE
Sorceress visual bugs, behavior + crashes

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#936]
![ze](https://cloud.githubusercontent.com/assets/19625520/15853715/38a9c3d6-2c74-11e6-8a85-652a856afe5e.png)

1 Sorceress has a level listed in her first battle in DQN, 60. Final battle, 50. No level listed in DQO.

2 The sorceress uses Azra's portrait next to HP/PSI in DQN.

3 When sorceress dies, game crashes.

4 No 5-section boost bar for Sorceress in DQN like defenders have, which she had in DQO. **(I just checked, Azra lacks this too for the final battle.)**

5 Azra and Sorceress get scalped in Sorceress's final battle. Her boost bar also blocks out her face.

6 Her spells are much better, but also she casts them quite a bit more often than in DQO. Tested both on x4. I gotta say, I like her being more spellslingy, though. Makes her more of a participant.

**Comment by ManDude** [comment]
She casts them too fast because of #922, probably.

**Comment by larsiusprime** [comment]
Fixed most of the critical stuff in 0.9.0
