### ISSUE TITLE
Final sidequest baddies no longer list what they hatch into, are no longer ++ enemies

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#937]
![ze](https://cloud.githubusercontent.com/assets/19625520/15853916/268c1950-2c75-11e6-98e8-a2936420d5fc.png)

**Comment by ManDude** [comment]
I noticed the ++ thing too, I reported it at #873.

**Comment by larsiusprime** [comment]
Fixed in next build.
