### ISSUE TITLE
[Bug?] Missing tile decorations?

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#938]
Maybe these were just deemed unnecessary in the transition to DQN, but on the off chance any of these are glitched out like red obsidian is:

![ze](https://cloud.githubusercontent.com/assets/19625520/15854628/d964736c-2c78-11e6-8d10-dfbed6ca4711.png)

1 Cool purple crystal fragments replaced with generic rocks.

2 Red obsidian stone and walls are missing, as noted elsewhere, but so are their swirlystones.

3 Craters and holes decorating tall stone you can't place crusaders  on replaced with generic rocks. The rocks look a bit messy, in comparison.

4 Red splattered stone decorations gone.

5 Pipes(?) are gone.

6 Craters in the desert gone, probably because the desert got a lot less white. :P

7 Not really a decoration issue, but jeez grass is... distractingly plain and featureless. Looks like it needs some pattern on the grass or something, I dunno.

**Comment by larsiusprime** [comment]
This might be something I could address but I'd rather focus on DQ2 at the moment. Cutting for now.
