### ISSUE TITLE
Enemies spawned from other enemies don't get affected by Book of Blood/Poison

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#941]
Unsure whether I should continue playing the game or not hehe. :P

**Comment by larsiusprime** [comment]
This is good stuff :) I assume in the original game they were affected by
this stuff?

On Tue, Jun 7, 2016 at 3:32 PM, ManDude <notifications@github.com> wrote:

> Unsure whether I should continue playing the game or not hehe. :P
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/941>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-NvRtaaSnQeX5wivuQtJ0zQxcUuzks5qJdV4gaJpZM4IwVLQ>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
I think...? I don't have it right now. Maybe @dqhol can confirm.

**Comment by ManDude** [comment]
Just checked, yes they are affected in DQOld.

**Comment by Jym77** [comment]
Also, Mad Ghouls spawnned by Cultist in Endless 2 (normal) do attack despite all other enemies having their attack removed. I assume it is related (as in "enemies spawnned don't get level-wide effects applied").

**Comment by ManDude** [comment]
bump
