### ISSUE TITLE
Book of Face does not apply Troll status effect

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#942]
I also checked the code via mod, it'a not even programmed to apply it.

**Comment by larsiusprime** [comment]
Yeah, so I did some research and I found out that the "trollface" image is
actually copyrighted and the author has been known to request that people
take it down if it's in a commercial product, so I decided to pre-emptively
remove it from DQDX.

On Tue, Jun 7, 2016 at 7:56 PM, ManDude <notifications@github.com> wrote:

> I also checked the code via mod, it'a not even programmed to apply it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/942>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-JTOZEMLAPJZmiDGl2361E0489n4ks5qJhNHgaJpZM4IwgDY>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Aw, shucks. Guess I'll close this then.

**Comment by dqhol** [comment]
@larsiusprime Couldn't you have replaced it with a generic angry green face? A troll of the greener variety?

**Comment by larsiusprime** [comment]
I suppose, I have a giant queue full of bugs at the moment though :) You
can reopen this if you want and I'll flag it as low priority and I'll
circle back whenever.

On Tue, Jun 7, 2016 at 8:49 PM, dqhol <notifications@github.com> wrote:

> @larsiusprime <https://github.com/larsiusprime> Couldn't you have
> replaced it with a generic angry green face? A troll of the greener variety?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/942#issuecomment-224465152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-GJpcbasGNCtfjWXnZjcEOQbtLzvks5qJh-ngaJpZM4IwgDY>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ManDude** [comment]
Well, troll could really ruin your game, so I'm gonna keep it closed unless everyone asks for it. :V
