### ISSUE TITLE
Crashes / bugs when importing / exporting a save.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#944]
Select Import, then click any button on the screen. Now load a save or just cancel. Immediately you'll get a Null Object Reference. Same with exporting.

Also, when doing either, don't do anything for a while. Eventually the music will try to loop and freeze the game up completely, stopping the music until you do import or export a save or cancel.

**Comment by larsiusprime** [comment]
- [ ] Fix it so you can't click on anything while import/export dialog is up

**Comment by larsiusprime** [comment]
Fixed in 0.9.2
