### ISSUE TITLE
I let the spawner boss of the final sidequest hit me and won.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#945]
This doesn't quite seem right. Each ++ enemy should do a final hit of 9999 damage to Azra. Skipping entire lengths of battle dialogue and winning by being hit seems... very wrong.

I've always thought Ozimal Kaz ought to have a final hit of 9999 too. I've seen people get hit by him and go "... I won? How? What?"

![ze](https://cloud.githubusercontent.com/assets/19625520/15883767/486df1e8-2d19-11e6-8528-0200665ec917.png)

**Comment by larsiusprime** [comment]
Yeah, seems a reasonable change.

**Comment by larsiusprime** [comment]
Okay damaging a "walking boss" does NOT affect their total HP, and Ozimal has enough end-battle HP to kill a level 60 Azra, so I see no reason to just artifically inflate every "walking boss" end hit stat to 9999

**Comment by larsiusprime** [comment]
Fixed in 0.9.2.

Now all walking bosses have the "max_end_hit" type which inflates their end hit damage to 9999. Previously it was just simply using the square root of their health.

**Comment by larsiusprime** [comment]
Question -- should *all* of the "main container" enemies in SQ7 have this big giant max end hit, or just the first one? Because each container spawns a bunch of trash mobs and then a new container.

**Comment by larsiusprime** [comment]
(Also as far as I can tell Tltetl-Meztli will nearly always pop the first container before he gets to the end anyways)

**Comment by ManDude** [comment]
I think all ++ enemies should have max end damage.

**Comment by larsiusprime** [comment]
Yeah, seems reasonable. Also boss tag so you can target them appropriately. Going in and adding this all now.

**Comment by larsiusprime** [comment]
Okay, done.
