### ISSUE TITLE
Water enemies stop swimming 1 tile late on 1-tile waters

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#947]
![dq12](https://cloud.githubusercontent.com/assets/7569514/15883990/1328a290-2d45-11e6-9506-c61d62c3ee63.png)
This water enemy is shown leaving its swimming state 1 tile after the water tile.

**Comment by larsiusprime** [comment]
Does this bug occur anywhere except this one level? (I think it's the only one where we have single water tiles)

**Comment by ManDude** [comment]
Doesn't happen on River Escape, so it's probably because that's a single water tile.
