### ISSUE TITLE
Many books missing time/price/damage context.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#949]
![ze](https://cloud.githubusercontent.com/assets/19625520/15887428/3b51db66-2d30-11e6-9de5-b6260fdedd8a.png)

PSI Shield in DQO mentions being impacted by Crystal, but the explosions mention nothing about dragonfire. Not sure if any other books have skillpoint synergy.

Also, what does 'PSI Tax' even mean? That could probably use some elaboration.

**Comment by ManDude** [comment]
Psi Tax means you gain less Psi from all sources.

**Comment by larsiusprime** [comment]
Each book's skillpoint synergy is indicated by the icon on the cover. Maybe that's too subtle?

**Comment by larsiusprime** [comment]
Fixed in 0.9.5 -- now it's at least as informative as the original game.
