### ISSUE TITLE
Missing cutscene sprites in sidequest cutscenes with orig graphics

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#951]
![dq00](https://cloud.githubusercontent.com/assets/7569514/15904344/8d78f6ea-2da8-11e6-8ce9-5b585ad5e271.png)

**Comment by ManDude** [comment]
![dq00-1](https://cloud.githubusercontent.com/assets/7569514/15904615/9415e66a-2da9-11e6-8411-e703b27cc26d.png)

**Comment by ManDude** [comment]
![dq00-3](https://cloud.githubusercontent.com/assets/7569514/15904683/e1f14118-2da9-11e6-99d7-8b45f0356d8c.png)
![dq00-4](https://cloud.githubusercontent.com/assets/7569514/15904760/2ccec5d4-2daa-11e6-93a6-bcc1accc29c7.png)
![dq00-5](https://cloud.githubusercontent.com/assets/7569514/15904971/f116af88-2daa-11e6-9bf9-b9226d33f03e.png)

**Comment by dqhol** [comment]
And here!

![ze](https://cloud.githubusercontent.com/assets/19625520/15989126/b202ee82-303a-11e6-9d58-e9dc3c3207b2.png)

**Comment by ManDude** [comment]
bump, still happening.
