### ISSUE TITLE
Out-of-bounds speech bubble in sidequest 2 outro

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#952]
![dq02](https://cloud.githubusercontent.com/assets/7569514/15904425/dc10efa6-2da8-11e6-8afa-be6a0d02d022.png)

**Comment by larsiusprime** [comment]
Same with HD art or just original art?

**Comment by ManDude** [comment]
Also happens with HD art.

**Comment by ManDude** [comment]
Fixed.
