### ISSUE TITLE
"Azra was slain" and battle ends, but HP bar shows > 0 (even after OK)

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#953]
0.9.0, win7x64, HD mode@1704x960windowed

OK this was 16X and I was typing a bug report at the time, so I didn't see exactly what happened, but:

![dq-azra-slain-not-yet](https://cloud.githubusercontent.com/assets/16719964/15904654/1fb4ad52-2db2-11e6-8554-08e8691fcaa2.png)

Further, knowing it still plays a few seconds at the end of a battle (I thought you'd changed that back?  but then I saw in 0.9.0 that it was still there), I hit OK then immediately hit spacebar to pause.  It was still 79 HP until fadeout.

**Comment by ManDude** [comment]
Before she got hit by the last enemy, how much HP did she have?

**Comment by larsiusprime** [comment]
I'm sure she's really dead, but it should definitely update the HP bar to 0 before it freezes everything so that it's not confusing.

**Comment by IBwWG** [comment]
@ManDude that's what I'm not sure, I left the game running while I was typing the bug report.

@larsiusprime so even the additional frames that keep going before fadeout, the first one of them shouldn't have updated the HP bar?

**Comment by larsiusprime** [comment]
I've fixed it so that there's no additional frames before fadeout anymore,
it hard freezes on battle end.

I should force it at least to update the mcguffin HP bar.

On Wed, Jun 8, 2016 at 3:54 PM, KJB <notifications@github.com> wrote:

> @ManDude <https://github.com/ManDude> that's what I'm not sure, I left
> the game running while I was typing the bug report.
>
> @larsiusprime <https://github.com/larsiusprime> so even the additional
> frames that keep going before fadeout, the first one of them shouldn't have
> updated the HP bar?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/953#issuecomment-224724131>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-NwYgQiUffua92CfYutLpjLj6_h0ks5qJyvpgaJpZM4IxOZe>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Fixed in 2.0.7
