### ISSUE TITLE
Revenant on the final sidequest cheat in Old Graphics, Wide Mode.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#961]
![ze](https://cloud.githubusercontent.com/assets/19625520/15918164/038f699e-2dd2-11e6-892d-36a7c27a447d.png)

You cheeky little bugger. VAC ban pls.

**Comment by larsiusprime** [comment]
Wow, haha.

**Comment by larsiusprime** [comment]
Fixed in 0.9.7

**Comment by dqhol** [comment]
@larsiusprime The website only lists up to 9.5, June 10. New buildings not being auto-uploaded?

**Comment by larsiusprime** [comment]
There's definitely new stuff up there now

**Comment by dqhol** [comment]
There isn't. It says the directory is at 500 items, though. That's an interesting number. Do the directories cap out at 500 items?

**Comment by ManDude** [comment]
Only up to 0.9.5 is showing to me, too.
