### ISSUE TITLE
Pressing Tab in towns results in hands pointing at nothing.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#967]
I suspect it's cycling through the character recruitment screen options, even though it's not open. I didn't even know Tab did anything...? Is the fact that it does anything at all a bug?

![ze](https://cloud.githubusercontent.com/assets/19625520/15928831/4c962caa-2e17-11e6-85e9-2d7d2973855b.png)

**Comment by ManDude** [comment]
That's what Tab is supposed to do: Select buttons. :) Though selecting an invisible button counts as a bug.
