### ISSUE TITLE
German Translation: Main Menu

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#969]
The main menu contains an entry called "Loggt", which does not fit here. It should be more like "Logs".
![dq1_german_menu_loggt](https://cloud.githubusercontent.com/assets/1015465/15942303/23f77304-2e84-11e6-9f2b-b57979d766ba.png)

**Comment by larsiusprime** [comment]
Thanks! By that do you mean you think "Logs" would be the better
translation *in German* ?

On Thu, Jun 9, 2016 at 1:53 PM, Bernd Ritter <notifications@github.com>
wrote:

> The main menu contains an entry called "Loggt", which does not fit here.
> It should be more like "Logs".
> [image: dq1_german_menu_loggt]
> <https://cloud.githubusercontent.com/assets/1015465/15942303/23f77304-2e84-11e6-9f2b-b57979d766ba.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/969>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-BjILs3axtq3wD6yiCIWxyV_RqV1ks5qKGERgaJpZM4IySl6>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by commel** [comment]
Well, "loggt" ist the verb. I can understand why it was translated that way but in this context it does not make much sense. Will this debug menu be in the final release? If so it would change it to "Logs" or "Log-Dateien".

**Comment by larsiusprime** [comment]
Cool, I'll ping the translator on all your suggestions, it's likely that I
didn't give him enough context.

That debug menu currently doesn't do anything because my crashdumping
utility is temporarily broken, but I do plan to ship it eventually, so I
would definitely like to have the correct text labels for it.

On Thu, Jun 9, 2016 at 2:01 PM, Bernd Ritter <notifications@github.com>
wrote:

> Well, "loggt" ist the verb. I can understand why it was translated that
> way but in this context it does not make much sense. Will this debug menu
> be in the final release? If so it would change it to "Logs" or
> "Log-Dateien".
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/969#issuecomment-224993929>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-NaXEJoGOgcz3k_LCLD5Qz6_apjeks5qKGMUgaJpZM4IySl6>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ThomasFaust** [comment]
"Logs" or "Log-Dateien" is indeed good.
(Also hi there, translator here. I have no idea if I did that or the previous translator. In any case, let's fix some stuff!)

**Comment by larsiusprime** [comment]
Fixed in 1.0.1
