### ISSUE TITLE
German Translation: Abort or Cancel Button oversize

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#970]
The Abort or Cancel button is too small to fit "Abbrechen". This is in every dialog i've seen.

![screenshot_20160609_205443](https://cloud.githubusercontent.com/assets/1015465/15942376/6908a120-2e84-11e6-9de2-cb1edeae8514.png)

**Comment by larsiusprime** [comment]
Thanks, I have the power to adjust specific UI elements on a per-locale
basis, so I can fix anything like this you find.

On Thu, Jun 9, 2016 at 1:55 PM, Bernd Ritter <notifications@github.com>
wrote:

> The Abort or Cancel button is too small to fit "Abbrechen". This is in
> every dialog i've seen.
>
> [image: screenshot_20160609_205443]
> <https://cloud.githubusercontent.com/assets/1015465/15942376/6908a120-2e84-11e6-9de2-cb1edeae8514.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/970>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-GMHl_h-29E5I6zSiLA32BK53kGJks5qKGGOgaJpZM4IyStn>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by commel** [comment]
![screenshot_20160609_210400](https://cloud.githubusercontent.com/assets/1015465/15942681/b5527d3e-2e85-11e6-8124-a0c5ce5776e1.png)

It thiny bit more here for the "Abbrechen"/Cancel button :-)

**Comment by commel** [comment]
![screenshot_20160609_210505](https://cloud.githubusercontent.com/assets/1015465/15942721/e0beabb4-2e85-11e6-921e-b0c76be804a2.png)

This is the "group" menu, the green "zurücksetzen", the white ghost "ausweichen", and the blue "ausrüsten".

**Comment by commel** [comment]
Next to the blue "Ausrüsten" button there can be a red "Rückgängig" button. 
![screenshot_20160609_211647](https://cloud.githubusercontent.com/assets/1015465/15943083/99f19848-2e87-11e6-9a5f-aad7c4e17444.png)

**Comment by ThomasFaust** [comment]
Let's see... how about changing "Abbrechen" to "Abbruch" (verb to noun, meaning stays the same)?
As for the other ones:

...
no clue, any suggestions? You could go ahead and abbreviate stuff, so "Zurücksetzen" becomes "Zurücks.", "Ausweichen" becomes "Ausw."

There's no good way of abbreviating "Ausrüsten" without it looking silly, though.
Would "Zurück" instead of "Rückgängig" work better? I think it might.

**Comment by commel** [comment]
In the difficulty screen before battle
![screenshot_20160609_212511](https://cloud.githubusercontent.com/assets/1015465/15943324/c690116c-2e88-11e6-90b2-eda932e36111.png)

The "Fortgeschritten" is a bit cut off. Also the "Abbrechen" is a bit short on the left.

**Comment by commel** [comment]
I think @larsiusprime said that he can change the size of the label based on the locale.

**Comment by larsiusprime** [comment]
I have full power to change the size of buttons and labels and font sizes
and positions and all that good stuff, but if there's a perfectly good
abbreviation, that's nice too because it's a much faster and cleaner fix.

On Thu, Jun 9, 2016 at 2:28 PM, Bernd Ritter <notifications@github.com>
wrote:

> I think @larsiusprime <https://github.com/larsiusprime> said that he can
> change the size of the label based on the locale.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/970#issuecomment-225000909>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-G6Up14k-HjucyiCrUf6hMdtBqxbks5qKGlkgaJpZM4IyStn>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by commel** [comment]
May you can try out the abbreviations and we have a look in the next build how it looks and feels?

**Comment by larsiusprime** [comment]
I'll have to give these a pass post-launch I think to deal with it correctly

**Comment by larsiusprime** [comment]
- [ ] Regular dialogs: widen
- [ ] Battle dialogs: widen
- [ ] Party menu

**Comment by larsiusprime** [comment]
Fixed in 2.0.8
