### ISSUE TITLE
German Translation: Overside in misc menu

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#971]
The text in german is floating out on the right side of the menu.
![screenshot_20160609_205543](https://cloud.githubusercontent.com/assets/1015465/15942433/9d65d730-2e84-11e6-9875-9728505f8fd9.png)

**Comment by ThomasFaust** [comment]
can you insert a line break there, Lars? cutting this down to fewer words would be nasty.

**Comment by faho** [comment]
"Beim Start auf Updates prüfen"?

**Comment by larsiusprime** [comment]
We don't even have an auto-updater any more....
