### ISSUE TITLE
German Translation: Previous and Next button

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#974]
Letzter means "the last one", but the button jumps to the previous chatter. Would recommend to translate it as "Vorheriger" in combination with "Nächster".
![screenshot_20160609_210829](https://cloud.githubusercontent.com/assets/1015465/15942851/92096670-2e86-11e6-8116-f37add1332ad.png)

Same here as well, this is after the dialogue:
![screenshot_20160609_211046](https://cloud.githubusercontent.com/assets/1015465/15942866/a6d4d72e-2e86-11e6-9256-64a392f1c6a0.png)

**Comment by ManDude** [comment]
"Last one" is also a way to say "previous one", though it can get a bit confusing.

**Comment by commel** [comment]
True, usually those jumping labels are named "zurück"/"weiter" i guess.

**Comment by ThomasFaust** [comment]
Yup, "zurück" and "weiter" would be perfect.

**Comment by larsiusprime** [comment]
Fixed in 1.0.1
