### ISSUE TITLE
German Translation: Send next waves out of bounds

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#975]
In the game screen itself is the "send next" label in german bouncing out of bounds.
![screenshot_20160609_211221](https://cloud.githubusercontent.com/assets/1015465/15942947/fc4f3f78-2e86-11e6-8908-54d20461a692.png)

**Comment by ThomasFaust** [comment]
I'd just cut that down to "NÄCHSTE" (next). Opinions?

**Comment by larsiusprime** [comment]
Works for me. Kill all the words.
