### ISSUE TITLE
German Translation: Kram for "scrap"

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#976]
I have no other good idea right now but I wanted to note that "Kram" is sounding strange when I know it is "scrap".
![screenshot_20160609_211849](https://cloud.githubusercontent.com/assets/1015465/15943203/36dd0fe8-2e88-11e6-9ba6-e45382b7d83f.png)

**Comment by ThomasFaust** [comment]
Not my idea. It always bugged me, but I got used to it. (On the other hand, all other possible ideas - Müll, Zeug, Schrott - sound strange as well.)

**Comment by commel** [comment]
Yeah i know, I have any good idea myself.

**Comment by larsiusprime** [comment]
Closing unless you guys come up with something.
