### ISSUE TITLE
German Translation: Ä-Umlaut looks strange within capital letters

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#977]
Is this a small ä?
![screenshot_20160609_213745](https://cloud.githubusercontent.com/assets/1015465/15943695/8b5ca216-2e8a-11e6-83ec-7043ba2e1d1b.png)

**Comment by commel** [comment]
Same here:
![screenshot_20160609_214613](https://cloud.githubusercontent.com/assets/1015465/15943984/b9eb08ce-2e8b-11e6-825c-24237b92385b.png)


But in the heroes menu on the right it works:
![screenshot_20160609_214640](https://cloud.githubusercontent.com/assets/1015465/15943975/af387b78-2e8b-11e6-95d5-4e4fd188eade.png)

**Comment by larsiusprime** [comment]
I must be using toUpperCase() rather than a UTF-8-aware variety.

On Thu, Jun 9, 2016 at 2:47 PM, Bernd Ritter <notifications@github.com>
wrote:

> Same here:
> [image: screenshot_20160609_214613]
> <https://cloud.githubusercontent.com/assets/1015465/15943984/b9eb08ce-2e8b-11e6-825c-24237b92385b.png>
>
> But in the heroes menu on the right it works:
> [image: screenshot_20160609_214640]
> <https://cloud.githubusercontent.com/assets/1015465/15943975/af387b78-2e8b-11e6-95d5-4e4fd188eade.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/977#issuecomment-225005631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-C9g5sEblqZxSdN9Qk4kyysmT6loks5qKG3IgaJpZM4IyVF2>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
1. Find Utf-8 aware haxe library with toUpperCase() function
2. Discover another weird error in the process
3. Fix said error
4. Pull request
5. Long live open source

https://github.com/restorer/zame-haxe-stringutils/pull/2

**Comment by larsiusprime** [comment]
Fixed in 0.9.4
