### ISSUE TITLE
Windows Build 0.9.3 - crash to desktop when switching to German

### ISSUE THREAD

**Issue by ThomasFaust** [larsiusprime/tdrpg-bugs#979]
Okay, so I start the game, go into the menu with the savegames/language selection, and when I want to change the language to German it gives me a crash to desktop and a "null object reference" pop-up.

This happens in windowed and full screen mode. No other changes have been made in the options menu.

**Comment by larsiusprime** [comment]
Not a problem, null object crashes are usually easy to fix.

PROTIP: if you run the game from the command line (run cmd, then navigate to the directory and type "DefendersQuest.exe"), you'll usually get a stack trace on these which makes it *super easy* for me to fix them.

But this sounds easy to repro.

**Comment by larsiusprime** [comment]
@ManDude -- probably a working directory error. Are you trying to call it directly without navigating to its directory first? You have to launch it while you're in the same directory or else it can't find it's assets.

**Comment by ThomasFaust** [comment]
C:\def>Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleMouseEvent lime/_backend/native/NativeApplication.hx line 337
Called from lime.app.Event_Float_Float_Int_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 188
Called from lime.app.Application::onMouseUp lime/app/Application.hx line 431
Called from openfl.display.Stage::onMouseUp openfl/display/Stage.hx line 461
Called from openfl.display.Stage::__onMouse openfl/display/Stage.hx line 1079
Called from openfl.display.Stage::__fireEvent openfl/display/Stage.hx line 899
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.ui.FlxTypedButton::onUpEventListener flixel/ui/FlxButton.hx line 499
Called from flixel.addons.ui.FlxUIButton::onUpHandler flixel/addons/ui/FlxUIButton.hx line 331
Called from flixel.addons.ui.FlxUITypedButton::onUpHandler flixel/addons/ui/FlxUITypedButton.hx line 1080
Called from flixel.ui.FlxTypedButton::onUpHandler flixel/ui/FlxButton.hx line 513
Called from flixel.addons.ui.FlxUICheckBox::_clickCheck flixel/addons/ui/FlxUICheckBox.hx line 257
Called from *::_Function_5_1 flixel/addons/ui/FlxUIRadioGroup.hx line 390
Called from flixel.addons.ui.FlxUIRadioGroup::_onCheckBoxEvent flixel/addons/ui/FlxUIRadioGroup.hx line 476
Called from flixel.addons.ui.FlxUIRadioGroup::_onClick flixel/addons/ui/FlxUIRadioGroup.hx line 498
Called from flixel.addons.ui.FlxUI::event flixel/addons/ui/FlxUI.hx line 144
Called from com.leveluplabs.tdrpg.Popup_Localization::getEvent com/leveluplabs/tdrpg/Popup_Localization.hx line 349
Called from com.leveluplabs.tdrpg.Popup_Localization::refresh com/leveluplabs/tdrpg/Popup_Localization.hx line 122
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by ManDude** [comment]
@larsiusprime I tried launching it from %windir%/System32 and from the Run thing and neither worked.

**Comment by larsiusprime** [comment]
Perfect.

**Comment by larsiusprime** [comment]
@ThomasFaust: it does seem like a weird bug, I'll put in a crash guard, but my best bet for you is to go to the save slot screen, click on the "save files" button, and trash the settings and locale files, then restart and see if it persists.

**Comment by ThomasFaust** [comment]
Deleted those files, still not working.

**Comment by larsiusprime** [comment]
@ThomasFaust : try downloading the build again and unzipping a clean version. The crash you're experiencing is because it's trying to set the font on a button that should exist but doesn't, which makes me wonder if the ui markup file is damaged in your copy or something.

**Comment by ThomasFaust** [comment]
@larsiusprime third time I downloaded and unpacked it now - I reckon that's not the problem. I wonder, can this be reproduced on another windows computer or is it just me?

**Comment by larsiusprime** [comment]
@ThomasFaust : Hmmm, no idea what's going on, I just downloaded & unpacked version 0.9.3 with no issues. 

At any rate, 0.9.4 should show up in an hour or so, it has a crash guard on the line you were QTD'ing on. If it still breaks, try trashing EVERYTHING in the DQ save folder (back up anything you want to keep of course) and try that maybe? Have you ever run a DQ DX testing build before? Are you on a weird limited account or anything? What OS? Did you put it in a weird folder (like a network folder?) that might not have enough space, or the correct permissions?

**Comment by ThomasFaust** [comment]
New version is running just fine.

My OS is Windows 10 (need a dxdiag log?), no other weirdness apart from that. Tried different install folders. Been running it from the SSD, but that shouldn't be an issue. In any case: yay, it works!

**Comment by larsiusprime** [comment]
whew
