### ISSUE TITLE
German Translation: Neu <N?> zuweisen

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#980]
This is when i got my second defender. I have no idea what this button should mean, but it opens the character customization menu.

![screenshot_20160609_215044](https://cloud.githubusercontent.com/assets/1015465/15944131/67e52d2e-2e8c-11e6-9d9a-1975e37062c1.png)

**Comment by ManDude** [comment]
Could be a comment from the translator accidentally left in.

**Comment by ThomasFaust** [comment]
<ShaggyVoice> It wasn't me </ShaggyVoice>

**Comment by ThomasFaust** [comment]
in any case, "Neu zuweisen" should work, right?

**Comment by commel** [comment]
Sure!

**Comment by larsiusprime** [comment]
Fixed in 1.0.1
