### ISSUE TITLE
German Translation: Color chooser out of bounds

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#981]
The color chooser it a bit out of bounds on the right. Also the "Abbrechen" button is too small.
![screenshot_20160609_215200](https://cloud.githubusercontent.com/assets/1015465/15944163/94783f70-2e8c-11e6-9d8b-9eda597640ec.png)

**Comment by larsiusprime** [comment]
This seems to be fixed in the latest build.
