### ISSUE TITLE
Eztli-Tenoch has no magic runes in Japanese

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#982]
![dq04](https://cloud.githubusercontent.com/assets/7569514/15945627/5d941c50-2e8b-11e6-8933-c37aadeacb6f.png)

**Comment by larsiusprime** [comment]
Is this NG+ mode or regular mode?

**Comment by ManDude** [comment]
Regular.

**Comment by larsiusprime** [comment]
Great, thanks.

On Thu, Jun 9, 2016 at 4:30 PM, ManDude <notifications@github.com> wrote:

> Regular.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/982#issuecomment-225032805>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-FGdxJ4D0UZ-KRlUgZBr_5iUQJefks5qKIXqgaJpZM4IyYqi>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
What's almost certainly happening is it's trying to render japanese text in
runes with a font that only has glyphs for english letters.

So what I need to do is to detect if its using the symbol font, and if so,
render the text underneath it in english, which results in crazy unreadable
letters. In NG+, it will render in the native text and font, and appear
properly localized.

On Thu, Jun 9, 2016 at 4:35 PM, Lars Doucet <lars.doucet@gmail.com> wrote:

> Great, thanks.
>
> On Thu, Jun 9, 2016 at 4:30 PM, ManDude <notifications@github.com> wrote:
>
>> Regular.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/larsiusprime/tdrpg-bugs/issues/982#issuecomment-225032805>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAtG-FGdxJ4D0UZ-KRlUgZBr_5iUQJefks5qKIXqgaJpZM4IyYqi>
>> .
>>
>
>
>
> --
> www.fortressofdoors.com -- Games, Art, Design
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Fixed in 2.0.6
