### ISSUE TITLE
Locale error

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#983]
![dq05](https://cloud.githubusercontent.com/assets/7569514/15946044/ebf322e2-2e8c-11e6-8da3-6dd6aff582a5.png)

**Comment by ManDude** [comment]
![dq06-1](https://cloud.githubusercontent.com/assets/7569514/15946259/f96337f4-2e8d-11e6-8a9c-cbc278990321.png)
![dq06](https://cloud.githubusercontent.com/assets/7569514/15946260/f9831696-2e8d-11e6-84ad-821ea0fca271.png)

**Comment by ManDude** [comment]
![dq06-2](https://cloud.githubusercontent.com/assets/7569514/15946367/848f91ec-2e8e-11e6-8d5c-9aa2929c4262.png)
1 line too low.

**Comment by larsiusprime** [comment]
Fixed in 1.0.0
