### ISSUE TITLE
Random fireball at the top-left when exploding a Crystal

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#984]
![dq09](https://cloud.githubusercontent.com/assets/7569514/15946091/199e5112-2e8d-11e6-8134-673b52cecebe.png)
It turns randomly then disappears. Might be a bug with the explosion attack. i think this happeened with Dragon Fire too.

**Comment by larsiusprime** [comment]
I cannot reproduce this right now, but I have DEFINITELY seen it before. Let me know if you see it again.

**Comment by ManDude** [comment]
Seems to still be happening as per #1263

**Comment by Nicholas-Steel** [comment]
Well, in the video i provided it doesn't seem to target anything specifically? I recorded playing through the level twice (boosting my party members the first time) and the errant Fireball often didn't target anything. It only sometimes happens to strike a party member by mere chance (maaaybe rarely an enemy sometimes).

**Comment by larsiusprime** [comment]
Fixed in 2.1.2
