### ISSUE TITLE
Suggestion: Ending achievements.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#985]
A while back I believe there was talk on adding achievements for the various different endings, as an indication that there was more than one ending, that they should look for others. And I guess so that people who got the 'Bakal dies' or 'Markos dies' endings didn't get too upset.

Ending A: The Way Out
Ending B: All Is Lost
Ending C: A Painful End
Ending D: A Bittersweet End
Ending E: A Glorious End

I'd also maybe consider putting a grayed out [???] or [Locked] in the journal where the final entry is supposed to go, if Ending C or D is unlocked but Ending E isn't.

Could all be unnecessary, though. :)

Edit: One for unlocking all the monument books could be nice, too, if the plan to import DQ1 save data into DQ2 for a bonus remains.

**Comment by IBwWG** [comment]
I like this--as a newcomer I hadn't realized there were more than two endings (A and E.)  :)

**Comment by dqhol** [comment]
Out of curiosity, did this get cut?
