### ISSUE TITLE
Update Credits

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#986]
Lars wants to update the credits with the names of everyone who has contributed to DQDX.

**Comment by ManDude** [comment]
Right.

**Comment by larsiusprime** [comment]
This is a good place for all of you to list the name you would like to be
credited under (screen name, real name, "anonymous", I don't care, up to
you)

On Fri, Jun 10, 2016 at 12:27 PM, ManDude <notifications@github.com> wrote:

> Right.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/986#issuecomment-225244551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-PqG3nsDYUIRKzo4GjhFzrOGd0Qcks5qKZ6RgaJpZM4IzJBu>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
> KJB of IBwWG

for me, thanks :)

**Comment by ManDude** [comment]
ManDude

**Comment by commel** [comment]
Bernd Ritter for Holarse Linuxgaming

**Comment by larsiusprime** [comment]
I feel really bad about overlooking this, this will be the first thing in the next patch.
