### ISSUE TITLE
[Suggestion] Reload mod button

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#988]
Self-explanatory. Saves a lot of time if you just want to test things out quickly. Also I can see myself (and other modding enthusiasts) using this a lot.

**Comment by larsiusprime** [comment]
What's the ideal UX? Should it be on a specific screen, or be a hotkey, etc?

**Comment by ManDude** [comment]
Pressing the Mods button should give you the option to choose between Unload and Reload.

**Comment by ManDude** [comment]
Oh looks like this is implemented properly now. Thanks!
