### ISSUE TITLE
Localisation: Switches back to english on version change

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#989]
Yesterday I played with build 0.9.3 and today I started build 0.9.3-2 from a different directory. I did not clean my configuration files in ~/.local/share/LevelUpLabs. I went directly to the main menu but now it is in english.

Somehow the game does not recognize my previous configured german version. In locale.xml the value in /data/locale was "en-US". When i changed it to "de-DE" the german version appears again. 

This also happened when I switched from a previous release/demo to the 0.9.2 version.

**Comment by larsiusprime** [comment]
Weird, does it happen between multiple runs of the same version?

Which OS is this for? That path directory looks like either OSX or Linux.
Do you have trouble with any other data resetting between builds?

On Fri, Jun 10, 2016 at 1:50 PM, Bernd Ritter <notifications@github.com>
wrote:

> Yesterday I played with build 0.9.3 and today I started build 0.9.3-2 from
> a different directory. I did not clean my configuration files in
> ~/.local/share/LevelUpLabs. I went directly to the main menu but now it is
> in english.
>
> Somehow the game does not recognize my previous configured german version.
> In locale.xml the value in /data/locale was "en-US". When i changed it to
> "de-DE" the german version appears again.
>
> This also happened when I switched from a previous release/demo to the
> 0.9.2 version.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/989>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAtG-NY95PHZq9Mc2vVzaSqELHCaZ70jks5qKbH7gaJpZM4IzOQj>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Also one heads up -- the DEMO version and the FULL version store their data
in separate locations, not sure if that's part of what's going on here or
not.

On Fri, Jun 10, 2016 at 1:52 PM, Lars Doucet <lars.doucet@gmail.com> wrote:

> Weird, does it happen between multiple runs of the same version?
>
> Which OS is this for? That path directory looks like either OSX or Linux.
> Do you have trouble with any other data resetting between builds?
>
> On Fri, Jun 10, 2016 at 1:50 PM, Bernd Ritter <notifications@github.com>
> wrote:
>
>> Yesterday I played with build 0.9.3 and today I started build 0.9.3-2
>> from a different directory. I did not clean my configuration files in
>> ~/.local/share/LevelUpLabs. I went directly to the main menu but now it is
>> in english.
>>
>> Somehow the game does not recognize my previous configured german
>> version. In locale.xml the value in /data/locale was "en-US". When i
>> changed it to "de-DE" the german version appears again.
>>
>> This also happened when I switched from a previous release/demo to the
>> 0.9.2 version.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/larsiusprime/tdrpg-bugs/issues/989>, or mute the
>> thread
>> <https://github.com/notifications/unsubscribe/AAtG-NY95PHZq9Mc2vVzaSqELHCaZ70jks5qKbH7gaJpZM4IzOQj>
>> .
>>
>
>
>
> --
> www.fortressofdoors.com -- Games, Art, Design
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by commel** [comment]
I tried to enforce it now but the issue does not want to show itself anymore.
