### ISSUE TITLE
German Translation: Artifacts in the achievement list

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#990]
Found this in the submenu "achievements" from the main menu:

![screenshot_20160610_210729](https://cloud.githubusercontent.com/assets/1015465/15975753/68718012-2f4f-11e6-8e4f-4cfde6545741.png)

**Comment by ManDude** [comment]
Looks like a weird line break issue.

**Comment by ManDude** [comment]
Yep. $N should be changed to <N>.

**Comment by larsiusprime** [comment]
Fixed in 1.0.1
