### ISSUE TITLE
German Translation: More PSI needed out of bounds

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#991]
The mouse icon when the hero is out of PSI exceeds the bounds. I would suggest instead of "BRAUCHE PSI" something shorter like "PSI LEER".
![screenshot_20160610_211648](https://cloud.githubusercontent.com/assets/1015465/15976058/e23be71a-2f50-11e6-828d-748a9ce4cbba.png)

**Comment by ThomasFaust** [comment]
agreed!

**Comment by faho** [comment]
Or "Mehr PSI"?

**Comment by ThomasFaust** [comment]
Or "KEIN PSI"?

**Comment by ManDude** [comment]
Well whatever it is, you guys have to reach a consensus. ;)

**Comment by larsiusprime** [comment]
@ThomasFaust:
Pick one :)

**Comment by ThomasFaust** [comment]
Make it "KEIN PSI", then.

**Comment by faho** [comment]
I'm okay with that.
