### ISSUE TITLE
Confirmation window with 3 close buttons

### ISSUE THREAD

**Issue by Skiski** [larsiusprime/tdrpg-bugs#992]
Hi.

This is a problem I had after the second battle, when upgrading the lightning spell.
On the window to confirm the use of a skill point, there are 3 close buttons.
![confirmation-window](https://cloud.githubusercontent.com/assets/3219501/15979011/d4888ac2-2f61-11e6-961f-d8fac82c65e4.png)
I'm using the test version on Steam, on Fedora 22 (linux) 64 bit.

But I manages to find the "good" close button and I was able to continue the game.

**Comment by Skiski** [comment]
I can reproduce the bug by just clicking on the bonus button on the main menu. I've tried setting the game in french and it's the same, but with "fermer/fermer/fermer" instead.
![confirmation-window2](https://cloud.githubusercontent.com/assets/3219501/15993741/bcf0e640-30ef-11e6-8058-58b57ce8afd9.png)

**Comment by ManDude** [comment]
Already reported, two times in fact. :V

**Comment by larsiusprime** [comment]
Fixed
