### ISSUE TITLE
No 32-bit Linux builds

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#996]
There seem to be, sometimes, two 64-bit Linux builds made for the same version (as before) (also the same steam vs vanilla flag), but no 32-bit as you had mentioned in the todo list.  I was going to give it a whirl on a couple Linux machines we had here.

**Comment by IBwWG** [comment]
Er, is this what you meant by "set up run script with 32/64"...in #995 ?

**Comment by IBwWG** [comment]
Oh, I see now too that it's not checked off in #968 .  OTOH without a build to test, there might be more issues than you would want for a final release? Also some of the things in that list (Linux 64-bit) are already going, but not checked off...so...I'm not sure.  Sorry for the probable dupe here.

**Comment by larsiusprime** [comment]
My CI server can't make 32 bit linux builds for some reason, I have to do them manually, so you won't ever see them on the server. They'll pop up in itch and the steam, review branch though. Do you own the game on steam? I can get you some keys if you need.

**Comment by IBwWG** [comment]
I don't have a steam account or itch, but I was planning to get an itch developer account soon anyway, if they're also used as consumer accounts we can use itch instead.  If not I'll set up a steam account.

**Comment by larsiusprime** [comment]
Give me your email address, or ping me on twitter, somewhere I can send you a private message

**Comment by larsiusprime** [comment]
Anyways I think I'll close this for now as I've got tested and deployed 32-bit/64-bit "universal" linux builds now, up on both steam & itch.
