### ISSUE TITLE
Strange vertical row of tiles defenders can't be placed on in River Escape.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#997]
Not that you would put anyone there, but the fact that it's blanked out is odd.

![ze](https://cloud.githubusercontent.com/assets/19625520/15984729/24cf1bd6-2fa3-11e6-9f47-c888b350e8e1.png)

So  much grass decoration, too. :D

**Comment by larsiusprime** [comment]
Is this extra "padding space" that's filled in because you're running the game in sprite mode on a resolution > 800x600 but < 1920x1080 ?

**Comment by larsiusprime** [comment]
Still a bug if it is of course (should not be a standable terrain), but that would explain it.

**Comment by ManDude** [comment]
Nope, this is in the middle of the normal map layout.

**Comment by larsiusprime** [comment]
Fixed in 2.1.0. Just a stupid bug in the map layout, was literally just missing that column and it was positioned in such a way it's not obvious at a glance.
