### ISSUE TITLE
Sorceress's spell icons all out of order

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#999]
![dq-icons-disorder](https://cloud.githubusercontent.com/assets/16719964/15985115/63f6db10-2fe3-11e6-8838-b026d8f238f9.png)
0.9.5-11-g20b07b4 - full - vanilla, build 1, win7x64, HD mode@1704x960windowed

Also, I just cast Frenzy, and it's making the healing icon (which is in Frenzy's original spot) greyed.  I guess it's a display issue then.  If I click or press three and I get a healing cursor, with WAIT.

**Comment by ManDude** [comment]
This is not Azra, this is the sorceress (or unazra). Does this happen with actual Azra?

**Comment by IBwWG** [comment]
Oh, right, indeed.  AKA "???" in the finishing dialog, a bit awkward by the way ("??? survived, but with injuries...")

I don't think it does with actual Azra, or at least I didn't notice; for her though I only played a brand new hero mode game, and only got as far as having the frenzy spell.  As of then, things were normal.

**Comment by joaociocca** [comment]
Played last night from a ng+ save, last battle on extreme, spells seemed in order.

**Comment by Geardan** [comment]
Just encountered this on 2.0.1 Steam build. Very confusing! Neither using the hotkeys nor clicking the spell icon result in the spell shown in that box. Instead you get the spell that would normally be assigned to that slot/hotkey if you were on an Azra stage. It also causes the cooldown displays to get super weird.

**Comment by noxnebulous** [comment]
I have also seen this bug! The icon clicked does not match the spell that is cast, and then the cooldown timer doesn't match, either! Even with the numerical hotkeys, the cooldowns are still all out of whack.

**Comment by ManDude** [comment]
Fixed for me (reopen if not fixed for anyone else).
